In [1]:

import pandas as pd
import json

# مسیر فایل
file_path = r"D:\progam\Laqaee\Oman-Laws_RAG_Phase_1.json"

# 1. خوندن فایل JSON
with open(file_path, "r", encoding="utf-8") as f:
    data = json.load(f)

# 2. تبدیل به DataFrame
if isinstance(data, list):
    df = pd.DataFrame(data)
elif isinstance(data, dict):
    first_key = list(data.keys())[0]
    df = pd.DataFrame(data[first_key])



text_dupes = df[df.duplicated(subset=["text"], keep=False)]
text_counts = text_dupes.groupby("text").size().reset_index(name="count").sort_values(by="count", ascending=False)



# 5. تعداد کل تکراری‌ها
print("تعداد رکوردها:", len(df))
print("تعداد رکوردهای تکراری بر اساس ستون متن:", len(text_dupes))

# حذف رکوردهای تکراری بر اساس ستون 'text' و نگه داشتن اولین رکورد
df_unique = df.drop_duplicates(subset=["text"], keep="first")

# تعداد رکوردها بعد از حذف تکراری‌ها
print("تعداد رکوردها بعد از حذف تکراری‌ها:", len(df_unique))

# حذف رکوردهایی که ستون 'text' خالی یا NaN هست
df_clean = df_unique.dropna(subset=['text'])

# همچنین می‌تونیم رکوردهایی که طول متن صفره هم حذف کنیم
df_clean = df_clean[df_clean['text'].str.strip() != ""]

print("تعداد رکوردها بعد از حذف متن‌های خالی:", len(df_clean))

تعداد رکوردها: 12547
تعداد رکوردهای تکراری بر اساس ستون متن: 2897
تعداد رکوردها بعد از حذف تکراری‌ها: 10537
تعداد رکوردها بعد از حذف متن‌های خالی: 10535

In [2]:
print("ستون‌ها:")
print(df_clean.columns.tolist())

print("\nتعداد رکوردها:", len(df_clean))

print("\nنوع داده هر ستون:")
print(df_clean.dtypes)

print("\nتعداد مقادیر خالی در هر ستون:")
print(df_clean.isna().sum())

ستون‌ها:
['json_link', 'short_link', 'canonical_link', 'date', 'title', 'text', 'html', 'error']

تعداد رکوردها: 10535

نوع داده هر ستون:
json_link         object
short_link        object
canonical_link    object
date              object
title             object
text              object
html              object
error             object
dtype: object

تعداد مقادیر خالی در هر ستون:
json_link             0
short_link            0
canonical_link        0
date                  0
title                 0
text                  0
html                  0
error             10535
dtype: int64

In [3]:
import re
import pandas as pd


def clean_text(text):
    # حذف فاصله اضافی در ابتدا و انتهای متن
    text = text.strip()
    # جایگزینی چند فاصله متوالی با یک فاصله
    text = re.sub(r'\s+', ' ', text)
    # حذف خطوط خالی یا فقط شامل فاصله
    text = re.sub(r'\n\s*\n', '\n', text)

    return text

def clean_header(text):
    text = re.sub(r'^(?:تحميل|English|نص معدل|\s)+', '', text)
    return text


noise_pattern = re.compile(
    r"""
    [\s\.]*                                   # فاصله یا نقطه قبل نویز
    (                                        # بلاک نویز
        (?:
            [0-9\u0660-\u0669]{1,4}           # عدد ۱ تا ۴ رقمی
            \s*/\s*
            [0-9\u0660-\u0669]{1,4}           # عدد ۱ تا ۴ رقمی
            \s*
        ){2,}                                 # حداقل دو تکرار
    )
    $                                         # فقط انتهای متن
    """,
    re.VERBOSE
)

def remove_trailing_numeric_noise(text):
    if not isinstance(text, str):
        return text
    return re.sub(noise_pattern, "", text).strip()
from datetime import datetime

AR_MONTHS = {
    "يناير": 1,
    "فبراير": 2,
    "مارس": 3,
    "أبريل": 4,
    "ابريل": 4,
    "مايو": 5,
    "يونيو": 6,
    "يوليو": 7,
    "أغسطس": 8,
    "اغسطس": 8,
    "سبتمبر": 9,
    "أكتوبر": 10,
    "اكتوبر": 10,
    "نوفمبر": 11,
    "ديسمبر": 12,
}

def parse_arabic_date(text):
    if not isinstance(text, str):
        return pd.NaT

    # حذف عبارت ثابت
    text = text.replace("تاريخ المقالة", "").strip()

    # استخراج روز، ماه، سال
    m = re.search(r"(\d{1,2})\s+([^\s]+)\s+(\d{4})", text)
    if not m:
        return pd.NaT

    day = int(m.group(1))
    month_ar = m.group(2)
    year = int(m.group(3))

    month = AR_MONTHS.get(month_ar)
    if not month:
        return pd.NaT

    try:
        return datetime(year, month, day)
    except ValueError:
        return pd.NaT

# اعمال تابع تمیزسازی روی ستون
df_clean['text'] = df_clean['text'].apply(clean_text)
df_clean['text'] = df_clean['text'].apply(clean_header)
df_clean['text'] = df_clean['text'].apply(remove_trailing_numeric_noise)

df_clean['date'] = df_clean['date'].apply(clean_text)
df_clean["date"] = df_clean["date"].apply(parse_arabic_date)

df_clean['title'] = df_clean['title'].apply(clean_text)
df_clean['html'] = df_clean['html'].apply(clean_text)

In [4]:
# اضافه کردن ستون متن و تعداد کلمات
df_clean['text_word_count'] = df_clean['text'].apply(lambda x: len(x.split()))
# ابتدا تعداد کلمات هر عنوان را محاسبه کن
df_clean['title_word_count'] = df_clean['title'].apply(lambda x: len(str(x).split()))


print("\nآمار طول متن:")
print(df_clean['text_word_count'].describe())
print("\nآمار طول عنوان:")
print(df_clean['title_word_count'].describe())

آمار طول متن:
count     10535.000000
mean        689.552159
std        3050.563075
min           0.000000
25%          14.000000
50%         133.000000
75%         356.000000
max      220969.000000
Name: text_word_count, dtype: float64

آمار طول عنوان:
count    10535.000000
mean        16.159279
std          6.188719
min          2.000000
25%         12.000000
50%         16.000000
75%         20.000000
max         66.000000
Name: title_word_count, dtype: float64

In [5]:
short_texts = df_clean[(df_clean['text_word_count'] > 90) & (df_clean['text_word_count'] < 100)]

print("تعداد قوانین خیلی کوتاه:", len(short_texts))

for i, row in short_texts.head().iterrows():
    print("-------------------")
    print("Title:", row['title'])
    print("Word count:", row['text_word_count'])
    print("id:",row['canonical_link'])
    print("Text:")
    print(row['text'])

تعداد قوانین خیلی کوتاه: 207
-------------------
Title: مرسوم سلطاني رقم ٦ / ٧٤ بخصوص إعادة تنظيم دائرة الحسابات والخزينة
Word count: 98
id: https://qanoon.om/p/1974/rd1974006/
Text:
نحن قابوس بن سعيد سلطان عمان نظرا لما تقتضيه المصلحة العامة فقد قررنا إعادة تنظيم دائرة الحسابات والخزينة. رسمنا بما هو آت المادة ١ تسمى هذه الدائرة بدائرة المالية بدلا من دائرة الحسابات والخزينة. المادة ٢ تقع مسؤولة هذه الدائرة على مستشار الشؤون المالية. المادة ٣ تستقل دائرة تدقيق الحسابات عن دائرة المالية وتكون تحت مسؤولية وزارة شؤون الديوان السلطاني. المادة ٤ ينشر هذا المرسوم في الجريدة الرسمية. صدر في: ١٩ محرم ١٣٩٤هـ الموافق: ١٢ فبراير ١٩٧٤م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٥٠) الصادر في ٢ / ٣ / ١٩٧٤م
-------------------
Title: مرسوم سلطاني رقم ١٧ / ٧٤ بالتصديق على اتفاقية تأسيس البنك العربي للتنمية الاقتصادية في أفريقيا والنظام الأساسي المرافق لها
Word count: 92
id: https://qanoon.om/p/1974/rd1974017/
Text:
نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على اتفاقية تأسيس البنك العربي للتنمية الاقتصادية في أفريقيا بين حكومات الجامعة العربية والموقع عليها بتاريخ ١١ مارس ١٩٧٤. رسمنا بما هو آت المادة ١ التصديق على اتفاقية تأسيس البنك العربي للتنمية الاقتصادية في أفريقيا والنظام الأساسي المرافق لها. المادة ٢ ينشر هذا المرسوم في الجريدة الرسمية ويعتبر نافذا به من تاريخ نشره. صدر في: ١٣ ربيع الثاني ١٣٩٤هـ الموافق: ٦ مايو ١٩٧٤م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٥٥) الصادر في ١٥ / ٥ / ١٩٧٤م
-------------------
Title: مرسوم سلطاني رقم ٤١ / ٧٤ بتشكيل مجلس للتنمية
Word count: 99
id: https://qanoon.om/p/1974/rd1974041/
Text:
نحن قابوس بن سعيد سلطان عمان نظرا لما تقتضيه المصلحة العامة ونظرا لما للتنمية من أهمية بالغة. فقد قررنا المادة ١ تشكيل مجلس للتنمية برئاستنا وعضوية كل من: وزير الدولة للشؤون الخارجية مساعدا وزير الداخلية عضوا وزير الصحة عضوا وزير المواصلات عضوا وزير التجارة والصناعة عضوا وزير الزراعة والأسماك والنفط والمعادن عضوا مندوبا عن المالية عضوا المادة ٢ ينشر هذا المرسوم في الجريدة الرسمية ويعمل به من تاريخه. صدر في: ٣ ذو القعدة ١٣٩٤هـ الموافق: ١٧ نوفمبر ١٩٧٤م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٦٨) الصادر في ١ / ١٢ / ١٩٧٤م
-------------------
Title: مرسوم سلطاني رقم ٤٦ / ٧٤ بتعيين سفير في وزارة الخارجية
Word count: 97
id: https://qanoon.om/p/1974/rd1974046/
Text:
نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على المادة (٦) من قانون السلكين الدبلوماسي والقنصلي رقم ٤٦ لسنة ١٩٧٣ الصادر بتاريخ ٢٦ / ١٢ / ١٩٧٣، وبناء على ما عرضه وزير الدولة للشؤون الخارجية. رسمنا بما هو آت المادة ١ يعين السيد / محمد عارف الحوكي بدرجة سفير بوزارة الخارجية. المادة ٢ على وزير الدولة للشؤون الخارجية تنفيذ هذا المرسوم ويعمل به اعتبارا من تاريخه. صدر في: ١٦ ذي القعدة ١٣٩٤هـ الموافق: ١ ديسمبر ١٩٧٤م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٦٩) الصادر في ١٥ / ١٢ / ١٩٧٤م
-------------------
Title: مرسوم سلطاني رقم ٥٣ / ٧٤ بإضافة أعضاء جدد إلى مجلس التنمية
Word count: 96
id: https://qanoon.om/p/1974/rd1974053/
Text:
نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على المرسوم السلطاني رقم ٤١ / ٧٤ الخاص بتشكيل مجلس التنمية، وبناء على ما عرضه علينا أعضاء المجلس. قررنا ما يلي المادة ١ يضاف إلى عضوية مجلس التنمية كل من: وزير شؤون الأراضي. وزير الدولة ووالي ظفار. المادة ٢ على المعنيين بالأمر تنفيذ هذا المرسوم ويعمل به من تاريخه. المادة ٣ ينشر هذا المرسوم في الجريدة الرسمية. صدر في: ٢٤ ذي القعدة ١٣٩٤هـ الموافق: ٩ ديسمبر ١٩٧٤م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٦٩) الصادر في ١٥ / ١٢ / ١٩٧٤م

In [6]:
df_clean = df_clean[(df_clean['text_word_count'] >= 70)]
print("\nآمار طول متن:")
print(df_clean['text_word_count'].describe())

آمار طول متن:
count      7522.000000
mean        960.162191
std        3574.620576
min          71.000000
25%         125.000000
50%         195.000000
75%         692.000000
max      220969.000000
Name: text_word_count, dtype: float64

In [7]:
texts_q1 = df_clean[df_clean['text_word_count'] < 132]

for i, row in texts_q1.iterrows():
    print("\n-----------------")
    print("link:", row['canonical_link'])
    print("Title:", row['title'])
    print("Word count:", row['text_word_count'])
    print("Text :")
    print(row['text'])

print("-----------")
print("total news :", len(texts_q1))

-----------------
link: https://qanoon.om/p/1974/rd1974006/
Title: مرسوم سلطاني رقم ٦ / ٧٤ بخصوص إعادة تنظيم دائرة الحسابات والخزينة
Word count: 98
Text :
نحن قابوس بن سعيد سلطان عمان نظرا لما تقتضيه المصلحة العامة فقد قررنا إعادة تنظيم دائرة الحسابات والخزينة. رسمنا بما هو آت المادة ١ تسمى هذه الدائرة بدائرة المالية بدلا من دائرة الحسابات والخزينة. المادة ٢ تقع مسؤولة هذه الدائرة على مستشار الشؤون المالية. المادة ٣ تستقل دائرة تدقيق الحسابات عن دائرة المالية وتكون تحت مسؤولية وزارة شؤون الديوان السلطاني. المادة ٤ ينشر هذا المرسوم في الجريدة الرسمية. صدر في: ١٩ محرم ١٣٩٤هـ الموافق: ١٢ فبراير ١٩٧٤م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٥٠) الصادر في ٢ / ٣ / ١٩٧٤م

-----------------
link: https://qanoon.om/p/1974/rd1974011/
Title: مرسوم سلطاني رقم ١١ / ٧٤ بتعديل الفقرة (٣) من المادة (٢) من قانون الجنسية العماني رقم (١) لسنة ١٩٧٢
Word count: 126
Text :
بعد الاطلاع على قانون الجنسية العمانية رقم (١) لسنة ١٩٧٢ وبناء على ما عرضه معالي وزير الداخلية والعدل على صاحب الجلالة السلطان المعظم. فقد تقرر مايلي المادة ١ تعدل المادة ٢ فقرة ٣ من القانون كالآتي: أن يسبق طلبه إقامة فعلية متواصلة وشرعية في عمان لمدة لا تقل عن عشر سنوات ولا مانع من أن يترك البلد بين حين وآخر في مهماته الخاصة على أن لا تكون فترة غيابه في سنة تتجاوز الشهرين، أما إذا كان متزوجا بعمانية فتخفض مدة الإقامة إلى خمس سنين بعد الزواج. المادة ٢ ينشر هذا التعديل في الجريدة الرسمية. صدر في: ١٧ صفر ١٣٩٤هـ الموافق: ١٢ مارس ١٩٧٤م حمد بن حمود وزير شؤون الديوان السلطاني نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٥٢) الصادر في ١ / ٤ / ١٩٧٤م

-----------------
link: https://qanoon.om/p/1974/rd1974014/
Title: مرسوم سلطاني رقم ١٤ / ٧٤ بالتصديق على اتفاقية تأسيس المصرف الدولي العربي للتجارة الخارجية والتنمية والنظام الأساسي المرافق لها
Word count: 102
Text :
نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على اتفاقية تأسيس المصرف العربي الدولي للتجارة الخارجية والتنمية بين كل من سلطنة عمان وجمهورية مصر العربية والجمهورية العربية الليبية، والنظام الأساسي المرافق للاتفاقية والموقع عليها منا بتاريخ ٢٤ / ٩ / ١٩٧٣. قررنا المادة ١ التصديق على اتفاقية تأسيس المصرف العربي الدولي للتجارة الخارجية والتنمية والنظام الأساسي المرافق لها. المادة ٢ ينشر هذا المرسوم في الجريدة الرسمية ويعتبر نافذا ويعمل به من تاريخ نشره. صدر في: ٢٠ صفر١٣٩٤هـ الموافق: ١٤ مارس ١٩٧٤م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٥٣) الصادر في ١٥ / ٤ / ١٩٧٤م

-----------------
link: https://qanoon.om/p/1974/rd1974017/
Title: مرسوم سلطاني رقم ١٧ / ٧٤ بالتصديق على اتفاقية تأسيس البنك العربي للتنمية الاقتصادية في أفريقيا والنظام الأساسي المرافق لها
Word count: 92
Text :
نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على اتفاقية تأسيس البنك العربي للتنمية الاقتصادية في أفريقيا بين حكومات الجامعة العربية والموقع عليها بتاريخ ١١ مارس ١٩٧٤. رسمنا بما هو آت المادة ١ التصديق على اتفاقية تأسيس البنك العربي للتنمية الاقتصادية في أفريقيا والنظام الأساسي المرافق لها. المادة ٢ ينشر هذا المرسوم في الجريدة الرسمية ويعتبر نافذا به من تاريخ نشره. صدر في: ١٣ ربيع الثاني ١٣٩٤هـ الموافق: ٦ مايو ١٩٧٤م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٥٥) الصادر في ١٥ / ٥ / ١٩٧٤م

-----------------
link: https://qanoon.om/p/1974/rd1974030/
Title: مرسوم سلطاني رقم ٣٠ / ٧٤ بتعيين سكرتير أول في وزارة الخارجية
Word count: 105
Text :
نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على المادتين (٦) و (٦٠) من قانون السلكين الدبلوماسي والقنصلي رقم ٤٦ لسنة ١٩٧٣ الصادر في ٢٦ / ١٢ / ١٩٧٣، وبناء على ما عرضه علينا وزير الدولة للشؤون الخارجية. رسمنا بما هو آت المادة ١ يعين السيد / اسماعيل مبارك ابراهيم بدرجة سكرتير أول في وزارة الخارجية. المادة ٢ على وزير الدولة للشؤون الخارجية تنفيذ هذا المرسوم ويعمل به اعتبار من تاريخه وينشر في الجريدة الرسمية. صدر في: ١٠ رجب ١٣٩٤هـ الموافق: ٢٩ يوليو ١٩٧٤م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٦١) الصادر في ١٥ / ٨ / ١٩٧٤م

-----------------
link: https://qanoon.om/p/1974/rd1974031/
Title: مرسوم سلطاني رقم ٣١ / ٧٤ بتعيين مستشار في وزارة الخارجية
Word count: 102
Text :
نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على المادتين (٦) و (٦٠) من قانون السلكين الدبلوماسي والقنصلي رقم ٤٦ لسنة ١٩٧٣ الصادر في ٢٦ / ١٢ / ١٩٧٣، وبناء على ما عرضه وزير الدولة للشؤون الخارجية. رسمنا بما هو آت المادة ١ يعين السيد / عبدالمنعم النكلاوي بدرجة مستشار في وزارة الخارجية. المادة ٢ على وزير الدولة للشؤون الخارجية تنفيذ هذا المرسوم ويعمل به اعتبارا من تاريخه وينشر في الجريدة الرسمية. صدر في: ١٠ رجب ١٣٩٤هـ الموافق: ٢٩ يوليو ١٩٧٤م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٦١) الصادر في ١٥ / ٨ / ١٩٧٤م

-----------------
link: https://qanoon.om/p/1974/rd1974032/
Title: مرسوم سلطاني رقم ٣٢ / ٧٤ بتعيين وزير مفوض في وزارة الخارجية
Word count: 103
Text :
نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على المادتين (٦) و (٦٠) من قانون السلكين الدبلوماسي والقنصلي رقم ٤٦ لسنة ١٩٧٣ الصادر في ٢٦ / ١٢ / ١٩٧٣، وبناء على ما عرضه وزير الدولة للشؤون الخارجية. رسمنا بما هو آت المادة ١ يعين السيد / مختار محمد الزواري بدرجة وزير مفوض في وزارة الخارجية. المادة ٢ على وزير الدولة للشؤون الخارجية تنفيذ هذا المرسوم ويعمل به من تاريخه وينشر في الجريدة الرسمية. صدر في: ١٠ رجب ١٣٩٤هـ الموافق: ٢٩ يوليو ١٩٧٤م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٦١) الصادر في ١٥ / ٨ / ١٩٧٤م

-----------------
link: https://qanoon.om/p/1974/rd1974039/
Title: مرسوم سلطاني رقم ٣٩ / ٧٤ بتعيين مستشار بوزارة الخارجية
Word count: 108
Text :
نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على المادتين (٦) و (٦٠) من قانون السلكين الدبلوماسي والقنصلي رقم ٤٦ / ٧٣ الصادر بتاريخ ٢٦ / ١٢ / ١٩٧٣، وبناء على ما عرضه علينا وزير الدولة للشؤون الخارجية. رسمنا بما هو آت المادة ١ يعين السيد / عادل محمد سعيد فضل بدرجة مستشار بوزارة الخارجية. المادة ٢ على وزير الدولة للشؤون الخارجية تنفيذ هذا المرسوم ويعمل به اعتبارا من ١ / ٩ / ١٩٧٤ وينشر في الجريدة الرسمية. صدر في: ٢٦ شعبان ١٣٩٤هـ الموافق: ١٤ سبتمبر ١٩٧٤م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٦٨) الصادر في ١ / ١٢ / ١٩٧٤م

-----------------
link: https://qanoon.om/p/1974/rd1974041/
Title: مرسوم سلطاني رقم ٤١ / ٧٤ بتشكيل مجلس للتنمية
Word count: 99
Text :
نحن قابوس بن سعيد سلطان عمان نظرا لما تقتضيه المصلحة العامة ونظرا لما للتنمية من أهمية بالغة. فقد قررنا المادة ١ تشكيل مجلس للتنمية برئاستنا وعضوية كل من: وزير الدولة للشؤون الخارجية مساعدا وزير الداخلية عضوا وزير الصحة عضوا وزير المواصلات عضوا وزير التجارة والصناعة عضوا وزير الزراعة والأسماك والنفط والمعادن عضوا مندوبا عن المالية عضوا المادة ٢ ينشر هذا المرسوم في الجريدة الرسمية ويعمل به من تاريخه. صدر في: ٣ ذو القعدة ١٣٩٤هـ الموافق: ١٧ نوفمبر ١٩٧٤م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٦٨) الصادر في ١ / ١٢ / ١٩٧٤م

-----------------
link: https://qanoon.om/p/1974/rd1974044/
Title: مرسوم سلطاني رقم ٤٤ / ٧٤ بتشكيل مجلس للشؤون المالية
Word count: 77
Text :
نحن قابوس بن سعيد سلطان عمان بناء على ما تقتضيه المصلحة العامة. رسمنا بما هو آت المادة ١ يشكل مجلس للشؤون المالية برئاستنا وعضوية كل من: قيس عبدالمنعم الزواوي نائبا لنا المستشارون الاقتصاديون أعضاء المادة ٢ ينشر هذا المرسوم في الجريدة الرسمية ويعمل به من تاريخه. صدر في: ١٧ ذي القعدة ١٣٩٤هـ الموافق: ٢ ديسمبر ١٩٧٤م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٦٩) الصادر في ١٥ / ١٢ / ١٩٧٤م

-----------------
link: https://qanoon.om/p/1974/rd1974045/
Title: مرسوم سلطاني رقم ٤٥ / ٧٤ بشأن تخويل حق التوقيع على المعاملات المالية الداخلية والخارجية
Word count: 125
Text :
نحن قابوس بن سعيد سلطان عمان بناء على ما تقتضيه المصلحة العامة، وبعد موافقتنا على ما عرضه نائب مجلس المالية. قررنا ما يلي المادة ١ خولنا في التوقيع على المعاملات المالية الخارجية لكل من: أ) نائب مجلس المالية. ب) المستشار الاقتصادي. المادة ٢ خولنا حق التوقيع على المعاملات المالية الداخلية لكل من: أ) نائب مجلس المالية. ب) الوكيل المساعد لدائرة المالية. المادة ٣ يلغى كل مرسوم أو قرار سابق يتعارض وهذا المرسوم. المادة ٤ على كافة الوزارات والدوائر الحكومية تنفيذ هذا المرسوم ويعمل به من تاريخه. المادة ٥ ينشر هذا المرسوم في الجريدة الرسمية. صدر في: ١٧ ذي القعدة ١٣٩٤هـ الموافق: ٢ ديسمبر ١٩٧٤م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٦٩) الصادر في ١٥ / ١٢ / ١٩٧٤م

-----------------
link: https://qanoon.om/p/1974/rd1974046/
Title: مرسوم سلطاني رقم ٤٦ / ٧٤ بتعيين سفير في وزارة الخارجية
Word count: 97
Text :
نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على المادة (٦) من قانون السلكين الدبلوماسي والقنصلي رقم ٤٦ لسنة ١٩٧٣ الصادر بتاريخ ٢٦ / ١٢ / ١٩٧٣، وبناء على ما عرضه وزير الدولة للشؤون الخارجية. رسمنا بما هو آت المادة ١ يعين السيد / محمد عارف الحوكي بدرجة سفير بوزارة الخارجية. المادة ٢ على وزير الدولة للشؤون الخارجية تنفيذ هذا المرسوم ويعمل به اعتبارا من تاريخه. صدر في: ١٦ ذي القعدة ١٣٩٤هـ الموافق: ١ ديسمبر ١٩٧٤م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٦٩) الصادر في ١٥ / ١٢ / ١٩٧٤م

-----------------
link: https://qanoon.om/p/1974/rd1974048/
Title: مرسوم سلطاني رقم ٤٨ / ٧٤ بتعيين مستشار للمراسم بديوان جلالة السلطان
Word count: 73
Text :
نحن قابوس بن سعيد سلطان عمان قررنا الآتي المادة ١ يعين الاستاذ نورالدين أحمد فرغل مستشارا للمراسم في ديواننا اعتبارا من تاريخ إعارته من القصر الجمهوري بجمهورية مصر العربية. المادة ٢ ينشر هذا المرسوم في الجريدة الرسمية ويعمل به من تاريخ نشره. صدر في: ٢٤ ذي القعدة ١٣٩٤هـ الموافق: ٩ ديسمبر ١٩٧٤م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٦٩) الصادر في ١٥ / ١٢ / ١٩٧٤م

-----------------
link: https://qanoon.om/p/1974/rd1974051/
Title: مرسوم سلطاني رقم ٥١ / ٧٤ بنقل وتعيين موظف
Word count: 115
Text :
نحن قابوس بن سعيد سلطان عمان ونظرا لما تقتضيه المصلحة العامة، وبناء على ما عرضه علينا وزير الزراعة والأسماك والنفط والمعادن. رسمنا بما هو آت المادة ١ ينقل السيد / سالم محمد عبدالله شعبان من وزارة الشؤون الاجتماعية والعمل إلى وزارة الزراعة والأسماك والنفط والمعادن. المادة ٢ يعين السيد / سالم محمد عبدالله شعبان بدرجة وكيل مساعد للشؤون الفنية بوزارة الزراعة والأسماك والنفط والمعادن. المادة ٣ على المعنيين بالأمر تنفيذ هذا المرسوم ويعمل به من تاريخه. المادة ٤ ينشر هذا المرسوم في الجريدة الرسمية. صدر في: ٢٤ ذي القعدة ١٣٩٤هـ الموافق: ٩ ديسمبر ١٩٧٤م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٦٩) الصادر في ١٥ / ١٢ / ١٩٧٤م

-----------------
link: https://qanoon.om/p/1974/rd1974052/
Title: مرسوم سلطاني رقم ٥٢ / ٧٤ بإلغاء الضرائب الجمركية على الصادرات التي لا تتعارض واحتياجات الاستهلاك المحلي
Word count: 90
Text :
نحن قابوس بن سعيد سلطان عمان تحقيقا للمصلحة العامة وتشجيعا للإنتاج الوطني. نرسم بما يلي المادة ١ تلغى الضرائب الجمركية على الصادرات التي لا تتعارض واحتياجات الاستهلاك المحلي. المادة ٢ يقوم وزير التجارة والصناعة من وقت لآخر بإصدار لوائح بأسماء المواد المعفاة من الضرائب حسب هذا المرسوم. المادة ٣ ينشر هذا المرسوم في الجريدة الرسمية ويعمل به من تاريخه. صدر في: ٢٤ ذي القعدة ١٣٩٤هـ الموافق: ٩ ديسمبر ١٩٧٤م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٦٩) الصادر في ١٥ / ١٢ / ١٩٧٤م

-----------------
link: https://qanoon.om/p/1974/rd1974053/
Title: مرسوم سلطاني رقم ٥٣ / ٧٤ بإضافة أعضاء جدد إلى مجلس التنمية
Word count: 96
Text :
نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على المرسوم السلطاني رقم ٤١ / ٧٤ الخاص بتشكيل مجلس التنمية، وبناء على ما عرضه علينا أعضاء المجلس. قررنا ما يلي المادة ١ يضاف إلى عضوية مجلس التنمية كل من: وزير شؤون الأراضي. وزير الدولة ووالي ظفار. المادة ٢ على المعنيين بالأمر تنفيذ هذا المرسوم ويعمل به من تاريخه. المادة ٣ ينشر هذا المرسوم في الجريدة الرسمية. صدر في: ٢٤ ذي القعدة ١٣٩٤هـ الموافق: ٩ ديسمبر ١٩٧٤م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٦٩) الصادر في ١٥ / ١٢ / ١٩٧٤م

-----------------
link: https://qanoon.om/p/1974/rd1974054/
Title: مرسوم سلطاني رقم ٥٤ / ٧٤ بإنشاء ديوان تشريفات جلالة السلطان المعظم
Word count: 111
Text :
نحن قابوس بن سعيد سلطان عمان نظرا لما تقتضيه المصلحة العامة واستكمالا لمقومات نهضة عمان. قررنا الآتي المادة ١ ينشأ ديوان تشريفات لنا. المادة ٢ يقوم الديوان بتخطيط وتنظيم قواعد المراسم للسلطنة بصفة عامة وما يختص بنا بصفة خاصة. المادة ٣ على جميع الجهات المعنية بالمراسم في السلطنة تنسيق ما يخص مراسم السلطنة في المناسبات المختلفة مع ديوان التشريفات وإقرارها منه وبصفة خاصة ما يتعلق بنا وضيوفنا. المادة ٤ ينشر هذا المرسوم في الجريدة الرسمية ويعمل به من تاريخ نشره. صدر في: ٢٤ ذي القعدة ١٣٩٤هـ الموافق: ٩ ديسمبر ١٩٧٤م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٦٩) الصادر في ١٥ / ١٢ / ١٩٧٤م

-----------------
link: https://qanoon.om/p/1974/rd1974055/
Title: مرسوم سلطاني رقم ٥٥ / ٧٤ بتكليف وزير المواصلات القيام بأعمال مساعد رئيس مجلس التنمية بالوكالة
Word count: 91
Text :
نحن قابوس بن سعيد سلطان عمان بناء على ما عرضه علينا مساعد رئيس مجلس التنمية رسمنا بما هو آت المادة ١ يكلف المهندس عبدالحافظ سالم رجب وزير المواصلات بالقيام بأعمال مساعد رئيس مجلس التنمية بالوكالة، في فترات غيابه في الخارج. المادة ٢ على المعنيين بالأمر تنفيذ هذا المرسوم ويعمل به من تاريخه. المادة ٣ ينشر هذا المرسوم في الجريدة الرسمية. صدر في: ١٦ ذي الحجة ١٣٩٤هـ الموافق: ٢٩ ديسمبر ١٩٧٤م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٧١) الصادر في ١٥ / ١ / ١٩٧٥م

-----------------
link: https://qanoon.om/p/1974/rd1974056/
Title: مرسوم سلطاني رقم ٥٦ / ٧٤ بترقية موظفين بوزارة الخارجية إلى درجة سفير وآخر إلى درجة وزير مفوض
Word count: 103
Text :
نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على القانون الخاص بنظام السلكين الدبلوماسي والقنصلي لعام ١٩٧٥، وبناء على ما عرضه علينا وزير الدولة للشؤون الخارجية قررنا ما يلي المادة ١ يرقى الشيخ عبدالله أحمد الغزالي إلى درجة سفير. المادة ٢ يرقى سالم محمد الغيلاني إلى درجة سفير. المادة ٣ يرقى سالم أحمد خلفان إلى درجة وزير مفوض. المادة ٤ يعمل بهذا المرسوم اعتبارا من أول يناير ١٩٧٥، وينشر في الجريدة الرسمية. صدر في: ١٦ ذي الحجة ١٣٩٤هـ الموافق: ٢٩ ديسمبر ١٩٧٤م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٧١) الصادر في ١٥ / ١ / ١٩٧٥م

-----------------
link: https://qanoon.om/p/1975/rd1975001/
Title: مرسوم سلطاني رقم ١ / ٧٥ بالمصادقة على قرارين وزاريين صادرين من وزير المواصلات
Word count: 131
Text :
نحن قابوس بن سعيد سلطان عمان بناء على ما عرضه علينا وزير المواصلات، وبعد الاطلاع على القرارين الوزاريين رقم روم / ٤ – ع / ٤ / ٩٠٧١ و روم / ٤ – ع / ٤ / ٩٠٧٢ الصادرين بتاريخ ٢٧ / ١١ / ١٩٧٤. رسمنا بما هو آت المادة ١ نصادق على ما جاء في القرارين رقم روم / ٤ – ع / ٤ / ٩٠٧١ و روم / ٤ – ع / ٤ / ٩٠٧٢ بتعيين وكيلين مساعدين لدائرة المياه ودائرة النقليات بوزارة المواصلات. المادة ٢ على المعنيين بالأمر تنفيذ هذا المرسوم اعتبارا من تاريخه، وينشر في الجريدة الرسمية. صدر في: ٤ محرم ١٣٩٥هـ الموافق: ١٦ يناير ١٩٧٥م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٧٢) الصادر في ١ / ٢ / ١٩٧٥م

-----------------
link: https://qanoon.om/p/1975/rd1975002/
Title: مرسوم سلطاني رقم ٢ / ٧٥ بالمصادقة على قرارين وزاريين صادرين من وزير الزراعة والأسماك والنفط والمعادن
Word count: 102
Text :
نحن قابوس بن سعيد سلطان عمان بناء على ما عرضه علينا وزير الزراعة والأسماك والنفط والمعادن، وبعد الاطلاع على القرارين الوزاريين رقم ١ و٢ الصادرين بتاريخ ٩ / ١٢ / ١٩٧٤. رسمنا بما هو آت المادة ١ نصادق على ما جاء في القرارين رقم ١ و٢ بتعيين وكيلين مساعدين لشؤون الثروة السمكية والإدارة العامة بوزارة الزراعة والأسماك والنفط والمعادن. المادة ٢ ينشر هذا المرسوم في الجريدة الرسمية ويعمل به اعتبارا من تاريخه. صدر في: ٤ محرم ١٣٩٥هـ الموافق: ١٦ يناير ١٩٧٥م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٧٢) الصادر في ١ / ٢ / ١٩٧٥م

-----------------
link: https://qanoon.om/p/1975/rd1975004/
Title: مرسوم سلطاني رقم ٤ / ٧٥ بنقل وكيل وزارة المواصلات إلى مجلس التنمية، وتعيينه وكيلا لشؤون التخطيط
Word count: 88
Text :
نحن قابوس بن سعيد سلطان عمان بناء على ما تقتضيه المصلحة العامة. رسمنا بما هو آت المادة ١ ينقل المهندس سيف سالم المعمري من وزارة المواصلات إلى مجلس التنمية. المادة ٢ يعين المذكور وكيلا لشؤون التخطيط بمجلس التنمية. المادة ٣ على المعنيين بالأمر تنفيذ هذا المرسوم اعتبارا من ١ / ١ / ١٩٧٥، وينشر في الجريدة الرسمية. صدر في: ١٨ ذو الحجة ١٣٩٤هـ الموافق: ١ يناير ١٩٧٥م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٧٣) الصادر في ١٥ / ٢ / ١٩٧٥م

-----------------
link: https://qanoon.om/p/1975/rd1975005/
Title: مرسوم سلطاني رقم ٥ / ٧٥ بوقف العمل بقانون إدارة الكهرباء
Word count: 117
Text :
نحن قابوس بن سعيد سلطان عمان بناء على ما عرضه علينا وزير المواصلات ونظرا لما اقتضته المصلحة العامة. رسمنا بما هو آت المادة ١ يوقف العمل بقانون إدارة الكهرباء بعمان الصادر بموجب مرسوم سابق بتاريخ ١٧ شوال ١٣٩٣ الموافق ١٣ نوفمبر ١٩٧٣، والمنشور في الجريدة الرسمية رقم (٤٤) الصادرة في ١ / ١٢ / ١٩٧٣، وذلك حتى إشعار آخر. المادة ٢ على وزير المواصلات تسيير أعمال دائرة الكهرباء طبقا للقوانين والأنظمة المتبعة في الدولة. المادة ٣ على كافة المعنيين بالأمر تنفيذ هذا المرسوم وينشر في الجريدة الرسمية. صدر في: ٢٣ محرم ١٣٩٥هـ الموافق: ٤ فبراير ١٩٧٥م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٧٣) الصادر في ١٥ / ٢ / ١٩٧٥م

-----------------
link: https://qanoon.om/p/1975/rd1975007/
Title: مرسوم سلطاني رقم ٧ / ٧٥ بترقية موظف بوزارة الخارجية إلى درجة وزير مفوض
Word count: 106
Text :
نحن قابوس بن سعيد سلطان عمان، بعد الاطلاع على المادة (١٢) من قانون السلكين الدبلوماسي والقنصلي رقم ٥٠ / ٧٤ الصادر بتاريخ ٧ / ١٢ / ١٩٧٤، وبناء على ما عرضه علينا وزير الدولة للشؤون الخارجية. رسمنا بما هو آت المادة ١ يرقى السيد / فولاذ محمد حديد إلى درجة وزير مفوض بوزارة الخارجية. المادة ٢ على وزير الدولة للشؤون الخارجية تنفيذ هذا المرسوم اعتبارا من ١ / ٢ / ١٩٧٥، وينشر في الجريدة الرسمية. صدر في: ٤ صفر ١٣٩٥هـ الموافق: ١٥ شباط (فبراير) ١٩٧٥م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٧٤) الصادر في ١ / ٣ / ١٩٧٥م

-----------------
link: https://qanoon.om/p/1975/rd1975008/
Title: مرسوم سلطاني رقم ٨ / ٧٥ بتعيين مستشار شؤون النفط بوزارة الزراعة والأسماك والنفط والمعادن نائبا لرئيس مجلس محافظي البنك المركزي العماني ورئيسا تنفيذيا له بالإضافة إلى عمله
Word count: 109
Text :
نحن قابوس بن سعيد سلطان عمان نظرا لما تقتضيه المصلحة العامة، وبناء على ما عرضه علينا نائب رئيس مجلس المالية، وبعد الرجوع إلى قانون الأعمال المصرفية الصادر عام ١٩٧٤. رسمنا بما هو آت المادة ١ يعين الدكتور يوسف نعمة الله نائبا لرئيس مجلس محافظي البنك المركزي العماني ورئيسا تنفيذيا له اعتبارا من أول يناير ١٩٧٥ على أن يبقى مستشارا لشؤون النفط بوزارة الزراعة والأسماك والنفط والمعادن. المادة ٢ على المعنيين بالأمر تنفيذ هذا المرسوم وينشر في الجريدة الرسمية. صدر في: ٤ صفر ١٣٩٥هـ الموافق: ١٥ شباط (فبراير) ١٩٧٥م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٧٤) الصادر في ١ / ٣ / ١٩٧٥م

-----------------
link: https://qanoon.om/p/1975/rd1975012/
Title: مرسوم سلطاني رقم ١٢ / ٧٥ بترقية موظفين إلى درجة مدير بديوان تشريفات جلالة السلطان المعظم
Word count: 82
Text :
نحن قابوس بن سعيد سلطان عمان بناء على ما تقتضيه المصلحة العامة. رسمنا بما هو آت المادة ١ يرقى جمعان محمد الشب مديرا لدائرة المحاسبة في ديوان تشريفاتنا بصلالة. المادة ٢ يرقى الرائد جابر تسكر مديرا في ديوان تشريفاتنا. المادة ٣ على المعنيين بالأمر تنفيذ هذا المرسوم وينشر في الجريدة الرسمية. صدر في: ٢٠ ربيع الأول ١٣٩٥هـ الموافق: ٢ أبريل ١٩٧٥م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٧٧) الصادر في ١٥ / ٤ / ١٩٧٥م

-----------------
link: https://qanoon.om/p/1975/rd1975013/
Title: مرسوم سلطاني رقم ١٣ / ٧٥ بإضافة أعضاء جدد إلى مجلس إدارة غرفة تجارة وصناعة عمان
Word count: 112
Text :
نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على النظام العام لغرفة التجارة والصناعة بعمان الصادر في ١٥ مايو ١٩٧٣ وخاصة على المادة (٢٩) منه، وبناء على ما اقترحه علينا المنتخبون الثمانية في مجلس إدارة الغرفة. رسمنا بما هو آت المادة ١ ينضم إلى مجلس الإدارة الأعضاء التالية أسماؤهم: ١- سالم بن عبدالله بن حامد الاسحاقي. ٢- سالم بن هلال الخليلي. ٣- محمد عبدالرسول الجمالي. ٤- عامر المعشني. المادة ٢ ينشر هذا المرسوم في الجريدة الرسمية ويعمل به من تاريخ نشره. صدر في: ٢٥ ربيع الأول ١٣٩٥هـ الموافق: ٧ أبريل ١٩٧٥م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٧٧) الصادر في ١٥ / ٤ / ١٩٧٥م

-----------------
link: https://qanoon.om/p/1975/rd1975014/
Title: مرسوم سلطاني رقم ١٤ / ٧٥ بتعيين وكيل للمديرية العامة للمالية
Word count: 79
Text :
نحن قابوس بن سعيد سلطان عمان نظرا لما تقتضيه المصلحة العامة وبناء على ما عرضه علينا نائب مجلس المالية. رسمنا بما هو آت المادة ١ يرقى السيد/ محمد موسى إلى درجة وكيل للمديرية العامة للمالية اعتبارا من ١ أبريل ١٩٧٥. المادة ٢ ينشر هذا المرسوم في الجريدة الرسمية. صدر في: ١٧ ربيع الأول ١٣٩٥هـ الموافق: ٣٠ مارس ١٩٧٥م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٧٨) الصادر في ١ / ٥ / ١٩٧٥م

-----------------
link: https://qanoon.om/p/1975/rd1975018/

In [8]:
from langdetect import detect

def is_english(text):
    try:
        # تشخیص زبان متن
        return detect(text) == 'en'
    except:
        # برای متن‌های خالی یا عددی که قابل تشخیص نیستند
        return False

# پیدا کردن سطرهای انگلیسی
# ماسک بولی
english_mask = df_clean['text'].apply(is_english)

print(f"تعداد سطرهای انگلیسی: {english_mask.sum()}")

# حذف سطرهای انگلیسی
df_clean = df_clean.loc[~english_mask].reset_index(drop=True)

تعداد سطرهای انگلیسی: 30

In [9]:
print(df_clean['text_word_count'].describe())

count      7492.000000
mean        939.981046
std        3545.746924
min          71.000000
25%         124.750000
50%         194.000000
75%         680.000000
max      220969.000000
Name: text_word_count, dtype: float64

In [10]:
n_samples = 200
random_samples = df_clean.sample(n=n_samples)

for i, row in random_samples.iterrows():
    print("Title:", row['title'])

Title: مرسوم سلطاني رقم ٦١ / ٢٠١٠ بمنح الدرجة الخاصة
Title: مرسوم سلطاني رقم ١٦ / ٢٠١٢ بتعديل بعض أحكام المرسوم السلطاني رقم ١٠ / ٢٠١٠ بتعيين أعضاء لجنة حقوق الإنسان
Title: مرسوم سلطاني رقم ٣٧ / ٧٩ بتجديد عضوية الاستاذ محمود محمد مراد في مجلس محافظي البنك المركزي العماني
Title: مرسوم سلطاني رقم ٣٣ / ٢٠٢٥ بإجراء تنقلات وتعيينات في السلك الدبلوماسي
Title: مرسوم سلطاني رقم ٦٠ / ٨٨ بإجازة اتفاقية التعاون الاقتصادي والفني بين حكومة سلطنة عمان والاتحاد الاقتصادي البلجيكي اللوكسمبورجي والتصديق عليها
Title: مرسوم سلطاني رقم ٥٨ / ٢٠١١ بتعيين عضوين في مجلس الدولة
Title: مرسوم سلطاني رقم ٨١ / ٩٧ بتعيين أعضاء المجلس البلدي لبلدية مسقط
Title: هيئة الخدمات المالية: قرار رقم خ / ٢ / ٢٠٢٥ باعتماد نماذج معايير التقارير المالية الدولية
Title: مرسوم سلطاني رقم ٢٠ / ٩٢ بالتصديق على اتفاقية تجنب الازدواج الضريبي على الدخل الناشئ عن نشاط النقل الجوي الدولي بين حكومة سلطنة عمان وحكومة جمهورية تنزانيا المتحدة
Title: الجريدة الرسمية العدد ١٥٣٩
Title: مرسوم سلطاني رقم ٤٩ / ٨١ بنقل وكيل شؤون الأراضي في وزارة شؤون الأراضي والبلديات وتعديل هيكلها التنظيمي
Title: مرسوم سلطاني رقم ١٨ / ٢٠٠٦ بتعديل المرسوم السلطاني رقم ١٨ / ٩٧ بتأسيس شركة مساهمة عمانية عامة باسم “بنك التنمية العماني” والملحق المرافق له
Title: مرسوم سلطاني رقم ٨٦ / ٩٦ بإصدار قانون معاشات ومكآفات ما بعد الخدمة لموظفي ديوان البلاط السلطاني العمانيين
Title: قانون السجون (معدل)
Title: الهيئة العامة لسوق المال: قرار رقم ١٣٢ / ٢٠٢١ بإصدار مبادئ حوكمة الشركات التي تمتلك الحكومة فيها حصصا
Title: مرسوم سلطاني رقم ٥٤ / ٢٠٢٤ بتعيين قضاة في المحكمة العليا
Title: مرسوم سلطاني رقم ٢٨ / ٨٢ بتعيين مفتش عام للشرطة والجمارك
Title: مرسوم سلطاني رقم ٨٩ / ٢٠٢٠ بإنشاء وزارة العمل وتحديد اختصاصاتها واعتماد هيكلها التنظيمي
Title: مرسوم سلطاني رقم ٣٧ / ٨٦ بالتصديق على اتفاقية تبادل الإعفاء الضريبي بين حكومة سلطنة عمان وحكومة دولة الكويت
Title: مرسوم سلطاني رقم ٩٨ / ٢٠٠٥ بإصدار قانون التوفيق والمصالحة
Title: مرسوم سلطاني رقم ٨١ / ٨٤ بنظام استحقاق الأراضي الحكومية
Title: مرسوم سلطاني رقم ٧٠ / ٩٥ بتعيين نائب لرئيس مجلس المحافظين بالبنك المركزي العماني
Title: مرسوم سلطاني رقم ٣٧ / ٩٥ بمنح امتياز إنشاء وإدارة وتشغيل شبكة الصرف الصحي بمحافظة مسقط
Title: قرار اللجنة العليا للتعامل مع فيروس كوفيد-١٩ بتاريخ ١٧ مارس ٢٠٢٠م
Title: وزارة التراث والسياحة: قرار وزاري رقم ١١٥٢ / ٢ / ٢٥١ / ٢٠٢٣ باعتبار منطقة وادي شاب منطقة سياحية
Title: مرسوم سلطاني رقم ٩١ / ٨٩ بنقل سفير إلى ديوان عام وزارة الخارجية
Title: مرسوم سلطاني رقم ٦٠ / ٩٨ برد الجنسية العمانية
Title: مرسوم سلطاني رقم ٨٩ / ٨١ بتعيين سفير السلطنة لدى جمهورية السودان الديمقراطية سفير فوق العادة ومفوض للسلطنة غير مقيم لدى جمهورية الغابون
Title: مرسوم سلطاني رقم ٢ / ٧٩ بإصدار نظام اللجنة الوطنية العمانية للتربية والثقافة والعلوم
Title: مرسوم سلطاني رقم ٧ / ٢٠٢٢ بالتصديق على اتفاقية بين حكومة سلطنة عمان وحكومة جمهورية كولومبيا حول الإعفاء المتبادل من التأشيرة لحاملي جوازات السفر الدبلوماسية والخاصة والخدمة والرسمية
Title: مرسوم سلطاني رقم ٣٣ / ٩٧ بتعيين رئيس مجلس المناقصات
Title: شرطة عمان السلطانية: قرار رقم ٥٣ / ٢٠٢٣ بتعديل بعض أحكام اللائحة التنفيذية لقانون الجمارك الموحد لدول مجلس التعاون لدول الخليج العربية
Title: وزارة التجارة والصناعة وترويج الاستثمار: قرار وزاري رقم ٢٠٩ / ٢٠٢١ باعتبار مواصفة قياسية عمانية ملزمة
Title: مرسوم سلطاني رقم ٦ / ٢٠١٧ بالتصديق على اتفاقية بين سلطنة عمان وجمهورية المجر لتجنب الازدواج الضريبي ومنع التهرب المالي بالنسبة للضرائب على الدخل
Title: مرسوم سلطاني رقم ٥٥ / ٢٠١٣ بتعديل بعض أحكام المرسوم السلطاني رقم ٨١ / ٩٨ بتأسيس شركة مساهمة عمانية مقفلة باسم “شركة صناديق الاستثمار الوطنية” والملحق المرفق به
Title: مرسوم سلطاني رقم ٥٣ / ٩٤ بتشكيل مجلس إدارة سوق مسقط للأوراق المالية
Title: مرسوم سلطاني رقم ٣٦ / ٩٩ بالتصديق على اتفاقية تجنب الازدواج الضريبي بالنسبة للضرائب على الدخل ومنع التهرب الضريبي بين حكومة سلطنة عمان وحكومة الجمهورية الإيطالية
Title: مرسوم سلطاني رقم ٧٢ / ٢٠٠٩ بالتصديق على الملحق الإضافي لتعديل اتفاقية تجنب الازدواج الضريبي ومنع التهرب الضريبي بالنسبة للضرائب على الدخل بين حكومة سلطنة عمان وحكومة جمهورية أوزبكستان
Title: مرسوم سلطاني رقم ٧١ / ٢٠٠٨ بتعديل بعض أحكام قانون التأمينات الاجتماعية
Title: مرسوم سلطاني رقم ٤٢ / ٢٠١٥ بإصدار تعديلات على بعض أحكام قانون تصنيف وثائق الدولة وتنظيم الأماكن المحمية
Title: هيئة تنظيم الاتصالات: قرار رقم ٢٢ / ٢٠٢١ بتعديل بعض أحكام الترخيص من الفئة الأولى لشركة المداخل للاستثمار (ش.م.م) لإنشاء وتشغيل نظام لتقديم خدمات الاتصالات العامة البحرية
Title: مرسوم سلطاني رقم ١٨ / ٧٨ بتعيين سفراء غير مقيمين لسلطنة عمان لدى كل من الجمهورية العربية السورية والجمهورية التركية
Title: مرسوم سلطاني رقم ٤٩ / ٨٢ بنقل سفير السلطنة لدى الجمهورية الباكستانية وتعيينه سفيرا فوق العادة ومفوضا للسلطنة لدى جمهورية الصين الشعبية
Title: البنك المركزي العماني: قرار رقم ب م / ٥٧ / ٩ / ٢٠٢٣ بإصدار لائحة نظام الخصم المباشر والشيكات المرتجعة
Title: مرسوم سلطاني رقم ٣٨ / ٨٠ بمنح الجنسية العمانية لبعض الأفراد في قوات السلطان المسلحة
Title: مرسوم سلطاني رقم ٦٣ / ٧٧ بالتصديق على اتفاقية القرض لمشروع المراكز الإدارية والاجتماعية بالمنطقة الجنوبية
Title: وزارة التجارة والصناعة: قرار وزاري رقم ٢٠١ / ٢٠١٦ بتعديل بعض أحكام قواعد وشروط انتخاب أعضاء مجالس إدارة شركات المساهمة العامة والأحكام الخاصة بمسؤولياتهم
Title: مرسوم سلطاني رقم ٨٨ / ٨٦ بتعديل بعض أحكام قانون السجل التجاري رقم ٣ / ٧٤
Title: أمر سامي: منح وسام
Title: الجريدة الرسمية العدد ١٥٧٢
Title: مرسوم سلطاني رقم ٧٢ / ٩٦ بتعديل بعض أحكام قانون التأمينات الاجتماعية
Title: وزارة العدل: قرار وزاري رقم ٥٢١ / ٢٠١٢ بتعديل بعض أحكام لائحة تنظيم أعمال الخبرة أمام المحاكم
Title: مرسوم سلطاني رقم ١٠٧ / ٢٠٠٥ بالتصديق على اتفاقية التعاون في مجال النقل البري بين حكومة سلطنة عمان وحكومة الجمهورية العربية السورية
Title: الادعاء العام: قرار رقم ١٧٨ / ٢٠١٤ بتعيين أعضاء بالادعاء العام
Title: مرسوم سلطاني رقم ١١٠ / ٢٠٠٦ بالترخيص بالجمع بين الجنسية العمانية والجنسية البريطانية
Title: وزارة الثروة الزراعية والسمكية وموارد المياه: قرار وزاري رقم ٨٢ / ٢٠٢٢ بتعديل بعض أحكام اللائحة التنفيذية لقانون المراعي وإدارة الثروة الحيوانية
Title: مرسوم سلطاني رقم ٤٤ / ٩٧ بتعيين رئيس لمجلس إدارة مؤسسة عمان للصحافة والأنباء والنشر والإعلان
Title: مرسوم سلطاني رقم ٤٨ / ٢٠٠١ بالتعيين في بعض المناصب وتعيين عضو في مجلس الدولة
Title: مرسوم سلطاني رقم ٢٩ / ٨١ بإعادة تشكيل مجلس التنمية وتعديل اختصاصاته
Title: مرسوم سلطاني رقم ٥٦ / ٩٩ بالتصديق على اتفاقية التعاون الاقتصادي والفني بين حكومة سلطنة عمان وحكومة جمهورية مصر العربية
Title: وزارة الصحة: قرار وزاري رقم ١٤ / ٨٧ بتنظيم مواعيد دوام ومناوبة الصيدليات الخاصة
Title: مرسوم سلطاني رقم ١٠٣ / ٨٢ بتعيين سفير فوق العادة ومفوض للسلطنة غير مقيم لدى كل من جمهورية يوغوسلافيا الاشتراكية – جمهورية رومانيا الاشتراكية – جمهورية مالطا
Title: وزارة الثروة الزراعية والسمكية وموارد المياه: قرار وزاري رقم ٥٢ / ٢٠٢١ بتعديل بعض أحكام القرار الوزاري رقم ٣١ / ٢٠٠٩ بإعلان مناطق حجر زراعية
Title: مرسوم سلطاني رقم ٧٤ / ٩٥ بإجازة التوقيع على اتفاقية التشجيع والحماية المتبادلة للاستثمارات بين حكومة سلطنة عمان وحكومة الجمهورية الفرنسية والتصديق عليها
Title: وزارة التجارة والصناعة: قرار وزاري رقم ١٤٨ / ٢٠١٧ باعتبار مواصفتين قياسيتين أجنبيتين مواصفات قياسية عمانية ملزمة
Title: هيئة تنظيم الخدمات العامة: قرار رقم ٢٥ / ٢٠٢٢ بتعديل بعض أحكام لائحة تنظيم خدمة المياه الصالحة للشرب
Title: مرسوم سلطاني رقم ٥٢ / ٢٠١١ بتعديل بعض أحكام المرسوم السلطاني رقم ٥٩ / ٩٦ بإنشاء المركز العماني لترويج الاستثمار وتنمية الصادرات
Title: مرسوم سلطاني رقم ٦٤ / ٨٦ بإنشاء أمانة عامة لمجلس الخدمة المدنية وتعيين أمين عام لها
Title: مرسوم سلطاني رقم ٣٩ / ٢٠٠٩ بالتجريد من الجنسية العمانية
Title: وزارة التجارة والصناعة: قرار وزاري رقم ٣١ / ٨٨ بتعديل بعض أحكام القرار الوزاري رقم ٦٤ / ٨٥ في شأن تنظيم البيع بالأسعار المخفضة
Title: وزارة التجارة والصناعة وترويج الاستثمار: قرار وزاري رقم ٣٩٢ / ٢٠٢٢ باعتبار مواصفة قياسية عمانية ملزمة
Title: مرسوم سلطاني رقم ٨٩ / ٨٤ بتقرير صفة المنفعة العامة لمشروع الخدمات للمساكن الشعبية بالعذيبة
Title: مرسوم سلطاني رقم ١٣ / ٢٠١٦ بالموافقة على انضمام سلطنة عمان إلى الاتفاقية الدولية للنظام المنسق لتصنيف وتبويب السلع
Title: مرسوم سلطاني رقم ١٤ / ٩٣ بمنح الجنسية العمانية
Title: وزارة العدل والشؤون القانونية: استدراك
Title: مرسوم سلطاني رقم ١٦ / ٨٦ بنقل مدير عام المديرية العامة للمشاريع والصيانة بديوان شؤون البلاط السلطاني إلى الدرجة الخاصة (أ)
Title: مرسوم سلطاني رقم ٩٢ / ٢٠٠٧ بإنشاء هيئة عامة للكهرباء والمياه وتعيين رئيس لها
Title: وزارة العدل والشؤون القانونية: فتوى رقم ٢٠٢٧٣٣٦٣٧
Title: مرسوم سلطاني رقم ٢١ / ٢٠١٩ بتعديل بعض أحكام المرسوم السلطاني رقم ٢ / ٩٣ بإنشاء الجمعية السلطانية العمانية لهواة اللاسلكي
Title: الهيئة العامة لحماية المستهلك: قرار وزاري رقم ٣٣٦ / ٢٠١٧ بإصدار اللائحة المالية للهيئة العامة لحماية المستهلك
Title: مرسوم سلطاني رقم ٧٢ / ٨٤ بالتصديق على الاتفاقية الثنائية بين حكومة سلطنة عمان وحكومة جمهورية قبرص بشأن الخدمات الجوية بين إقليميهما وما وراءهما
Title: مرسوم سلطاني رقم ٥٩ / ٢٠٢٣ بإنشاء سفارة لسلطنة عمان في أستراليا
Title: مرسوم سلطاني رقم ٤١ / ٢٠٠٨ بتعديل الهيكل التنظيمي لوزارة المالية وبعض المسميات
Title: وزارة الثروة الزراعية والسمكية وموارد المياه: قرار وزاري رقم ١١٧ / ٢٠٢١ بحظر استيراد الأسماك الحية من مقاطعة أستوبي (Stouby) في مملكة الدنمارك
Title: وزارة التجارة والصناعة: قرار وزاري رقم ٥١ / ٨٤ بتطبيق المواصفات القياسية العمانية للمواد المسموح بإضافتها للزيوت والدهون الغذائية
Title: وزارة العدل والشؤون القانونية: فتوى رقم ٢٢٢٧٧٠٥٢٤
Title: مرسوم سلطاني رقم ١٠١ / ٩١ بالتفويض في توقيع على اتفاقية بشأن تنظيم الخدمات الجوية بين حكومة سلطنة عمان وحكومة جمهورية بلغاريا
Title: مرسوم سلطاني رقم ٦٧ / ٢٠١٣ بإجراء تنقلات وتعيينات في السلك الدبلوماسي
Title: وزارة العدل والشؤون القانونية: فتوى رقم ١٩٢٧٢٢٨١٧
Title: مرسوم سلطاني رقم ٤٠ / ٩١ بتجديد رئاسة مقبول بن علي بن سلطان لمجلس إدارة غرفة تجارة وصناعة عمان
Title: مرسوم سلطاني رقم ٣٧ / ٧٦ بالتصديق على اتفاقية البترول المبرمة بين حكومة سلطنة عمان ومجموعة شركات ألف والموقعة من قبل معالي وزير الزراعة والأسماك والنفط والمعادن بتاريخ ٢٣ / ٩ / ١٩٧٦
Title: وزارة العدل والشؤون القانونية: فتوى رقم ٢٠٢٧٣٢٩٥٥
Title: مرسوم سلطاني رقم ١ / ٢٠٢٤ بالتصديق على الميزانية العامة للدولة للسنة المالية ٢٠٢٤م
Title: مرسوم سلطاني رقم ١٣ / ٨٣ باعتماد الهيكل التنظيمي لوزارة المواصلات
Title: هيئة تنظيم الاتصالات: قرار رقم ١٢٧ / ٢٠١٨ بتعديل بعض أحكام لائحة النفاذ والربط البيني
Title: الجريدة الرسمية العدد ١٥٤٩
Title: مرسوم سلطاني رقم ٣٤ / ٢٠١٢ بتعديل نظام الصندوق العماني للاستثمار ومرسوم إصداره
Title: مرسوم سلطاني رقم ٨٠ / ٨٨ برد الجنسية العمانية
Title: مرسوم سلطاني رقم ٣١ / ٨٠ بتفويض مندوب السلطنة الدائم لدى منظمة المؤتمر الإسلامي بالتوقيع على الاتفاقية العامة للتعاون الاقتصادي والفني والتجاري بين الدول الأعضاء في المنظمة
Title: مرسوم سلطاني رقم ٤٩ / ٩٣ بالتفويض في توقيع الاتفاق الثقافي بين سلطنة عمان وجمهورية كوريا
Title: بلدية مسقط: قرار رقم ٥٥ / ٢٠١٧ بشأن تحديد الجزاءات الإدارية على مخالفات بلدية مسقط
Title: مجلس الشؤون الإدارية للقضاء: قرار رقم ٣٠٠ / ٢٠١٧ بنقل مقر المحكمة الابتدائية في ولاية شناص
Title: وزارة العدل والشؤون القانونية: قرار وزاري رقم ٥٩ / ٢٠٢١ بتخويل صفة الضبطية القضائية لبعض موظفي وزارة التراث والسياحة
Title: وزارة التجارة والصناعة: قرار وزاري رقم ٧٤ / ٢٠١٣ بتعديل بعض أحكام لائحة تنظيم المنطقة الحرة بالمزيونة
Title: مرسوم سلطاني رقم ١٠٦ / ٢٠٠٧ بإلغاء المرسوم السلطاني رقم ٨٨ / ٩٨ في شأن نادي الصحافة
Title: مرسوم سلطاني رقم ٤٤ / ٩٢ بإجازة التنازل بين شركات المجموعة الحاصلة على حقوق الامتياز في الاتفاقية النفطية الموقعة بتاريخ ١٨ مارس ٨٤
Title: مرسوم سلطاني رقم ٥١ / ٨٥ بنقل سفير إلى ديوان عام وزارة الخارجية
Title: وزارة الشؤون القانونية: فتوى رقم ١٨٢٧٠٨٩٨٨
Title: وزارة الزراعة والثروة السمكية: قرار وزاري رقم ١٠٥ / ٢٠٢٠ بتعديل بعض أحكام القرار الوزاري رقم ٣١ / ٢٠٠٩ بإعلان مناطق حجر زراعية
Title: مرسوم سلطاني رقم ٧٨ / ٩٧ بإلغاء الهيئة العمانية للإنتاج الفني التلفزيوني
Title: مرسوم سلطاني رقم ٢٩ / ٩٩ بإجازة التوقيع والتصديق على مذكرة التفاهم بين حكومة سلطنة عمان وحكومة المملكة المتحدة لبريطانيا العظمى وأيرلندا الشمالية في شأن المجلس الثقافي البريطاني
Title: مرسوم سلطاني رقم ٧٣ / ٩٩ بتعديل المرسوم السلطاني رقم ١١٥ / ٩٤ بتحديد حالات التنازل والحجز على استحقاقات الموظفين
Title: جهاز الضرائب: قرار رقم ٧٩ / ٢٠٢٠ في شأن قواعد التقارير لكل دولة
Title: وزارة العدل والشؤون القانونية: فتوى رقم ٢١٢٧٥٢٥١٩
Title: مرسوم سلطاني رقم ١٧ / ٢٠١١ بتعيين وكيلين في وزارة القوى العاملة
Title: وزارة الشؤون القانونية: فتوى رقم ١٧٢٧٠٠٠٢٦٩٦٩
Title: مرسوم سلطاني رقم ١٢٩ / ٢٠٠٧ بتعيين سفير غير مقيم
Title: مرسوم سلطاني رقم ٨٨ / ٩٩ بإجازة تنازل شركة ترايتون عمان ريسورسز انك عن جزء من حقوقها والتزاماتها في الاتفاقية النفطية الموقعة في ١٠ يونيو ١٩٩٨م
Title: مرسوم سلطاني رقم ٦٣ / ٧٨ بتعديل اختصاصات وزارة المواصلات وهيكلها التنظيمي
Title: الهيئة العامة لسوق المال: قرار رقم خ / ٥ / ٢٠١٨ بتعديل بعض أحكام لائحة شؤون الموظفين بالهيئة العامة لسوق المال
Title: الهيئة العمانية للاعتماد الأكاديمي: قرار رقم ١٦ / ٢٠١٩ بتعديل بعض أحكام القرار رقم ٤ / ٢٠١٧ بشأن تحديد رسوم عملية تدقيق جودة البرامج التأسيسية العامة والتظلم من تقارير تدقيق جودة البرامج التأسيسية العامة
Title: وزارة الإسكان: قرار وزاري رقم ٢٠ / ٢٠٢٠ بتعديل بعض أحكام اللائحة التنفيذية لقانون الإسكان الاجتماعي
Title: مرسوم سلطاني رقم ٩١ / ٢٠٠٤ بتعيين سفير غير مقيم
Title: وزارة العمل: قرار وزاري رقم ٣٦ / ٢٠٢٣ بإصدار نظام قياس كفاية الأداء الوظيفي
Title: مرسوم سلطاني رقم ٧٦ / ٩٥ بإجازة الاتفاقية النفطية بين حكومة السلطنة ومجموعة شركات
Title: مرسوم سلطاني رقم ٦٩ / ٢٠١٤ بالتصديق على اتفاقية النقل الجوي بين حكومة سلطنة عمان وحكومة الولايات المتحدة الأمريكية
Title: مرسوم سلطاني رقم ٤٨ / ٩٨ بإصدار قانون السجون
Title: مرسوم سلطاني رقم ٨٩ / ٢٠٠٥ بتقرير صفة المنفعة العامة لمشروع إنشاء سد وادي ضيقة بولاية قريات (المرحلة الأولى)
Title: مرسوم سلطاني رقم ٥١ / ٢٠٠٢ بتعديل بعض أحكام قانون شركات التأمين
Title: مرسوم سلطاني رقم ٣١ / ٩٢ بشأن زيادة رأس مال المصارف العاملة في السلطنة
Title: وزارة القوى العاملة: قرار وزاري رقم ٢٠٠ / ٢٠١٩ بإيقاف التصريح باستقدام القوى العاملة غير العمانية بصفة مؤقتة في بعض الأعمال
Title: مرسوم سلطاني رقم ٤٤ / ٧٧ بتعديل نص المادة (٦) من الباب الثالث من المرسوم السلطاني حول المياه الإقليمية والجرف القاري والمنطقة المحصورة بالسلطنة لصيد الأسماك الصادر في ١٧ / ٧ / ١٩٧٢
Title: وزارة التعليم العالي: قرار وزاري رقم ٧٤ / ٢٠٠٤ بفرض رسوم دراسة الماجستير في القانون بكلية الشريعة والقانون
Title: مرسوم سلطاني رقم ٨٧ / ٨٤ بإصدار قانون الضمان الاجتماعي
Title: وزارة العدل والشؤون القانونية: قرار وزاري رقم ٧٠ / ٢٠٢٥ في شأن نظام تدريب المحامين المتدربين والموظفين المفوضين بالحضور والمرافعة عن وحدات الجهاز الإداري للدولة وغيرها من الأشخاص الاعتبارية العامة
Title: مرسوم سلطاني رقم ٣٣ / ٢٠٠٩ بشأن انضمام سلطنة عمان إلى اتفاقية تقديم المساعدة في حالة وقوع حادث نووي أو طارئ إشعاعي
Title: مرسوم سلطاني رقم ٥١ / ٩٧ باعتماد الهيكل التنظيمي لوزارة الإعلام
Title: شرطة عمان السلطانية: قرار رقم ٢٦ / ٩٤ بشأن استيراد المركبات ذات مقود على الجانب الأيمن
Title: أمر سامي: منح وسام
Title: المؤسسة العامة للمناطق الصناعية: قرار رقم ٢٢٠ / ٢٠١٧ بإصدار لائحة الاستثمار بالمناطق التابعة للمؤسسة العامة للمناطق الصناعية
Title: مرسوم سلطاني رقم ٧١ / ٩٢ باعتماد الهيكل التنظيمي لهيئة التدريب المهني
Title: مرسوم سلطاني رقم ٥٥ / ٩٢ بالتفويض في توقيع اتفاقية الحدود الدولية بين سلطنة عمان والجمهورية اليمنية
Title: ديوان البلاط السلطاني: قرار رقم ٤ / ٢٠١٩ بتعديل بعض أحكام القرار رقم ٣٨ / ٢٠١٣ بتشكيل اللجنة الرئيسية لمشروع كلية الأجيال لعلوم الصناعات الحرفية والمهن التقليدية
Title: مرسوم سلطاني رقم ١٠٦ / ٢٠٠٤ بالتصديق على تعديل مونتريال ١٩٩٧ وبكين ١٩٩٩ على بروتوكول مونتريال حول المواد المستنفدة لطبقة الأوزون
Title: مرسوم سلطاني رقم ٦٤ / ٢٠٢٥ بإجازة اتفاقية امتياز الاستكشاف والتعدين بين حكومة سلطنة عمان وشركة العالمية المتكاملة للهندسة ش.م.م للمنطقة رقم (51 – I)
Title: مرسوم سلطاني رقم ٥٧ / ٨٢ بتعديل دستور منظمة الصحة العالمية
Title: مرسوم سلطاني رقم ٢٧ / ٨٧ بتعيين أمين سر للجنة التخطيط للتنمية والبيئة بالمنطقة الجنوبية
Title: مرسوم سلطاني رقم ٥٣ / ٧٩ بترقية السيد سالم بن علي آل سعيد وتعيينه نائبا لمحافظ العاصمة
Title: وزارة التربية والتعليم: قرار وزاري رقم ١٩ / ٩٤ بتعديل مسمى السكرتارية العامة للجنة الوطنية العمانية للتربية والثقافة والعلوم
Title: مرسوم سلطاني رقم ١٨ / ٢٠١٨ بإنشاء كلية عمان للعلوم الصحية والمعهد العالي للتخصصات الصحية وإصدار نظامهما
Title: مرسوم سلطاني رقم ٦١ / ٧٧ بإصدار قانون الضمان الاجتماعي
Title: مرسوم سلطاني رقم ٣٩ / ٢٠٢٢ بنقل اختصاص حصر وتثمين الممتلكات من وزارة الداخلية إلى وزارة الإسكان والتخطيط العمراني
Title: مرسوم سلطاني رقم ٤٠ / ٧٦ بالتصديق على اتفاقية الحصانات والامتيازات لمنظمة المؤتمر الإسلامي
Title: هيئة تنظيم الاتصالات: قرار رقم ٢١ / ٢٠٢١ بتعديل بعض أحكام الترخيص من الفئة الأولى لشركة الربط العربي الدولية (ش.م.م) لإنشاء وتشغيل نظام لتقديم خدمات اتصالات عامة دولية
Title: مرسوم سلطاني رقم ٥١ / ٨١ بتفويض وزير النفط والمعادن في الموافقة على طلب تعديل المادة ٤ فقرة (١) أ من الاتفاقية النفطية المبرمة بين حكومة السلطنة وشركة كونتانا الدولية المحدودة
Title: المجلس العماني للاختصاصات الطبية: قرار رقم ٢٤ / ٢٠٢٤ بتعديل بعض أحكام لائحة التدريب في المجلس العماني للاختصاصات الطبية
Title: وزارة التجارة والصناعة وترويج الاستثمار: قرار رقم ٢٠٩ / ٢٠٢٠ بتحديد قائمة الأنشطة المحظور مزاولة الاستثمار الأجنبي فيها
Title: وزارة النقل والاتصالات وتقنية المعلومات: تعميم رقم ١١ / ٢٠٢٥ السياسة العامة للاستخدام الآمن والأخلاقي لأنظمة الذكاء الاصطناعي أبريل ٢٠٢٥م
Title: المركز الوطني للإحصاء والمعلومات: قرار رقم ١٠٣ / ٢٠٢٢ بإصدار استراتيجية البيانات الوطنية
Title: مرسوم سلطاني رقم ٢٩ / ٢٠١٨ بإصدار قانون حظر تملك غير العمانيين للأراضي والعقارات في بعض الأماكن
Title: مرسوم سلطاني رقم ٦٣ / ٢٠٢٥ بالتصديق على اتفاقية بين حكومة سلطنة عمان وحكومة الجمهورية الإسلامية الإيرانية بشأن التشجيع والحماية المتبادلة للاستثمارات
Title: مرسوم سلطاني رقم ٩٧ / ٩٤ بالتصديق على بعض الاتفاقيات بين سلطنة عمان وبعض الدول
Title: مرسوم سلطاني رقم ٤٤ / ٨٧ باجراء تعديلات في المرسوم السلطاني رقم ٢٥ / ٨٤ بتنظيم القضاء الجزائي
Title: قانون الجمعيات الأهلية (معدل)
Title: مرسوم سلطاني رقم ٨٧ / ٢٠٠١ بإجراء التعداد العام للسكان والمساكن والمنشآت
Title: وزارة العدل والشؤون القانونية: قرار وزاري رقم ٤ / ٢٠٢١ بتخويل صفة الضبطية القضائية لبعض موظفي وزارة النقل والاتصالات وتقنية المعلومات
Title: مرسوم سلطاني رقم ١٣٢ / ٢٠٢٠ بتعيين قاضيين في المحكمة العليا
Title: وزارة القوى العاملة: قرار وزاري رقم ١٦٨ / ٢٠٢٠ بتحديد نسبة القوى العاملة في منشآت القطاع الخاص العاملة بقطاع الثروة السمكية
Title: مرسوم سلطاني رقم ١ / ٨٨ بالتصديق على الموازنة العامة للدولة لعام ١٩٨٨م
Title: مرسوم سلطاني رقم ٢٨ / ٢٠٠٥ بتعيينات في الادعاء العام
Title: مرسوم سلطاني رقم ١٠٢ / ٢٠٠٦ بإعادة تشكيل اللجنة العليا لتخطيط المدن وتعديل بعض أحكام المرسوم السلطاني رقم ٢٧ / ٨٥
Title: وزارة التجارة والصناعة: قرار وزاري رقم ١١ / ٢٠٢٠ باعتبار مواصفات قياسية دولية مواصفات قياسية عمانية ملزمة
Title: مرسوم سلطاني رقم ٣٢ / ٢٠٢٤ بنقل موظف إلى وزارة الخارجية
Title: وزارة النقل والاتصالات: قرار وزاري رقم ١٨٦ / ٢٠١٦ بإصدار لائحة التطقيم الآمن للسفن العمانية
Title: مرسوم سلطاني رقم ٦٨ / ٨٣ بتعديل الهيكل التنظيمي لديوان شؤون البلاط السلطاني
Title: مرسوم سلطاني رقم ٩٤ / ٢٠٠٠ بإصدار قانون الخدمة ونظام معاشات ومكافآت ما بعد الخدمة لمنتسبي وزارة مكتب القصر
Title: مرسوم سلطاني رقم ٣٥ / ٩٦ بالتصديق على تعديل في اتفاقية تنظيم خدمات النقل الجوي بين سلطنة عمان وجمهورية تونس
Title: مرسوم سلطاني رقم ٤٨ / ٨٣ باعتماد اختصاصات وزارة المواصلات
Title: مرسوم سلطاني رقم ١٧ / ٨٨ بإنشاء وزارة للخدمة المدنية وتحديد اختصاصاتها
Title: مرسوم سلطاني رقم ٥٣ / ٢٠٠٥ بتعيين وكيل لوزارة التنمية الاجتماعية
Title: وزارة الشؤون القانونية: فتوى رقم ١٨٢٧٠٢٩٧٠
Title: وزارة العدل والشؤون القانونية: فتوى رقم ٢١٢٧٤٧٥١٧
Title: البنك المركزي العماني: قرار رقم م م / ٢٩١٦ / ١٧٩ / ١٢ / ١٧ / ١٦ بتعديل بعض أحكام القرار رقم ب م / ٥٥ / ٣ / ٢٠١٤ بإنشاء اللجنة العليا للاستقرار المالي وإصدار لائحتها التنظيمية
Title: مرسوم سلطاني رقم ٢٥ / ٨٧ بتعيين قائد لقوات سلطان عمان البرية
Title: مرسوم سلطاني رقم ٨ / ٩٠ بتعيين السيد خالد بن حمد بن حمود البوسعيدي بوزارة العمل والتدريب المهني
Title: مرسوم سلطاني رقم ٥٩ / ٨٣ بتعيين وكيلين لوزارة شؤون الديوان السلطاني وتحديد اختصاصاتهما
Title: مرسوم سلطاني رقم ٩ / ٢٠٢١ في شأن الهيئة العمانية للاعتماد الأكاديمي وضمان جودة التعليم
Title: وزارة الزراعة والثروة السمكية: قرار وزاري رقم ٩١ / ٢٠١٥ بتعديل القرار الوزاري رقم ٣١ / ٢٠٠٩ بإعلان مناطق حجر زراعية
Title: مرسوم سلطاني رقم ٣ / ٢٠١٦ بتقرير صفة المنفعة العامة لمشروع تطوير حديقة مرفع فلج دارس بولاية نزوى
Title: مرسوم سلطاني رقم ١٥ / ٢٠٠٠ بتعديل بعض أحكام المرسوم السلطاني رقم ٧١ / ٩٣ بإنشاء صندوق لدعم الأنشطة الرياضية
Title: وزارة الإسكان والتخطيط العمراني: قرار وزاري رقم ٩٠ / ٢٠٢٣ بمنح المؤسسات الصغيرة والمتوسطة حق الانتفاع بالأراضي المملوكة للدولة
Title: مرسوم سلطاني رقم ١٢ / ٢٠٠١ بتعديل بعض أحكام قانون مزاولة مهنة الطب البشري وطب الأسنان الصادر بالمرسوم السلطاني رقم ٢٢ / ٩٦
Title: مرسوم سلطاني رقم ٢٤ / ٧٥ في تقدير الديات والأروش
Title: مرسوم سلطاني رقم ٦٢ / ٢٠١٣ بإنشاء المتحف الوطني وإصدار نظامه

In [11]:
title_mask = df_clean[df_clean['title_word_count'] <= 11]

n_samples = 100
random_samples = title_mask.sample(n=n_samples)

for i, row in random_samples.iterrows():
    print("Title:", row['title'])


print("-----------")
print("total news :", len(title_mask))

Title: وزارة الخارجية: استدراك
Title: مرسوم سلطاني رقم ٤٩ / ٢٠١٢ بتعيين أمين عام لمجلس التعليم
Title: مرسوم سلطاني رقم ٢١ / ٨٧ بتعيين نائبين لوالي ظفار
Title: مرسوم سلطاني رقم ٥٦ / ٢٠٠٩ بمنح الجنسية العمانية
Title: الجريدة الرسمية العدد ١٤٦٤
Title: مرسوم سلطاني رقم ٦ / ٩٠ بإجراء تعديل في التشكيل الوزاري
Title: وزارة العدل والشؤون القانونية: فتوى رقم ٢٢٢٧٥٩٣٥٤
Title: وزارة العدل والشؤون القانونية: استدراك
Title: مرسوم سلطاني رقم ٩٤ / ٢٠٠٧ بإجراء تعديل وزاري
Title: مرسوم سلطاني رقم ٦٩ / ٩٥ بإجراء تعديل في التشكيل الوزاري
Title: الجريدة الرسمية العدد ١٦٢٣
Title: مرسوم سلطاني رقم ١٣ / ٢٠١١ بإجراء تعديل في التشكيل الوزاري
Title: مرسوم سلطاني رقم ٣٥ / ٢٠٠٣ بإصدار قانون العمل
Title: مرسوم سلطاني رقم ٢٤ / ٩٦ بمنح الجنسية العمانية
Title: مرسوم سلطاني رقم ٤٩ / ٩٥ بإعادة تشكيل مجلس الشؤون المالية
Title: مرسوم سلطاني رقم ٨٠ / ٧٧ بمنح الجنسية العمانية لبعض الأشخاص
Title: الجريدة الرسمية العدد ١٤٥٧
Title: مرسوم سلطاني رقم ٥٧ / ٢٠٢١ بإصدار نظام جهاز الاستثمار العماني
Title: مرسوم سلطاني رقم ٦٤ / ٢٠٢٢ برد الجنسية العمانية
Title: الجريدة الرسمية العدد ١٤٣١
Title: مرسوم سلطاني رقم ٢١ / ٧٦ في اختصاصات وزارة شؤون الشباب
Title: مرسوم سلطاني رقم ٤٧ / ٢٠٢٢ بمنح الجنسية العمانية
Title: نظام جهاز الضرائب (معدل)
Title: المرسوم السلطاني رقم ٥٢ / ٢٠٢٣ بإصدار قانون الحماية الاجتماعية (معدل)
Title: الجريدة الرسمية العدد ١٥٦٣
Title: مرسوم سلطاني رقم ٧٤ / ٢٠٠٦ بتعديل بعض أحكام قانون العمل
Title: أمر سامي: منح وسام
Title: قانون الأسلحة والذخائر (معدل)
Title: مرسوم سلطاني رقم ٦٥ / ٢٠٢٠ بتعيين وزير للزراعة والثروة السمكية
Title: مرسوم سلطاني رقم ٧٤ / ٢٠٠٩ بتعيين سفير غير مقيم
Title: مرسوم سلطاني رقم ١٣ / ٢٠١٥ بمنح الجنسية العمانية
Title: مرسوم سلطاني رقم ٥٧ / ٩٠ بتعيين قائد للبحرية السلطانية العمانية
Title: مرسوم سلطاني رقم ١٠ / ٢٠١٤ بتعيين سفير غير مقيم
Title: مرسوم سلطاني رقم ٣٠ / ٢٠٠٨ بإصدار قانون مساءلة الأحداث
Title: مرسوم سلطاني رقم ١٧ / ٢٠٠٩ برد الجنسية العمانية
Title: مرسوم سلطاني رقم ٥٧ / ٢٠١٠ بترقية موظفين إلى الدرجة الخاصة
Title: مرسوم سلطاني رقم ٥٦ / ٨٢ بإصدار القانون المالي
Title: الجريدة الرسمية العدد ١٥٦٨
Title: مرسوم سلطاني رقم ٨٢ / ٢٠٠٠ بإصدار قانون براءات الاختراع
Title: مرسوم سلطاني رقم ١٣ / ٨٢ بإجراء تعديل في التشكيل الوزاري
Title: مرسوم سلطاني رقم ٩٧ / ٢٠١١ بتعيين أعضاء مجلس الدولة
Title: قرار اللجنة العليا للتعامل مع فيروس كوفيد-١٩ بتاريخ ٢١ أكتوبر ٢٠٢٠م
Title: مرسوم سلطاني رقم ٢ / ٩٧ بتعديل مسمى وظيفي
Title: وزارة العدل والشؤون القانونية: فتوى رقم ٢٢٢٧٥٧٩٧٧
Title: مرسوم سلطاني رقم ١٣ / ٨٥ بإصدار قانون البعثات والإعانات الدراسية
Title: مرسوم سلطاني رقم ٦٩ / ٢٠٢٥ برد الجنسية العمانية
Title: الجريدة الرسمية العدد ١٤٩٤
Title: مرسوم سلطاني رقم ٣٢ / ٩٥ بتعيين وزير مفوض بوزارة الخارجية
Title: مرسوم سلطاني رقم ٦٢ / ٢٠١١ بمنح الدرجة الخاصة
Title: مرسوم سلطاني رقم ٩ / ٨٩ بتعيين مستشار بوزارة الداخلية
Title: مرسوم سلطاني رقم ٥٥ / ٢٠٠٧ بتعيين عضو في مجلس الدولة
Title: مرسوم سلطاني رقم ٦٥ / ٢٠٢٢ بمنح الجنسية العمانية
Title: مرسوم سلطاني رقم ٥ / ٧٤ بخصوص وحدة الحفر سي-اي-ثورنتون
Title: مرسوم سلطاني رقم ٩٩ / ٨٥ بتعيين رئيس للمجلس الاستشاري للدولة
Title: وزارة العدل والشؤون القانونية: فتوى رقم ٢٠٢٧٣٢٠٩١
Title: مرسوم سلطاني رقم ١٢٠ / ٢٠٠٧ بتعيين سفيرين غير مقيمين
Title: أمر سامي: منح وسام
Title: مرسوم سلطاني رقم ٣٠ / ٢٠١٠ بإصدار قانون مجلس البحث العلمي
Title: وزارة الشؤون القانونية: فتوى رقم ١٨٢٧٠٥٢٢٧
Title: الجريدة الرسمية العدد ١٤٦٠
Title: مرسوم سلطاني رقم ١٢١ / ٢٠١٠ بتعيين سفير غير مقيم
Title: الجريدة الرسمية العدد ١٥٦٩
Title: الجريدة الرسمية العدد ١٥٨١
Title: مرسوم سلطاني رقم ٢٠ / ٩٧ بتعيين سفير غير مقيم
Title: مرسوم سلطاني رقم ٢٨ / ٧٥ بتشكيل مجلس الخدمة المدنية
Title: مرسوم سلطاني رقم ١٦ / ٢٠٠٦ بتعيين أعضاء في الادعاء العام
Title: مرسوم سلطاني رقم ٣٣ / ٢٠٠٨ بتعيين سفراء غير مقيمين
Title: الجريدة الرسمية العدد ١٥٣٦
Title: مرسوم سلطاني رقم ٨٢ / ٢٠٠٣ بتعيين سفير غير مقيم
Title: مرسوم سلطاني رقم ٩٠ / ٢٠٢٢ برد الجنسية العمانية
Title: مرسوم سلطاني رقم ٧٨ / ٢٠١٩ بتعيين أمين عام لمجلس الشورى
Title: مرسوم سلطاني رقم ٤٥ / ٢٠٠٤ بإصدار قانون الحجر البيطري
Title: مرسوم سلطاني رقم ٤٧ / ٩٨ بإصدار القانون المالي
Title: مرسوم سلطاني رقم ٤١ / ٢٠٢٢ بتعيين محافظين
Title: مرسوم سلطاني رقم ٣٤ / ٢٠١٨ برد الجنسية العمانية
Title: وزارة العدل والشؤون القانونية: فتوى رقم ٢٠٢٧٣٣٦٣٧
Title: مرسوم سلطاني رقم ١١٠ / ٢٠٠٧ بشأن إحرامات مبنى وزارة الخارجية
Title: مرسوم سلطاني رقم ٩ / ٨٦ بإصدار قانون جامعة السلطان قابوس
Title: قانون البعثات والإعانات الدراسية رقم ٧ / ٧٣
Title: مرسوم سلطاني رقم ٥٣ / ٨٤ بتعيين مستشار لوزارة التجارة والصناعة
Title: مرسوم سلطاني رقم ٧٨ / ٢٠٠٣ بتعيين عضو في مجلس الدولة
Title: الجريدة الرسمية العدد ١٥٠٩
Title: وزارة الشؤون القانونية: فتوى رقم ١٨٢٧٠٠٢٦١
Title: مرسوم سلطاني رقم ٥٢ / ٢٠٠٤ بمنح الجنسية العمانية
Title: مرسوم سلطاني رقم ٧٥ / ٨٨ بمنح الجنسية العمانية
Title: مرسوم سلطاني رقم ٧٠ / ٢٠٠٩ بتعيين وكيلين لوزارة الخارجية
Title: مرسوم سلطاني رقم ٥٠ / ٢٠١٦ بإنشاء وحدة دعم التنفيذ والمتابعة
Title: مرسوم سلطاني رقم ٣٨ / ٨٥ بتعديل في قانون الضمان الاجتماعي
Title: الجريدة الرسمية العدد ١٦١٨
Title: مرسوم سلطاني رقم ٨ / ٢٠٢٢ بنقل موظف إلى وزارة الخارجية
Title: مرسوم سلطاني رقم ١٩ / ٢٠١٢ بتعيين سفيرة غير مقيمة
Title: وزارة العدل والشؤون القانونية: فتوى رقم ٢٣٢٧٨٣٨٦٦
Title: قرار اللجنة العليا للتعامل مع فيروس كوفيد-١٩ بتاريخ ١٢ مارس ٢٠٢١م
Title: وزارة العدل والشؤون القانونية: فتوى رقم ٢٣٢٧٩٠٠٥٢
Title: مرسوم سلطاني رقم ٨٥ / ٢٠١٠ بتعيين مستشار بوزارة الشؤون الرياضية
Title: مرسوم سلطاني رقم ٣٢ / ٢٠١٦ بمنح الجنسية العمانية
Title: مرسوم سلطاني رقم ٢ / ٢٠٠٤ بتعيين وكيل بوزارة التربية والتعليم
Title: وزارة الشؤون القانونية: فتوى رقم ١٨٢٧٠١٤٠٩
Title: قانون تنظيم أعمال الوساطة في المجالات العقارية (معدل)
Title: مرسوم سلطاني رقم ٩٤ / ٢٠٢٢ بالتعيين في بعض المناصب
-----------
total news : 2083

In [12]:
import re
import pandas as pd

# =========================
# 1. CLEANING & PRE-PROCESSING
# =========================

def clean_text(text: str) -> str:
    if not isinstance(text, str):
        return ""

    # حفاظت از نوع سندهایی که دو نقطه دارند
    protected_starts = [
        "مرسوم", "أمر", "امر", "قرار", "قانون", "بيان", "منشور", "تعميم",
        "لجنة", "إعلان", "اعلان", "ديوان"
    ]

    match = re.match(r"^([^:]+)[:：]\s*(.*)", text)
    if match:
        prefix = match.group(1).strip()
        content = match.group(2).strip()
        is_protected = any(doc in prefix for doc in protected_starts)
        if is_protected:
            text = f"{prefix} {content}"
        else:
            text = content # حذف نام وزارتخانه

    # حذف نویزهای عددی و پرانتزها
    text = re.sub(r"(رقم|عدد)?\s*[\d٠-٩]+[\s\\/\-]+[\d٠-٩]+", " ", text)
    text = re.sub(r"(العدد|رقم)\s*[\d٠-٩]+", " ", text)
    text = re.sub(r"\([\d٠-٩]+\)", " ", text)

    # یکسان‌سازی کاراکترها
    text = re.sub(r"[إأآا]", "ا", text)
    text = re.sub(r"ى\b", "ي", text) # یکسان‌سازی ی آخر

    # حذف فاصله‌های اضافی
    text = re.sub(r"\s+", " ", text).strip()

    return text

def normalize_legal_action(text: str) -> str:
    """
    توسعه گسترده دایره لغات برای پوشش موارد خاص (تخویل، تطبیق، استحداث و...)
    """
    # پیشوندها: بـ، و، لـ، فـ، کـ + (الـ) اختیاری
    prefix = r"\b(?:ب|و|ل|ف|ك)?(?:ال)?"

    actions_map = {
        # --- اعطای اختیار و صلاحیت (گروه جدید مهم) ---
        f"{prefix}تخويل\\b": "منح",      # تخويل صفة الضبطية -> منح
        f"{prefix}تولي\\b": "تكليف",      # تولي السيد... -> تكليف
        f"{prefix}تكليف\\b": "تكليف",
        f"{prefix}اسناد\\b": "تفويض",     # اسناد الاختصاصات
        f"{prefix}تسيير\\b": "تكليف",     # تسيير اعمال
        f"{prefix}اختيار\\b": "تعيين",    # اختيار من يتولى
        f"{prefix}انابة\\b": "تفويض",     # ضوابط الانابة

        # --- فنی / اجرایی / مالی ---
        f"{prefix}تطبيق\\b": "تطبيق",     # تطبيق المواصفات
        f"{prefix}العمل\\b": "تطبيق",     # العمل بمواصفات
        f"{prefix}استحداث\\b": "انشاء",   # استحداث مديريات
        f"{prefix}اضافة\\b": "تعديل",     # اضافة عضو/مادة -> نوعی اصلاح است
        f"{prefix}ضم\\b": "تعيين",        # ضم عضو -> تعيين
        f"{prefix}تحصيل\\b": "فرض",       # تحصيل رسم -> فرض
        f"{prefix}فرض\\b": "فرض",         # فرض رسم
        f"{prefix}استقطاع\\b": "فرض",     # استقطاع نسبة
        f"{prefix}الزام\\b": "الزام",     # الزام اصحاب المنشات
        f"{prefix}سماح\\b": "تصريح",      # السماح لمواطني...
        f"{prefix}ترخيص\\b": "تصريح",     # بالترخيص
        f"{prefix}ادراج\\b": "ادراج",     # ادراج في القائمة (تروریسم)
        f"{prefix}تنسيق\\b": "تنظيم",     # تنسيق العمل

        # --- موارد استاندارد (قبلی) ---
        f"{prefix}تصديق\\b": "تصديق",
        f"{prefix}مصادقة\\b": "تصديق",
        f"{prefix}اجازة\\b": "تصديق",
        f"{prefix}موافقة\\b": "تصديق",
        f"{prefix}اعتماد\\b": "اعتماد",
        f"{prefix}اصدار\\b": "اصدار",
        f"{prefix}تعديل\\b": "تعديل",
        f"{prefix}تعديلات\\b": "تعديل",
        f"{prefix}الغاء\\b": "الغاء",
        f"{prefix}تنظيم\\b": "تنظيم",
        f"{prefix}انشاء\\b": "انشاء",
        f"{prefix}تاسيس\\b": "انشاء",
        f"{prefix}تشكيل\\b": "تشكيل",
        f"{prefix}اعادة تشكيل\\b": "اعادة تشكيل",
        f"{prefix}تعيين\\b": "تعيين",
        f"{prefix}تسمية\\b": "تعيين",
        f"{prefix}نقل\\b": "نقل",
        f"{prefix}ترقية\\b": "ترقية",
        f"{prefix}ترقيات\\b": "ترقية",
        f"{prefix}منح\\b": "منح",
        f"{prefix}رد\\b": "رد",
        f"{prefix}تجريد\\b": "تجريد",
        f"{prefix}سحب\\b": "تجريد",
        f"{prefix}تنازل\\b": "تنازل",     # تنازل عن الجنسية
        f"{prefix}احالة\\b": "احالة",     # احالة الى التقاعد
        f"{prefix}استبدال\\b": "استبدال", # استبدال عضو
        f"{prefix}تفويض\\b": "تفويض",
        f"{prefix}انضمام\\b": "انضمام",
        f"{prefix}تحديد\\b": "تحديد",
        f"{prefix}تخصيص\\b": "تخصيص",
        f"{prefix}حظر\\b": "حظر",
        f"{prefix}منع\\b": "حظر",
        f"{prefix}وقف\\b": "وقف",
        f"{prefix}ايقاف\\b": "وقف",
        f"{prefix}حل\\b": "حل",
        f"{prefix}دمج\\b": "دمج",
        f"{prefix}نشر\\b": "نشر",
        f"{prefix}زيادة\\b": "زيادة",
        f"{prefix}تخفيض\\b": "تخفيض",
        f"{prefix}رفع\\b": "رفع",
        f"{prefix}اشهار\\b": "اشهار",
        f"{prefix}استثناء\\b": "استثناء",
        f"{prefix}اعفاء\\b": "اعفاء",
        f"{prefix}تجديد\\b": "تجديد",
        f"{prefix}استمرار\\b": "تجديد",
        f"{prefix}تمديد\\b": "تمديد",
        f"{prefix}تصنيف\\b": "تصنيف",
        f"{prefix}اعتبار\\b": "اعتبار",
        f"{prefix}توقيع\\b": "توقيع",
        f"{prefix}تقرير\\b": "تقرير",
        f"{prefix}بدء\\b": "بدء",
        f"{prefix}تحويل\\b": "تحويل",
        f"{prefix}تغيير\\b": "تغيير",
        f"{prefix}تصحيح\\b": "تصحيح",
        f"{prefix}تفسير\\b": "تفسير",
        f"{prefix}سريان\\b": "سريان",
        f"{prefix}تعويض\\b": "تعويض",

        # --- هندل کردن جملات اسمی (Implicit Actions) ---
        # وقتی تیتر با اسم شروع می‌شود، فعل متناظر را جایگزین می‌کنیم
        f"^{prefix}الاحكام\\b": "تنظيم الاحكام",
        f"^{prefix}القانون\\b": "اصدار القانون",
        f"^{prefix}ترخيص\\b": "منح ترخيص",
        f"^{prefix}سياسة\\b": "اعتماد سياسة", # السياسة العامة
        f"^{prefix}بيان\\b": "اصدار بيان",

        # --- نویزها ---
        f"{prefix}اجراء\\b": "",
        f"{prefix}بخصوص\\b": "تنظيم",
        r"\bخاص\s+(?:ب|ل)?": "تنظيم ",
    }

    for pattern, repl in actions_map.items():
        text = re.sub(pattern, repl, text)

    return text

# =========================
# 2. LISTS
# =========================

DOC_TYPES = [
    "مرسوم سلطاني", "مرسوم",
    "امر سامي", "امر",
    "قرار وزاري", "قرار اداري", "قرار ديواني", "قرار", "ترخيص",
    "قانون", "لائحة", "نظام", "تعميم", "منشور", "بيان", "اعلان",
    "لجنة" # برای کمیته‌های خاص
]

LEGAL_ACTIONS = [
    "تقرير صفة المنفعة العامة",
    "اعادة تشكيل", "تحديد اختصاصات",
    "تصديق", "اصدار", "تعديل", "الغاء", "تنظيم", "تغيير", "تصحيح", "تفسير",
    "انشاء", "تشكيل", "تعيين", "نقل", "ترقية", "منح",
    "رد", "تجريد", "تنازل", "احالة", "اعتماد", "تفويض", "تكليف",
    "انضمام", "تحديد", "تخصيص", "حظر", "وقف", "حل", "دمج",
    "نشر", "زيادة", "تخفيض", "رفع", "اشهار", "استثناء",
    "اعفاء", "تجديد", "تمديد", "تصنيف", "اعتبار",
    "توقيع", "تقرير", "بدء", "سريان", "تصريح",
    "الحاق", "تحويل", "فرض", "الزام", "ادراج",
    "استقطاع", "استبدال", "تعويض", "تطبيق"
]

# =========================
# 3. EXTRACTION LOGIC
# =========================

def extract_title_semantic(title_raw: str):
    clean = clean_text(title_raw)

    # فیلتر نویز مطلق
    if "الجريدة الرسمية" in clean or re.search(r"فتوى\s+رقم\s*$", clean):
        return None
    if clean.strip() in ["استدراك", "استدراك في شأن النشيد الوطني"]: # استدراک‌های بدون محتوا
        return None

    # 1. Detect Doc Type
    doc_type = None

    # هندل کردن "اللجنة العليا" و "لجنة العقوبات"
    if "اللجنة" in clean and "قرار" in clean:
         # استخراج نام کمیته به عنوان نوع سند
         match_comm = re.match(r"(.*لجنة.*?):?\s*قرار", clean)
         if match_comm:
             doc_type = "قرار لجنة"
         else:
             doc_type = "قرار"

    if not doc_type:
        sorted_doc_types = sorted(DOC_TYPES, key=len, reverse=True)
        for dt in sorted_doc_types:
            if clean.startswith(dt):
                doc_type = dt
                clean = clean[len(dt):].strip()

                # Normalize doc type
                if "قرار" in dt: doc_type = "قرار"
                if "مرسوم" in dt: doc_type = "مرسوم"
                if "امر" in dt: doc_type = "امر"
                break

    # Implicit Doc Types
    if not doc_type:
        if clean.startswith("قانون"): doc_type = "قانون"
        elif clean.startswith("ترخيص"): doc_type = "ترخيص"
        elif clean.startswith("بدمج") or clean.startswith("باصدار"): doc_type = "سند عام"

    # 2. Normalize Actions
    clean_normalized = normalize_legal_action(clean)

    # 3. Find Action (First occurrence priority)
    best_action = None
    best_index = float('inf')
    best_end_index = 0

    for act in LEGAL_ACTIONS:
        pattern = r"\b" + re.escape(act) + r"\b"
        match = re.search(pattern, clean_normalized)
        if match:
            # اولویت با فعلی است که در ابتدای جمله آمده باشد
            if match.start() < best_index:
                best_index = match.start()
                best_action = act
                best_end_index = match.end()

    # 4. Fallback Logic
    if not best_action:
        if "في شان" in clean_normalized or "بشان" in clean_normalized:
            best_action = "تنظيم"
            match = re.search(r"(في|ب)\s*شان", clean_normalized)
            if match: best_end_index = match.end()

    if not best_action and doc_type in ["قانون", "نظام", "لائحة"]:
        best_action = "اصدار"
        best_end_index = 0

    # 5. Extract Subject
    if best_action:
        subject = clean_normalized[best_end_index:].strip()
    else:
        subject = clean_normalized

    # Cleanup Subject
    subject = re.sub(r"^\s*(على|في|ب|عن|الى|ل|من)\s+", "", subject)

    # Validation
    if len(subject) < 3 or "فتوى رقم" in clean:
        return None

    if not doc_type and not best_action:
        return None

    # اگر نوع سند پیدا نشد اما فعل داریم، فرض می‌کنیم سند عمومی است
    if not doc_type and best_action:
        doc_type = "سند"

    return f"{doc_type} | {best_action} | {subject}"

# Example Usage:
df_clean["title_semantic"] = df_clean['title'].apply(extract_title_semantic)

failed_mask = df_clean['title_semantic'].isna() | (df_clean['title_semantic'].str.strip() == '')
print('تعداد نمونه‌هایی که title_semantic استخراج نشده:')
print(failed_mask.sum())
failed_df = df_clean.loc[failed_mask]

تعداد نمونه‌هایی که title_semantic استخراج نشده:
475

In [13]:
n_samples = 200
random_samples = df_clean.sample(n=n_samples)

for i, row in random_samples.iterrows():
    print("title_raw:", row['title'])
    print("Title_embd:", row['title_semantic'])
    print("--------------")

title_raw: مرسوم سلطاني رقم ٣١ / ٩٥ بتعيين سفراء غير مقيمين
Title_embd: مرسوم | تعيين | سفراء غير مقيمين
--------------
title_raw: مرسوم سلطاني رقم ٤٤ / ٢٠١٠ بتعيين سفير غير مقيم
Title_embd: مرسوم | تعيين | سفير غير مقيم
--------------
title_raw: مرسوم سلطاني رقم ٢٤ / ٨٧ بتعيين رئيس للإدارة واللوازم بوزارة الدفاع
Title_embd: مرسوم | تعيين | رئيس للادارة واللوازم بوزارة الدفاع
--------------
title_raw: وزارة التنمية الاجتماعية: قرار وزاري رقم ٢٣٥ / ٢٠١٤ بإصدار اللائحة التنظيمية لصرف الأجهزة التعويضية والوسائل المساعدة
Title_embd: قرار | اصدار | اللائحة التنظيمية لصرف الاجهزة التعويضية والوسائل المساعدة
--------------
title_raw: هيئة حماية المستهلك: قرار رقم ١ / ٢٠٢٣ بتعديل بعض أحكام اللائحة التنفيذية لقانون حماية المستهلك
Title_embd: قرار | تعديل | بعض احكام اللائحة التنفيذية لقانون حماية المستهلك
--------------
title_raw: وزارة التعليم العالي والبحث العلمي والابتكار: قرار وزاري رقم ٤٠ / ٢٠٢١ بإصدار لائحة تنظيم التدريب الخاص
Title_embd: قرار | اصدار | لائحة تنظيم التدريب الخاص
--------------
title_raw: مرسوم سلطاني رقم ٦ / ٩٩ بتحديد اختصاصات وزارة الأوقاف والشؤون الدينية واعتماد هيكلها التنظيمي
Title_embd: مرسوم | تحديد اختصاصات | وزارة الاوقاف والشؤون الدينية اعتماد هيكلها التنظيمي
--------------
title_raw: وزارة التجارة والصناعة وترويج الاستثمار: قرار وزاري رقم ٣٠٦ / ٢٠٢٢ بتعديل بعض أحكام اللائحة التنفيذية لقانون استثمار رأس المال الأجنبي
Title_embd: قرار | تعديل | بعض احكام اللائحة التنفيذية لقانون استثمار راس المال الاجنبي
--------------
title_raw: مرسوم سلطاني رقم ٣٩ / ٩٣ بتسمية عضو في مجلس الشورى
Title_embd: مرسوم | تعيين | عضو في مجلس الشوري
--------------
title_raw: وزارة التجارة والصناعة: قرار وزاري رقم ٤٥ / ٩٥ بتعديل القرار الوزاري رقم ١١٢ / ٨٨ بإصدار اللائحة التنفيذية لقانون سوق مسقط للأوراق المالية
Title_embd: قرار | تعديل | القرار الوزاري اصدار اللائحة التنفيذية لقانون سوق مسقط للاوراق المالية
--------------
title_raw: مرسوم سلطاني رقم ١٠٢ / ٩١ بالتصديق على اتفاقية التعاون الثقافي والتربوي بين حكومة سلطنة عمان وحكومة جمهورية الهند
Title_embd: مرسوم | تصديق | علي اتفاقية التعاون الثقافي والتربوي بين حكومة سلطنة عمان وحكومة جمهورية الهند
--------------
title_raw: مرسوم سلطاني رقم ١١ / ٨١ بتأسيس شركة عمان للتعدين المحدودة المسؤولية
Title_embd: مرسوم | انشاء | شركة عمان للتعدين المحدودة المسؤولية
--------------
title_raw: مرسوم سلطاني رقم ٢٢ / ٢٠٠٦ بتعيين وكيلين في وزارة التراث والثقاقة
Title_embd: مرسوم | تعيين | وكيلين في وزارة التراث والثقاقة
--------------
title_raw: مرسوم سلطاني رقم ٦٢ / ٢٠٠٠ بتعديل مسمى أكاديمية الشرطة وإصدار نظام كلية الشرطة
Title_embd: مرسوم | تعديل | مسمي اكاديمية الشرطة اصدار نظام كلية الشرطة
--------------
title_raw: مرسوم سلطاني رقم ٣٢ / ٨٩ بالتصديق على الاتفاقية الثنائية بين حكومة السلطنة وحكومة بروناي دار السلام بشأن الخدمات الجوية
Title_embd: مرسوم | تصديق | علي الاتفاقية الثنائية بين حكومة السلطنة وحكومة بروناي دار السلام بشان الخدمات الجوية
--------------
title_raw: مرسوم سلطاني رقم ٨٢ / ٢٠٠٨ بتعديل بعض أحكام المرسوم السلطاني رقم ٤٣ / ٩٧ بإنشاء مؤسسة عمان للصحافة والنشر والإعلان والنظام المرافق له
Title_embd: مرسوم | تعديل | بعض احكام المرسوم السلطاني انشاء مؤسسة عمان للصحافة نشر والاعلان والنظام المرافق له
--------------
title_raw: وزارة العدل والشؤون القانونية: فتوى رقم ٢٠٢٧٣٣٣٠٠
Title_embd: None
--------------
title_raw: مرسوم سلطاني رقم ١١ / ٩٠ بتحديد اختصاصات وزارة البيئة وتعديل هيكلها التنظيمي
Title_embd: مرسوم | تحديد اختصاصات | وزارة البيئة تعديل هيكلها التنظيمي
--------------
title_raw: مرسوم سلطاني رقم ٧٢ / ٢٠٢٤ بإجازة اتفاقية امتياز استخراج ومعالجة الملح البحري بين حكومة سلطنة عمان وشركة نقاء للملح ش م م للمنطقة رقم (٥١ ك)
Title_embd: مرسوم | تصديق | اتفاقية امتياز استخراج ومعالجة الملح البحري بين حكومة سلطنة عمان وشركة نقاء للملح ش م م للمنطقة رقم (٥١ ك)
--------------
title_raw: وزارة الصحة: قرار وزاري رقم ١٤ / ٨٧ بتنظيم مواعيد دوام ومناوبة الصيدليات الخاصة
Title_embd: قرار | تنظيم | مواعيد دوام ومناوبة الصيدليات الخاصة
--------------
title_raw: مرسوم سلطاني رقم ٨٣ / ٢٠٠٥ بتعيين أمين عام لمجلس البحث العلمي
Title_embd: مرسوم | تعيين | امين عام لمجلس البحث العلمي
--------------
title_raw: وزارة العدل والشؤون القانونية: استدراك
Title_embd: None
--------------
title_raw: الهيئة العامة لتنمية المؤسسات الصغيرة والمتوسطة: قرار رقم ٦٩ / ٢٠١٧ بتحديد الرسوم والمقابل المالي للخدمات التي تقدمها الهيئة العامة لتنمية المؤسسات الصغيرة والمتوسطة
Title_embd: قرار | تحديد | الرسوم والمقابل المالي للخدمات التي تقدمها الهيئة العامة لتنمية المؤسسات الصغيرة والمتوسطة
--------------
title_raw: مرسوم سلطاني رقم ١٠ / ٩٧ بانضمام سلطنة عمان إلى هيئة الموارد الوراثية للأغذية والزراعة
Title_embd: مرسوم | انضمام | سلطنة عمان الي هيئة الموارد الوراثية للاغذية والزراعة
--------------
title_raw: مرسوم سلطاني رقم ٦٠ / ٢٠٠٩ بتعيين سفير غير مقيم
Title_embd: مرسوم | تعيين | سفير غير مقيم
--------------
title_raw: مرسوم سلطاني رقم ٣٣ / ٧٦ بالمصادقة على انضمام حكومة سلطنة عمان إلى اتفاقية وارسو للنقل الجوي
Title_embd: مرسوم | تصديق | علي انضمام حكومة سلطنة عمان الي اتفاقية وارسو للنقل الجوي
--------------
title_raw: مكتب وزير الدولة ومحافظ ظفار: قرار وزاري رقم ٢٤ / ٢٠١٦ بتعديل القرار الوزاري رقم ٥٠١ / ٢٠١٢ بتسمية أعضاء المجلس البلدي للفترة الأولى
Title_embd: قرار | تعديل | القرار الوزاري تعيين اعضاء المجلس البلدي للفترة الاولي
--------------
title_raw: وزارة التراث والسياحة: قرار وزاري رقم ١٢٤ / ٢٠٢١ بشأن إضافة نشاط تنظيم رحلات سياحة المغامرات إلى أنشطة مكاتب السفر والسياحة
Title_embd: قرار | تعديل | نشاط تنظيم رحلات سياحة المغامرات الي انشطة مكاتب السفر والسياحة
--------------
title_raw: وزارة الثروة الزراعية والسمكية وموارد المياه: قرار وزاري رقم ٢٤١ / ٢٠٢٤ بحظر استيراد الطيور الحية من بعض الدول
Title_embd: قرار | حظر | استيراد الطيور الحية من بعض الدول
--------------
title_raw: مرسوم سلطاني رقم ٨٩ / ٢٠٢٠ بإنشاء وزارة العمل وتحديد اختصاصاتها واعتماد هيكلها التنظيمي
Title_embd: مرسوم | انشاء | وزارة تطبيق تحديد اختصاصاتها اعتماد هيكلها التنظيمي
--------------
title_raw: مرسوم سلطاني رقم ٣٨ / ٢٠٠٢ بتحديد اختصاصات وزارة الصحة
Title_embd: مرسوم | تحديد اختصاصات | وزارة الصحة
--------------
title_raw: وزارة الثروة الزراعية والسمكية وموارد المياه: قرار وزاري رقم ٢٢٦ / ٢٠٢٥ بحظر استيراد الطيور الحية من بعض الدول
Title_embd: قرار | حظر | استيراد الطيور الحية من بعض الدول
--------------
title_raw: مرسوم سلطاني رقم ٢٦ / ٩٧ بإنشاء كلية الشريعة والقانون
Title_embd: مرسوم | انشاء | كلية الشريعة والقانون
--------------
title_raw: مرسوم سلطاني رقم ١٠٦ / ٩٤ بالتصديق على الاتفاق الثقافي بين سلطنة عمان وجمهورية كوريا
Title_embd: مرسوم | تصديق | علي الاتفاق الثقافي بين سلطنة عمان وجمهورية كوريا
--------------
title_raw: وزارة القوى العاملة: قرار وزاري رقم ٢٤٦ / ٢٠١٨ باستمرار إيقاف التصريح باستقدام قوى عاملة غير عمانية بصفة مؤقتة في بعض المهن
Title_embd: قرار | تجديد | وقف التصريح باستقدام قوي عاملة غير عمانية بصفة مؤقتة في بعض المهن
--------------
title_raw: الجريدة الرسمية العدد ١٤٩٧
Title_embd: None
--------------
title_raw: مرسوم سلطاني رقم ٣٩ / ٢٠٠٢ بتعديل قانون بمنح شركة الغاز العمانية (ش.م.ع.م) امتياز إدارة مرفق نقل الغاز
Title_embd: مرسوم | تعديل | قانون منح شركة الغاز العمانية (ش.م.ع.م) امتياز ادارة مرفق نقل الغاز
--------------
title_raw: مرسوم سلطاني رقم ٣٨ / ٩٩ بالموافقة على انضمام سلطنة عمان إلى اتفاقية تمييز المتفجرات البلاستيكية بغرض كشفها
Title_embd: مرسوم | تصديق | علي انضمام سلطنة عمان الي اتفاقية تمييز المتفجرات البلاستيكية بغرض كشفها
--------------
title_raw: هيئة المنطقة الاقتصادية الخاصة بالدقم: قرار رقم ٢١ / ٢٠١٥ بإصدار لائحة تسجيل المشروعات في المنطقة الاقتصادية الخاصة بالدقم
Title_embd: قرار | اصدار | لائحة تسجيل المشروعات في المنطقة الاقتصادية الخاصة بالدقم
--------------
title_raw: وزارة القوى العاملة: قرار وزاري رقم ٣٣٨ / ٢٠١٤ بإيقاف التصريح باستقدام القوى العاملة غير العمانية بصفة مؤقتة في بعض الأعمال
Title_embd: قرار | وقف | التصريح باستقدام القوي العاملة غير العمانية بصفة مؤقتة في بعض الاعمال
--------------
title_raw: وزارة التعليم العالي: قرار وزاري رقم ٢٩ / ٢٠١٧ بإصدار النظام الأكاديمي لكليات العلوم التطبيقية
Title_embd: قرار | اصدار | النظام الاكاديمي لكليات العلوم التطبيقية
--------------
title_raw: شرطة عمان السلطانية: قرار رقم ٢٤٩ / ٢٠١٨ بتعديل بعض أحكام اللائحة التنفيذية لنظام كلية الشرطة
Title_embd: قرار | تعديل | بعض احكام اللائحة التنفيذية لنظام كلية الشرطة
--------------
title_raw: مرسوم سلطاني رقم ٣٦ / ٩٦ بالتصديق على تعديلات في اتفاقية تنظيم خدمات النقل الجوي بين سلطنة عمان وجمهورية مصر العربية
Title_embd: مرسوم | تصديق | علي تعديل في اتفاقية تنظيم خدمات نقل الجوي بين سلطنة عمان وجمهورية مصر العربية
--------------
title_raw: مرسوم سلطاني رقم ٢٠ / ٢٠٠٦ بتعديل اسم المديرية العامة للحصر والشؤون الإدارية بالأمانة العامة للضرائب بوزارة المالية
Title_embd: مرسوم | تعديل | اسم المديرية العامة للحصر والشؤون الادارية بالامانة العامة للضرائب بوزارة المالية
--------------
title_raw: مرسوم سلطاني رقم ٤٤ / ٨٠ بإصدار قانون السلكين الدبلوماسي والقنصلي لعام ١٩٨٠
Title_embd: مرسوم | اصدار | قانون السلكين الدبلوماسي والقنصلي لعام ١٩٨٠
--------------
title_raw: بلدية مسقط: قرار رقم ٩٦ / ٢٠١٩ بتعديل بعض أحكام القرار رقم ١ / ٢٠١٨ بتحديد الرسوم والأثمان والتأمينات والضمانات المالية التي تحصلها بلدية مسقط
Title_embd: قرار | تعديل | بعض احكام القرار تحديد الرسوم والاثمان والتامينات والضمانات المالية التي تحصلها بلدية مسقط
--------------
title_raw: مرسوم سلطاني رقم ١٠٢ / ٨٢ بتعيين سفير فوق العادة ومفوض للسلطنة غير مقيم لدى جمهورية السنغال
Title_embd: مرسوم | تعيين | سفير فوق العادة ومفوض للسلطنة غير مقيم لدي جمهورية السنغال
--------------
title_raw: وزارة العدل والشؤون القانونية: فتوى رقم ١٩٢٧٢٥٦٦٨
Title_embd: None
--------------
title_raw: مرسوم سلطاني رقم ١٩ / ٢٠١٢ بتعيين سفيرة غير مقيمة
Title_embd: مرسوم | تعيين | سفيرة غير مقيمة
--------------
title_raw: مرسوم سلطاني رقم ٦٣ / ٢٠١٤ باعتماد الهيكل التنظيمي للأمانة العامة للمجلس الأعلى للتخطيط
Title_embd: مرسوم | اعتماد | الهيكل التنظيمي للامانة العامة للمجلس الاعلي للتخطيط
--------------
title_raw: وزارة العدل والشؤون القانونية: فتوى رقم ٢٠٢٧٣٤٣٤٠
Title_embd: None
--------------
title_raw: مرسوم سلطاني رقم ١٩ / ٩٩ بتعيين عضو بالمجلس البلدي لبلدية مسقط
Title_embd: مرسوم | تعيين | عضو بالمجلس البلدي لبلدية مسقط
--------------
title_raw: مرسوم سلطاني رقم ٥٦ / ٢٠١٩ بإجراء بعض التعديلات على قانون معاشات ومكافآت ما بعد الخدمة لموظفي ديوان البلاط السلطاني العمانيين
Title_embd: مرسوم | تعديل | علي قانون معاشات ومكافات ما بعد الخدمة لموظفي ديوان البلاط السلطاني العمانيين
--------------
title_raw: وزارة الداخلية: قرار وزاري رقم ٢٢ / ٢٠٢٣ بتعديل القرار الوزاري رقم ٢٢٢ / ٢٠٢٢ بتسمية أعضاء المجالس البلدية للفترة الثالثة
Title_embd: قرار | تعديل | القرار الوزاري تعيين اعضاء المجالس البلدية للفترة الثالثة
--------------
title_raw: مرسوم سلطاني رقم ٥٧ / ٢٠٢١ بإصدار نظام جهاز الاستثمار العماني
Title_embd: مرسوم | اصدار | نظام جهاز الاستثمار العماني
--------------
title_raw: مرسوم سلطاني رقم ٥١ / ٧٧ بإنشاء بنك الإسكان العماني
Title_embd: مرسوم | انشاء | بنك الاسكان العماني
--------------
title_raw: وزارة التجارة والصناعة: قرار وزاري رقم ١ / ٢٠٠٠ بإضافة فقرة جديدة إلى المادة (١) من القرار الوزاري رقم ٢٠٨ / ٩٥ بتنظيم العروض الترويجية
Title_embd: قرار | تعديل | فقرة جديدة الي المادة من القرار الوزاري تنظيم العروض الترويجية
--------------
title_raw: مرسوم سلطاني رقم ٨٨ / ٨١ باعتماد توقيع سفير السلطنة لدى جمهورية الصين الشعبية على اتفاقية التعاون الثقافي والصحي والإعلامي بين حكومة السلطنة وحكومة جمهورية الصين الشعبية والتصديق عليها
Title_embd: مرسوم | اعتماد | توقيع سفير السلطنة لدي جمهورية الصين الشعبية علي اتفاقية التعاون الثقافي والصحي والاعلامي بين حكومة السلطنة وحكومة جمهورية الصين الشعبية تصديق عليها
--------------
title_raw: مرسوم سلطاني رقم ٣ / ٢٠١٨ بإنشاء مركز التدريب الإعلامي وإصدار نظامه
Title_embd: مرسوم | انشاء | مركز التدريب الاعلامي اصدار نظامه
--------------
title_raw: مرسوم سلطاني رقم ٧٩ / ٨٢ بتفويض وزير المواصلات بالتوقيع نيابة عن جلالة السلطان على اتفاقية تنظيم الخدمات الجوية بين سلطنة عمان والمملكة المغربية
Title_embd: مرسوم | تفويض | وزير المواصلات توقيع نيابة عن جلالة السلطان علي اتفاقية تنظيم الخدمات الجوية بين سلطنة عمان والمملكة المغربية
--------------
title_raw: مرسوم سلطاني رقم ٢٩ / ٢٠٠٣ بإصدار قانون معاشات ومكافآت ما بعد الخدمة لموظفي جهاز الأمن الداخلي
Title_embd: مرسوم | اصدار | قانون معاشات ومكافات ما بعد الخدمة لموظفي جهاز الامن الداخلي
--------------
title_raw: وزارة العدل: قرار وزاري رقم ١٧٨ / ٢٠١٩ بتخويل صفة الضبطية القضائية لبعض موظفي وزارة النقل والاتصالات
Title_embd: قرار | منح | صفة الضبطية القضائية لبعض موظفي وزارة نقل والاتصالات
--------------
title_raw: مرسوم سلطاني رقم ١٠٤ / ٩٦ بالتصديق على ملحق اتفاقية تجنب الازدواج الضريبي بين حكومة سلطنة عمان وحكومة الجمهورية الفرنسية والبروتوكول المرفق به
Title_embd: مرسوم | تصديق | علي ملحق اتفاقية تجنب الازدواج الضريبي بين حكومة سلطنة عمان وحكومة الجمهورية الفرنسية والبروتوكول المرفق به
--------------
title_raw: مرسوم سلطاني رقم ٣٣ / ٩٦ بالتصديق على تعديلات في اتفاقية تنظيم خدمات النقل الجوي بين سلطنة عمان ومملكة هولندا
Title_embd: مرسوم | تصديق | علي تعديل في اتفاقية تنظيم خدمات نقل الجوي بين سلطنة عمان ومملكة هولندا
--------------
title_raw: وزارة الشؤون القانونية: فتوى رقم ١٧٢٧٠٠٠٢٨٣٥٤
Title_embd: None
--------------
title_raw: شرطة عمان السلطانية: قرار رقم ٨٣ / ٢٠١٥ بتعديل بعض أحكام اللائحة التنفيذية لقانون الأحوال المدنية
Title_embd: قرار | تعديل | بعض احكام اللائحة التنفيذية لقانون الاحوال المدنية
--------------
title_raw: مرسوم سلطاني رقم ٥ / ٩١ بنقل مديرين عامين إلى الدرجة المالية الأولى من الحلقة الأولى
Title_embd: مرسوم | نقل | مديرين عامين الي الدرجة المالية الاولي من الحلقة الاولي
--------------
title_raw: الجريدة الرسمية العدد ١٤٣٤
Title_embd: None
--------------
title_raw: شرطة عمان السلطانية: قرار رقم ٢٠ / ٢٠١٦ بتعديل بعض أحكام اللائحة التنفيذية لقانون إقامة الأجانب
Title_embd: قرار | تعديل | بعض احكام اللائحة التنفيذية لقانون اقامة الاجانب
--------------
title_raw: مرسوم سلطاني رقم ٤٤ / ٨٢ بتعيين وكيل للأوقاف والشؤون الإسلامية
Title_embd: مرسوم | تعيين | وكيل للاوقاف والشؤون الاسلامية
--------------
title_raw: مجلس الخدمة المدنية: قرار رقم ٢ / ٢٠١٤ بتعديل بعض أحكام القرار رقم ٨ / ٢٠١١ بتحديد الوظائف ذات الطبيعة الخاصة المستثناة من شرط الإعلان عند التعيين
Title_embd: قرار | تعديل | بعض احكام القرار تحديد الوظائف ذات الطبيعة الخاصة المستثناة من شرط الاعلان عند تعيين
--------------
title_raw: مرسوم سلطاني رقم ٥٢ / ٢٠٢٤ بإصدار قانون السجلات الوطنية
Title_embd: مرسوم | اصدار | قانون السجلات الوطنية
--------------
title_raw: مرسوم سلطاني رقم ٩٢ / ٢٠٠٠ بإصدار قانون حماية المستنبطات النباتية
Title_embd: مرسوم | اصدار | قانون حماية المستنبطات النباتية
--------------
title_raw: مرسوم سلطاني رقم ١٢٧ / ٢٠٢٠ بنقل مستشار من وزارة الصحة إلى المكتب الخاص
Title_embd: مرسوم | نقل | مستشار من وزارة الصحة الي المكتب الخاص
--------------
title_raw: مرسوم سلطاني رقم ٦٦ / ٨٢ بنقل سفير السلطنة لدى جمهورية جيبوتي وتعيينه سفيرا فوق العادة ومفوضا للسلطنة لدى دولة الكويت
Title_embd: مرسوم | نقل | سفير السلطنة لدي جمهورية جيبوتي وتعيينه سفيرا فوق العادة ومفوضا للسلطنة لدي دولة الكويت
--------------
title_raw: مرسوم سلطاني رقم ٧٩ / ٢٠٠٨ بتعيين سفير غير مقيم
Title_embd: مرسوم | تعيين | سفير غير مقيم
--------------
title_raw: وزارة التنمية الاجتماعية: قرار وزاري رقم ١٦٩ / ٢٠٢٥ بإصدار اللائحة التنظيمية لدور الرعاية الاجتماعية
Title_embd: قرار | اصدار | اللائحة التنظيمية لدور الرعاية الاجتماعية
--------------
title_raw: وزارة الداخلية: قرار وزاري رقم ٢٣٨ / ٢٠١٤ بتعديل القرار الوزاري رقم ٩٢ / ٩٣ بإصدار أحكام تنظيم زواج العمانيين من أجانب
Title_embd: قرار | تعديل | القرار الوزاري اصدار احكام تنظيم زواج العمانيين من اجانب
--------------
title_raw: ترخيص من الفئة الأولى لشركة أواصر عمان وشركاؤهم (ش.م.ع.م) لإنشاء وتشغيل نظام خدمات اتصالات عامة ثابتة (معدل)
Title_embd: ترخيص | انشاء | وتشغيل نظام خدمات اتصالات عامة ثابتة (معدل)
--------------
title_raw: مرسوم سلطاني رقم ١٦ / ٩٤ بتعيين رئيس لجامعة السلطان قابوس
Title_embd: مرسوم | تعيين | رئيس لجامعة السلطان قابوس
--------------
title_raw: مرسوم سلطاني رقم ١٠١ / ٩٧ بالتصديق على اتفاقية تشجيع وحماية الاستثمار بين حكومة سلطنة عمان وحكومة جمهورية باكستان الإسلامية
Title_embd: مرسوم | تصديق | علي اتفاقية تشجيع وحماية الاستثمار بين حكومة سلطنة عمان وحكومة جمهورية باكستان الاسلامية
--------------
title_raw: مرسوم سلطاني رقم ٨٨ / ٢٠٠٢ بالتصديق على المقرر رقم ٣ / ١ المعتمد بمؤتمر الأطراف لاتفاقية بازل للتحكم في نقل النفايات والتخلص منها عبر الحدود
Title_embd: مرسوم | تصديق | علي المقرر المعتمد بمؤتمر الاطراف لاتفاقية بازل للتحكم في نقل النفايات والتخلص منها عبر الحدود
--------------
title_raw: وزارة التراث والسياحة: قرار وزاري رقم ٢٢٠ / ٢٠٢٢ بتعديل بعض أحكام القرار الوزاري رقم ١٠٠ / ٢٠٢١ بتحديد رسوم زيارة مركز فتح الخير
Title_embd: قرار | تعديل | بعض احكام القرار الوزاري تحديد رسوم زيارة مركز فتح الخير
--------------
title_raw: مرسوم سلطاني رقم ٣٨ / ٢٠٠١ بالتصديق على الاتفاقية رقم (١٨٢) والتوصية رقم (١٩٠) بشأن حظر أسوأ أشكال عمل الأطفال والإجراءات الفورية للقضاء عليها
Title_embd: مرسوم | تصديق | علي الاتفاقية رقم والتوصية رقم بشان حظر اسوا اشكال عمل الاطفال والاجراءات الفورية للقضاء عليها
--------------
title_raw: مرسوم سلطاني رقم ٧٥ / ٢٠٢١ بتعيين عضوة في مجلس الدولة
Title_embd: مرسوم | تعيين | عضوة في مجلس الدولة
--------------
title_raw: قانون الأراضي لعام ١٩٨٠ (معدل)
Title_embd: قانون | اصدار | الاراضي لعام ١٩٨٠ (معدل)
--------------
title_raw: مرسوم سلطاني رقم ٢٠ / ٩٢ بالتصديق على اتفاقية تجنب الازدواج الضريبي على الدخل الناشئ عن نشاط النقل الجوي الدولي بين حكومة سلطنة عمان وحكومة جمهورية تنزانيا المتحدة
Title_embd: مرسوم | تصديق | علي اتفاقية تجنب الازدواج الضريبي علي الدخل الناشئ عن نشاط نقل الجوي الدولي بين حكومة سلطنة عمان وحكومة جمهورية تنزانيا المتحدة
--------------
title_raw: مرسوم سلطاني رقم ٧٤ / ٢٠١٣ بتقرير صفة المنفعة العامة لمشروع ازدواجية طريق إزكي – عز بمحافظة الداخلية
Title_embd: مرسوم | تقرير صفة المنفعة العامة | لمشروع ازدواجية طريق ازكي – عز بمحافظة الداخلية
--------------
title_raw: مرسوم سلطاني رقم ٩٠ / ٢٠٠٣ بتعديل بعض أحكام قانون المحاماة
Title_embd: مرسوم | تعديل | بعض احكام قانون المحاماة
--------------
title_raw: مرسوم سلطاني رقم ٤١ / ٩٩ بإصدار نظام الجامعات الخاصة
Title_embd: مرسوم | اصدار | نظام الجامعات الخاصة
--------------
title_raw: الجريدة الرسمية العدد ١٦٠٣
Title_embd: None
--------------
title_raw: مرسوم سلطاني رقم ٢١ / ٨٩ بتعيين أمين عام لمجلس التنمية
Title_embd: مرسوم | تعيين | امين عام لمجلس التنمية
--------------
title_raw: مرسوم سلطاني رقم ٤٢ / ٢٠١٨ في شأن الهيئة العامة للكهرباء والمياه
Title_embd: مرسوم | تنظيم | الهيئة العامة للكهرباء والمياه
--------------
title_raw: مرسوم سلطاني رقم ٧٣ / ٢٠٢٥ بالتصديق على تعديلات اتفاقية إنشاء المنظمة البحرية الدولية
Title_embd: مرسوم | تصديق | علي تعديل اتفاقية انشاء المنظمة البحرية الدولية
--------------
title_raw: مرسوم سلطاني رقم ١٠٨ / ٨٢ بتعيين وكيل لوزارة الكهرباء والمياه
Title_embd: مرسوم | تعيين | وكيل لوزارة الكهرباء والمياه
--------------
title_raw: شرطة عمان السلطانية: قرار رقم ١٦ / ٢٠٠٨ باعتماد الجزء الثاني من اشتراطات السلامة من أخطار الحريق
Title_embd: قرار | اعتماد | الجزء الثاني من اشتراطات السلامة من اخطار الحريق
--------------
title_raw: مرسوم سلطاني رقم ٧٩ / ٢٠٠٤ بإجازة الاتفاقية النفطية بين حكومة سلطنة عمان وشركة هنت عمان مسندم للاستكشاف
Title_embd: مرسوم | تصديق | الاتفاقية النفطية بين حكومة سلطنة عمان وشركة هنت عمان مسندم للاستكشاف
--------------
title_raw: مرسوم سلطاني رقم ٢٦ / ٢٠١٨ بإنشاء مركز عمان للتحكيم التجاري
Title_embd: مرسوم | انشاء | مركز عمان للتحكيم التجاري
--------------
title_raw: مرسوم سلطاني رقم ١٢ / ٢٠١٧ بإجازة الاتفاقية النفطية الموقعة بين حكومة سلطنة عمان وشركة النفط العمانية للاستكشاف والإنتاج ش.م.م للمنطقة رقم (٤٨)
Title_embd: مرسوم | تصديق | الاتفاقية النفطية الموقعة بين حكومة سلطنة عمان وشركة النفط العمانية للاستكشاف والانتاج ش.م.م للمنطقة رقم
--------------
title_raw: مرسوم سلطاني رقم ٨٧ / ٢٠٠٧ بتعيين مستشار للدولة
Title_embd: مرسوم | تعيين | مستشار للدولة
--------------
title_raw: مرسوم سلطاني رقم ٦٠ / ٩٣ بتعديل بعض الأحكام المنظمة للعلاقة بين ملاك ومستجأري المساكن والمحلات التجارية والصناعية وتسجيل عقود الإيجار الخاصة بها
Title_embd: مرسوم | تعديل | بعض الاحكام المنظمة للعلاقة بين ملاك ومستجاري المساكن والمحلات التجارية والصناعية وتسجيل عقود الايجار الخاصة بها
--------------
title_raw: مرسوم سلطاني رقم ٤ / ٢٠٠١ بتعديل بعض أحكام قانون البعثات والإعانات الدراسية
Title_embd: مرسوم | تعديل | بعض احكام قانون البعثات والاعانات الدراسية
--------------
title_raw: مرسوم سلطاني رقم ٩٣ / ٢٠٠٥ بتعيين وكيل لوزارة النقل والاتصالات
Title_embd: مرسوم | تعيين | وكيل لوزارة نقل والاتصالات
--------------

In [14]:
n_samples = min(500, len(failed_df))
random_samples = failed_df.sample(n=n_samples, random_state=42)

for _, row in random_samples.iterrows():
    if len(str(row['title']).split()) > 10:  # تعداد کلمات بیشتر از 10
        print("title:", row['title'])

title: مرسوم سلطاني رقم ٥٩ / ٧٩ بنقل تبعية ديوان التشريع والجريدة الرسمية
title: مرسوم سلطاني رقم ٤٥ / ٧٨ بإلحاق المديرية العامة للأشغال العامة بوزارة الشؤون الاجتماعية والعمل
title: وزارة الصحة: قرار وزاري رقم ٤١ / ٩١ بشأن الفحوصات الطبية للكشف عن الأمراض المعدية للوافدين للسلطنة بغرض العمل
title: مرسوم سلطاني رقم ٨٦ / ٢٠٢٥ بتعديل بعض أحكام قانون الجريدة الرسمية

In [15]:
import re
import pandas as pd

# اصلاحات انجام شده در پترن:
# 1. اضافه کردن (?:في|بتاريخ) برای پوشش هر دو حالت.
# 2. اضافه کردن \d+ بلافاصله بعد از دو نقطه/فاصله. این مهمترین بخش است که
#    باعث می‌شود عباراتی مثل "صدر في سلطنة" (که بعدش عدد نیست) نادیده گرفته شوند.
FOOTER_PATTERN = re.compile(
   r'(صدر\s+(?:في|بتاريخ)\s*[:]?\s*\d+[\s\S]*?(?:الصادر|الصادرة)\s+في\s+.*?\d{4}\s*[مهـ]?\.?)'
)

def extract_and_remove_footer(text):
    if not isinstance(text, str):
        return text, None

    # استفاده از finditer برای پیدا کردن تمام موارد ممکن
    matches = list(FOOTER_PATTERN.finditer(text))

    if matches:
        # همیشه آخرین مورد پیدا شده را انتخاب می‌کنیم (چون فوتر در انتهای متن است)
        last_match = matches[-1]
        footer = last_match.group(1).strip()

        # متن را بر اساس مکان شروع فوتر برش می‌زنیم تا مطمئن شویم
        # اگر مورد مشابهی در وسط متن بود اشتباهاً حذف نشود.
        start_index = last_match.start()
        clean_text = text[:start_index].strip()

        return clean_text, footer

    return text, None

In [16]:
df_clean[['text', 'footer']] = df_clean['text'].apply(
    lambda x: pd.Series(extract_and_remove_footer(x))
)
failed_mask = df_clean['footer'].isna() | (df_clean['footer'].str.strip() == '')
print('تعداد نمونه‌هایی که footer استخراج نشده:')
print(failed_mask.sum())

تعداد نمونه‌هایی که footer استخراج نشده:
729

In [17]:
failed_df = df_clean.loc[failed_mask]

n_samples = min(500, len(failed_df))
random_samples = failed_df.sample(n=n_samples, random_state=42)

for _, row in random_samples.head(500).iterrows():
    print(row['text'][-400:])
    print("="*80)

ركة ثوابت الشمال للتجارة والمقاولات – تضامنية. إعلان عن انتهاء أعمال التصفية لشركة مشاريع صحم الشامخة الوطنية – تضامنية. إعلان عن انتهاء أعمال التصفية لشركة رموز الاتحاد الخليجي للمقاولات ش.م.م. إعلان عن انتهاء أعمال التصفية لشركة مجان للغوص والخدمات الفنية البحرية ش.م.م. إعلان عن انتهاء أعمال التصفية لشركة المعدن النادر ش.م.م. إعلان عن انتهاء أعمال التصفية لشركة أسطول مسقط للمشاريع الحديثة ش.م.م.
================================================================================
 المادة (٣٩) من قانون تنظيم وتخصيص قطاع الكهرباء والمياه المرتبطة به المشار إليه بند جديد برقم (ط مكررا)، يكون نصه كالآتي: “ط مكررا – الأحكام والشروط والإجراءات والضوابط الفنية المتعلقة بإنتاج وبيع الكهرباء باستخدام مصادر الطاقة المتجددة”. المادة (٤) تلغى عبارة “والهيئة العامة للكهرباء والمياه” الواردة في البند (٢١) من المادة (٢٢) من قانون تنظيم وتخصيص قطاع الكهرباء والمياه المرتبطة به المشار إليه
================================================================================
الالتزام بجميع التدابير الاحترازية الموضوعة من قبل الجهات المختصة وأهمها لبس الكمامة والتباعد الاجتماعي سواء في أماكن السكن أو العمل والأماكن العامة، وعدم التهاون في الالتزام بها. ونظرا لتسارع المستجدات حول التحورات والطفرات في فيروس كورونا فإن اللجنة العليا في متابعة وتقييم مستمرين للوضع الوبائي المحلي والعالمي، وستتخذ القرارات المناسبة كلما دعت الحاجة وفقا لذلك. حفظ الله الجميع من كل سوء ومكروه.
================================================================================
١١٤) ريال عماني، أي أن المقاول الأول لم يتحمل أي نفقات إضافية تجاه الأعمال غير المكتملة في تاريخ إخلائه من المشروع، وبما ينفي عدم مشروعية استخدام الوزارة لحقها بموجب قانون المعاملات المدنية المشار إليه. لذلك، انتهى الرأي إلى جواز إسناد وزارة…………… إكمال الأعمال غير المكتملة في مشروع مبنى………….. في ولاية محضة إلى شركة…………….. المسجلة لدى مجلس المناقصات في الدرجة الأولى، وذلك على النحو المبين بالأسباب.
================================================================================
شين المنصوص عليها في المادة (٤) من نظام معاشات ومكافآت أفراد الحرس السلطاني العماني. ثالثا: منطوق الرأي: انتهى الرأي إلى استحقاق المعروضة حالتها لمعاش زوجها المرحوم الضابط المدني / …………. كاملا ومقداره (……………….ر.ع) …………. ريالا عمانيا، وذلك من تاريخ التحاق ابنته “…………………” بالعمل، وعدم وجود مستفيدين آخرين، واستيفائها كافة شروط الاستحقاق، والتنسيق مع صندوق …………… لوقف صرف معاشها عن مدة خدمتها الوظيفية.
================================================================================
موالا عامة، وتتمتع بمزايا وحقوق الخزانة العامة وامتيازاتها على أموال المدينين، وللجهاز حماية هذه الأموال بالطرق ووفق الإجراءات المنصوص عليها في نظام تحصيل الضرائب والرسوم وغيرها من المبالغ المستحقة لوحدات الجهاز الإداري للدولة. المادة (١٣) يعفى الجهاز من كافة الضرائب والرسوم، وذلك دون الإخلال بقانون الجمارك الموحد لدول مجلس التعاون لدول الخليج العربية. [1] عدلت بموجب المرسوم السلطاني رقم ٥ / ٢٠٢٤.
================================================================================
وجب المرسوم السلطاني رقم ٩٢ / ٢٠٠٥. [١٥] عدل عنوان الباب واستبدل بكلمة “المدين” عبارة “المحكوم عليه” وبكلمة “الدائن” عبارة “المحكوم له” أينما وردت في مواد الفصل الأول منه بموجب المرسوم السلطاني رقم ٩٢ / ٢٠٠٥. [١٦] عدلت بموجب المرسوم السلطاني رقم ٩٢ / ٢٠٠٥. [١٧] ألغيت بموجب المرسوم السلطاني رقم ٩٢ / ٢٠٠٥. [١٨] عدلت بموجب المرسوم السلطاني رقم ٩٢ / ٢٠٠٥. [١٩] عدلت بموجب المرسوم السلطاني رقم ٩٢ / ٢٠٠٥
================================================================================
دة (١٠) تعتبر صحيحة التصرفات والإجراءات التي تمت في شأن المجمعات السياحية قبل العمل بهذا النظام. [١] استبدل بعبارة “تملك غير العمانيين للعقارات في المجمعات السياحية المتكاملة” عبارة “تملك العقارات في المجمعات السياحية المتكاملة” أينما وردت في النظام، وعدلت المادة (١) بموجب المرسوم السلطاني رقم ٦٥ / ٢٠٠٧. [٢] أضيفت بموجب المرسوم السلطاني رقم ٦٥ / ٢٠٠٧. [٣] أضيفت بموجب المرسوم السلطاني رقم ٧٦ / ٢٠١٠
================================================================================
لى سند صحيح، وخليقا بالرفض. لذلك انتهى الرأي، إلى: أولا: أحقية شركة……….. المنفذة لمشروع إنشاء شبكات توزيع المياه بولاية……. في محافظة…….. في مطالبتها المالية نتيجة لرفع الحد الأدنى لأجور العمانيين العاملين في القطاع الخاص البالغ قدرها (………. ر.ع)………….. ريالا عمانيا. ثانيا: وعدم أحقيتها في المطالبة بالتعويض عن الزيادة في حصة المساهمة للهيئة العامة للتأمينات الاجتماعية، وذلك على النحو المبين بالأسباب.
================================================================================
مة، عليه، يتعذر على الوزارة إبداء الرأي المطلوب. لذلك، انتهى الرأي إلى عدم جواز صرف منحة نهاية الخدمة للموظفين المنقولين من الهيئة العامة للمياه إلى الشركة العمانية لخدمات الصرف الصحي ممن أكملوا (٥) خمس سنوات بالخدمة، وتعذر إبداء الرأي في شأن مدى جواز صرف منحة نهاية الخدمة لموظفي الهيئة ممن ألغيت وظائفهم ولم يكملوا (٥) خمس سنوات خدمة بسبب إلغاء الهيئة العامة للمياه، وذلك على النحو المبين بالأسباب.
================================================================================
وارد البشرية بصندوق تقاعد موظفي الخدمة المدنية قبل التعديل، وذلك إعمالا للأثر الفوري للنصوص القانونية والتي لا تطبق بأثر رجعي على من اكتملت مراكزهم القانونية قبل تاريخ العمل بها، وتظل تلك المراكز محكومة بالقواعد القانونية التي نشأت واكتملت في ظل العمل بها. لذلك، انتهى الرأي إلى عدم جواز صرف منحة نهاية الخدمة لموظفي صندوق تقاعد موظفي الخدمة المدنية وهم على رأس العمل، وذلك على النحو المبين بالأسباب.
================================================================================
 المحامين والمستشارين القانونيين رقم ٢٠٥ / ١٢ / ٢٠٢٥ بالموافقة على تأسيس شركة مدنية للمحاماة. وزارة التجارة والصناعة وترويج الاستثمار إعلان بشأن تسجيل نموذج صناعي. الإعلانات الخاصة بالنشر عن طلبات تسجيل العلامات التجارية. إعلان بشأن العلامات التي تم التأشير في السجلات بالترخيص بالانتفاع. إعلان بشأن العلامات التي تم التأشير في السجلات بانتقال ملكيتها. إعلان بشأن تجديد مدة حماية علامات تجارية مسجلة.
================================================================================
رة:– ٣٥ × ٣٥ سم ٣- مقاس علم الطاولة:– ٢٦ × ١٧ سم الملحق رقم (٢)شعار الدولة الملحق رقم (٣)النشيد الوطني أولا: النشيد[١] يا ربَّنا احفظ لناجلالة السلطانوالشعبَ في الأوطانبالعزّ والأمانوليدمْ مؤيداعاهلا ممجدابالنفوسِ يفتدىيا عمان نحنُ من عهدِ النبيأوفياء من كرامِ العربفارتقي هام السماءواملئي الكونَ الضياءواسعدي وانعمي بالرخاء ثانيا: الصيغة الموسيقية للنشيد: [١] عدل بموجب المرسوم السلطاني رقم ٢ / ٢٠٢٠
================================================================================
فية لشركة ينابيع الصحراء للتجارة والمقاولات – توصية. إعلان عن انتهاء أعمال التصفية لشركة محمد الزدجالي الحديثة للمقاولات ش.م.م. إعلان عن انتهاء أعمال التصفية لشركة المحترف للتأمين ش.م.م. إعلان عن انتهاء أعمال التصفية لشركة معالم الشرس المتحدة للتجارة – تضامنية. إعلان عن انتهاء أعمال التصفية لشركة مسارات الجنوب المتحدة للتجارة – تضامنية. إعلان عن انتهاء أعمال التصفية لشركة ربوع الخوض المتحدة ش.م.م.
================================================================================
، وأن تقتصر الخدمة على الاستلام والتسليم. – كما قررت اللجنة إعادة فتح: محلات كهربائي المركبات، وتغيير الزيوت، وإصلاح الفرامل، وبيع الإطارات وإصلاحها. بشرط السماح بوجود زبونين كحد أقصى في نفس الوقت. – كما قررت اللجنة السماح كذلك لشركات الصرافة بمزاولة خدماتها. ويشترط لمزاولة مختلف الأنشطة الاقتصادية المذكورة آنفا الالتزام بكل الاشتراطات الصحية التي تحددها الجهات المعنية. حفظ الله الجميع من كل مكروه
================================================================================
 / ٢٠٠٨. [١١] أضيفت بموجب المرسوم السلطاني رقم ١٣٢ / ٢٠٠٨. [١٢] أضيفت بموجب المرسوم السلطاني رقم ١٣٢ / ٢٠٠٨. [١٣] عدلت بموجب الرسوم السلطاني رقم ١٣٢ / ٢٠٠٨. [١٤] أضيفت بموجب المرسوم السلطاني رقم ١٣٢ / ٢٠٠٨. [١٥] عدلت بموجب الرسوم السلطاني رقم ١٣٢ / ٢٠٠٨. [١٦] عدلت بموجب الرسوم السلطاني رقم ١٣٢ / ٢٠٠٨. [١٧] عدلت بموجب المرسوم السلطاني رقم ١٣٢ / ٢٠٠٨. [١٨] أضيفت بموجب المرسوم السلطاني رقم ١٣٢ / ٢٠٠٨
================================================================================
لمجرات الماسية للتجارة – تضامنية. إعلان عن انتهاء أعمال التصفية لشركة مشاريع الرسيس المميزة للتجارة ش.م.م. إعلان عن انتهاء أعمال التصفية لشركة آفاق مجز للتجارة والمقاولات ش.م.م. إعلان عن انتهاء أعمال التصفية لشركة تأصيل للاستثمار والتدريب ش.م.م. إعلان عن انتهاء أعمال التصفية لشركة بيت الكرم المتكاملة للتجارة والمقاولات ش.م.م. إعلان عن انتهاء أعمال التصفية لشركة أعالي غلاء للتجارة والمقاولات ش.م.م.
================================================================================
و آت مادة (١) يفوض نائب رئيس الوزراء للشؤون المالية والاقتصادية بالتوقيع على اتفاقية تجنب الازدواج الضريبي بين حكومة سلطنة عمان وحكومة الجمهورية الفرنسية، المشار إليها. مادة (٢) ينشر هذا المرسوم في الجريدة الرسمية ويعمل به اعتبارا من تاريخ صدوره. صدر في: أول رجب سنة ١٤٠٩هـ الموافق: ٨ فبراير سنة ١٩٨٩م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٤٠١) الصادر في ١٥ / ٢ / ١٩٨٩م
================================================================================
لدرجات والرواتب الموحد والتي لديها أنظمة تصنيف خاصة ولا يوجد لديها قيد في نهايات المجموعة النوعية للوظائف الحرفية والمجموعة النوعية لوظائف الخدمات المعاونة. ثالثا: منطوق الرأي: جواز ترقية شاغلي الوظائف الحرفية والخدمات المعاونة لما يجاوز الدرجة المالية الثالثة عشرة من جدول الدرجات والرواتب الموحد للموظفين العمانيين المدنيين بالدولة إذا توفرت في شأنهم شروط الترقية، وذلك على النحو المبين في الأسباب.
================================================================================
: ١ – أحقية الفاضل / (مدير دائرة الموارد البشرية) المكافأة المخصصة لمكافأة التكليف نظير قيامه بتسيير أعمال (مدير دائرة الخدمات الإدارية). ٢ – عدم أحقية كل من: أ – الفاضل / مساعد مدير عام المديرية العامة لرعاية الصناعات الحرفية المكلف بتسيير أعمال المديرية العامة لرعاية…………. لمكافأة التكليف. ب – الفاضل / مساعد مدير دائرة المشتريات والعقود المكلف بتسيير أعمال دائرة المشتريات والعقود لمكافأة التكليف.
================================================================================
ابقة، إذ تم تعيينهما في ذلك الحين وفقا لمؤهلات ومدد خبرة معينة تتفق مع الحد الأدنى لمتطلبات شغل الدرجة المالية المعينين عليها، مع التنويه إلى أن مدة الخبرة السابقة يعتد بها عند احتساب المستحقات التقاعدية لكل منهما. لذلك؛ انتهى الرأي إلى عدم أحقية كل من: الفاضل / ………………….، والفاضل / ……………………… في تعديل درجتيهما الماليتين بناء على سنوات الخبرة العملية السابقة لديهما، وذلك على النحو الوارد في الأسباب.
================================================================================
ت ش.م.م. إعلان عن انتهاء أعمال التصفية لشركة فخر سمائل الشاملة – تضامنية. إعلان عن انتهاء أعمال التصفية لشركة الوشق الأبيض للتجارة – توصية. إعلان عن انتهاء أعمال التصفية لشركة مشاريع الحمادي المتكاملة ش.م.م. إعلان عن انتهاء أعمال التصفية لشركة مشاريع المروة الذهبية – توصية. إعلان عن انتهاء أعمال التصفية لشركة طيف المكارم – تضامنية. إعلان عن انتهاء أعمال التصفية لشركة زهور الأفراض المتميزة – توصية.
================================================================================
مرتبطة بالثروة المائية الحية، والأحكام الأخرى الواردة في اللائحة التنفيذية المنصوص عليهما في البندين (د) و(هـ) من المادة (٥٨) من قانون الثروة المائية الحية المشار إليه. لذلك، انتهى الرأي إلى أن تفسير كلمة (اللائحة) الواردة في قانون الثروة المائية الحية المشار إليه تمتد لتشمل اللوائح والقرارات المنفذة لقانون الثروة المائية الحية، وذلك إلى حين صدور لائحته التنفيذية، وذلك على النحو المبين في الأسباب.
================================================================================
لمنشور في الجريدة الرسمية العدد (١٤٧٣)، الصادر في ١ جمادى الآخرة ١٤٤٤هـ، الموافق ٢٥ ديسمبر ٢٠٢٢م، إذ ورد البند رقم (١) على النحو الآتي: م اسم الفائز المجال ١ حارث بن محمد بن شامس البطاشي تحقيق التراث العماني والصحيح هو: م اسم الفائز المجال ١ الشيخ / حارث بن محمد بن شامس البطاشي تحقيق التراث العماني لذا لزم التنويه. المراسم السلطانية نشر في عدد الجريدة الرسمية رقم (١٤٧٤) الصادر في ١ من يناير ٢٠٢٣م.
================================================================================
ت اللجنة الجهات ذات العلاقة بتخصيص أماكن لغسل الموتى في كل الولايات، والتعامل مع كل جثة حسب مقتضيات مخاطر العدوى. وتدعو اللجنة كافة أفراد المجتمع والمؤسسات إلى ضرورة الالتزام بالإجراءات الاحترازية والوقائية لمنع انتشار فيروس كورونا (كوفيد19)، وتؤكد على مخاطر التجمعات عموما، بما فيها التجمعات داخل المنازل، في احتمالات انتشار الوباء. حفظ الله عمان وسلطانها وجميع المواطنين والمقيمين، من كل شر ومكروه.
================================================================================
ونا (كوفيد19) أن توجه عناية الجميع إلى أن العمل بقرار منع الحركة ليلا سينتهي في الساعة الخامسة من صباح غد السبت 15 أغسطس 2020م. وإذ تقدر اللجنة التجاوب الكبير الذي أبداه المواطنون والمقيمون فإنها تهيب بالجميع الاستمرار في التقيد التام بارتداء الكمامات والمحافظة على التباعد الجسدي والمداومة على نظافة اليدين وسائر الإجراءات الوقائية للحد من انتشار فيروس كورونا. حفظ الله تعالى الجميع من كل سوء ومكروه
================================================================================
دة للحد من الجائحة، فقد قررت اللجنة العليا تمديد سريان العمل بقرار السماح لحركة الأفراد والمركبات، ومزاولة أنشطة محلات بيع المواد الغذائية والمخابز والمطاعم ومحلات مواد البناء والمواد الكهربائية والصحية ومحلات بيع الأعلاف في ولاية صور فقط في الفترة من الساعة السابعة صباحا وحتى الساعة الخامسة مساء يومي الخميس والجمعة 12 – 13 ذي الحجـة 1442هـ الموافق 22 – 23 يوليو 2021م. حفظ الله الجميع من كل مكروه.
================================================================================
٩] عدلت بموجب المرسوم السلطاني رقم ١٩ / ٢٠٠٥ والمرسوم السلطاني رقم ٧١ / ٢٠٠٨. [٣٠] عدلت بموجب المرسوم السلطاني رقم ٦٠ / ٩٧. [٣١] عدلت بموجب المرسوم السلطاني رقم ٦٠ / ٩٧. [٣٢] عدلت بموجب المرسوم السلطاني رقم ٦٠ / ٩٧. [٣٣] أضيفت بموجب المرسوم السلطاني رقم ٧٢ / ٩٦. [٣٤] عدلت بموجب المرسوم السلطاني رقم ٦٠ / ٩٧. [٣٥] عدلت بموجب المرسوم السلطاني رقم ٦٠ / ٩٧. [٣٦] عدل بموجب المرسوم السلطاني رقم ١٩ / ٢٠٠٥
================================================================================
رئة، الأمر الذي يضحى معه طلب الشركة بتعويضها في هذه الحالة غير قائم على سند صحيح، وخليقا بالرفض. لذلك، انتهى الرأي إلى الآتي: ١ – أحقية الشركة في فارق الأجور للقوى العاملة الوطنية نتيجة رفع الحد الأدنى للأجور. ٢ – عدم أحقية الشركة في فارق الأجور الناتجة عن منح العامل إجازة يوم الخميس، وعدم أحقيتها في فارق الأجور نتيجة تغيير ساعات العمل الأسبوعية من ٤٨ إلى ٤٥ ساعة، وذلك على النحو المبين في الأسباب.
================================================================================
بن محمد الحارثي ١٠ – اللواء عبدالله بن علي الحارثي ١١ – اللواء أحمد بن علي كشوب ١٢ – اللواء الركن غصن بن هلال العلوي ١٣ – اللواء الركن حمد بن ناصر النبهاني ١٤ – العميد أول محمد بن حمد الصارمي وذلك تقديرا من لدن جلالته أيده الله لدورهم في تأدية الواجب الوطني وقد صدر أمر المنح بتاريخ ٢٧ من جمادى الأولى ١٤٤٢هـ، الموافق ١١ من يناير ٢٠٢١م. نشر في عدد الجريدة الرسمية رقم (١٣٧٥) الصادر في ١٧ / ١ / ٢٠٢١م.
================================================================================
مال دراساته العليا على نفقته الخاصة لمدة (٤) أربع سنوات، وحيث إن لائحة الموارد البشرية الصادرة من هيئة تقنية المعلومات “آنذاك” ألزمت الموظف بالعمل في الهيئة لمدة مساوية لمدة سنوات الدراسة، ولما كانت لائحة الموارد البشرية المذكورة في كتاب طلب الرأي القانوني المشار إليه، لم تراجع أو تنشر من قبل الوزارة، عليه، فإن وزارة العدل والشؤون القانونية تعتذر عن عدم إبداء الرأي القانوني في الموضوع المشار إليه.
================================================================================
ن البلاط السلطاني العمانيين على المعروضة حالته هو نص المادة (٢٤) من قانون التخصيص الملغى، الذي قرر استمرار الموظف المنقول في الخضوع لهذا القانون، ومعاملته معاملة الموظف الحكومي عند انتهاء خدمته. لذلك، انتهى الرأي إلى أن ما قام به صندوق تقاعد موظفي ديوان البلاط السلطاني من صرف المعاش التقاعدي للمعروضة حالته، والامتناع عن صرف منحة التقاعد له، يتفق وصحيح حكم القانون، وذلك على النحو المبين في الأسباب.
================================================================================
تاريخ صدوره. [١] استبدلت عبارة “رئيس محكمة الاستئناف المختصة” بعبارة “رئيس المحكمة التجارية” أينما وردت في القانون فيما عدا المادتين (٣٧) و(٥٦) حيث استبدلت عبارة “رئيس المحكمة الابتدائية المختصة” بعبارة “رئيس المحكمة التجارية” بموجب المرسوم السلطاني رقم ٣ / ٢٠٠٧. [٢] عدلت بموجب المرسوم السلطاني رقم ٣ / ٢٠٠٧. [٣] عدلت بموجب المرسوم السلطاني رقم ٣ / ٢٠٠٧. [٤] عدلت بموجب المرسوم السلطاني رقم ٣ / ٢٠٠٧
================================================================================
لمحكمة على طلب التسليم أو إذا وافق الشخص المطلوب تسليمه في جلسة المحاكمة على أن يسلم فللحكومة تقدير أمر تسليمه. مادة (١٤) يجب على الدولة طالبة التسليم أن تتقدم لاستلام الشخص المطلوب تسليمه خلال ثلاثين يوما من تاريخ إخطارها بالموافقة على طلب التسليم، وإلا وجب إخلاء سبيله، ولا يجوز القبض عليه مرة أخرى أو اتخاذ أي إجراء آخر في شأنه إلا بناء على طلب جديد. [١] أضيفت بموجب المرسوم السلطاني رقم ٣٦ / ٢٠٠٩
================================================================================
ان مناطق حجر زراعية. الهيئة العامة للمناطق الاقتصادية الخاصة والمناطق الحرة قرار رقم ٦٢ / ٢٠٢٢ صادر في ٢٠ / ٧ / ٢٠٢٢ بتعديل بعض أحكام القرار رقم ٨ / ٢٠١٦ بتحديد رسوم الخدمات المقدمة من الهيئة العامة للمناطق الاقتصادية الخاصة والمناطق الحرة. هيئة تنظيم الاتصالات قرار رقم ١٠٨ / ٢٠٢٢ صادر في ١٩ / ٧ / ٢٠٢٢ بإصدار لائحة جودة خدمات الاتصالات. إعلانات رسمية وزارة العمل إعلان بشأن طلب تسجيل نقابات عمالية.
================================================================================
 ٣ / ٨٣، والقول بغير ذلك يتصادم مع قاعدة الأثر الفوري المباشر للقانون، وانعدام الأثر الرجعي له، الأمر الذي لا يجوز معه سحب الجنسية العمانية منهما. لذلك انتهى الرأي، إلى الآتي: ١ – جواز منح الجنسية العمانية للمعروضة حالاتهن: الفاضلة / ……، والفاضلة / …………….، والفاضلة / …………….. ٢ – عدم جواز سحب الجنسية العمانية من المعروضة حالتاهما: الفاضلة / …………….، والفاضلة / …………….، وذلك على النحو المبين بالأسباب.
================================================================================
2022م. وتؤكد اللجنة على ضرورة استمرار التزام أنشطة القاعات والخيام والمنظمين للمؤتمرات والمعارض الدولية والمحلية والأنشطة ذات الطابع الجماهيري بنسبة 70٪ من الطاقة الاستيعابية، شريطة تطبيق جميع الإجراءات والاشتراطات الوقائية المعتمدة. كما تؤكد على متابعتها الدائمة لتطورات الجائحة محليا وعالميا، وأنها ستتخذ الإجراءات المناسبة بما يتفق مع المستجدات المتعلقة بالجائحة. حفظ الله الجميع من كل سوء ومكروه.
================================================================================
بلها المجلس بما لا يتعارض مع أهداف المركز. المادة (١١) تعتبر أموال المركز أموالا عامة وتتمتع بمزايا وحقوق الخزانة العامة وامتيازاتها على أموال المدينين، وللمركز حماية هذه الأموال وتحصيلها بالطرق ووفق الإجراءات التي تحصل بها الضرائب والرسوم وغيرها من المبالغ المستحقة لوحدات الجهاز الإداري للدولة. المادة (١٢) تسري على المركز وموظفيه أحكام القوانين والنظم واللوائح المعمول بها في ديوان البلاط السلطاني
================================================================================
 المرسوم. المادة ٤ على كل من وزير شؤون الأراضي والبلديات ووزير الزراعة والأسماك والنفط والمعادن تنفيذ هذا المرسوم وإصدار اللوائح الكفيلة بتنسيق العمل بين وزارتيهما طبقا لأحكامه. المادة ٥ ينشر هذا المرسوم في الجريدة الرسمية ويعمل به من تاريخ نشره. صدر في: أول جمادى الثانية ١٣٩٨هـ الموافق: ٨ مايو ١٩٧٨م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (١٤٧) الصادر في ١٥ / ٥ / ١٩٧٨م
================================================================================
انتهاء أعمال التصفية لشركة الجماهير المتحدة ش.م.م. إعلان عن انتهاء أعمال التصفية لشركة أبناء الوشيل للمقاولات – تضامنية. إعلان عن انتهاء أعمال التصفية لشركة بن شير للتجارة ش.م.م. إعلان عن انتهاء أعمال التصفية لشركة راشد بن سهيل بن سويد البادي وولده للتجارة – تضامنية. إعلان عن انتهاء أعمال التصفية لشركة الحبن للاستشارات الإدارية والمالية ش.م.م. إعلان عن انتهاء أعمال التصفية لشركة سيف للأعمال ش.ش.و.
================================================================================
 في هذا القانون عند انتهاء خدمتها دون الإخلال بقاعدة حظر الجمع بين معاشين، وبناء عليه وبحكم اللزوم لا يجوز للمعروضة حالتها طلب ضم مدة خدمتها السابقة إلى مدة خدمتها الجديدة في الديوان في حساب المعاش. لذلك، انتهى الرأي إلى عدم أحقية المعروضة حالتها في طلب ضم مدة خدمتها السابقة في وزارة الصحة إلى مدة خدمتها في الديوان واعتبارهما مدة واحدة في حساب مستحقاتها التقاعدية، وذلك على النحو المبين في الأسباب.
================================================================================

In [18]:
n_samples = 715
random_samples = df_clean.sample(n=n_samples)

for i, row in random_samples.head(715).iterrows():
    print("------")
    print(row['footer'])

------
صدر في: ٦ من ربيع الثاني سنة ١٤٢٥ هـ الموافق: ٢٦ من مايو سنة ٢٠٠٤ م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٧٦٨) الصادر في ١ / ٦ / ٢٠٠٤م
------
صدر في: ٢١ من شعبان سنة ١٤١٧هـ الموافق: ١ من يناير سنة ١٩٩٧م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٥٩٠) الصادر في ١ / ١ / ١٩٩٧م.
------
صدر في: ١٢ من صفر سنة ١٤٢٧هـ الموافق: ١٢ من مارس سنة ٢٠٠٦م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٨١١) الصادر في ١٥ / ٣ / ٢٠٠٦م
------
صدر في: ١٦ من جمادى الأولى سنة ١٤٤٠هـ الموافق: ٢٣ من يناير سنة ٢٠١٩م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (١٢٧٨) الصادر في ٢٧ / ١ / ٢٠١٩م.
------
صدر في: ١١ محرم سنة ١٤٠٢هـ الموافق: ٩ نوفمبر سنة ١٩٨١م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٢٢٩) الصادر في ١٥ / ١١ / ١٩٨١م
------
صدر في: ٨ من جمادى الأولى سنة ١٤٢٦هـ الموافق: ١٥ من يونيو سنة ٢٠٠٥م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٧٩٤) الصادر في ٢ / ٧ / ٢٠٠٥م.
------
صدر في: ١٨ جمادى الثانية ١٣٩٨هـ الموافق: ٢٥ مايو ١٩٧٨م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (١٤٨) الصادر في ١ / ٦ / ١٩٧٨م
------
صدر في: ٨ من شعبان سنة ١٤٢٠هـ الموافق: ١٦ من نوفمبر سنة ١٩٩٩م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٦٦٠) الصادر في ١ / ١٢ / ١٩٩٩م
------
صدر في: ١٤ من شعبان سنة ١٤٣١هـ الموافق: ٢٦ من يوليو سنة ٢٠١٠م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٩١٦) الصادر في ١ / ٨ / ٢٠١٠م
------
صدر في: ١٦ من ربيع الأول ١٤٢٣هـ الموافق: ٢٩ من مايو ٢٠٠٢م نشر في عدد الجريدة الرسمية رقم (٧٢١) الصادر في ١٥ / ٦ / ٢٠٠٢م
------
صدر في: ٢٠ من ربيع الأول سنة ١٤٣٧هـ الموافق: ١ من يناير سنة ٢٠١٦م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (١١٣٠) الصادر في ٣ / ١ / ٢٠١٦م.
------
صدر في: ١٩ من جمادى الأولى ١٤٤٤هـ الموافق: ١٥ من ديسمبر ٢٠٢٢م محمد بن سلطان بن حمود البوسعيدي نائب رئيس المجلس الأعلى للقضاء نشر في عدد الجريدة الرسمية رقم (١٤٧٣) الصادر في ٢٥ من ديسمبر ٢٠٢٢م.
------
صدر في: ١٤ من محرم سنة ١٤٣٢هـ الموافق: ٢٠ من ديسمبر سنة ٢٠١٠م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٩٢٦) الصادر في ١ / ١ / ٢٠١١م.
------
صدر في: ٢ من رجب سنة ١٤٢٩هـ الموافق: ٥ من يوليو سنة ٢٠٠٨م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٨٦٧) الصادر في ١٥ / ٧ / ٢٠٠٨م.
------
صدر في: ١٦ من شوال سنة ١٤٢٠هـ الموافق: ٢٣ من يناير سنة ٢٠٠٠م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٦٦٤) الصادر في ١ / ٢ / ٢٠٠٠م
------
صدر في: ٥ ذو القعدة سنة ١٤١٣هـ الموافق: ٢٧ أبريل سنة ١٩٩٣م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٥٠٢) الصادر في ١ / ٥ / ١٩٩٣م
------
صدر في: ٢ من رجب سنة ١٤٢٩هـ الموافق: ٥ من يوليو سنة ٢٠٠٨م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في الجريدة الرسمية رقم (٨٦٧) الصادر في ١٥ / ٧ / ٢٠٠٨م.
------
صدر في: ٢٩ من شعبان ١٤٤٤هـ الموافق: ٢٢ من مارس ٢٠٢٣م د. ليلى بنت أحمد بن عوض النجار وزيرة التنمية الاجتماعية نشر في عدد الجريدة الرسمية رقم (١٤٩٠) الصادر في ٢٥ من أبريل ٢٠٢٣م.
------
صدر في: ٧ من جمادى الأولى سنة ١٤٤٧هـ الموافق: ٢٩ من أكتوبر سنة ٢٠٢٥م هيثم بن طارق سلطان عمان نشر في عدد الجريدة الرسمية رقم (١٦٢٠) الصادر في ٢ من نوفمبر ٢٠٢٥م.
------
صدر في: ٢٣ من جمادى الأولى ١٤٢٠هـ الموافق: ٥ من سبتمبر ١٩٩٩م نشر في عدد الجريدة الرسمية رقم (٦٥٥) الصادر في ١٥ / ٩ / ١٩٩٩م
------
صدر في: ٧ من ذي الحجة ١٤٣٥هـ الموافق: ١ من أكتوبر ٢٠١٤م د. علي بن مسعود بن علي السنيدي وزير التجارة والصناعة رئيس مجلس إدارة صندوق الرفد نشر في عدد الجريدة الرسمية رقم (١٠٧٤) الصادر في ١٩ / ١٠ / ٢٠١٤م.
------
صدر في: ٢٥ من جمادى الآخرة سنة ١٤١٦هـ الموافق: ١٩ من نوفمبر سنة ١٩٩٥م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٥٦٤) الصادر في ٢ / ١٢ / ١٩٩٥م
------
None
------
صدر في: ١٢ من جمادى الثانية سنة ١٤٣١هـ الموافق: ٢٦ من مايو سنة ٢٠١٠م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٩١٢) الصادر في ١ / ٦ / ٢٠١٠م.
------
None
------
صدر في: ١٠ ربيع الثاني ١٤٠٢هـ الموافق: ٤ فبراير ١٩٨٢م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٢٣٥) الصادر في ١٥ / ٢ / ١٩٨٢م
------
صدر في: ٧ من ربيع الثاني سنة ١٤٣٣هـ الموافق: ٢٩ من فبراير سنة ٢٠١٢م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٩٦٣) الصادر في ٣ / ٣ / ٢٠١٢م
------
صدر في: ٢٦ ذي القعدة سنة ١٤٠٥هـ الموافق: ١٣ أغسطس سنة ١٩٨٥م العقيد الركن / سالم بن عبدالله الغزالي وزير التجارة والصناعة نشر في عدد الجريدة الرسمية رقم (٣١٩) الصادر في ١ / ٩ / ١٩٨٥م
------
صدر في: ١٢ من جمادى الآخرة سنة ١٤١٦هـ الموافق: ٦ من نوفمبر سنة ١٩٩٥م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٥٦٣) الصادر في ١٥ / ١١ / ١٩٩٥م
------
صدر في: ١١ من رمضان سنة ١٤٢٨هـ الموافق: ٢٣ من سبتمبر سنة ٢٠٠٧م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٨٤٨) الصادر في ١ / ١٠ / ٢٠٠٧م.
------
صدر في: ١٤ من ربيع الثاني سنة ١٤٣٥هـ الموافق: ١٦ من فبراير سنة ٢٠١٤م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (١٠٤٣) الصادر في ١٩ / ١ / ٢٠١٤م
------
None
------
صدر في: ٢٣ من جمادى الآخرة سنة ١٤١٧هـ الموافق: ٥ من نوفمبر سنة ١٩٩٦م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٥٨٧) الصادر في ١٦ / ١١ / ١٩٩٦م.
------
صدر في: ١٨ من ربيع الأول سنة ١٤٣٩هـ الموافق: ٧ من ديسمبر سنة ٢٠١٧م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (١٢٢٢) الصادر في ١٠ / ١٢ / ٢٠١٧م
------
صدر في: ١٩ من رجب ١٤٤٦هـ الموافق: ١٩ من يناير ٢٠٢٥م د. رحمة بنت إبراهيم بن سعيد المحروقية وزيرة التعليم العالي والبحث العلمي والابتكار نشر في عدد الجريدة الرسمية رقم (١٥٨٢) الصادر في ٢ من فبراير ٢٠٢٥م.
------
صدر في: ١٩ جمادى الأولى سنة ١٤٠٩هـ الموافق: ٢٩ ديسمبر سنة ١٩٨٨م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٣٩٨) الصادر في ١ / ١ / ١٩٨٩م
------
صدر في: ١٤ من صفر سنة ١٤٣٦هـ الموافق: ٧ من ديسمبر سنة ٢٠١٤م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (١٠٨٢) الصادر في ١٤ / ١٢ / ٢٠١٤م.
------
صدر في: ٩ شعبان ١٣٩٧هـ الموافق: ٢٦ يوليو ١٩٧٧م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (١٣٠) الصادر في ١ / ٨ / ١٩٧٧م
------
صدر في: ٢٧ من ذي الحجة سنة ١٤٢٠هـ الموافق: ٢ من أبريل سنة ٢٠٠٠م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٦٦٩) الصادر في ١٥ / ٤ / ٢٠٠٠م
------
صدر في: ٢٣ من جمادى الأولى سنة ١٤١٩ هـ الموافق: ١٤ من سبتمبر سنة ١٩٩٨ م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٦٣١) الصادر في ١٥ / ٩ / ١٩٩٨م
------
صدر في: ١٧ من شوال سنة ١٤٢٢هـ الموافق: ١ من يناير سنة ٢٠٠٢م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٧١٠) الصادر في ١ / ١ / ٢٠٠٢م.
------
صدر في: ٢٦ من ربيع الثاني سنة ١٤٣١هـ الموافق: ١١ من أبريل سنة ٢٠١٠م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٩٠٩) الصادر في ١٧ / ٤ / ٢٠١٠م.
------
صدر في: ١٢ من محرم سنة ١٤٢٨هـ الموافق: ٣١ من يناير سنة ٢٠٠٧م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٨٣٢) الصادر في ٣ / ٢ / ٢٠٠٧م.
------
صدر في: ٨ من محرم ١٤٤٥هـ الموافق: ٢٦ من يوليو ٢٠٢٣م د. سعيد بن حمد بن سعيد الربيعي رئيس جامعة التقنية والعلوم التطبيقية نشر في عدد الجريدة الرسمية رقم (١٥٠٤) الصادر في ٣٠ من يوليو ٢٠٢٣م.
------
صدر في: ٢٥ / ٣ / ١٤٣٤هـ الموافق: ٦ / ٢ / ٢٠١٣م عبدالملك بن عبدالله الخليلي وزير العدل نشر في عدد الجريدة الرسمية رقم (١٠٠١) الصادر في ١٦ / ٢ / ٢٠١٣م
------
صدر في: ٢٨ محرم سنة ١٤٠٢هـ الموافق: ٢٦ نوفمبر سنة ١٩٨١م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٢٣١) الصادر في ١٥ / ١٢ / ١٩٨١م
------
صدر في: ٢ من صفر سنة ١٤٢١هـ الموافق: ٦ من مايو سنة ٢٠٠٠م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٦٧١) الصادر في ١٥ / ٥ / ٢٠٠٠م.
------
صدر في: ٨ ربيع ثاني ١٤٠٠هـ الموافق: ٢٥ فبراير ١٩٨٠م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (١٨٩) الصادر في ١ / ٣ / ١٩٨٠م.
------
صدر في: ٧ من محرم سنة ١٤٤٣هـ الموافق: ١٦ من أغسطس سنة ٢٠٢١م هيثم بن طارق سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (١٤٠٤) الصادر في ٢٢ / ٨ / ٢٠٢١م.
------
صدر في: ٢٧ من رمضان سنة ١٤٣٤هـ الموافق: ٥ من أغسطس سنة ٢٠١٣م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (١٠٢٤) الصادر في ١٨ / ٨ / ٢٠١٣م
------
صدر في: ٤ ذو الحجة سنة ١٤١١هـ الموافق: ١٧ يونيو سنة ١٩٩١م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٤٥٨) الصادر في ١ / ٧ / ١٩٩١م
------
صدر في: ٧ ربيع الثاني سنة ١٤١٣هـ الموافق: ٤ أكتوبر سنة ١٩٩٢م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٤٨٩) الصادر في ١٧ / ١٠ / ١٩٩٢م
------
صدر في: ٨ ربيع الأول ١٤٠٠هـ الموافق: ٢٦ يناير ١٩٨٠م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (١٨٧) الصادر في ٢ / ٢ / ١٩٨٠م
------
صدر في: ١ شعبان سنة ١٤١٣هـ الموافق: ٢٤ يناير سنة ١٩٩٣م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٤٩٦) الصادر في ١ / ٢ / ١٩٩٣م
------
صدر في: ٤ من رجب ١٤٣٤هـ الموافق: ١٤ من مايو ٢٠١٣م سيف بن محمد بن سيف الشبيبي وزير الإسكان نشر في عدد الجريدة الرسمية رقم (١٠١٣) الصادر في ١٩ / ٥ / ٢٠١٣م.
------
صدر في: ١٤ من ذي الحجة سنة ١٤١٧هـ الموافق: ٢١ من أبريل سنة ١٩٩٧م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٥٩٧) الصادر في ١٥ / ٤ / ١٩٩٧م
------
صدر في: ٢٤ صفر ١٤٢٩هـ الموافق: ٢ مارس ٢٠٠٨م الفريق مالك بن سليمان المعمري المفتش العام للشرطة والجمارك نشر في عدد الجريدة الرسمية رقم (٨٥٩) الصادر في ١٥ / ٣ / ٢٠٠٨م
------
صدر في: ٢٩ صفر ١٤١٢هـ موافق: ٩ سبتمبر ١٩٩١م سالم بن عبدالله الغزالي وزير التجارة والصناعة نشر في عدد الجريدة الرسمية رقم (٤٦٣) الصادر في ١٥ / ٩ / ١٩٩١م
------
None
------
صدر في: ١٣ من جمادى الآخرة سنة ١٤٤٥هـ الموافق: ٢٧ من ديسمبر سنة ٢٠٢٣م هيثم بن طارق سلطان عمان نشر في عدد الجريدة الرسمية رقم (١٥٢٦) الصادر في ٣١ من ديسمبر ٢٠٢٣م.
------
صدر في: ٨ من جمادى الأولى سنة ١٤٢٢هـ الموافق: ٢٩ من يوليو سنة ٢٠٠١م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٧٠٠) الصادر في ١ / ٨ / ٢٠٠١م
------
صدر في: ١٨ من صفر سنة ١٤٢٩هـ الموافق: ٢٥ من فبراير سنة ٢٠٠٨م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٨٥٨) الصادر في ١ / ٣ / ٢٠٠٨م.
------
صدر في: ٢٠ من رمضان سنة ١٤٢٩هـ الموافق: ٢١ من سبتمبر سنة ٢٠٠٨م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٨٧٢) الصادر في ٦ / ١٠ / ٢٠٠٨م
------
صدر في: ١٦ من جمادى الأولى سنة ١٤١٧هـ الموافق: ٢٩ من سبتمبر سنة ١٩٩٦م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٥٨٤) الصادر في ١ / ١٠ / ١٩٩٦م.
------
صدر في: ١٨ من جمادى الثانية سنة ١٤٤٢هـالموافق: ١ من فبراير سنة ٢٠٢١م هيثم بن طارقسلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (١٣٧٨) الصادر في ٧ / ٢ / ٢٠٢١م.
------
صدر في: ٢٤ من محرم سنة ١٤١٧هـ الموافق: ١١ من يونيو سنة ١٩٩٦م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٥٧٧) الصادر في ١٥ / ٦ / ١٩٩٦م
------
صدر في: ٨ جمادى الثاني سنة ١٤١٠هـ الموافق: ٦ يناير سنة ١٩٩٠م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٤٢٣) الصادر في ١٥ / ١ / ١٩٩٠م.
------
None
------
صدر في: ٥ من ربيع الثاني ١٤٣٤هـ الموافق: ١٦ من فبراير ٢٠١٣م يحيى بن سعيد بن عبدالله الجابري رئيس مجلس إدارة الهيئة العامة لسوق المال نشر في عدد الجريدة الرسمية رقم (١٠٠٢) الصادر في ٢٣ / ٢ / ٢٠١٣م.
------
صدر في: ١٩ من ذي القعدة ١٤٤٤هـ الموافق: ٨ من يونيو ٢٠٢٣م د. هلال بن علي بن هلال السبتي وزير الصحة نشر في عدد الجريدة الرسمية رقم (١٤٩٧) الصادر في ١١ من يونيو ٢٠٢٣م.
------
صدر في: ٢٠ ربيع الأول ١٤٢٣هـ الموافق: ٢ من يونيو ٢٠٠٢م د. يحيى بن محفوظ المنذري وزير التعليم العالي نشر في عدد الجريدة الرسمية رقم (٧٢١) الصادر في ١٥ / ٦ / ٢٠٠٢م
------
صدر في: ٣ من رمضان ١٤٣٨هـ الموافق: ٢٩ من مايو ٢٠١٧م عبدالله بن ناصر بن عبدالله البكري وزير القوى العاملة نشر في عدد الجريدة الرسمية رقم (١١٩٧) الصادر في ٤ / ٦ / ٢٠١٧م
------
صدر في: ٢٠ شوال سنة ١٤٠٧هـ الموافق: ١٦ يونيو سنة ١٩٨٧م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٣٦٢) الصادر في ١ / ٧ / ١٩٨٧م.
------
صدر في: ٢ من جمادى الآخرة سنة ١٤٤٤هـ الموافق: ٢٦ من ديسمبر سنة ٢٠٢٢م هيثم بن طارق سلطان عمان نشر في عدد الجريدة الرسمية رقم (١٤٧٤) الصادر في ١ من يناير ٢٠٢٣م.
------
صدر في: ١٣ من محرم سنة ١٤٢٣هـ الموافق: ٢٧ من مارس سنة ٢٠٠٢م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٧١٦) الصادر في ١ / ٤ / ٢٠٠٢م.
------
صدر في: ٢٣ من جمادى الثانية ١٤٣٥هـ الموافق: ٢٣ من ابريل ٢٠١٤م حسين بن علي بن زاهر الهلالي المدعي العام نشر في عدد الجريدة الرسمية رقم (١٠٥٧) الصادر في ٤ / ٥ / ٢٠١٤م
------
صدر في: ٢٦ من جمادى الآخرة سنة ١٤٢٠هـ الموافق: ٦ من أكتوبر سنة ١٩٩٩م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٦٥٧) الصادر في ١٦ / ١٠ / ١٩٩٩م.
------
صدر في: ٤ من ربيع الثاني سنة ١٤٢٧هـ الموافق: ٢ من مايو سنة ٢٠٠٦م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٨١٥) الصادر في ١٥ / ٥ / ٢٠٠٦م.
------
صدر في: ٦ ربيع الأول سنة ١٤٠١هـ الموافق: ١٣ يناير سنة ١٩٨١م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٢٠٩) الصادر في ١٥ / ١ / ١٩٨١م
------
صدر في: ١٨ من جمادى الثانية سنة ١٤٢٨هـ الموافق: ٣ من يوليو سنة ٢٠٠٧م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٨٤٣) الصادر في ١٥ / ٧ / ٢٠٠٧م
------
صدر في: ٢ من جمادى الآخرة سنة ١٤٤٤هـ الموافق: ٢٦ من ديسمبر سنة ٢٠٢٢م هيثم بن طارق سلطان عمان نشر في عدد الجريدة الرسمية رقم (١٤٧٤) الصادر في ١ يناير ٢٠٢٣م.
------
None
------
صدر في: ٢٢ من ربيع الآخر ١٤١٦هـ الموافق: ١٨ من سبتمبر ١٩٩٥م د / علي بن محمد بن موسى وزير الصحة نشر في عدد الجريدة الرسمية رقم (٥٦٠) الصادر في ١ / ١٠ / ١٩٩٥م
------
صدر في: ١٩ من ذي القعدة سنة ١٤٣٤هـ الموافق: ٢٥ من سبتمبر سنة ٢٠١٣م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (١٠٢٨) الصادر في ٢٩ / ٩ / ٢٠١٣م.
------
None
------
صدر في: ١٦ من ذي القعدة سنة ١٤١٤هـ الموافق: ٢٧ أبريل سنة ١٩٩٤م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٥٢٦) الصادر في ١ / ٥ / ١٩٩٤م
------
صدر في: ٢٧ من محرم ١٤٣٧هـ الموافق: ١٠ من نوفمبر ٢٠١٥م هيثم بن طارق آل سعيد الوزير المشرف على هيئة الوثائق والمحفوظات الوطنية نشر في عدد الجريدة الرسمية رقم (١١٢٣) الصادر في ١٥ / ١١ / ٢٠١٥م.
------
صدر في: ٥ من ذي القعدة سنة ١٤٢٣هـ الموافق: ٨ من يناير سنة ٢٠٠٣م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٧٣٥) الصادر في ١٥ / ١ / ٢٠٠٣م.
------
صدر في: ٩ ربيع الأول سنة ١٤١١هـ الموافق: ٢٩ سبتمبر سنة ١٩٩٠م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٤٤٠) الصادر في ١ / ١٠ / ١٩٩٠م.
------
صدر في: ٢٨ شعبان ١٣٩٨هـ الموافق: ٣ أغسطس ١٩٧٨م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (١٥٣) الصادر في ١٥ / ٨ / ١٩٧٨م
------
صدر في: ١٧ من ذي القعدة سنة ١٤٤٦هـ الموافق: ١٥ من مايو سنة ٢٠٢٥م هيثم بن طارق سلطان عمان نشر في عدد الجريدة الرسمية رقم (١٥٩٦) الصادر في ١٨ من مايو ٢٠٢٥م.
------
صدر في: ٢١ من محرم سنة ١٤١٨هـ الموافق: ٢٨ من مايو سنة ١٩٩٧م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٦٠٠) الصادر في ١ / ٦ / ١٩٩٧م.
------
صدر في: ٢٦ من شوال سنة ١٤٢٦هـ الموافق: ٢٨ من نوفمبر سنة ٢٠٠٥م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٨٠٤) الصادر في ٥ / ١٢ / ٢٠٠٥م.
------
صدر في: ١٣ من شعبان سنة ١٤١٩هـ الموافق: ٢ من ديسمبر سنة ١٩٩٨م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٦٣٧) الصادر في ١٥ / ١٢ / ١٩٩٨م.
------
None
------
صدر في: ١٣ من ذي القعدة ١٤٤٦هـ الموافق: ١١ من مايو ٢٠٢٥م سالم بن ناصر العوفي وزير الطاقة والمعادن رئيس مجلس إدارة هيئة تنظيم الاتصالات نشر في عدد الجريدة الرسمية رقم (١٥٩٦) الصادر في ١٨ من مايو ٢٠٢٥م.
------
صدر في: ٩ صفر سنة ١٤٠٥هـ الموافق: ٣ نوفمبر سنة ١٩٨٤م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٣٠٠) الصادر في ١٥ / ١١ / ١٩٨٤م.
------
صدر في: ٨ من جمادى الأولى سنة ١٤١٦هـ الموافق: ٣ من أكتوبر سنة ١٩٩٥م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٥٦١) الصادر في ١٥ / ١٠ / ١٩٩٥م
------
صدر في: ٢٥ / ٤ / ١٤٣٧هـ الموافق: ٤ / ٢ / ٢٠١٦م أحمد بن عبدالله بن محمد الشحي وزير البلديات الإقليمية وموارد المياه نشر في عدد الجريدة الرسمية رقم (١١٣٦) الصادر في ٢١ / ٢ / ٢٠١٦م.
------
صدر في: ٢٥ جمادى الآخرة سنة ١٤١٢هـ الموافق: ١ يناير سنة ١٩٩٢م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٤٧٠) الصادر في ١ / ١ / ١٩٩٢م
------
صدر في: ٩ من ربيع الثاني ١٤٣٧هـ الموافق: ١٩ من يناير ٢٠١٦م خالد بن هلال بن سعود البوسعيدي وزير ديوان البلاط السلطاني نشر في عدد الجريدة الرسمية رقم (١١٣٣) الصادر في ٣١ / ١ / ٢٠١٦م
------
صدر في: ٢٩ من ذي الحجة سنة ١٤٣١هـ الموافق: ٥ من ديسمبر سنة ٢٠١٠م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٩٢٥) الصادر في ١٥ / ١٢ / ٢٠١٠م
------
صدر في: ٢٥ من ربيع الآخر سنة ١٤٤٥هـ الموافق: ٩ من نوفمبر سنة ٢٠٢٣م هيثم بن طارق سلطان عمان نشر في عدد الجريدة الرسمية رقم (١٥١٩) الصادر في ١٢ من نوفمبر ٢٠٢٣م.
------
صدر في: ٢١ من صفر ١٤٣٦هـ الموافق: ١٤ من ديسمبر ٢٠١٤م حمود بن فيصل البوسعيدي وزير الداخلية نشر في عدد الجريدة الرسمية رقم (١٠٨٣) الصادر في ٢١ / ١٢ / ٢٠١٤م
------
None
------
صدر في: ١٨ من ربيع الثاني سنة ١٤٣٧هـ الموافق: ٢٨ من يناير سنة ٢٠١٦م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (١١٣٣) الصادر في ٣١ / ١ / ٢٠١٦م
------
صدر في: ٢ من رجب سنة ١٤٢٣هـ الموافق: ٩ من سبتمبر سنة ٢٠٠٢م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٧٢٧) الصادر في ١٥ / ٩ / ٢٠٠٢م
------
صدر في: ١٩ من ذي القعدة ١٤٤٢هـ الموافق: ٣٠ من يونيو ٢٠٢١م ناصر بن خميس الجشمي رئيس مجلس إدارة هيئة تنظيم الاتصالات نشر في عدد الجريدة الرسمية رقم (١٤٠٦) الصادر في ٥ / ٩ / ٢٠٢١م
------
صدر في: ٢٢ ربيع الثاني ١٣٩٩هـ الموافق: ٢١ مارس ١٩٧٩م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (١٦٧) الصادر في ١ / ٤ / ١٩٧٩م
------
صدر في: ١٢ شعبان ١٤٠٢هـ الموافق: ٥ يونيو ١٩٨٢م قابوس بن سعيد سلطان عمان ملاحظة: مرفقات المرسوم غير متوفرة. نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٢٤٣) الصادر في ١ / ٧ / ١٩٨٢م
------
None
------
صدر في: ٢١ من ذي القعدة سنة ١٤٣٠هـ الموافق: ٩ من نوفمبر سنة ٢٠٠٩م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٨٩٩) الصادر في ١٥ / ١١ / ٢٠٠٩م
------
صدر في: ٢٢ / ٤ / ١٤٤٥هـ الموافق: ٦ / ١١ / ٢٠٢٣م د. سعود بن حمود بن أحمد الحبسي وزير الثروة الزراعية والسمكية وموارد والمياه نشر في عدد الجريدة الرسمية رقم (١٥١٩) الصادر في ١٢ من نوفمبر ٢٠٢٣م.
------
صدر في: ٢٦ من ذي القعدة سنة ١٤٣٥هـ الموافق: ٢١ من سبتمبر سنة ٢٠١٤م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (١٠٧٢) الصادر في ٢٨ / ٩ / ٢٠١٤م.
------
صدر في: ٢٧ من ربيع الأول سنة ١٤٣٢هـ الموافق: ٣ من مارس سنة ٢٠١١م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٩٣١) الصادر في ١٥ / ٣ / ٢٠١١م
------
صدر في: ٢٨ من شعبان ١٤٤١هـ الموافق: ٢٢ من ابريل ٢٠٢٠م د. علي بن مسعود بن علي السنيدي رئيس مجلس إدارة الهيئة العامة للتخصيص والشراكة نشر في عدد الجريدة الرسمية رقم (١٣٤٠) الصادر في ٣ / ٥ / ٢٠٢٠م.
------
صدر في: ١٧ من رجب سنة ١٤٣٦هـ الموافق: ٦ من مايو سنة ٢٠١٥م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (١١٠٠) الصادر في ١٠ / ٥ / ٢٠١٥م.
------
None
------
صدر في: ٢٨ رجب سنة ١٤١٤هـ الموافق: ١١ يناير سنة ١٩٩٤م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٥١٩) الصادر في ١٥ / ١ / ١٩٩٤م.
------
صدر في: ٢١ من شوال ١٤٤٣هـ الموافق: ٢٢ من مايو ٢٠٢٢م ناصر بن خميس الجشمي رئيس مجلس إدارة هيئة تنظيم الاتصالات نشر في عدد الجريدة الرسمية رقم (١٤٤٣) الصادر في ٢٩ / ٥ / ٢٠٢٢م
------
None
------
صدر في: ٢٤ من محرم ١٤٤٤هـ الموافق: ٢٢ من أغسطس ٢٠٢٢م حمود بن فيصل البوسعيدي وزير الداخلية نشر في عدد الجريدة الرسمية رقم (١٤٥٦) الصادر في ٢٨ من أغسطس ٢٠٢٢م.
------
صدر في: ٢٥ من محرم سنة ١٤١٥هـ الموافق: ٤ يوليو سنة ١٩٩٤م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٥٣١) الصادر في ١٦ / ٧ / ١٩٩٤م
------
صدر في: ٢٥ من شعبان سنة ١٤٢٥هـ الموافق: ١٠ من أكتوبر سنة ٢٠٠٤م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٧٧٧) الصادر في ١٦ / ١٠ / ٢٠٠٤م
------
صدر في: ٦ من صفر ١٤٣٨هـ الموافق: ٦ من نوفمبر ٢٠١٦م عبدالله بن ناصر بن عبدالله البكري وزير القوى العاملة نشر في عدد الجريدة الرسمية رقم (١١٧٠) الصادر في ١٣ / ١١ / ٢٠١٦م
------
صدر في: ٣٠ من جمادى الثانية سنة ١٤٢٧هـ الموافق: ٢٦ من يوليو سنة ٢٠٠٦م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٨٢٠) الصادر في ١ / ٨ / ٢٠٠٦م
------
صدر في: ١٣ من محرم ١٤٤٣هـالموافق: ٢٢ من أغسطس ٢٠٢١م د. ليلى بنت أحمد بن عوض النجاروزيرة التنمية الاجتماعية نشر في عدد الجريدة الرسمية رقم (١٤٠٥) الصادر في ٢٩ / ٨ / ٢٠٢١م
------
None
------
صدر في: ٢٩ ذو القعدة سنة ١٤١٢هـ الموافق: ٣١ مايو سنة ١٩٩٢م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (٤٨٠) الصادر في ١ / ٦ / ١٩٩٢م

In [19]:
# اضافه کردن ستون طول متن و تعداد کلمات
df_clean['text_word_count'] = df_clean['text'].apply(lambda x: len(x.split()))

print("\nآمار طول متن:")
print(df_clean['text_word_count'].describe())

آمار طول متن:
count     7492.000000
mean       263.253604
std        932.541465
min         27.000000
25%         80.000000
50%        104.000000
75%        155.000000
max      28623.000000
Name: text_word_count, dtype: float64

In [20]:
n_samples = 500
random_samples = df_clean.sample(n=n_samples)

for i, row in random_samples.iterrows():
    print('=' * 80)
    print(f'Index: {i}')
    print(row['text'][-300:])

================================================================================
Index: 3416
التي يقدرها الاستثناء من هذا الشرط لمن أمضى بنجاح ثمان سنوات دراسية. البند (٧) أن يخضع لنفس المتطلبات الدراسية اللازمة للحصول على المؤهل في التعليم دون الجامعي والجامعي والدراسات العليا، وأن تكون الدراسة نظامية. المادة الثانية ينشر هذا القرار في الجريدة الرسمية، ويعمل به من اليوم التالي لتاريخ نشره.
================================================================================
Index: 652
٤ تحل اللجنة العليا لإعداد الترشيحات النهائية لنيل أوسمة الاستحقاق المشكلة بمقتضى المرسوم السلطاني رقم ٥٢ / ٧٦. مادة ٥ على الجهات المعنية في السلطنة معاونة المجلس الأعلى لرعاية الشباب في تنفيذ هذا المرسوم كل في حدود اختصاصه. مادة ٦ ينشر هذا المرسوم في الجريدة الرسمية ويعمل به اعتبارا من تاريخ صدوره.
================================================================================
Index: 287
يس بلدية العاصمة إلى وظيفة وكيل وزارة لشؤون البلديات بوزارة شؤون الأراضي والبلديات اعتبارا من ١ /٦ / ١٩٧٨. المادة ٣ على وزير شؤون الأراضي والبلديات إعادة ترتيب الهيكل التنظيمي للوزارة وتحديد اختصاصات الوظائف فيها طبقا لهذا المرسوم. المادة ٤ ينشر هذا المرسوم في الجريدة الرسمية ويعمل به من تاريخ نشره.
================================================================================
Index: 5239
ارات، تسري على الوحدة القوانين والنظم المطبقة على ديوان البلاط السلطاني فيما لم يرد بشأنه نص خاص في النظام المرفق، وبما لا يتعارض مع أحكامه. المادة الثالثة يلغى كل ما يخالف هذا المرسوم والنظام المرفق، أو يتعارض مع أحكامهما. المادة الرابعة ينشر هذا المرسوم في الجريدة الرسمية، ويعمل به من تاريخ صدوره.
================================================================================
Index: 2897
مبر ١٩٦٥، وبناء على ما تقتضيه المصلحة العامة. رسمنا بما هو آت مادة (١) التصديق على الاتفاقية الدولية للقضاء على جميع أشكال التمييز العنصري المشار إليها. مادة (٢) على جهات الاختصاص إيداع وثيقة الانضمام إلى الاتفاقية طبقا لأحكامها. مادة (٣) ينشر هذا المرسوم في الجريدة الرسمية، ويعمل به من تاريخ صدوره.
================================================================================
Index: 1796
م، وبناء على ما تقتضيه المصلحة العامة. رسمنا بما هو آت مادة (١) الموافقة على انضمام سلطنة عمان إلى الاتفاقية الدولية للبحث والإنقاذ المشار إليها. مادة (٢) على جهات الاختصاص إيداع وثائق الانضمام إلى الاتفاقية وفقا لأحكامها. مادة (٣) ينشر هذا المرسوم في الجريدة الرسمية ويعمل به اعتبارا من تاريخ صدوره.
================================================================================
Index: 4934
) من عقد توظيف الموظفين المحليين من اللائحة التنظيمية للملحقيات الثقافية المشار إليها، نصه الآتي: ٤ – إجازة طارئة بحد أقصى (٥) خمسة أيام في السنة. المادة الثالثة يلغى كل ما يخالف هذا القرار، أو يتعارض مع أحكامه. المادة الرابعة ينشر هذا القرار في الجريدة الرسمية، ويعمل به من اليوم التالي لتاريخ نشره.
================================================================================
Index: 5489
ة النفطية بين حكومة سلطنة عمان، وشركة أوكسيدنتال عمان بلوك ٧٢ ش.م.م للمنطقة رقم (٧٢) الموقعة بتاريخ ٢٨ من فبراير ٢٠١٩م، وبناء على ما تقتضيه المصلحة العامة. رسمنا بما هو آت المادة الأولى إجازة الاتفاقية النفطية المشار إليها. المادة الثانية ينشر هذا المرسوم في الجريدة الرسمية، ويعمل به من تاريخ صدوره.
================================================================================
Index: 6080
إصدار الترخيص (٥٠) للمنشآت ٢ تجديد الترخيص (٥٠) للمنشآت المادة الثانية يلغى البند (٢ / و) من المادة (٧) من اللائحة التنفيذية لقانون النقل البري المشار إليها، كما يلغى كل ما يخالف هذا القرار، أو يتعارض مع أحكامه. المادة الثالثة ينشر هذا القرار في الجريدة الرسمية، ويعمل به من اليوم التالي لتاريخ نشره.
================================================================================
Index: 3110
رب الضريبي بالنسبة للضرائب على الدخل وعلى رأس المال الموقعة في مسقط بتاريخ ١٢ جمادى الأولى ١٤٢٥هـ الموافق ٣٠ يونيو ٢٠٠٤م، وبناء على ما تقتضيه المصلحة العامة. رسمنا بما هو آت المادة الأولى التصديق على الاتفاقية المشار إليها. المادة الثانية ينشر هذا المرسوم في الجريدة الرسمية، ويعمل به من تاريخ صدوره.
================================================================================
Index: 4840
 الذين تجمع بينهم علاقة زوجية أو قرابة من الدرجة الأولى، شريطة وجود موافقة كتابية، وموقعة من قبل العميل المحول، أو وكيله القانوني لكل عملية تحويل. المادة الثالثة يلغى كل ما يخالف هذا القرار، أو يتعارض مع أحكامه. المادة الرابعة ينشر هذا القرار في الجريدة الرسمية، ويعمل به من اليوم التالي لتاريخ نشره.
================================================================================
Index: 6128
 كل من: مملكة كمبوديا، وجمهورية لاوس الديمقراطية الشعبية. المادة الخامسة يعين الدكتور الشيخ عبدالله بن سالم بن حمد الحارثي، سفيرنا لدى مملكة نيذرلاندز، ليكون سفيرا لنا فوق العادة، ومفوضا غير مقيم لدى دوقية لوكسمبورج الكبرى. المادة السادسة ينشر هذا المرسوم في الجريدة الرسمية، ويعمل به من تاريخ صدوره.
================================================================================
Index: 6402
قتضيه المصلحة العامة. تقرر المادة الأولى تجرى التعديلات المرفقة على أحكام لائحة التدريب في المجلس العماني للاختصاصات الطبية، المشار إليها. المادة الثانية يلغى كل ما يخالف التعديلات المرفقة، أو يتعارض مع أحكامها. المادة الثالثة ينشر هذا القرار في الجريدة الرسمية، ويعمل به من اليوم التالي لتاريخ نشره.
================================================================================
Index: 6859
نهم: – المهندس مسعود بن سعيد بن هاشم الهاشمي محافظا لجنوب الباطنة بالدرجة الخاصة. – محمود بن يحيى بن سليمان الذهلي محافظا لشمال الشرقية بالدرجة الخاصة. – الشيخ أحمد بن مسلم بن سهيل جداد الكثيري محافظا للوسطى بالدرجة الخاصة. المادة الثانية ينشر هذا المرسوم في الجريدة الرسمية، ويعمل به من تاريخ صدوره.
================================================================================
Index: 6754
ة ناثو العالمية ش.م.م. إعلان عن انتهاء أعمال التصفية لشركة درة النصيب للتجارة والمقاولات – توصية. إعلان عن انتهاء أعمال التصفية لشركة رياحين الخوض للتجارة ش.م.م. إعلان عن انتهاء أعمال التصفية لشركة عيون الباز للتجارة والمقاولات – تضامنية. إعلان عن انتهاء أعمال التصفية لشركة تاول لخدمات الشباب ش.م.م.
================================================================================
Index: 1725
رقم ٨ / ٩٢ على النحو التالي: (يشكل المجلس البلدي من رئيس البلدية وخمسة وعشرين عضوا منهم تسعة أعضاء يمثلون الأجهزة الحكومية يختارهم رؤساء وحداتهم ممن يشغلون درجة مدير عام، وستة عشر عضوا يمثلون الولايات التابعة لمحافظة مسقط). مادة (٢) ينشر هذا المرسوم في الجريدة الرسمية ويعمل به اعتبارا من تاريخ نشره.
================================================================================
Index: 2057
مي، والتنمية لشؤون التنمية، والداخلية، والزراعة والثروة السمكية، والمواصلات، والنفط والمعادن، والبلديات الإقليمية والبيئة لشؤون البيئة. ويتولى مدير عام شؤون المحميات الطبيعية بوزارة البلديات الإقليمية والبيئة أمانة اللجنة. مادة (٢) ينشر هذا المرسوم في الجريدة الرسمية، ويعمل به اعتبارا من تاريخ نشره.
================================================================================
Index: 5230
و آت المادة الأولى تجرى التعديلات المرفقة على المرسوم السلطاني رقم ٣٥ / ٢٠١٢ بإصدار نظام الهيئة العامة لترويج الاستثمار وتنمية الصادرات. المادة الثانية يلغى كل ما يخالف التعديلات المرفقة، أو يتعارض مع أحكامهما. المادة الثالثة ينشر هذا المرسوم في الجريدة الرسمية، ويعمل به من اليوم التالي لتاريخ نشره.
================================================================================
Index: 5122
ة العامة، تقرر المادة الأولى يحظر استيراد الطيور الحية ومنتجاتها ومشتقاتها ومخلفاتها من جمهورية العراق، وذلك لحين زوال سبب الحظر، وصدور قرار بهذا الشأن. المادة الثانية على الجهات المختصة تنفيذ هذا القرار، كل في مجال اختصاصه. المادة الثالثة ينشر هذا القرار في الجريدة الرسمية، ويعمل به من تاريخ صدوره.
================================================================================
Index: 5636
ان اوبلاست Kurganskaya Oblast ويستثنى من ذلك المنتجات المعاملة حراريا وفقا للقانون الصحي لحيوانات اليابسة الصادر من المنظمة العالمية لصحة الحيوان (OIE). المادة الثانية على الجهات المختصة تنفيذ هذا القرار، كل في مجال اختصاصه. المادة الثالثة ينشر هذا القرار في الجريدة الرسمية، ويعمل به من تاريخ صدوره.
================================================================================
Index: 3258
٩٦، وعلى قانون الإجراءات المدنية والتجارية الصادر بالمرسوم السلطاني رقم ٢٩ / ٢٠٠٢، وبناء على ما تقتضيه المصلحة العامة. رسمنا بما هو آت المادة الأولى تجرى التعديلات المرافقة على قانون الإجراءات المدنية والتجارية، المشار إليه. المادة الثانية ينشر هذا المرسوم في الجريدة الرسمية، ويعمل به من تاريخ نشره.
================================================================================
Index: 7028
 – تضامنية. إعلان عن انتهاء أعمال التصفية لمؤسسة الإعمار ش.م.م. إعلان عن انتهاء أعمال التصفية لشركة مشاريع أمواج مجيس الحديثة للتجارة – توصية. إعلان عن انتهاء أعمال التصفية لشركة الفارس الذهبي الشاملة للتجارة – تضامنية. إعلان عن انتهاء أعمال التصفية لشركة وديان الرحيبات للتجارة والمقاولات – تضامنية.
================================================================================
Index: 482
نون السلكين الدبلوماسي والقنصلي لعام ١٩٨٠، وبناء على ما تقتضيه المصلحة العامة. رسمنا بما هو آت مادة ١ يعين السفير مال الله علي حبيب، سفيرنا لدى المملكة المتحدة، سفيرا لنا فوق العادة ومفوضا للسلطنة غير مقيم لدى دوقية لوكسمبرج الكبرى. مادة ٢ ينشر هذا المرسوم في الجريدة الرسمية ويعمل بع من تاريخ صدوره.
================================================================================
Index: 5221
مرسوم السلطاني رقم ١٠١ / ٩٦، وعلى قانون السلطة القضائية الصادر بالمرسوم السلطاني رقم ٩٠ / ٩٩، وبناء على ما تقتضيه المصلحة العامة. رسمنا بما هو آت المادة الأولى يعين الواردة أسماؤهم في القائمة المرفقة قضاة في المحكمة العليا. المادة الثانية ينشر هذا المرسوم في الجريدة الرسمية، ويعمل به من تاريخ صدوره.
================================================================================
Index: 3029
ة من مصادر ثابتة بأحكام اللائحة المرافقة. مادة (٢) تلغى لائحة التحكم في ملوثات الهواء المنبعثة من مصادر ثابتة الصادرة بالقرار الوزاري رقم ٥ / ٨٦ المشار إليه، كما يلغى كل ما يخالف أحكام اللائحة المرافقة أو يتعارض مع أحكامها مادة (٣) ينشر هذا القرار في الجريدة الرسمية، ويعمل به اعتباراً من تاريخ نشره.
================================================================================
Index: 2313
 بالمرسوم السلطاني رقم ١٠١ / ٩٦، وعلى المرسوم السلطاني رقم ٣ / ٨٣ بقانون تنظيم الجنسية العمانية وتعديلاته، وبناء على ما تقتضيه المصلحة العامة. رسمنا بما هو آت مادة (١) يمنح سرندرا ديراج لال راجيا كرو الجنسية العمانية. مادة (٢) ينشر هذا المرسوم في الجريدة الرسمية، ويعمل به اعتبارا من ١٢ / ١٢ / ١٩٨٣م.
================================================================================
Index: 1311
/ ٨٦ بإصدار قانون السلكين الدبلوماسي والقنصلي، وبناء على ما تقتضيه المصلحة العامة. رسمنا بما هو آت مادة (١) يعين السفير راشد بن ناصر بن سليمان اللمكي سفيرا لنا فوق العادة ومفوضا لدى الجمهورية الجزائرية الديمقراطية الشعبية. مادة (٢) ينشر هذا المرسوم في الجريدة الرسمية ويعمل به اعتبارا من تاريخ صدوره.
================================================================================
Index: 1038
لحة العامة. رسمنا بما هو آت مادة ١ يعين سالم بن إسماعيل بن علي السويد وكيلا لوزارة التراث القومي والثقافة نقلا من وزارة الخارجية. مادة ٢ يعين مال الله بن علي بن حبيب مستشارا لوزارة التراث القومي والثقافة بنفس درجته ومخصصاته. مادة ٣ ينشر هذا المرسوم في الجريدة الرسمية ويعمل به اعتبارا من تاريخ صدوره.
================================================================================
Index: 5380
٩٨، وإلى المرسوم السلطاني رقم ١ / ٢٠١٨ بالتصديق على الميزانية العامة للدولة للسنة المالية ٢٠١٨م، وبعد العرض على جلالة السلطان – حفظه الله ورعاه -، وبناء على ما تقتضيه المصلحة العامة، تقرر مادة وحيدة ينشر في الجريدة الرسمية الحساب الختامي للدولة عن السنة المالية ٢٠١٨م، طبقا للجداول التفصيلية المرفقة.
================================================================================
Index: 7062
ت مدركة المتحدة ش.ش.و. إعلان عن انتهاء أعمال التصفية لشركة مخازن اللوجستية ش.م.م. إعلان عن انتهاء أعمال التصفية لشركة دار الشراع الوطنية ش.م.م. إعلان عن انتهاء أعمال التصفية لشركة جنائن بابل المعلقة – تضامنية. إعلان عن انتهاء أعمال التصفية لشركة عاصم بن حمود بن راشد السعيدي وشركاه للتجارة – تضامنية.
================================================================================
Index: 5338
وي: خلال شهر نوفمبر. المادة السادسة تفرض على كل من يخالف أحكام المادة الثانية من هذا القرار غرامة إدارية لا تقل عن (٥٠) خمسين ريالا عمانيا، ولا تزيد على (٢٠٠) مائتي ريال عماني، وتضاعف الغرامة عند تكرار المخالفة. المادة السابعة ينشر هذا القرار في الجريدة الرسمية، ويعمل به من اليوم التالي لتاريخ نشره.
================================================================================
Index: 5273
رقم ٤٠ / ٢٠١٥، وإلى موافقة مجلس الخدمة المدنية في اجتماعه رقم ١ / ٢٠١٩، المنعقد بتاريخ ٢٤ / ٢ / ٢٠١٩م، وبناء على ما تقتضيه المصلحة العامة، تقرر المادة الأولى يعمل بمدونة قواعد السلوك الوظيفي للموظفين المدنيين في وحدات الجهاز الإداري للدولة، المرفقة. المادة الثانية ينشر هذا القرار في الجريدة الرسمية.
================================================================================
Index: 6660
حة العامة. تقرر المادة الأولى يعمل بأحكام اللائحة التنظيمية لضوابط تخطيط الأراضي المرفقة. المادة الثانية يلغى القرار الوزاري رقم ٥٣ / ٢٠١٣ المشار إليه، كما يلغى كل ما يخالف اللائحة المرفقة، أو يتعارض مع أحكامها. المادة الثالثة ينشر هذا القرار في الجريدة الرسمية، ويعمل به من اليوم التالي لتاريخ نشره.
================================================================================
Index: 6775
.م.م. إعلان عن انتهاء أعمال التصفية لشركة المركز المالي للأوراق المالية ش.م.م. إعلان عن انتهاء أعمال التصفية لشركة حمود بن سلطان بن سعيد العامري وولده – توصية. إعلان عن انتهاء أعمال التصفية لشركة مشاريع بركات الظاهرة – توصية. إعلان عن انتهاء أعمال التصفية لشركة عنوان الجنوب للتجارة والمقاولات ش.م.م.
================================================================================
Index: 4003
لأولى إجازة تنازل شركة ريكس أويل آند جاز أل. تى. دى وشركة بتروسى هولدنج لمنطقة الامتياز رقم (٥٠) البحرية عن جميع حقوقها والتزاماتها في الاتفاقية النفطية الموقعة بتاريخ ٢٨ فبراير ٢٠١١م المشار إليها إلى شركة مصيرة أويل ليمتد. المادة الثانية ينشر هذا المرسوم في الجريدة الرسمية، ويعمل به من تاريخ صدوره.
================================================================================
Index: 5755
 الاطلاع على النظام الأساسي للدولة الصادر بالمرسوم السلطاني رقم ١٠١ / ٩٦، وبناء على ما تقتضيه المصلحة العامة. رسمنا بما هو آت المادة الأولى يعين سمو السيد فاتك بن فهر بن تيمور آل سعيد مبعوثا خاصا لجلالة السلطان بمرتبة وزير. المادة الثانية ينشر هذا المرسوم في الجريدة الرسمية، ويعمل به من تاريخ صدوره.
================================================================================
Index: 256
وان العام بوزارة الخارجية. المادة ٢ على وزير الدولة للشؤون الخارجية تنفيذ هذا المرسوم ويعمل به اعتبارا من ١ / ١٢ / ١٩٧٧ وينشر في الجريدة الرسمية. صدر في: الأول من شهر صفر ١٣٩٨هـ الموافق: ١٠ يناير ١٩٧٨م قابوس بن سعيد سلطان عمان نشر هذا المرسوم في عدد الجريدة الرسمية رقم (١٤٠) الصادر في ١٥ / ١ / ١٩٧٨م
================================================================================
Index: 6863
لحاملي جوازات السفر الدبلوماسية والخاصة والخدمة، الموقعة في مدينة نيويورك بتاريخ ٢١ من سبتمبر ٢٠٢٣م، وبناء على ما تقتضيه المصلحة العامة. رسمنا بما هو آت المادة الأولى التصديق على الاتفاقية المشار إليها، وفقا للصيغة المرفقة. المادة الثانية ينشر هذا المرسوم في الجريدة الرسمية، ويعمل به من تاريخ صدوره.
================================================================================
Index: 5730
٢٠١٨، وبناء على ما تقتضيه المصلحة العامة. تقرر المادة الأولى تجرى التعديلات المرفقة على اللائحة التنفيذية لقانون النقل البري المشار إليها. المادة الثانية يلغى كل ما يخالف التعديلات المرفقة، أو يتعارض مع أحكامها. المادة الثالثة ينشر هذا القرار في الجريدة الرسمية، ويعمل به من اليوم التالي لتاريخ نشره.
================================================================================
Index: 5495
عمل باللائحة والقرارات المعمول بها، فيما لا يتعارض مع أحكام القانون المرفق. المادة الثالثة يلغى القانون الإحصائي الصادر بالمرسوم السلطاني رقم ٢٩ / ٢٠٠١، كما يلغى كل ما يخالف القانون المرفق، أو يتعارض مع أحكامه. المادة الرابعة ينشر هذا المرسوم في الجريدة الرسمية، ويعمل به من اليوم التالي لتاريخ نشره.
================================================================================
Index: 6928
يعها” ويتم تسجيل ملكية الأوراق المالية للمشتري في يوم التسوية. ولا يجوز أن تكون تلك التسوية معلقة على شرط أو أجل، وتكون نهائية وغير قابلة للإلغاء. المادة الثانية يلغى كل ما يخالف هذا القرار، أو يتعارض مع أحكامه. المادة الثالثة ينشر هذا القرار في الجريدة الرسمية، ويعمل به من اليوم التالي لتاريخ نشره.
================================================================================
Index: 66
ا لما تقتضيه المصلحة العامة، وبناء على ما عرضه علينا مساعد رئيس مجلس التنمية. رسمنا بما هو آت المادة ١ يعمل بالقانون رقم ١ / ٧٥ الخاص بالتنمية الاقتصادية لسنة ١٩٧٥ المرفق نصه اعتبارا من اليوم الأول من شهر فبراير ١٩٧٥. المادة ٢ على جميع الوزراء كل فيما يخصه تنفيذ هذا القانون وينشر في الجريدة الرسمية.
================================================================================
Index: 3783
ئب على الدخل بين حكومة سلطنة عمان وحكومة مملكة هولندا الموقعة في مدينة مسقط بتاريخ ١٥ شوال ١٤٣٠هـ الموافق ٥ أكتوبر ٢٠٠٩م، وبناء على ما تقتضيه المصلحة العامة. رسمنا بما هو آت المادة الأولى التصديق على الاتفاقية المشار إليها. المادة الثانية ينشر هذا المرسوم في الجريدة الرسمية، ويعمل به من تاريخ صدوره.
================================================================================
Index: 1023
لندية بالاستمرار في مزاولة أعمال التأمين في السلطنة. تقرر مادة ١ يجدد قيد شركة التأمين الهولندية في سجل شركات التأمين المعد بالوزارة لمدة ثلاث سنوات اعتبارا من ١٥ يوليو ١٩٨٦ لمزاولة أعمال التأمين العام السابق الترخيص لها بها وذلك من خلال توكيلها في السلطنة. مادة ٢ ينشر هذا القرار في الجريدة الرسمية.
================================================================================
Index: 4614
ت النافذة، فيما لا يتعارض مع أحكام هذا المرسوم والقانون المرفق. المادة الثالثة يلغى قانون بلدية مسقط الصادر بالمرسوم السلطاني رقم ٨ / ٩٢، كما يلغى كل ما يخالف هذا المرسوم والقانون المرفق، أو يتعارض مع أحكامهما. المادة الرابعة ينشر هذا المرسوم في الجريدة الرسمية، ويعمل به من اليوم التالي لتاريخ نشره.
================================================================================
Index: 2924
الخدمات الجوية الموقعة بتاريخ ٢٩ شعبان ١٤٢٣هـ الموافق ٤ نوفمبر ٢٠٠٢م، وبناء على ما تقتضيه المصلحة العامة. رسمنا بما هو آت مادة (١) التصديق على الاتفاقية بين حكومة السلطنة وحكومة دولة الكويت بشأن تنظيم الخدمات الجوية المشار إليها. مادة (٢) ينشر هذا المرسوم في الجريدة الرسمية، ويعمل به من تاريخ صدوره.
================================================================================
Index: 3847
 رقم ١٠١ / ٩٦، وعلى قانون الخدمة المدنية الصادر بالمرسوم السلطاني رقم ١٢٠ / ٢٠٠٤، وبناء على ما تقتضيه المصلحة العامة. رسمنا بما هو آت المادة الأولى يعين الدكتور محمد بن سيف بن سلطان الحوسني وكيلا لوزارة الصحة للشؤون الصحية. المادة الثانية ينشر هذا المرسوم في الجريدة الرسمية، ويعمل به من تاريخ صدوره.
================================================================================
Index: 1714
وقعة في مسقط بتاريخ ١١ يناير ١٩٩٢م، وبناء على ما تقتضيه المصلحة العامة. رسمنا بما هو آت مادة (١) التصديق على الاتفاقية بين حكومة سلطنة عمان وحكومة جمهورية بلغاريا بشأن الخدمات الجوية بين إقليميهما وما وراءهما المشار إليها. مادة (٢) ينشر هذا المرسوم في الجريدة الرسمية ويعمل به اعتبارا من تاريخ صدوره.
================================================================================
Index: 4876
مصلحة العامة، تقرر المادة الأولى تجرى التعديلات المرفقة على لوائح الاشتراطات الصحية الخاصة بالأنشطة ذات الصلة بالصحة العامة، المشار إليها. المادة الثانية يلغى كل ما يخالف التعديلات المرفقة، أو يتعارض مع أحكامها. المادة الثالثة ينشر هذا القرار في الجريدة الرسمية، ويعمل به من اليوم التالي لتاريخ نشره.
================================================================================
Index: 1384
ام المياه بما لا يتعارض مع النظام الأساسي للهيئة. وعلى الجهات المذكورة إمداد الهيئة بجميع ما تتوصل إليه من معلومات في هذا المجال. مادة (٥) يلغى كل ما يخالف هذا المرسوم أو يتعارض مع أحكامه أو مع أحكام النظام الأساسي المرافق. مادة (٦) ينشر هذا المرسوم في الجريدة الرسمية ويعمل به اعتبارا من تاريخ نشره.
================================================================================
Index: 4731

In [21]:
df_clean.iloc[10]

json_link                 https://qanoon.om/wp-json/wp/v2/posts/19879
short_link                                 https://qanoon.om/?p=19879
canonical_link                https://qanoon.om/p/1972/legacy1973005/
date                                              1972-12-28 00:00:00
title                                         قانون الشرطة رقم ٥ / ٧٣
text                نحن قابوس بن سعيد، سلطان عمان، أصدرنا القانون ...
html                <p><a class="pdf-link" href="http://data.qanoo...
error                                                             NaN
text_word_count                                                  6012
title_word_count                                                    6
title_semantic                                 قانون | اصدار | الشرطة
footer              صدر في :٢٢ ذي القعدة ١٣٩٢هـ الموافق ٢٨ ديسمبر ...
Name: 10, dtype: object

In [22]:
n_samples = 10
random_samples = df_clean.sample(n=n_samples)

for i, row in random_samples.iterrows():
    #print('=' * 80)
    print('-' * 10)
    #print(f'link: ',row['canonical_link'])
    print(f'Index: {i}')
    print(row['text'][:800])

----------
Index: 1179
نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على المرسوم السلطاني رقم ٢٦ / ٧٥ بإصدار قانون تنظيم الجهاز الإداري للدولة وتعديلاته، وعلى القانون رقم ٤ / ٧٤ في شأن الشركات التجارية، وعلى المرسوم السلطاني رقم ٤ / ٧٤ بإصدار قانون الحرف الأجنبية واستثمار الرأسمال الأجنبي، وعلى المرسوم السلطاني رقم ٨٣ / ٨٠ في شأن الدعم المالي للقطاع الخاص في مجالات الزراعة والأسماك والصناعة والمعادن والمحاجر، وعلى المرسوم السلطاني رقم ٧٠ / ٨١ باعتماد اللائحة التنفيذية للمرسوم السلطاني رقم ٨٣ / ٨٠ في مجال الصناعة، وبناء على ما تقتضيه المصلحة العامة. رسمنا بما هو آت مادة (١) يعمل في شأن الدعم المالي للقطاع الخاص في مجالي الصناعة والسياحة بأحكام النظام المرافق. مادة (٢) يصدر وزير التجارة والصناعة اللوائح والقرارات التنفيذية اللازمة لتطبيق أحكام هذا النظام. مادة (٣) يلغى المرسوم السلطاني رقم ٧٠ / ٨١ المشار إليه، كما يلغى
----------
Index: 263
نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على المرسوم رقم ٢٦ / ٧٥ بإصدار قانون تنظيم الجهاز الإداري للدولة وتعديلاته، وعلى المرسوم رقم ٤٢ / ٧٤ بإصدار قانون البترول والمعادن، وعلى اتفاقية البترول المبرمة بين حكومة السلطنة (ومجموعة ألف – سوميتومو) بتاريخ ١٤ / ٥ / ١٩٧٥ وخاصة المادة ٢١ منها، وعلى التنازل الصادر من مجموعة ألف – سوميتومو إلى شركة ونترشال جازلشافت عن حصة شائعة قدرها ٢٠٪ من نصيبها وحقوقها والتزاماتها في الاتفاقية المشار إليها وقبول شركة ونترشال جازلشافت لهذا التنازل بتاريخ ٣٠ / ١٢ / ١٩٧٧، وبناء على ما تقتضيه المصلحة العامة. رسمنا بما هو آت المادة ١ إجازة التنازل الصادر من مجموعة ألف – سوميتومو عن حصة شائعة قدرها ٢٠٪ من نصيبها وحقوقها والتزاماتها في الاتفاقية المبرمة بينها وبين حكومة السلطنة بتاريخ ١٤ / ٥ / ١٩٧٥ المشار إليها إلى شركة ونترشال جازلشافت WINTERSHALL AKTIEN – GESELLSCHAF
----------
Index: 3541
نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على النظام الأساسي للدولة الصادر بالمرسوم السلطاني رقم ١٠١ / ٩٦، وعلى المرسوم السلطاني رقم ٢٧ / ٨٥ بإنشاء اللجنة العليا لتخطيط المدن، وعلى المرسوم السلطاني رقم ٢٤ / ٢٠٠٦ بإنشاء أمانة عامة للجنة العليا لتخطيط المدن وتعيين أمين عام لها، وعلى المرسوم السلطاني رقم ١٠٢ / ٢٠٠٦ بإعادة تشكيل اللجنة العليا لتخطيط المدن وتعديل بعض أحكام المرسوم السلطاني رقم ٢٧ / ٨٥، وبناء على ما تقتضيه المصلحة العامة. رسمنا بما هو آت المادة الأولى يستبدل بنص المادة الأولى من المرسوم السلطاني رقم ١٠٢ / ٢٠٠٦ المشار إليه، النص الآتي: يعاد تشكيل اللجنة العليا لتخطيط المدن على النحو الآتي: – وزير الاقتصاد الوطني رئيسا – وزير الإسكان نائبا للرئيس – وزير الداخلية عضوا – المفتش العام للشرطة والجمارك عضوا – وزير البيئة والشؤون المناخية عضوا – وزير النقل والاتصالات عضوا – وزير البلديات
----------
Index: 4079
نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على النظام الأساسي للدولة الصادر بالمرسوم السلطاني رقم ١٠١ / ٩٦، وعلى المرسوم السلطاني رقم ٥٦ / ٢٠٠٠ باعتماد الهيكل التنظيمي لجهاز الرقابة المالية والإدارية للدولة، وعلى المرسوم السلطاني رقم ٢٧ / ٢٠١١ في شأن تعديل مسمى جهاز الرقابة المالية للدولة وتوسيع اختصاصاته، وعلى قانون الرقابة المالية والإدارية للدولة الصادر بالمرسوم السلطاني رقم ١١١ / ٢٠١١، وبناء على ما تقتضيه المصلحة العامة. رسمنا بما هو آت المادة الأولى يعتمد الهيكل التنظيمي لجهاز الرقابة المالية والإدارية للدولة وفقا للملحق المرفق. المادة الثانية يلغى المرسوم السلطاني رقم ٥٦ / ٢٠٠٠ المشار إليه، كما يلغى كل ما يخالف هذا المرسوم أو يتعارض مع أحكامه. المادة الثالثة ينشر هذا المرسوم في الجريدة الرسمية، ويعمل به من تاريخ صدوره.
----------
Index: 2291
نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على النظام الأساسي الصادر بالمرسوم السلطاني رقم ١٠١ / ٩٦، وعلى قانون النفط والمعادن الصادر بالمرسوم السلطاني رقم ٤٢ / ٧٤، وعلى المرسوم السلطاني رقم ٦٥ / ٩٦ بإجازة الاتفاقية النفطية بين حكومة السلطنة وشركة فيلبس بتروليوم عمان المحدودة، وعلى العقد المؤرخ ١٧ / ٥ / ١٩٩٧م والذي تنازلت بموجبه شركة فيليبس بتروليوم عمان المحدودة عن خمسة وعشرين بالمائة (٢٥٪) من حقوقها والتزاماتها في الاتفاقية النفطية الموقعة بتاريخ ١٥ يوليو ١٩٩٦م لشركة ميرسك أويل عمان أيه – أس القابلة لذلك التنازل، وعلى خطاب وزير النفط والمعادن بتاريخ ١٣ أبريل ١٩٩٧م، بالموافقة على التنازل، وبناء على ما تقتضيه المصلحة العامة. رسمنا بما هو آت مادة (١) إجازة تنازل شركة فيليبس بتروليوم عمان المحدودة عن خمسة وعشرين بالمائة (٢٥٪) من حقوقها والتزاماتها في الاتفاقية النفطية الموقعة بتاريخ ١٥ يوليو ١
----------
Index: 1094
نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على المرسوم السلطاني رقم ٢٦ / ٧٥ بإصدار قانون تنظيم الجهاز الإداري للدولة وتعديلاته، وعلى المرسوم السلطاني رقم ٨٧ / ٨١ بإنشاء سكرتارية مجلس الوزراء، وعلى المرسوم السلطاني رقم ٥٨ / ٨٦ بإلغاء وزارة شؤون الديوان السلطاني، وبناء على ما تقتضيه المصلحة العامة. رسمنا بما هو آت مادة (١) يتولى السيد نائب رئيس الوزراء للشؤون القانونية الإشراف على سكرتارية مجلس الوزراء وتعدل اللائحة الداخلية للمجلس وفقا لذلك. مادة (٢) يصدر بتنظيم السكرتارية وتحديد وضعها الإداري مرسوم سلطاني خاص. مادة (٣) ينشر هذا المرسوم في الجريدة الرسمية ويعمل به اعتبارا من تاريخ صدوره.
----------
Index: 3604
نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على النظام الأساسي للدولة الصادر بالمرسوم السلطاني رقم ١٠١ / ٩٦، وعلى قانون الجزاء العماني الصادر بالمرسوم السلطاني رقم ٧ / ٧٤، وعلى قانون تنظيم الجهاز الإداري للدولة الصادر بالمرسوم السلطاني رقم ٢٦ / ٧٥، وعلى قانون الشرطة الصادر بالمرسوم السلطاني رقم ٣٥ / ٩٠، وعلى قانون السلطة القضائية الصادر بالمرسوم السلطاني رقم ٩٠ / ٩٩، وعلى قانون الادعاء العام الصادر بالمرسوم السلطاني رقم ٩٢ / ٩٩، وعلى قانون الإجراءات الجزائية الصادر بالمرسوم السلطاني رقم ٩٧ / ٩٩، وعلى اختصاصات مكتب وزير الدولة ومحافظ ظفار المحددة وفقا للملحق رقم (١) المرافق للمرسوم السلطاني رقم ٣٧ / ٢٠٠٣، وبناء على ما تقتضيه المصلحة العامة. رسمنا بما هو آت المادة الأولى يكون لوزير الدولة ومحافظ ظفار سلطة التوقيف والتحفظ على الأشخاص المخالفين في حالات النزاعات القبلية في المحافظة أو التعدي على
----------
Index: 5539
استنادا إلى قانون شركات التأمين الصادر بالمرسوم السلطاني رقم ١٢ / ٧٩، وإلى قانون تأمين المركبات الصادر بالمرسوم السلطاني رقم ٣٤ / ٩٤، وإلى المرسوم السلطاني رقم ٩٠ / ٢٠٠٤ بنقل اختصاصات التأمين من وزارة التجارة والصناعة إلى الهيئة العامة لسوق المال، وإلى اللائحة التنفيذية لقانون شركات التأمين الصادرة بالقرار الوزاري رقم ٥ / ٨٠، وإلى قرار تنظيم متطلبات ترخيص مزاولة أعمال التأمين الصادر بالقرار رقم خ / ٣١ / ٢٠٠٧، وإلى القرار الإداري رقم خ / ٢٢ / ٢٠٠٧ بالترخيص لشركة إيه أي جي ميمسا للتأمين المحدودة (فرع عمان) بمزاولة أعمال التأمين العام، وإلى موافقة الهيئة العامة لسوق المال بتاريخ ١٩ مارس ٢٠١٣م على تعديل المسمى التجاري لشركة إيه أي جي ميمسا للتأمين المحدودة (فرع عمان) إلى شركة إيه أي جي ميا المحدودة (فرع عمان)، وبناء على ما تقتضيه المصلحة العامة، تقرر المادة الأولى يلغى ترخيص شركة إيه أي جي ميا
----------
Index: 3124
نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على النظام الأساسي للدولة الصادر بالمرسوم السلطاني رقم ١٠١ / ٩٦، وعلى قانون المطبوعات والنشر الصادر بالمرسوم السلطاني رقم ٤٩ / ٨٤، وعلى قانون الرقابة على المصنفات الفنية الصادر بالمرسوم السلطاني رقم ٦٥ / ٩٧ وتعديلاته، وعلى قانون تنظيم الاتصالات الصادر بالمرسوم السلطاني رقم ٣٠ / ٢٠٠٢، وبناء على ما تقتضيه المصلحة العامة. رسمنا بما هو آت المادة الأولى يعمل بأحكام قانون المنشآت الخاصة للإذاعة والتلفزيون المرافق. المادة الثانية دون الإخلال بأحكام قانون المطبوعات والنشر وقانون تنظيم الاتصالات المشار إليهما يلغى كل ما يخالف أحكام هذا القانون أو يتعارض مع أحكامه. المادة الثالثة يصدر وزير الإعلام اللائحة التنفيذية لهذا القانون. المادة الرابعة ينشر هذا المرسوم في الجريدة الرسمية، ويعمل به من تاريخ نشره.
----------
Index: 7164
استنادا إلى قانون السلطة القضائية الصادر بالمرسوم السلطاني رقم ٩٠ / ٩٩، وإلى المرسوم السلطاني رقم ٣٥ / ٢٠٢٢ بشأن تنظيم إدارة شؤون القضاء، وإلى القرار الوزاري رقم ١١٩ / ٢٠٠١ بتحديد مقار ونطاق اختصاص المحاكم الابتدائية، وبناء على ما تقتضيه المصلحة العامة. تقرر المادة الأولى ينقل مقر المحكمة الابتدائية في نخل من مقرها الحالي إلى مقرها الجديد الواقع في منطقة (باب الظفور غرب)، مقابل مكتب الوالي، على الطريق العام المؤدي إلى ولاية الرستاق. المادة الثانية يعمل بهذا القرار اعتبارا من تاريخ ٢٩ / ٩ / ٢٠٢٤م. المادة الثالثة ينشر هذا القرار في الجريدة الرسمية.

In [23]:
import re

def extract_articles(text):
    if not isinstance(text, str) or not text.strip():
        return None

    # ---------------------------------------------------------
    # 1. برش مقدمه (Preamble Slicing) - اصلاح شده
    # ---------------------------------------------------------
    # تغییر: جستجو را فقط به 1000 کاراکتر اول محدود می‌کنیم تا
    # اگر کلمه 'تقرر' در وسط متن (مثلاً داخل ماده 20) آمد، کل متن برید نشود.

    start_markers = [r'رسمنا\s+بما\s+هو\s+آت', r'\bتقرر\b', r'\bقرر\b']
    processing_text = text

    # فقط در بخش ابتدایی متن دنبال این کلمات می‌گردیم
    preamble_limit = 1000
    search_scope = text[:preamble_limit]

    best_start_index = 0
    for marker in start_markers:
        match = re.search(marker, search_scope)
        if match:
            # اگر پیدا شد، متن را از آنجا به بعد در نظر می‌گیریم
            best_start_index = match.end()
            break

    if best_start_index > 0:
        processing_text = text[best_start_index:]

    # ---------------------------------------------------------
    # 2. پترن‌های اعداد و حروف
    # ---------------------------------------------------------
    number_words = [
        r'الأولى', r'الثانية', r'الثالثة', r'الرابعة', r'الخامسة', r'السادسة',
        r'السابعة', r'الثامنة', r'التاسعة', r'العاشرة', r'الحادية', r'الثانية',
        r'أولى', r'ثانية', r'ثالثة', r'رابعة', r'خامسة', r'سادسة',
        r'سابعة', r'ثامنة', r'تاسعة', r'عاشرة', r'حادية', r'ثاني',
        r'واحد', r'اثنان', r'ثلاثة', r'أربعة', r'خمسة', r'ستة',
        r'سبعة', r'ثمانية', r'تسعة', r'عشر', r'عشرة',
        r'العشرون', r'الثلاثون', r'الأربعون', r'الخمسون'
    ]
    word_pattern = '|'.join(number_words)

    # اصلاح پترن عدد: پشتیبانی از پرانتزهای مختلف و فاصله‌های احتمالی
    # همچنین هندل کردن "مکرر" (مثلاً ماده 5 مکرر)
    digit_part = r'(?:\(\s*[\d\u06F0-\u06F9\u0660-\u0669]+\s*\)|[\d\u06F0-\u06F9\u0660-\u0669]+)'
    text_part = f'(?:(?:{word_pattern})(?:\s+(?:عشر|عشرة))?)'

    # پترن نهایی:
    # گروه 1: کل هدر (مثلاً: المادة 5 مکرر)
    # گروه 2: کلمه کلیدی (المادة یا مادة)
    # اضافه شدن (?:\s+مكرر)? برای مواد مکرر
    full_pattern = re.compile(
        r'((?:^|\s|[.،؛:])(المادة|مادة)\s+(?:' + digit_part + r'|' + text_part + r')(?:\s+مكرر)?)',
        re.MULTILINE
    )

    matches = list(full_pattern.finditer(processing_text))
    if not matches:
        return None

    # ---------------------------------------------------------
    # 3. فیلتر کردن هوشمند رفرنس‌ها (Reference Logic Improved)
    # ---------------------------------------------------------
    valid_matches = []

    # لیست کلماتی که اگر قبل از "ماده" بیایند، یعنی ارجاع است (نه شروع ماده)
    # اضافه شدن "من" برای حل مشکل نمونه 3590
    ref_keywords = [
        'في', 'من', 'حكم', 'نص', 'أحكام', 'بموجب', 'مقتضى',
        'خلال', 'تطبيق', 'وفق', 'أحكام', 'مراعاة'
    ]
    ref_pattern = re.compile(r'\b(' + '|'.join(ref_keywords) + r')\s*$', re.UNICODE)

    for m in matches:
        start_idx = m.start()
        # گروه 2 شامل کلمه "مادة" یا "المادة" است
        keyword = m.group(2)

        # بررسی متن قبل (Prefix)
        prefix = processing_text[max(0, start_idx-20):start_idx]
        # تمیز کردن فاصله ها برای بررسی راحت تر
        prefix_clean = re.sub(r'\s+', ' ', prefix).strip()

        # 1. اگر قبلش کلمات ارجاعی مثل "في"، "من"، "حكم" بود -> حذف
        if ref_pattern.search(prefix_clean):
            continue

        # 2. بررسی حروف چسبان (ب، ل، ك) - اصلاح شده
        # نکته مهم: این حروف معمولا فقط به "المادة" (با الف و لام) می‌چسبند.
        # اگر کلمه "مادة" (بدون ال) باشد، معمولاً هدر اصلی است.
        if keyword == 'المادة':
            # چک می‌کنیم کاراکتر چسبیده به شروع مچ چیست
            # m.start(2) ایندکس شروع کلمه "المادة" است
            word_start = m.start(2)
            if word_start > 0:
                char_before = processing_text[word_start - 1]
                # اگر قبلش ب، ل، یا ک بود
                if char_before in 'بلك':
                    # برای اطمینان چک میکنیم که قبل از این حرف چسبان، فاصله یا شروع خط باشد
                    # مثال: "وبالمادة" (حذف شود) اما "جبال المادة" (حذف نشود - گرچه بعید است)
                    if word_start == 1 or (word_start > 1 and processing_text[word_start-2] in ' \t\n\r.،'):
                        continue

        valid_matches.append(m)

    if not valid_matches:
        return None

    # ---------------------------------------------------------
    # 4. استخراج متن
    # ---------------------------------------------------------
    extracted_articles = []
    for i, m in enumerate(valid_matches):
        # تمیز کردن هدر (حذف کاراکترهای اضافی اول اگر regex گرفته باشد)
        header_raw = m.group(1).strip()
        # حذف کاراکترهای غیر حرفی از ابتدای هدر (مثل نقطه یا ویرگول که در گروه 1 ممکن است باشد)
        header = re.sub(r'^[^\w\u0600-\u06FF]+', '', header_raw)

        start = m.end()

        if i + 1 < len(valid_matches):
            end = valid_matches[i+1].start()
            # یک نکته ظریف: پترن regex ما ممکن است با \s یا کاراکتر قبل شروع شود
            # بنابراین start مچ بعدی ممکن است کمی عقب تر از خود کلمه "ماده" باشد.
            # برای تمیزی بیشتر بهتر است تا شروع گروه "ماده" ی بعدی ببریم ولی همین هم کفایت میکند.
        else:
            end = len(processing_text)

        content = processing_text[start:end].strip()

        # حذف علائم نگارشی ابتدای متن (: - .)
        content = re.sub(r'^[:\-–.]\s*', '', content)

        # حذف پاورقی‌های احتمالی که به عدد ماده چسبیده‌اند مثل [1]
        # اگر می‌خواهید پاورقی در متن بماند، این خط را حذف کنید.
        # اما معمولا [1] بعد از "ماده (4)" جزو متن ماده است نه هدر.

        extracted_articles.append(f"{header} : {content}")

    return '\n----------------\n'.join(extracted_articles)
df_clean['articles'] = df_clean['text'].apply(extract_articles)

In [24]:
n_samples = 20
random_samples = df_clean.sample(n=n_samples)

for i, row in random_samples.iterrows():
    # print(f'Index: {i}')
    # print(row['text'])
    # print('-----' * 80)
    # print("[link]:")
    # print(row['canonical_link'])
    # print("[title]:")
    # print(row['title'])
    # print("[title_embd]:")
    # print(row['title_semantic'])
    print("[full text]:")
    print(row['text'][:800])
    print("[articles]:")
    print(row['articles'])
    # print("[footer]:")
    # print(row['footer'])

[full text]:
نحن هيثم بن طارق سلطان عمان بعد الاطلاع على النظام الأساسي للدولة، وعلى المرسوم السلطاني رقم ٦٧ / ٢٠٠٣ بتطبيق قانون الجمارك الموحد لدول مجلس التعاون لدول الخليج العربية، وبعد العرض على مجلس عمان، وبناء على ما تقتضيه المصلحة العامة. رسمنا بما هو آت المادة الأولى يعمل بقانون ضريبة القيمة المضافة، المرفق. المادة الثانية يصدر رئيس جهاز الضرائب اللائحة التنفيذية للقانون المرفق خلال مدة لا تزيد على (٦) ستة أشهر من تاريخ العمل به، كما يصدر القرارات اللازمة لتنفيذ أحكامه. المادة الثالثة يلغى كل ما يخالف القانون المرفق، أو يتعارض مع أحكامه. المادة الرابعة ينشر هذا المرسوم في الجريدة الرسمية، ويعمل به بعد (١٨٠) مائة وثمانين يوما من تاريخ نشره.
[articles]:
المادة الأولى : يعمل بقانون ضريبة القيمة المضافة، المرفق.
----------------
المادة الثانية : يصدر رئيس جهاز الضرائب اللائحة التنفيذية للقانون المرفق خلال مدة لا تزيد على (٦) ستة أشهر من تاريخ العمل به، كما يصدر القرارات اللازمة لتنفيذ أحكامه.
----------------
المادة الثالثة : يلغى كل ما يخالف القانون المرفق، أو يتعارض مع أحكامه.
----------------
المادة الرابعة : ينشر هذا المرسوم في الجريدة الرسمية، ويعمل به بعد (١٨٠) مائة وثمانين يوما من تاريخ نشره.
[full text]:
استنادا إلى قانون تنظيم الاتصالات الصادر بالمرسوم السلطاني رقم ٣٠ / ٢٠٠٢، وإلى اللائحة التنفيذية لقانون تنظيم الاتصالات الصادرة بالقرار رقم ١٤٤ / ٢٠٠٨، وإلى لائحة تنظيم تسجيل واستخدام الترددات والأجهزة الراديوية وتحديد أسعارها الصادرة بالقرار رقم ١٣٣ / ٢٠٠٨، وإلى القرار رقم ١٥ / ٢٠١٢ بشأن ضوابط تشغيل المحطات الأرضية على متن السفن في النطاقين (٥٩٢٥-٦٤٢٥) ميجاهرتز و(١٤-١٤,٥) جيجاهرتز، وإلى موافقة مجلس إدارة هيئة تنظيم الاتصالات، وإلى موافقة وزارة المالية، وبناء على ما تقتضيه المصلحة العامة. تقرر المادة الأولى تجرى التعديلات المرفقة على لائحة تنظيم تسجيل واستخدام الترددات والأجهزة الراديوية وتحديد أسعارها المشار إليها. المادة الثانية يلغى القرار رقم ١٥ / ٢٠١٢ المشار إليه، كما يلغى كل ما يخالف هذا القرار، أو يتعارض مع أحكامه. المادة الثالثة ينشر هذا القرار في الجريدة الرسمية، ويعمل به من اليوم
[articles]:
المادة الأولى : تجرى التعديلات المرفقة على لائحة تنظيم تسجيل واستخدام الترددات والأجهزة الراديوية وتحديد أسعارها المشار إليها.
----------------
المادة الثانية : يلغى القرار رقم ١٥ / ٢٠١٢ المشار إليه، كما يلغى كل ما يخالف هذا القرار، أو يتعارض مع أحكامه.
----------------
المادة الثالثة : ينشر هذا القرار في الجريدة الرسمية، ويعمل به من اليوم التالي لتاريخ نشره.
[full text]:
نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على النظام الأساسي للدولة الصادر بالمرسوم السلطاني رقم ١٠١ / ٩٦، وعلى قانون تنظيم الجنسية العمانية الصادر بالمرسوم السلطاني رقم ٣ / ٨٣ وتعديلاته، وبناء على ما تقتضيه المصلحة العامة. رسمنا بما هو آت مادة (١) تمنح الجنسية العمانية إلى كل من الواردة أسماؤهم في القائمة المرافقة. مادة (٢) ينشر هذا المرسوم في الجريدة الرسمية، ويعمل به اعتبارا من ٥ / ٦ / ١٩٩٦.
[articles]:
مادة (١) : تمنح الجنسية العمانية إلى كل من الواردة أسماؤهم في القائمة المرافقة.
----------------
مادة (٢) : ينشر هذا المرسوم في الجريدة الرسمية، ويعمل به اعتبارا من ٥ / ٦ / ١٩٩٦.
[full text]:
مراسيم سلطانية مرسوم سلطاني رقم ٦٢ / ٢٠٢٤ بالتصديق على اتفاقية بين سلطنة عمان وجمهورية إستونيا لتجنب الازدواج الضريبي ومنع التهرب الضريبي بالنسبة للضرائب على الدخل. أوامر سامية بمنح أوسمة ديوان البلاط السلطاني المراسم السلطانية أمر بمنح وسام. قرارات وزارية وزارة الإسكان والتخطيط العمراني قرار وزاري رقم ١٠١٦ / ٢٠٢٤ بإصدار اللائحة التنفيذية لقانون نزع الملكية للمنفعة العامة. وزارة التنمية الاجتماعية قرار وزاري رقم ٣٩٢ / ٢٠٢٤ بإصدار اللائحة التنظيمية لدور الرعاية المؤقتة. وزارة العمل قرار وزاري رقم ٧٢٩ / ٢٠٢٤ بشأن نظام حماية الأجور. قرار وزاري رقم ٧٣٠ / ٢٠٢٤ بشأن تنظيم الانتقال المؤقت للقوى العاملة غير العمانية بين منشآت القطاع الخاص. بيانات عامة وزارة التجارة والصناعة وترويج الاستثمار بيان عن المصنفات الأدبية والعلمية والفنية المودعة لدى المكتب الوطني للملكية الفكرية. إعلانات رسمية الإعلانات
[articles]:
None
[full text]:
استنادا إلى قانون تنظيم وزارة الخارجية الصادر بالمرسوم السلطاني رقم ٣٢ / ٢٠٠٨، وإلى لائحة جمعيات الصداقة العمانية الصادرة بالقرار الوزاري رقم ٣٤١ / ٢٠٠٧، وبناء على ما تقتضيه المصلحة العامة. تقرر المادة الأولى تشهر جمعية الصداقة العمانية الألمانية ويقيد نظامها الأساسي وهيكلها التنظيمي في السجل المعد لهذا الغرض في الوزارة. المادة الثانية ينشر هذا القرار في الجريدة الرسمية، ويعمل به من اليوم التالي لتاريخ نشره.
[articles]:
المادة الأولى : تشهر جمعية الصداقة العمانية الألمانية ويقيد نظامها الأساسي وهيكلها التنظيمي في السجل المعد لهذا الغرض في الوزارة.
----------------
المادة الثانية : ينشر هذا القرار في الجريدة الرسمية، ويعمل به من اليوم التالي لتاريخ نشره.
[full text]:
نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على النظام الأساسي للدولة الصادر بالمرسوم السلطاني رقم ١٠١ / ٩٦، وعلى نظام الهيئات والمؤسسات العامة الصادر بالمرسوم السلطاني رقم ١١٦ / ٩١، وعلى المرسوم السلطاني رقم ٣٨ / ٢٠١١ بإلغاء وزارة الاقتصاد الوطني، وعلى المرسوم السلطاني رقم ٣٠ / ٢٠١٢ بإنشاء المجلس الأعلى للتخطيط وإصدار نظامه، وبناء على ما تقتضيه المصلحة العامة. رسمنا بما هو آت المادة الأولى ينشأ مركز يسمى “المركز الوطني للإحصاء والمعلومات”، يتبع المجلس الأعلى للتخطيط. المادة الثانية يتمتع المركز بالشخصية الاعتبارية والاستقلال المالي والإداري، ويكون مقره محافظة مسقط. المادة الثالثة يصدر بتشكيل مجلس إدارة المركز قرار من المجلس الأعلى للتخطيط. المادة الرابعة تؤول إلى المركز من وزارة الاقتصاد الوطني (الملغاة) جميع المخصصات والموجودات الخاصة بالمديرية العامة للإحصاءات الاجتماعية، والمديرية العامة
[articles]:
المادة الأولى : ينشأ مركز يسمى “المركز الوطني للإحصاء والمعلومات”، يتبع المجلس الأعلى للتخطيط.
----------------
المادة الثانية : يتمتع المركز بالشخصية الاعتبارية والاستقلال المالي والإداري، ويكون مقره محافظة مسقط.
----------------
المادة الثالثة : يصدر بتشكيل مجلس إدارة المركز قرار من المجلس الأعلى للتخطيط.
----------------
المادة الرابعة : تؤول إلى المركز من وزارة الاقتصاد الوطني (الملغاة) جميع المخصصات والموجودات الخاصة بالمديرية العامة للإحصاءات الاجتماعية، والمديرية العامة للإحصاءات الاقتصادية، ومركز المعلومات والنشر، كما ينقل إليه بذات درجاتهم المالية جميع موظفي الجهات المذكورة.
----------------
المادة الخامسة : ينقل موظفو التقسيمات الإدارية التي كانت تتبع مباشرة وزير الاقتصاد الوطني وموظفو كل من مكتب أمين عام وزارة الاقتصاد الوطني والمديرية العامة للشؤون الإدارية والمالية بذات درجاتهم المالية إلى الجهات التي يصدر بتحديدها قرار من المجلس الأعلى للتخطيط، وإلى حين صدور هذا القرار يحتفظ الموظفون المذكورون بذات درجاتهم بصفة شخصية.
----------------
المادة السادسة : يصدر ببيان نظام المركز مرسوم سلطاني.
----------------
المادة السابعة : يلغى كل ما يخالف هذا المرسوم أو يتعارض مع أحكامه.
----------------
المادة الثامنة : ينشر هذا المرسوم في الجريدة الرسمية، ويعمل به من تاريخ صدوره.
[full text]:
استنادا إلى قانون المجالس البلدية الصادر بالمرسوم السلطاني رقم ١١٦ / ٢٠١١، وإلى اللائحة التنفيذية لقانون المجالس البلدية الصادرة بالقرار الديواني رقم ١٥ / ٢٠١٢، وإلى القرار الديواني رقم ٣٩ / ٢٠١٦ بتسمية أعضاء المجلس البلدي للفترة الثانية بمحافظة مسقط، وإلى النتائج النهائية لعملية الفرز لانتخابات أعضاء المجالس البلدية للفترة الثانية، وإلى بيان النتائج النهائية لانتخابات أعضاء مجلس الشورى للفترة التاسعة ٢٠١٩ م الصادر في ٢٩ صفر ١٤٤١هـ الموافق ٢٨ أكتوبر ٢٠١٩م، وبناء على ما تقتضيه المصلحة العامة، تقرر المادة الأولى يحل الفاضل راشد بن فقير بن محمد البلوشي محل الفاضل مظفر بن محمد بن ناصر الوهيبي، ليكون ممثل ولاية العامرات في عضوية المجلس البلدي لمحافظة مسقط. المادة الثانية ينشر هذا القرار في الجريدة الرسمية، ويعمل به من اليوم التالي لتاريخ نشره.
[articles]:
المادة الأولى : يحل الفاضل راشد بن فقير بن محمد البلوشي محل الفاضل مظفر بن محمد بن ناصر الوهيبي، ليكون ممثل ولاية العامرات في عضوية المجلس البلدي لمحافظة مسقط.
----------------
المادة الثانية : ينشر هذا القرار في الجريدة الرسمية، ويعمل به من اليوم التالي لتاريخ نشره.
[full text]:
نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على المرسوم السلطاني رقم ٢٦ / ٧٥ بإصدار قانون تنظيم الجهاز الإداري للدولة وتعديلاته، وعلى المرسوم السلطاني رقم ٧٣ / ٨٢ بتفويض وزير المواصلات في توقيع اتفاقية النقل الجوي بين حكومة سلطنة عمان وحكومة الجمهورية التونسية، وعلى الاتفاقية المشار إليها الموقعة في مسقط بتاريخ ١٦ نوفمبر ١٩٨٥، وبناء على ما تقتضيه المصلحة العامة. رسمنا بما هو آت مادة (١) التصديق على اتفاقية النقل الجوي المشار إليها بين حكومة سلطنة عمان وحكومة الجمهورية التونسية. مادة (٢) ينشر هذا المرسوم في الجريدة الرسمية ويعمل به اعتبارا من تاريخ صدوره.
[articles]:
مادة (١) : التصديق على اتفاقية النقل الجوي المشار إليها بين حكومة سلطنة عمان وحكومة الجمهورية التونسية.
----------------
مادة (٢) : ينشر هذا المرسوم في الجريدة الرسمية ويعمل به اعتبارا من تاريخ صدوره.
[full text]:
بعد الاطلاع على المرسوم السلطاني رقم ٨ / ٨٠ بإصدار قانون الخدمة المدنية ولائحته التنفيذية. وعلى القرار الوزاري رقم (٥) لسنة ١٩٨٤م وتعديلاته. وبناء على موافقة ديوان شؤون الموظفين رقم ٨ / ١٣ / ١٠٣٤٩ تاريخ ٣ / ١٢ / ١٩٨٦م. ووفقا لما تقتضيه مصلحة العمل. تقرر ما يلي مادة (١) إضافة مسمى وظيفة نائب مدير الطب الوقائي طبقا للشروط الموضحة بالكشف المرفق إلى الجداول المرفقة بالقرار الوزاري المشار إليه أعلاه واعتبارها جزء لا يتجزأ منه. مادة (٢) يعتبر هذا القرار نافذا من تاريخ صدوره وينشر في الجريدة الرسمية.
[articles]:
مادة (١) : إضافة مسمى وظيفة نائب مدير الطب الوقائي طبقا للشروط الموضحة بالكشف المرفق إلى الجداول المرفقة بالقرار الوزاري المشار إليه أعلاه واعتبارها جزء لا يتجزأ منه.
----------------
مادة (٢) : يعتبر هذا القرار نافذا من تاريخ صدوره وينشر في الجريدة الرسمية.
[full text]:
استنادا إلى المرسوم السلطاني رقم ٦٢ / ٢٠٠٧ بتنظيم كليات العلوم التطبيقية، وإلى القرار الوزاري رقم ٧٦ / ٢٠٠٨ بتشكيل وتحديد اختصاصات مجلس أمناء كليات العلوم التطبيقية، وإلى قرار مجلس أمناء كليات العلوم التطبيقية بجلسته المنعقدة بتاريخ ١٢ / ٥ / ٢٠٠٨م، وبناء على ما تقتضيه المصلحة العامة. تقرر مادة (١) يعتمد تحويل كلية التربية بالرستاق إلى كلية للعلوم التطبيقية اعتبارا من العام الأكاديمي ٢٠٠٨ / ٢٠٠٩م. مادة (٢) يسرى النظام الأكاديمي لكليات العلوم التطبيقية على الطلاب الذين يتم قبولهم وقيدهم للدراسة بالكلية المذكورة اعتبارا من العام الأكاديمي ٢٠٠٨ / ٢٠٠٩م ويستمر سريان النظام الأساسي لكليات التربية على الطلاب الخاضعين له لحين تخرجهم طبقا لأحكامه. مادة (٣) يسري المرسوم السلطاني رقم ٦٢ / ٢٠٠٧ المشار إليه وكافة النظم واللوائح المطبقة على كليات العلوم التطبيقية على أعضاء هيئة التدريس وشاغلي الوظائف ال
[articles]:
مادة (١) : يعتمد تحويل كلية التربية بالرستاق إلى كلية للعلوم التطبيقية اعتبارا من العام الأكاديمي ٢٠٠٨ / ٢٠٠٩م.
----------------
مادة (٢) : يسرى النظام الأكاديمي لكليات العلوم التطبيقية على الطلاب الذين يتم قبولهم وقيدهم للدراسة بالكلية المذكورة اعتبارا من العام الأكاديمي ٢٠٠٨ / ٢٠٠٩م ويستمر سريان النظام الأساسي لكليات التربية على الطلاب الخاضعين له لحين تخرجهم طبقا لأحكامه.
----------------
مادة (٣) : يسري المرسوم السلطاني رقم ٦٢ / ٢٠٠٧ المشار إليه وكافة النظم واللوائح المطبقة على كليات العلوم التطبيقية على أعضاء هيئة التدريس وشاغلي الوظائف المساندة وغيرهم من الموظفين العاملين بتلك الكلية.
----------------
مادة (٤) : يلفى كل ما يخالف هذا القرار أو يتعارض مع أحكامه.
----------------
مادة (٥) : ينشر هذا القرار في الجريدة الرسمية، ويعمل به من اليوم التالي لتاريخ نشره.
[full text]:
استنادا إلى المرسوم السلطاني رقم ٦ / ٢٠٠٢ بتحديد اختصاصات وزارة التعليم العالي واعتماد هيكلها التنظيمي، وإلى المرسوم السلطاني رقم ٦٢ / ٢٠٠٧ بتنظيم كليات العلوم التطبيقية، وإلى اللائحة التنفيذية للمرسوم السلطاني رقم ٦٢ / ٢٠٠٧ بتنظيم كليات العلوم التطبيقية الصادرة بالقرار الوزاري رقم ١٣ / ٢٠١٠، وبناء على ما تقتضيه المصلحة العامة، تقرر المادة الأولى تجرى التعديلات المرفقة على اللائحة التنفيذية لكليات العلوم التطبيقية المشار إليها. المادة الثانية يلغى كل ما يخالف التعديلات المرفقة، أو يتعارض مع أحكامها. المادة الثالثة ينشر هذا القرار في الجريدة الرسمية، ويعمل به من اليوم التالي لتاريخ نشره.
[articles]:
المادة الأولى : تجرى التعديلات المرفقة على اللائحة التنفيذية لكليات العلوم التطبيقية المشار إليها.
----------------
المادة الثانية : يلغى كل ما يخالف التعديلات المرفقة، أو يتعارض مع أحكامها.
----------------
المادة الثالثة : ينشر هذا القرار في الجريدة الرسمية، ويعمل به من اليوم التالي لتاريخ نشره.
[full text]:
نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على المرسوم السلطاني رقم ٢٦ / ٧٥ بإصدار قانون تنظيم الجهاز الإداري للدولة وتعديلاته، وعلى مشروع كل من اتفاقية التعاون الاقتصادي والفني واتفاقية تشجيع وحماية الاستثمارات الموقع عليهما بالأحرف الأولى بين سلطنة عمان وجمهورية مصر العربية، وبناء على ما تقتضيه المصلحة العامة. رسمنا بما هو آت مادة ١ يفوض نائب رئيس الوزراء للشؤون المالية والاقتصادية في التوقيع النهائي نيابة عن حكومة السلطنة على اتفاقية التعاون الاقتصادي والفني واتفاقية تشجيع وحماية الاستثمارات المشار إليهما بين سلطنة عمان وجمهورية مصر العربية. مادة ٢ ينشر هذا المرسوم في الجريدة الرسمية ويعمل به اعتبارا من تاريخ صدوره.
[articles]:
مادة ١ : يفوض نائب رئيس الوزراء للشؤون المالية والاقتصادية في التوقيع النهائي نيابة عن حكومة السلطنة على اتفاقية التعاون الاقتصادي والفني واتفاقية تشجيع وحماية الاستثمارات المشار إليهما بين سلطنة عمان وجمهورية مصر العربية.
----------------
مادة ٢ : ينشر هذا المرسوم في الجريدة الرسمية ويعمل به اعتبارا من تاريخ صدوره.
[full text]:
استنادا إلى القانون المالي الصادر بالمرسوم السلطاني رقم ٤٧ / ٩٨، وإلى المرسوم السلطاني رقم ٣٦ / ٢٠١٤ بتحديد اختصاصات وزارة الصحة واعتماد هيكلها التنظيمي، وإلى اللائحة التنفيذية للقانون المالي الصادرة بالقرار الوزاري رقم ١١٨ / ٢٠٠٨، وإلى لائحة رسوم الخدمات العلاجية الصادرة بالقرار الوزاري رقم ٥٥ / ٢٠٠٩، وإلى موافقة وزارة المالية، وبناء على ما تقتضيه المصلحة العامة. تقرر المادة الأولى تجرى التعديلات المرفقة على لائحة رسوم الخدمات العلاجية المشار إليها. المادة الثانية يلغى كل ما يخالف التعديلات المرفقة، أو يتعارض مع أحكامها. المادة الثالثة ينشر هذا القرار في الجريدة الرسمية، ويعمل به من اليوم التالي لتاريخ نشره.
[articles]:
المادة الأولى : تجرى التعديلات المرفقة على لائحة رسوم الخدمات العلاجية المشار إليها.
----------------
المادة الثانية : يلغى كل ما يخالف التعديلات المرفقة، أو يتعارض مع أحكامها.
----------------
المادة الثالثة : ينشر هذا القرار في الجريدة الرسمية، ويعمل به من اليوم التالي لتاريخ نشره.
[full text]:
نحن هيثم بن طارق سلطان عمان بعد الاطلاع على النظام الأساسي للدولة، وعلى قانون المناقصات الصادر بالمرسوم السلطاني رقم ٣٦ / ۲۰۰۸، وبناء على ما تقتضيه المصلحة العامة. رسمنا بما هو آت المادة الأولى تجرى التعديلات المرفقة على قانون المناقصات المشار إليه. المادة الثانية يُلغى كل ما يخالف التعديلات المرفقة، أو يتعارض مع أحكامها. المادة الثالثة ينشر هذا المرسوم في الجريدة الرسمية، ويعمل به من اليوم التالي لتاريخ نشره.
[articles]:
المادة الأولى : تجرى التعديلات المرفقة على قانون المناقصات المشار إليه.
----------------
المادة الثانية : يُلغى كل ما يخالف التعديلات المرفقة، أو يتعارض مع أحكامها.
----------------
المادة الثالثة : ينشر هذا المرسوم في الجريدة الرسمية، ويعمل به من اليوم التالي لتاريخ نشره.
[full text]:
استنادا إلى المرسوم السلطاني رقم ٣٧ / ٢٠٠٨ بتحديد اختصاصات وزارة التربية والتعليم واعتماد هيكلها التنظيمي، وإلى لائحة شؤون الطلاب بالمدارس الحكومية الصادرة بالقرار الوزاري رقم ٢٣٤ / ٢٠١٧، وبناء على ما تقتضيه مصلحة العمل، تقرر المادة الأولى يستبدل بنص البندين (٨ / و)، و (ز) من المادة (٣٩) من لائحة شؤون الطلاب بالمدارس الحكومية المشار إليها، النصان الآتيان: (٨ / و) – التدخين أو تناول المخدرات والمؤثرات العقلية أو أي مواد محظورة أو غير مصرح بتداولها أو الحضور إلى المدرسة تحت تأثيرها. ز – رفع موضوع الطالب إلى اللجنة في المديرية وفقا للملحق رقم (١٥) المرفق بهذه اللائحة، لإصدار قرار بنقله تأديبيا إلى مدرسة أخرى إذا كان مسجلا بالصفوف من الخامس إلى الثاني عشر (٥ – ١٢)، ويجوز تحويل الطالب إلى نظام تعليم الكبار إذا كان مسجلا في الصفوف من العاشر إلى الثاني عشر (١٠ – ١٢)، وذلك في حال ارتكابه أيا من ال
[articles]:
المادة الأولى : يستبدل بنص البندين (٨ / و)، و (ز) من المادة (٣٩) من لائحة شؤون الطلاب بالمدارس الحكومية المشار إليها، النصان الآتيان: (٨ / و) – التدخين أو تناول المخدرات والمؤثرات العقلية أو أي مواد محظورة أو غير مصرح بتداولها أو الحضور إلى المدرسة تحت تأثيرها. ز – رفع موضوع الطالب إلى اللجنة في المديرية وفقا للملحق رقم (١٥) المرفق بهذه اللائحة، لإصدار قرار بنقله تأديبيا إلى مدرسة أخرى إذا كان مسجلا بالصفوف من الخامس إلى الثاني عشر (٥ – ١٢)، ويجوز تحويل الطالب إلى نظام تعليم الكبار إذا كان مسجلا في الصفوف من العاشر إلى الثاني عشر (١٠ – ١٢)، وذلك في حال ارتكابه أيا من السلوكيات الآتية: ١ – تكرار أحد السلوكيات المنصوص عليها في البند (و) من هذه المادة للمرة الثانية أو المنصوص عليها في البند (هـ) من هذه المادة للمرة الثالثة، أو المنصوص عليها في البند (ج) من هذه المادة للمرة الخامسة، أو المنصوص عليها في البند (ب) من هذه المادة للمرة السادسة، أو المنصوص عليها في البند (أ) من هذه المادة للمرة السابعة. ٢ – الاعتداء على موظفي المدرسة أو العاملين بها أو سائقي وسائل النقل المدرسية وإيذاؤهم بدنيا. ٣ – الاعتداء الجنسي على أحد زملائه داخل المدرسة أو الإسهام فيه. ٤ – الترويج وتداول المخدرات والمؤثرات العقلية أو أي مواد محظورة أو غير مصرح بتداولها بين زملائه داخل المدرسة.
----------------
المادة الثانية : يلغى كل ما يخالف هذا القرار، أو يتعارض مع أحكامه.
----------------
المادة الثالثة : ينشر هذا القرار في الجريدة الرسمية، ويعمل به من اليوم التالي لتاريخ نشره.
[full text]:
استنادا إلى قانون الثروة المائية الحية الصادر بالمرسوم السلطاني رقم ٢٠ / ٢٠١٩، وإلى اللائحة التنفيذية لقانون الصيد البحري وحماية الثروة المائية الحية الصادرة بالقرار الوزاري رقم ٤ / ٩٤، وبناء على ما تقتضيه المصلحة العامة، تقرر المادة الأولى يستثنى موسم صيد وجمع الصفيلح لعام ٢٠١٩م من حكم البند (أ) من المادة (١٥) من اللائحة التنفيذية لقانون الصيد البحري وحماية الثروة المائية الحية المشار إليها ليبدأ اعتبارا من السابع من شهر ديسمبر، وينتهي في اليوم العشرين من الشهر ذاته. المادة الثانية ينشر هذا القرار في الجريدة الرسمية، ويعمل به من اليوم التالي لتاريخ نشره.
[articles]:
المادة الأولى : يستثنى موسم صيد وجمع الصفيلح لعام ٢٠١٩م من حكم البند (أ) من المادة (١٥) من اللائحة التنفيذية لقانون الصيد البحري وحماية الثروة المائية الحية المشار إليها ليبدأ اعتبارا من السابع من شهر ديسمبر، وينتهي في اليوم العشرين من الشهر ذاته.
----------------
المادة الثانية : ينشر هذا القرار في الجريدة الرسمية، ويعمل به من اليوم التالي لتاريخ نشره.
[full text]:
استنادا إلى القانون المالي الصادر بالمرسوم السلطاني رقم ٤٧ / ٩٨، وإلى المرسوم السلطاني رقم ٣٨ / ٢٠٠٢ بتحديد اختصاصات وزارة الصحة، وإلى اللائحة التنفيذية للقانون المالي الصادرة بالقرار الوزاري رقم ١١٨ / ٢٠٠٨، وإلى القرار الوزاري رقم ٥٠ / ٩١ بتحديد رسوم خدمات الحجر الصحي، وإلى موافقة وزارة المالية رقم مالية – ت (٧٥٣٤) م.ت.د / ٦ / ٣ / ٦٩٥، وبناء على ما تقتضيه المصلحة العامة. تقرر المادة الأولى يتم تحديد رسوم خدمات الحجر الصحي التي تقدمها وزارة الصحة على النحو الآتي: م خدمات الحجر الصحي الرسم ١ معاينة الباخرة وتفتيشها من الناحية الصحية والتأكد من خلوها من الآفات وخلو الطاقم من الأمراض ٥٠ ر.ع ٢ معاينة اللنش وتفتيشه من الناحية الصحية والتأكد من خلوه من الآفات وخلو الطاقم من الأمراض ٣٠ ر.ع ٣ توصيل ومرافقة مريض إلى المستشفى للشخص الأول ٣٠ ر.ع ٤ توصيل ومرافقة مريض إلى المستشفى للشخص الثاني ١٥ ر.ع ٥
[articles]:
المادة الأولى : يتم تحديد رسوم خدمات الحجر الصحي التي تقدمها وزارة الصحة على النحو الآتي: م خدمات الحجر الصحي الرسم ١ معاينة الباخرة وتفتيشها من الناحية الصحية والتأكد من خلوها من الآفات وخلو الطاقم من الأمراض ٥٠ ر.ع ٢ معاينة اللنش وتفتيشه من الناحية الصحية والتأكد من خلوه من الآفات وخلو الطاقم من الأمراض ٣٠ ر.ع ٣ توصيل ومرافقة مريض إلى المستشفى للشخص الأول ٣٠ ر.ع ٤ توصيل ومرافقة مريض إلى المستشفى للشخص الثاني ١٥ ر.ع ٥ توصيل ومرافقة مريض آخر على نفس الباخرة ١٠ ر.ع ٦ شهادة إفراج عن مادة غذائية ٥ ر.ع
----------------
المادة الثانية : يلغى القرار الوزاري رقم ٥٠ / ٩١ المشار إليه، كما يلغى كل ما يخالف هذ القرار أو يتعارض مع أحكامه.
----------------
المادة الثالثة : ينشر هذا القرار في الجريدة الرسمية، ويعمل به من اليوم التالي لتاريخ نشره.
[full text]:
استنادا إلى قواعد ونظم العقارات لمشروع الموج مسقط الصادر بالقرار الوزاري رقم ٣٩ / ٢٠٠٨، وإلى موافقة وزارة الإسكان بالكتاب رقم و س / م و / ١ / ١٨ / ١١٣٢ / ٢٠٠٩ المؤرخ في ١٧ رجب ١٤٣٠ هـ الموافق ١٤ من يوليو ٢٠٠٩م، وبناء على ما تفتضيه المصلحة العامة تقرر المادة الأولى يستبدل بنص البند (ب) من المادة (١٥) من قواعد ونظم العقارات للشروع الموج مسقط المشار إليه، النص الآتي: تسليم الوحدة العقارية إلى المشترى خلال ٣٦‏ شهرا من تاريخ توقيع عقد البيع. المادة الثانية ينشر هذا القرار في الجريدة الرسمية، ويعمل به من اليوم التالي لتاريخ نشره.
[articles]:
المادة الأولى : يستبدل بنص البند (ب) من المادة (١٥) من قواعد ونظم العقارات للشروع الموج مسقط المشار إليه، النص الآتي: تسليم الوحدة العقارية إلى المشترى خلال ٣٦‏ شهرا من تاريخ توقيع عقد البيع.
----------------
المادة الثانية : ينشر هذا القرار في الجريدة الرسمية، ويعمل به من اليوم التالي لتاريخ نشره.
[full text]:

In [25]:
import pandas as pd

# فیلتر کردن سطرهایی که 'articles' NaN یا None است
none_articles_df = df_clean[df_clean['articles'].isna()]

# نمایش تعداد این سطرها
print(f"تعداد نمونه هایی که ماده‌ای استخراج نشده: {len(none_articles_df)}")

# نمایش ستون 'text' برای ۱۰ نمونه اول (می‌توانید تعداد را تغییر دهید)
for i, text in enumerate(none_articles_df['text'][:800].head(50)):
    print(text)
    print("="*80)

تعداد نمونه هایی که ماده‌ای استخراج نشده: 390
نحن قابوس بن سعيد سلطان عمان حيث إن البلاد بحاجة إلى قانون جزاء يرتب علاقات الأفراد فيما بينهم ويحدد واجباتهم تجاه المجتمع والحق العام فقد أصدرنا قانون الجزاء العماني. ينشر هذا القانون في ملحق الجريدة الرسمية ويعمل به من تاريخ نشره.
================================================================================
نحن قابوس بن سعيد سلطان عمان بناء على ما تقتضيه المصلحة العامة، أصدرنا قانون السجون المرفق. ينشر هذا القانون في الجريدة الرسمية ويعمل به من تاريخ النشر.
================================================================================
نحن قابوس بن سعيد سلطان عمان بناء على ما عرضه علينا مجلس الشؤون المالية، رسمنا بما هو آت أولا الموافقة على الموازنة العامة للدولة لعام ١٩٧٦ حسب الجداول المرفقة. ثانيا على جميع الوزارات والدوائر الحكومية تنفيذ ذلك كل فيما يخصه. ثالثا ينشر هذا المرسوم في الجريدة الرسمية ويعمل به من تاريخ نشره.
================================================================================
استنادا إلى القانون المالي الصادر بالمرسوم السلطاني رقم ٤٧ / ٩٨، وإلى المرسوم السلطاني رقم ٢ / ٢٠١١ بالتصديق على الميزانية العامة للدولة للسنة المالية ٢٠١١م، وبعد العرض على المقام السامي. تقرر مادة وحيدة ينشر في الجريدة الرسمية الحساب الختامي للدولة عن السنة المالية ٢٠١١م طبقا للجداول التفصيلية المرفقة.
================================================================================
استنادا إلى القانون المالي الصادر بالمرسوم السلطاني رقم ٤٧ / ٩٨، وإلى المرسوم السلطاني رقم ١ / ٢٠١٢ بالتصديق على الميزانية العامة للدولة للسنة المالية ٢٠١٢م، وبعد العرض على المقام السامي. تقرر مادة وحيدة ينشر في الجريدة الرسمية الحساب الختامي للدولة عن السنة المالية ٢٠١٢م طبقا للجداول التفصيلية المرفقة.
================================================================================
استنادا إلى القانون المالي الصادر بالمرسوم السلطاني رقم ٤٧ / ٩٨، وإلى المرسوم السلطاني رقم ١ / ٢٠١٣ بالتصديق على الميزانية العامة للدولة للسنة المالية ٢٠١٣م، وبعد العرض على المقام السامي. تقرر مادة وحيدة ينشر في الجريدة الرسمية الحساب الختامي للدولة عن السنة المالية ٢٠١٣م طبقا للجداول التفصيلية المرفقة.
================================================================================
استنادا إلى القانون المالي الصادر بالمرسوم السلطاني رقم ٤٧ / ٩٨، وإلى المرسوم السلطاني رقم ١ / ٢٠١٤ بالتصديق على الميزانية العامة للدولة للسنة المالية ٢٠١٤م، وبعد العرض على المقام السامي – حفظه الله ورعاه -. تقرر مادة وحيدة ينشر في الجريدة الرسمية الحساب الختامي للدولة عن السنة المالية ٢٠١٤م طبقا للجداول التفصيلية المرفقة.
================================================================================
استنادا إلى القانون المالي الصادر بالمرسوم السلطاني رقم ٤٧ / ٩٨، وإلى المرسوم السلطاني رقم ١ / ٢٠١٥ بالتصديق على الميزانية العامة للدولة للسنة المالية ٢٠١٥م، وبعد العرض على المقام السامي – حفظه الله ورعاه -. تقرر مادة وحيدة ينشر في الجريدة الرسمية الحساب الختامي للدولة عن السنة المالية ٢٠١٥م طبقا للجداول التفصيلية المرفقة.
================================================================================
استنادا إلى القانون المالي الصادر بالمرسوم السلطاني رقم ٤٧ / ٩٨، وإلى المرسوم السلطاني رقم ٢ / ٢٠١٦ بالتصديق على الميزانية العامة للدولة للسنة المالية ٢٠١٦م، وبعد العرض على المقام السامي – حفظه الله ورعاه -، وبناء على ما تقتضيه المصلحة العامة، تقرر مادة وحيدة ينشر في الجريدة الرسمية الحساب الختامي للدولة عن السنة المالية ٢٠١٦م، طبقا للجداول التفصيلية المرفقة.
================================================================================
(٢٧) بتاريخ ١٣ / ٦ / ٢٠١٨م وزارة الشؤون القانونية – مناط ولايتها في إبداء الرأي القانوني. استقر إفتاء وزارة الشؤون القانونية على أن اختصاصها بإبداء الرأي القانوني، وإصدار الفتاوى والتفسيرات الرسمية المعتمدة في السلطنة للمراسيم السلطانية والقوانين والقرارات واللوائح الوزارية لا ينعقد إلا إذا ارتبط طلب الرأي بوجود نص في مرسوم سلطاني أو قانون أو لائحة أو قرار غم على الجهة طالبة الرأي وجه تطبيقه على حالة واقعية ماثلة لديها – مقتضى ذلك – أنه يلزم توافر إشكال قانوني صادف جهة الإدارة الطالبة، واقتضى استدعاء رأي الوزارة بشأنه – مؤدى ذلك – لا تنعقد وزارة الشؤون القانونية في إبداء الرأي القانوني إذا كان الطلب لمجرد الاستيضاح أو لمحض الفهم السليم لنصوص قانونية، دون أن يقوم لدى الجهة خلاف أو معضلة في تطبيق النص، أو لمجرد التثبت من صحة تقدير جهة الإدارة بمناسبة ممارستها سلطتها التقديرية حيال بعض المسائل – تطبيق. فبالإشارة إلى الكتاب رقم:……….. بتاريخ……….، الموافق……………. بشأن طلب الإفادة بالرأي القانوني حول ترقية بعض موظفي وزارة……………. يسرني أن أفيد معاليكم بأن إفتاء وزارة الشؤون القانونية قد استقر على أن اختصاصها بإبداء الرأي القانوني، وإصدار الفتاوى، والتفسيرات الرسمية المعتمدة في السلطنة للمراسيم السلطانية، والقوانين، والقرارات، واللوائح الوزارية لا ينعقد إلا إذا ارتبط طلب الرأي بوجود نص في مرسوم سلطاني أو قانون أو لائحة أو قرار غم على الجهة طالبة الرأي وجه تطبيقه على حالة واقعية ماثلة لديها، وأن ترتبط الحالة بمركز قانوني قائم، أو تتصل بالآثار التي تترتب على هذا المركز، ولا يقتصر على تفسير نصوص مجردة، وأن يتمخض عن ذلك مشكلة أو اختلاف في الرأي حول المركز القانوني أو آثاره يغم على الجهة المعنية الوصول إلى رأي قاطع في شأن ذلك، ومن ثم يلزم توافر إشكال قانوني صادف جهة الإدارة الطالبة، واقتضى استدعاء رأي الوزارة بشأنه، ومعنى ذلك أن طلب الرأي القانوني لمجرد الاستيضاح أو لمحض الفهم السليم لنصوص قانونية، دون أن يقوم لدى الجهة خلاف أو معضلة في تطبيق النص، أو لمجرد التثبت من صحة تقدير جهة الإدارة بمناسبة ممارستها سلطتها التقديرية حيال بعض المسائل، فإن ولاية وزارة الشؤون القانونية في إبداء الرأي لا تنعقد في هذه الحالة. وحيث إنه لم يتبين للمختصين في وزارة الشؤون القانونية موضوع طلب الرأي في الحالة المعروضة على وجه الدقة، أو موضع الغموض في إعمال النصوص القانونية بشأنها، ومن ثم، فإنه لا يجوز للوزارة أن تحل محل الجهة الإدارية صاحبة الاختصاص في تنفيذ القوانين واللوائح إزاء الحالة المعروضة. وتبعا لذلك، يتعذر على وزارة الشؤون القانونية إبداء الرأي في الحالة المعروضة، على النحو السالف بيانه.
================================================================================
(٣٩) بتاريخ ٣١ / ١٠ / ٢٠١٨م ١ – رسم – مفهومه قانونا والفرق بينه وبين الضريبة. إن الرسم بمعناه القانوني هو مبلغ من المال يجبيه أحد الأشخاص العامة كرها من الفرد نظير خدمة معينة تؤديها الدولة إليه، وبذلك يتكون من عنصرين، أولهما أنه يدفع مقابل خدمة معينة، ولذلك يعتد في تقديره أساسا بتكاليف تلك الخدمة، والثاني أنه لا يدفع اختيارا كما تدفع الأثمان العادية، وإنما يدفع كرها بطريق الإلزام، وتستأديه الدولة من الأفراد بما لها عليهم من سلطة الجباية شأنه في ذلك شأن الضريبة، وإن كان يختلف عنها في أنه يدفع مقابل خدمة معينة، وقد تقدم هذه الخدمة للفرد دون أن يطلبها، بل إنها قد تقدم له ولو أظهر عدم رغبته فيها، ولا يقوم عنصر الإكراه على التزام الفرد بدفع الرسم في سبيل الخدمة المطلوبة، لأن ذلك أمر طبيعي بالنسبة إلى جميع المعاملات المالية ومن بينها البيع والشراء ولكن أساس الإكراه بالنسبة إلى الرسم هو حالة الضرورة القانونية التي تلجئ الفرد إلى الدولة أو أحد الأشخاص الاعتبارية العامة لاقتضاء الخدمة لما قد يترتب على التخلف عن طلبها من جزاء أو أثر قانوني – تطبيق. ٢ – رسوم – رسوم قضائية – عدم التزام وحدات الجهاز الإداري للدولة بسداد الرسوم القضائية في الدعاوى المرفوعة منها. استقر إفتاء وزارة الشؤون القانونية على أن الدولة ومصالحها وفروعها لا يقع على عاتقها عبء أداء الضرائب والرسوم إلا إذا نص القانون على إلزامها بذلك صراحة، وهو ما يعتبر وفق التكييف القانوني السليم عدم خضوع الدولة للضريبة أو الرسم – أساس ذلك – أن فرض الضريبة أو الرسم ما هو إلا تكليف عام يتضمن المساهمة في الأعباء المالية للدولة، وليس من المتصور أن تخاطب الدولة ومصالحها وفروعها بهذا التكليف، لأنه ليس من شأن ذلك زيادة إيرادات الخزينة العامة كأحد الأهداف الأساسية الحاكمة لفرض الضريبة أو الرسم، ولا مردود لمثل هذا التكليف سوى تضخيم بنود الميزانية بغير زيادة حقيقية في إيرادات الخزينة العامة، فضلا عن زيادة التكلفة المالية على الجهات الحكومية من أجل الإنفاق على المراسلات والمخاطبات حتى تتمكن من سداد الرسوم المشار إليها، كما أنه لا يوجد ثمة نص يخضع الدولة ومصالحها وفروعها للرسوم القضائية – تطبيق. فبالإشارة إلى كتاب معاليكم رقم:………………….. بتاريخ………………، الموافق………………. بشأن طلب إبداء الرأي القانوني حول مدى التزام وزارة…………. بسداد الرسوم القضائية في الدعاوى المرفوعة منها. وتخلص الوقائع – حسبما يبين من الكتاب سالف الذكر ومرفقاته – في أن وزارة……………… تلقت تعميمين صادرين من الأمانة العامة لمجلس الشؤون الإدارية للقضاء رقمي (٣ – ٤ / ٢٠١٨) تضمنا التزام الجهات الحكومية بسداد رسوم الدعاوى والطعون بالاستئناف والكفالة وغيرها من الرسوم بناء على عدم موافقة وزارة المالية على إعفاء الجهات الحكومية من تلك الرسوم. وتشيرون إلى أن المحكمة الابتدائية في……… كانت قد امتنعت عن قيد صحيفة الدعوى المقدمة من وزارة…………….. إلا بعد سداد الرسوم القضائية عن تلك الدعوى. وإذ تستطلعون الرأي في الموضوع المشار إليه. وردا على ذلك، نفيد بأن الرسم بمعناه القانوني هو مبلغ من المال يجبيه أحد الأشخاص العامة كرها من الفرد نظير خدمة معينة تؤديها الدولة إليه، وهو بذلك يتكون من عنصرين، أولهما أنه يدفع مقابل خدمة معينة، ولذلك يعتد في تقديره أساسا بتكاليف تلك الخدمة، والثاني أنه لا يدفع اختيارا كما تدفع الأثمان العادية، وإنما يدفع كرها بطريق الإلزام، وتستأديه الدولة من الأفراد بما لها عليهم من سلطة الجباية شأنه في ذلك شأن الضريبة، وإن كان يختلف عنها في أنه يدفع مقابل خدمة معينة، وقد تقدم هذه الخدمة للفرد دون أن يطلبها، بل إنها قد تقدم له ولو أظهر عدم رغبته فيها، ولا يقوم عنصر الإكراه على التزام الفرد بدفع الرسم في سبيل الخدمة المطلوبة لأن ذلك أمر طبيعي بالنسبة إلى جميع المعاملات المالية ومن بينها البيع والشراء، ولكن أساس الإكراه بالنسبة إلى الرسم هو حالة الضرورة القانونية التي تلجئ الفرد إلى الدولة أو أحد الأشخاص الاعتبارية العامة لاقتضاء الخدمة لما قد يترتب على التخلف عن طلبها من جزاء أو أثر قانوني. (فتوى رقم و ش ق / ٣٧ / ٢ / ٥٠ / ٩٨ في ١٧ / ١ / ١٩٩٨م). وفي إطار ذلك استقر إفتاء وزارة الشؤون القانونية على أن الدولة ومصالحها وفروعها لا يقع على عاتقها عبء أداء الضرائب والرسوم إلا إذا نص القانون على إلزامها بذلك صراحة، وهو ما يعتبر وفق التكييف القانوني السليم عدم خضوع الدولة للضريبة أو الرسم، ومرد ذلك أن فرض الضريبة أو الرسم ما هو إلا تكليف عام يتضمن المساهمة في الأعباء المالية للدولة، وليس من المتصور أن تخاطب الدولة ومصالحها وفروعها بهذا التكليف، لأنه ليس من شأن ذلك زيادة إيرادات الخزينة العامة كأحد الأهداف الأساسية الحاكمة لفرض الضريبة أو الرسم، ولا مردود لمثل هذا التكليف سوى تضخيم بنود الميزانية بغير زيادة حقيقية في إيرادات الخزينة العامة، فضلا عن زيادة التكلفة المالية على الجهات الحكومية من أجل الإنفاق على المراسلات والمخاطبات حتى تتمكن من سداد الرسوم المشار إليها. وحيث إنه لا يوجد ثمة نص يخضع الدولة ومصالحها وفروعها للرسوم القضائية، فإنه يتعين تطبيق القاعدة المستقرة في هذا الشأن بعدم خضوع الجهات الحكومية للرسوم المشار إليها، وعدم التزامها بسدادها، ولا يجوز قانونا الاستناد إلى عدم النص على إعفاء الجهات الحكومية لإلزامها بأداء الرسوم القضائية. لذلك انتهى الرأي، إلى عدم التزام وزارة……………. بسداد الرسوم القضائية في الدعاوى المرفوعة منها، وذلك على النحو المبين بالأسباب.
================================================================================
استنادا إلى القانون المالي الصادر بالمرسوم السلطاني رقم ٤٧ / ٩٨، وإلى المرسوم السلطاني رقم ١ / ٢٠١٧ بالتصديق على الميزانية العامة للدولة للسنة المالية ٢٠١٧م، وبعد العرض على المقام السامي – حفظه الله ورعاه -، وبناء على ما تقتضيه المصلحة العامة، تقرر مادة وحيدة ينشر في الجريدة الرسمية الحساب الختامي للدولة عن السنة المالية ٢٠١٧م، طبقا للجداول التفصيلية المرفقة.
================================================================================
(٨) بتاريخ ١٣ / ٢ / ٢٠١٩م ١ – رسم – معناه القانوني – الفرق بينه وبين الضريبة. الرسم بمعناه القانوني هو مبلغ من المال يجبيه أحد الأشخاص العامة كرها من الفرد نظير خدمة معينة تؤديها الدولة إليه، وهو بذلك يتكون من عنصرين، أولهما أنه يدفع مقابل خدمة معينة، ولذلك يعتد في تقديره أساسا بتكاليف تلك الخدمة، والثاني أنه لا يدفع اختيارا كما تدفع الأثمان العادية، وإنما يدفع كرها بطريق الإلزام – الرسم تستأديه الدولة من الأفراد، بما لها عليهم من سلطة الجباية، شأنه في ذلك شأن الضريبة – أساس الإكراه – حالة الضرورة القانونية التي تلجئ الفرد إلى الدولة أو أحد الأشخاص الاعتبارية العامة لاقتضاء الخدمة مقابل رسم لما قد يترتب على التخلف عن طلبها من جزاء، أو أثر قانوني – الفرق بين الرسم والضريبة – الضريبة تدفع مقابل خدمة معينة، وقد تقدم هذه الخدمة للفرد دون أن يطلبها، بل إنها قد تقدم إليه، ولو أظهر عدم رغبته فيها – تطبيق. ٢- رسوم – رسوم قضائية – إعفاء الدولة ومصالحها من أدائها. استقر إفتاء وزارة الشؤون القانونية على أن الدولة ومصالحها وفروعها لا يقع على عاتقها عبء أداء الضرائب والرسوم، إلا إذا نص القانون على إلزامها بذلك صراحة، وهو ما يعتبر وفق التكييف القانوني السليم عدم خضوع الدولة للضريبة أو الرسم، – عدم وجود نص يخضع الدولة ومصالحها وفروعها للرسوم القضائية يتعين معه تطبيق القاعدة المستقرة المشار إليها – أساس ذلك – أن الضريبة أو الرسم ما هو إلا تكليف عام يتضمن المساهمة في الأعباء المالية للدولة، وليس من المتصور أن تخاطب الدولة ومصالحها وفروعها بهذا التكليف – إذ ليس من شأن ذلك زيادة إيرادات الخزينة العامة كأحد الأهداف الأساسية الحاكمة لفرض الضريبة أو الرسم – لا مردود لمثل هذا التكليف سوى تضخيم بنود الميزانية بغير زيادة حقيقية في إيرادات الخزينة العامة، فضلا عن التكلفة المالية على الجهات الحكومية من أجل الإنفاق على المراسلات والمخاطبات حتى تتمكن من سداد الرسوم – تطبيق. فبالإشارة إلى كتاب معاليكم رقم :………… بتاريخ ………، الموافق ……………. بشأن طلب إبداء الرأي القانوني حول مدى جواز فرض الرسوم القضائية على بلدية …………… وتخلص وقائع الموضوع – حسبما يبين من الكتاب سالف الذكر – في أن بلدية ……………. قد تلقت تعميما صادرا من الأمانة العامة لمجلس الشؤون الإدارية للقضاء رقم (٣ / ٢٠١٨) تضمن التزام الجهات الحكومية بسداد رسوم الدعاوى والطعون بالاستئناف والكفالة وغيرها من الرسوم بناء على عدم موافقة وزارة المالية على إعفاء الجهات الحكومية من تلك الرسوم. وتشيرون إلى أن بلدية ……………. قد قامت بقيد الاستئناف في الدعوى رقم (٧ / ٧١٠٢ / ٢٠١٩) في محكمة الاستئناف بمسقط ضد الفاضلة……………. مع سداد رسوم تسجيل الدعوى بمبلغ، وقدره (٥٠) خمسون ريالا عمانيا. وتذكرون أنه قد ثار الخلاف حول مدى التزام بلدية ……………. بسداد الرسوم القضائية في الدعاوى المرفوعة منها، فذهب رأي إلى عدم جواز دفع الرسوم باعتبار أن البلدية وحدة من وحدات الجهاز الإداري للدولة، وأن الأصل أن الدولة ومصالحها وفروعها لا يقع على عاتقها عبء أداء الضرائب والرسوم إلا إذا نص القانون على إلزامها بذلك، وهو ما يعتبر وفق تكييف القانون السليم عدم خضوع الدولة للضريبة أو الرسم، ذلك أن الضريبة أوالرسم ما هو إلا تكليف عام يتضمن المساهمة في الأعباء المالية للدولة، ولا جدوى من قيام الدولة بأداء الضريبة أو الرسم لنفسها، فليس من شأن ذلك زيادة إيرادات الخزينة العامة للدولة، وهو ما أكدت عليه فتوى وزارة الشؤون القانونية بتاريخ ٢٦ / ٢ / ٢٠٠٠م. بينما ذهب رأي آخر إلى التزام البلدية بدفع رسوم الدعاوى القضائية استنادا إلى التعميم المشار إليه. وإزاء ما تقدم، فإنكم تطلبون الرأي – وفقا للتكييف القانوني للوقائع – حول مدى التزام بلدية ……………. بسداد الرسوم القضائية في الدعاوى المرفوعة منها. وردا على ذلك , نفيد بأن الرسم بمعناه القانوني هو مبلغ من المال يجبيه أحد الأشخاص العامة كرها من الفرد نظير خدمة معينة تؤديها الدولة إليه، وهو بذلك يتكون من عنصرين، أولهما أنه يدفع مقابل خدمة معينة، ولذلك يعتد في تقديره أساسا بتكاليف تلك الخدمة، والثاني أنه لا يدفع اختيارا كما تدفع الأثمان العادية، وإنما يدفع كرها بطريق الإلزام، وتستأديه الدولة من الأفراد، بما لها عليهم من سلطة الجباية، شأنه في ذلك شأن الضريبة، وإن كان يختلف عنها في أنه يدفع مقابل خدمة معينة، وقد تقدم هذه الخدمة للفرد دون أن يطلبها، بل إنها قد تقدم له، ولو أظهر عدم رغبته فيها، ولا يقوم عنصر الإكراه على التزام الفرد بدفع الرسم في سبيل الخدمة المطلوبة، لأن ذلك أمر طبيعي بالنسبة إلى جميع المعاملات المالية، ومن بينها البيع والشراء، ولكن أساس الإكراه بالنسبة إلى الرسم هو حالة الضرورة القانونية التي تلجئ الفرد إلى الدولة أو أحد الأشخاص الاعتبارية العامة لاقتضاء الخدمة لما قد يترتب على التخلف عن طلبها من جزاء، أو أثر قانوني. (فتوى رقم و ش ق / ٣٧ / ٢ / ٥٠ / ٩٨ في ١٧ / ١ / ١٩٩٨م، وفتوى رقم ١٨٢٧١٠٦٠٩ في ٣١ / ١٠ / ٢٠١٨م). وفي إطار ذلك، فقد استقر إفتاء وزارة الشؤون القانونية على أن الدولة ومصالحها وفروعها لا يقع على عاتقها عبء أداء الضرائب والرسوم إلا إذا نص القانون على إلزامها بذلك صراحة، وهو ما يعتبر وفق التكييف القانوني السليم عدم خضوع الدولة للضريبة أو الرسم، ومرد ذلك أن فرض الضريبة أو الرسم ما هو إلا تكليف عام يتضمن المساهمة في الأعباء المالية للدولة، وليس من المتصور أن تخاطب الدولة ومصالحها وفروعها بهذا التكليف، لأنه ليس من شأن ذلك زيادة إيرادات الخزينة العامة كأحد الأهداف الأساسية الحاكمة لفرض الضريبة أو الرسم، ولا مردود لمثل هذا التكليف سوى تضخيم بنود الميزانية بغير زيادة حقيقية في إيرادات الخزينة العامة، فضلا عن زيادة التكلفة المالية على الجهات الحكومية من أجل الإنفاق على المراسلات والمخاطبات حتى تتمكن من سداد الرسوم المشار إليها. وحيث إنه لا يوجد ثمة نص يخضع الدولة ومصالحها وفروعها للرسوم القضائية، فإنه يتعين تطبيق القاعدة المستقرة في هذا الشأن بعدم خضوع الجهات الحكومية للرسوم المشار إليها، وعدم التزامها بسدادها، ولا يجوز قانونا الاستناد إلى عدم النص على إعفاء الجهات الحكومية لإلزامها بأداء الرسوم القضائية. لذلك انتهى الرأي، إلى عدم التزام بلدية …………… بسداد الرسوم القضائية في الدعاوى المرفوعة منها، وذلك على النحو المبين بالأسباب.
================================================================================

In [26]:
import pandas as pd
none_articles_df = df_clean[df_clean['articles'].isna()]
print(f"تعداد نمونه هایی که ماده‌ای استخراج نشده: {len(none_articles_df)}")

df_clean = df_clean[df_clean['articles'].notna()].reset_index(drop=True)

تعداد نمونه هایی که ماده‌ای استخراج نشده: 390

In [27]:
df_clean.iloc[0]['articles']

'المادة ١ : يعتبر عمانيا حكما: ١ – من ولد في عمان أو خارجا من أب عماني. ٢ – من ولد في عمان من والدين مجهولين. ٣ – الولد غير الشرعي القاصر الذي تثبت بنوته إذا كان أحد والديه الذي ثبتت البنوة أولا بالنظر إليه عمانيا. إذا كان ثبوت البنوة بالنظر إلى الأب والأم ناتجا عن عقد واحد أو حكم واحد اتخذ الولد تابعية الأب إذا كان هذا الأب عمانيا. ٤ – من ولد في عمان أو خارجها من أم عمانية وكان مجهول الأب أو لم تثبت نسبته لأبيه شرعا أو كان أبوه لا جنسية له. ٥ – من ولد في عمان وجعل منها محل إقامته العادية وكان أبوه قد ولد فيها على أن لا يكون الأب حاملا أي جنسية عند تلك الولادة. ٦ – من ينتمي بأصله لعمان ولم يكتسب جنسية أخرى ولم يتقدم لاختيار الجنسية العمانية حسب الأنظمة المرعية.\n----------------\nالمادة ٢ : يجوز منح الجنسية العمانية لأجنبي إذا توفرت فيه الشروط التالية: ١ – أن يكون بالغا سن الرشد. ٢ – أن يتقدم بطلب خطي. ٣ – أن يسبق طلبه إقامة فعلية متواصلة وشرعية في عمان لمدة لا تقل عن عشر سنوات، أما إذا كان متزوجا بعمانية فتخفض مدة الإقامة إلى سنتين بعد الزواج. ٤ – أن يكون حسن السيرة والسلوك وأن يكون سليم البنية وخاليا من العاهات. ٥ – أن يكون له وسيلة مشروعة للرزق تدر عليه ما يكفي لسد حاجته. ٦ – أن يكون قد قسم اليمين المنصوص عليها في المادة الثامنة من هذا النظام.\n----------------\nالمادة ٣ : تمنح الجنسية العمانية بمرسوم سلطاني ولا تمنح هذه الجنسية إلا بصورة إفرادية.\n----------------\nالمادة ٤ : يجوز بموجب مرسوم سلطاني منح الجنسية العمانية لأجنبي أدى خدمات جليلة لعمان دون التقيد بشروط التجنس المنصوص عليها في المادة الثانية من هذا النظام.\n----------------\nالمادة ٥ : يجوز أن تمنح زوجة الأجنبي الذي اكتسب الجنسية العمانية وأولاده الراشدين هذه الجنسية بناء على طلبهم دون أن تطبق عليهم شروط التجنس المنصوص عليها في المادة الثانية من هذا النظام. يصبح عمانيين حكما الأولاد القاصرون لأب تجنس بالجنسية العمانية إلا أنهم يستطيعون في السنة التي تلي بلوغهم سن الرشد طلب التخلي عن هذه الجنسية.\n----------------\nالمادة ٦ : تكتسب المرأة الأجنبية التي تتزوج من عماني الجنسية العمانية بقرار من وزير الداخلية والعدلية يصدر بناء على طلبها دون التقيد بشروط التجنس المنصوص عليها في المادة الثانية من هذا النظام باستثناء شرط حسن السيرة والسلوك.\n----------------\nالمادة ٧ : يمارس الأجنبي الذي اكتسب الجنسية العمانية الحقوق المدنية من تاريخ تجنسه ولا يمارس الحقوق العامة والسياسية إلا بعد انقضاء عشر سنوات من التاريخ المذكور.\n----------------\nالمادة ٨ : يقسم طالب التجنس أمام القضاء في الولاية التي يقوم فيها اليمين التالية: أقسم بالله العظيم أني موال لجلالة سلطان عمان وأني احترم قوانين عمان وعاداتها وتقاليدها وأن أكون مواطنا صالحا والله على ما أقول شهيد.\n----------------\nالمادة ٩ : يفقد العماني جنسيته العمانية إذا اكتسب جنسية أجنبية بعد أن يستحصل على الترخص بذلك بمرسوم سلطاني، ولا يعطى الترخص إلا بعد قيامه بجميع واجباته والتزاماته تجاه الدولة. يتبع الأولاد القاصرون والدهم في جنسيته الجديدة إذا كان قانون هذه الجنسية يكسبهم جنسيته. إلا أنه يجوز لهم استرداد الجنسية العمانية بناء على طلبهم خلال سنة واحدة منذ بلوغهم سن الرشد إذا كانت إقامتهم العادية في عمان أو كانوا قد عادوا إليها وصرحوا خطيا برغبتهم في الإقامة فيها.\n----------------\nالمادة ١٠ : المرأة العمانية التي تتزوج من أجنبي تبقى عمانية إلا إذا طلبت التنازل عن جنسيتها لاكتساب جنسية زوجها وكان قانون زوجها يمنحها هذه الجنسية. المرأة التي تفقد جنسيتها العمانية بموجب الفقرة السابقة تستطيع بعد انتهاء الزوجية أن تسترد الجنسية العمانية بقرار من وزير الداخلية والعدلية إذا كانت إقامتها العادية في الأراضي العمانية أو كانت عادت إليها وصرحت برغبتها في الإقامة فيها.\n----------------\nالمادة ١١ : يجرد من الجنسية العمانية بمرسوم سلطاني: ١ – كل من ثبت اكتسابه الجنسية العمانية بناء على بيان كاذب أو بطريق الغش أو الاحتيال وكل من اكتسبها معه بطريق التبعية. ٢ – كل من ثبت أنه يعتنق مبادئ وعقائد لا دينية أو ينتمي إلى جماعة أو حزب به تعتنق مبادئ لا دينية. ٣ – كل من ثبت عليه أنه مستخدم لدى دولة أجنبية بأي صفة كانت سواء داخل عمان أو خارجها ولم يلب طلب الحكومة العمانية بترك هذه الخدمة ضمن مدة معينة. ٤ – كل من ثبت عليه أنه يعمل لصالح دولة معادية. ٥ – المتجنس بالجنسية العمانية إذا حكم عليه بإحدى الجرائم الواقعة على أمن الدولة أو إذا انتمى إلى جماعة أو حزب قام بمؤامرة واعتداء على أمن الدولة.\n----------------\nالمادة ١٢ : يجوز لمن جرد من الجنسية العمانية أن يستردها إذا زالت الأسباب المؤدية للتجريد ويتم ذلك بموجب مرسوم سلطاني.\n----------------\nالمادة ١٣ : من أجل تطبيق هذا النظام إن كلمة عماني الواردة فيه تشمل الرجل والمرأة على السواء إلا في حال وجود نص صريح مخالف.\n----------------\nالمادة ١٤ : يعتبر سن الرشد في شؤون الجنسية تمام الثامنة عشرة.\n----------------\nالمادة ١٥ : يعاقب بالسجن مدة لا تتجاوز السنة أو بغرامة لا تزيد عن خمسمائة ريال سعيدي أو بالعقوبتين معا كل من يدلي أمام السلطات المختصة بمعلومات كاذبة أو يقدم وثائق غير صحيحة بقصد اكتساب الجنسية العمانية لنفسه أو لغيره.\n----------------\nالمادة ١٦ : تعين بمرسوم سلطاني لجنة برئاسة قاض وعضوية مدير الجوازات في وزارة الداخلية والعدلية وعضو مستقل مهمتها الفصل في المنازعات المتعلقة بالجنسية وفرض العقوبات المنصوص عليها في المادة السابقة وتتخذ قراراتها بالأكثرية.\n----------------\nالمادة ١٧ : يضع وزير الداخلية والعدلية تعليمات وزارته تتضمن طرق وأساليب تطبيق هذا النظام.\n----------------\nالمادة ١٨ : ينشر هذا النظام في الجريدة الرسمية. يناير ١٩٧٢م قابوس بن سعيد سلطان عمان (تاريخ النفاذ ٢٧ / ٤ / ٧٢) نشر هذا القانون في عدد الجريدة الرسمية رقم (١) الصادر في ٢٧ / ٤ / ١٩٧٢م'

In [28]:
DELIM = "\n----------------\n"
df_clean['num_articles'] = df_clean['articles'].apply(
    lambda x: len(x.split(DELIM)) if isinstance(x, str) else 0
)
df_clean['word_count_articles'] = df_clean['articles'].apply(
    lambda x: len(x.split()) if isinstance(x, str) else 0
)

def avg_words_per_article(text):
    if not isinstance(text, str):
        return 0
    parts = text.split(DELIM)
    return sum(len(p.split()) for p in parts) // len(parts)

df_clean['avg_words_per_article'] = df_clean['articles'].apply(avg_words_per_article)

In [29]:
import re
import pandas as pd

def extract_preamble(text):
    if not isinstance(text, str) or not text.strip():
        return None

    # ---------------------------------------------------------
    # 1. تعریف پترن‌های ماده (مشابه قبل)
    # ---------------------------------------------------------
    number_words = [
        r'الأولى', r'الثانية', r'الثالثة', r'الرابعة', r'الخامسة', r'السادسة',
        r'السابعة', r'الثامنة', r'التاسعة', r'العاشرة', r'الحادية', r'الثانية',
        r'أولى', r'ثانية', r'ثالثة', r'رابعة', r'خامسة', r'سادسة',
        r'سابعة', r'ثامنة', r'تاسعة', r'عاشرة', r'حادية', r'ثاني',
        r'واحد', r'اثنان', r'ثلاثة', r'أربعة', r'خمسة', r'ستة',
        r'سبعة', r'ثمانية', r'تسعة', r'عشر', r'عشرة',
        r'العشرون', r'الثلاثون', r'الأربعون', r'الخمسون'
    ]
    word_pattern = '|'.join(number_words)
    digit_part = r'(?:\(\s*[\d\u06F0-\u06F9\u0660-\u0669]+\s*\)|[\d\u06F0-\u06F9\u0660-\u0669]+)'
    text_part = f'(?:(?:{word_pattern})(?:\s+(?:عشر|عشرة))?)'

    full_pattern = re.compile(
        r'((?:^|\s|[.،؛:])(المادة|مادة)\s+(?:' + digit_part + r'|' + text_part + r')(?:\s+مكرر)?)',
        re.MULTILINE
    )

    matches = list(full_pattern.finditer(text))

    # متغیر برای ذخیره متن اولیه استخراج شده
    raw_preamble = text.strip()

    # ---------------------------------------------------------
    # 2. پیدا کردن نقطه شروع اولین ماده معتبر
    # ---------------------------------------------------------
    if matches:
        ref_keywords = [
            'في', 'من', 'حكم', 'نص', 'أحكام', 'بموجب', 'مقتضى',
            'خلال', 'تطبيق', 'وفق', 'أحكام', 'مراعاة'
        ]
        ref_pattern = re.compile(r'\b(' + '|'.join(ref_keywords) + r')\s*$', re.UNICODE)

        split_index = -1

        for m in matches:
            start_idx = m.start()
            keyword = m.group(2)
            prefix = text[max(0, start_idx-20):start_idx]
            prefix_clean = re.sub(r'\s+', ' ', prefix).strip()

            if ref_pattern.search(prefix_clean):
                continue

            if keyword == 'المادة':
                word_start = m.start(2)
                if word_start > 0:
                    char_before = text[word_start - 1]
                    if char_before in 'بلك':
                        if word_start == 1 or (word_start > 1 and text[word_start-2] in ' \t\n\r.،'):
                            continue

            split_index = start_idx
            break

        if split_index != -1:
            raw_preamble = text[:split_index].strip()

    # ---------------------------------------------------------
    # 3. پاکسازی عبارات دستوری از انتهای مقدمه (بخش جدید)
    # ---------------------------------------------------------

    # لیست عباراتی که باید از انتهای متن حذف شوند
    removal_phrases = [
        r'رسمنا\s+بما\s+هو\s+آت',  # رسمنا بما هو آت
        r'قررنا',                  # قررنا
        r'فقد\s+قررنا',            # فقد قررنا
        r'فقد\s+تقرر\s+ما\s*يلي',  # فقد تقرر مايلي / ما يلي
        r'فقد\s+تقرر',             # فقد تقرر
        r'أصدرنا\s+المرسوم\s+الآتي', # أصدرنا المرسوم الآتي
        r'أصدرنا\s+القانون\s+الآتي', # أصدرنا القانون الآتي
        r'ما\s*يلي'                 # مايلي (اگر تنها مانده باشد)
    ]

    # ترکیب پترن‌ها با OR
    # \s*[:.\-]*\s*$ به معنی: "به همراه هر گونه فاصله، نقطه، دو نقطه یا خط تیره که در انتهای خط باشد"
    clean_pattern = r'(?:' + '|'.join(removal_phrases) + r')\s*[:.\-]*\s*$'

    # حذف عبارت پیدا شده از انتهای متن
    clean_preamble = re.sub(clean_pattern, '', raw_preamble, flags=re.MULTILINE)

    # ---------------------------------------------------------
    # 4. پاکسازی نهایی علائم نگارشی باقی‌مانده
    # ---------------------------------------------------------
    # ممکن است بعد از حذف عبارت بالا، یک نقطه یا دو نقطه از جمله قبل باقی مانده باشد
    # مثال: "... ١٩٧٤. قررنا" -> بعد از حذف قررنا -> "... ١٩٧٤."
    # این خط علائم نگارشی اضافی انتهای متن را حذف می‌کند
    clean_preamble = re.sub(r'\s*[:.\-،]+\s*$', '', clean_preamble)

    return clean_preamble.strip()

# اجرا روی دیتافریم
df_clean['PREAMBLE'] = df_clean['text'].apply(extract_preamble)

In [30]:

# random_state=42 برای تکرارپذیری (هر بار نتیجه یکسان بدهد)
samples = df_clean[['text', 'articles', 'num_articles', 'word_count_articles', 'avg_words_per_article']].sample(n=5, random_state=42)

# پرینت کردن هر نمونه (با جداکننده برای خوانایی)
for idx, row in samples.iterrows():
    print(f"نمونه {idx}:")
    print(f"Text: {row['text']}")
    print(f"Num Articles: {row['num_articles']}")
    print(f"Word Count Articles: {row['word_count_articles']}")
    print(f"avg_words_per_article: {row['avg_words_per_article']}")
    print(f"articles: {row['articles']}")
    print("-" * 80)  # جداکننده بلند برای خواندن بهتر

نمونه 6095:
Text: استنادا إلى المرسوم السلطاني رقم ٣٥ / ٢٠١٤ بإنشاء كلية العلوم الشرعية وإصدار نظامها، وإلى اللائحة الداخلية لكلية العلوم الشرعية الصادرة بالقرار رقم ٣٥ / ٢٠١٨، وبناء على ما تقتضيه المصلحة العامة. تقرر المادة الأولى يعمل بأحكام النظام الأكاديمي لكلية العلوم الشرعية، المرفق. المادة الثانية يلغى كل ما يخالف هذا القرار، أو يتعارض مع أحكامه. المادة الثالثة ينشر هذا القرار في الجريدة الرسمية، ويعمل به من اليوم التالي لتاريخ نشره.
Num Articles: 3
Word Count Articles: 42
avg_words_per_article: 13
articles: المادة الأولى : يعمل بأحكام النظام الأكاديمي لكلية العلوم الشرعية، المرفق.
----------------
المادة الثانية : يلغى كل ما يخالف هذا القرار، أو يتعارض مع أحكامه.
----------------
المادة الثالثة : ينشر هذا القرار في الجريدة الرسمية، ويعمل به من اليوم التالي لتاريخ نشره.
--------------------------------------------------------------------------------
نمونه 4447:
Text: نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على النظام الأساسي للدولة الصادر بالمرسوم السلطاني رقم ١٠١ / ٩٦، وعلى المرسوم السلطاني رقم ٣ / ٢٠٠٨ بتحديد اختصاصات وزارة الإسكان واعتماد هيكلها التنظيمي، وعلى المرسوم السلطاني رقم ٣٢ / ٢٠١٢ بإسناد بعض الاختصاصات، وبناء على ما تقتضيه المصلحة العامة. رسمنا بما هو آت المادة الأولى تحدد اختصاصات وزارة الإسكان وفقا للملحق رقم (١) المرفق. المادة الثانية يعتمد الهيكل التنظيمي لوزارة الإسكان وفقا للملحق رقم (٢) المرفق. المادة الثالثة يلغى المرسوم السلطاني رقم ٣ / ٢٠٠٨ المشار إليه، كما يلغى كل ما يخالف هذا المرسوم، أو يتعارض مع أحكامه. المادة الرابعة ينشر هذا المرسوم في الجريدة الرسمية، ويعمل به من اليوم التالي لتاريخ نشره.
Num Articles: 4
Word Count Articles: 67
avg_words_per_article: 16
articles: المادة الأولى : تحدد اختصاصات وزارة الإسكان وفقا للملحق رقم (١) المرفق.
----------------
المادة الثانية : يعتمد الهيكل التنظيمي لوزارة الإسكان وفقا للملحق رقم (٢) المرفق.
----------------
المادة الثالثة : يلغى المرسوم السلطاني رقم ٣ / ٢٠٠٨ المشار إليه، كما يلغى كل ما يخالف هذا المرسوم، أو يتعارض مع أحكامه.
----------------
المادة الرابعة : ينشر هذا المرسوم في الجريدة الرسمية، ويعمل به من اليوم التالي لتاريخ نشره.
--------------------------------------------------------------------------------
نمونه 4677:
Text: استنادا إلى قانون السجل التجاري الصادر بالمرسوم السلطاني رقم ٣ / ٧٤، وإلى قانون التجارة الصادر بالمرسوم السلطاني رقم ٥٥ / ٩٠، وإلى المرسوم السلطاني رقم ١٠٢ / ٢٠٠٥ بتحديد اختصاصات وزارة التجارة والصناعة واعتماد هيكلها التنظيمي، وإلى اللائحة التنفيذية لقانون السجل التجاري الصادرة بالقرار الوزاري رقم ١٢١ / ٨٦، وإلى موافقة وزارة المالية، وبناء على ما تقتضيه المصلحة العامة. تقرر المادة الأولى يعمل في شأن تنظيم أعمال الباعة المتجولين بأحكام اللائحة المرفقة. المادة الثانية على الباعة المتجولين توفيق أوضاعهم طبقا لأحكام اللائحة المرفقة خلال (٦) ستة أشهر من تاريخ العمل بها. المادة الثالثة يلغى كل ما يخالف اللائحة المرفقة، أو يتعارض مع أحكامها. المادة الرابعة ينشر هذا القرار في الجريدة الرسمية، ويعمل به من اليوم التالي لتاريخ نشره.
Num Articles: 4
Word Count Articles: 65
avg_words_per_article: 15
articles: المادة الأولى : يعمل في شأن تنظيم أعمال الباعة المتجولين بأحكام اللائحة المرفقة.
----------------
المادة الثانية : على الباعة المتجولين توفيق أوضاعهم طبقا لأحكام اللائحة المرفقة خلال (٦) ستة أشهر من تاريخ العمل بها.
----------------
المادة الثالثة : يلغى كل ما يخالف اللائحة المرفقة، أو يتعارض مع أحكامها.
----------------
المادة الرابعة : ينشر هذا القرار في الجريدة الرسمية، ويعمل به من اليوم التالي لتاريخ نشره.
--------------------------------------------------------------------------------
نمونه 4832:
Text: استنادا إلى قانون سوق رأس المال الصادر بالمرسوم السلطاني رقم ٨٠ / ٩٨، وإلى اللائحة التنفيذية لقانون سوق رأس المال الصادرة بالقرار رقم ١ / ٢٠٠٩، وإلى لائحة تنظيم المقاصة والتسوية الصادرة بالقرار رقم ٥ / ٢٠١١، وإلى موافقة مجلس إدارة الهيئة العامة لسوق المال، وبناء على ما تقتضيه المصلحة العامة، تقرر المادة الأولى يستبدل بنص البند (١) من المادة (٥٥) من لائحة تنظيم المقاصة والتسوية المشار إليها، النص الآتي: البند (١) من المادة (٥٥) ١ – يجب على العميل المشتري تسديد قيمة الأوراق المالية للعضو المشتري بموجب شيك أو تحويل مصرفي أو تحويل من حساب زوجه أو أحد أقاربه من الدرجة الأولى، ويجوز له تسديد المبلغ نقدا إذا كانت القيمة لا تتجاوز (٢٠٠) مائتي ريال عماني. المادة الثانية يضاف بند جديد برقم (٦) إلى المادة (٥٥) من لائحة تنظيم المقاصة والتسوية المشار إليها، يكون نصه كالآتي: ٦ – يجوز للعضو التحويل النقدي بين حسابات العملاء الذين تجمع بينهم علاقة زوجية أو قرابة من الدرجة الأولى، شريطة وجود موافقة كتابية، وموقعة من قبل العميل المحول، أو وكيله القانوني لكل عملية تحويل. المادة الثالثة يلغى كل ما يخالف هذا القرار، أو يتعارض مع أحكامه. المادة الرابعة ينشر هذا القرار في الجريدة الرسمية، ويعمل به من اليوم التالي لتاريخ نشره.
Num Articles: 5
Word Count Articles: 155
avg_words_per_article: 30
articles: المادة الأولى : يستبدل بنص البند (١) من المادة (٥٥) من لائحة تنظيم المقاصة والتسوية المشار إليها، النص الآتي: البند (١) من المادة (٥٥) ١ – يجب على العميل المشتري تسديد قيمة الأوراق المالية للعضو المشتري بموجب شيك أو تحويل مصرفي أو تحويل من حساب زوجه أو أحد أقاربه من الدرجة الأولى، ويجوز له تسديد المبلغ نقدا إذا كانت القيمة لا تتجاوز (٢٠٠) مائتي ريال عماني.
----------------
المادة الثانية : يضاف بند جديد برقم (٦) إلى
----------------
المادة (٥٥) : من لائحة تنظيم المقاصة والتسوية المشار إليها، يكون نصه كالآتي: ٦ – يجوز للعضو التحويل النقدي بين حسابات العملاء الذين تجمع بينهم علاقة زوجية أو قرابة من الدرجة الأولى، شريطة وجود موافقة كتابية، وموقعة من قبل العميل المحول، أو وكيله القانوني لكل عملية تحويل.
----------------
المادة الثالثة : يلغى كل ما يخالف هذا القرار، أو يتعارض مع أحكامه.
----------------
المادة الرابعة : ينشر هذا القرار في الجريدة الرسمية، ويعمل به من اليوم التالي لتاريخ نشره.
--------------------------------------------------------------------------------
نمونه 3796:
Text: نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على النظام الأساسي للدولة الصادر بالمرسوم السلطاني رقم ١٠١ / ٩٦، وعلى قانون نزع الملكية للمنفعة العامة الصادر بالمرسوم السلطاني رقم ٦٤ / ٧٨، وبناء على ما تقتضيه المصلحة العامة. رسمنا بما هو آت المادة الأولى يعتبر مشروع إزالة وإعادة تخطيط مدينة روي بمحافظة مسقط المحدد في المذكرة والرسم التخطيطي الإجمالي المرفقين من مشروعات المنفعة العامة. المادة الثانية للجهات المختصة الاستيلاء بطريق التنفيذ المباشر على العقارات والأراضي اللازمة للمشروع وما عليها من منشآت طبقا لأحكام قانون نزع الملكية للمنفعة العامة المشار إليه. المادة الثالثة ينشر هذا المرسوم في الجريدة الرسمية، ويعمل به من تاريخ صدوره.
Num Articles: 3
Word Count Articles: 66
avg_words_per_article: 21
articles: المادة الأولى : يعتبر مشروع إزالة وإعادة تخطيط مدينة روي بمحافظة مسقط المحدد في المذكرة والرسم التخطيطي الإجمالي المرفقين من مشروعات المنفعة العامة.
----------------
المادة الثانية : للجهات المختصة الاستيلاء بطريق التنفيذ المباشر على العقارات والأراضي اللازمة للمشروع وما عليها من منشآت طبقا لأحكام قانون نزع الملكية للمنفعة العامة المشار إليه.
----------------
المادة الثالثة : ينشر هذا المرسوم في الجريدة الرسمية، ويعمل به من تاريخ صدوره.
--------------------------------------------------------------------------------

In [31]:
df_clean[['num_articles', 'word_count_articles', 'avg_words_per_article']].describe()

       num_articles  word_count_articles  avg_words_per_article
count   7102.000000          7102.000000            7102.000000
mean       4.191777           182.127992              29.431287
std       14.195364           953.851661              45.805649
min        1.000000            14.000000               8.000000
25%        2.000000            37.000000              15.000000
50%        3.000000            53.000000              19.000000
75%        4.000000            91.000000              26.000000
max      585.000000         29777.000000            1133.000000

In [32]:
#must be remove from df_clean
df_clean = df_clean[(df_clean['avg_words_per_article'] <= 100) & (df_clean['num_articles'] <= 10)]

In [33]:
article_q3 = df_clean[(df_clean['word_count_articles'] <= 200)]

# for i, row in article_q3.iterrows():
#     print("\n-----------------")
#     print("link:", row['canonical_link'])
#     print("Title:", row['title'])
#     print("Word count:", row['word_count'])
#     print("Text :")
#     print(row['text'])

print("-----------")
print("total  :", len(article_q3))

-----------
total  : 6352

In [34]:
article_q3[['num_articles', 'word_count_articles', 'avg_words_per_article']].describe()

       num_articles  word_count_articles  avg_words_per_article
count   6352.000000          6352.000000            6352.000000
mean       2.798489            60.431518              20.361933
std        1.016791            34.695296               9.078941
min        1.000000            14.000000               8.000000
25%        2.000000            35.000000              15.000000
50%        3.000000            49.000000              18.000000
75%        3.000000            74.000000              23.000000
max       10.000000           200.000000              99.000000

In [35]:
for i, row in article_q3.head(10).iterrows():
    print("-----------------")
    # print("link:", row['canonical_link'])
    # print("date:", row['date'])
    # print("Title:", row['title'])
    # print("title_semantic:", row['title_semantic'])
    print("Text after removing footer :")
    print(row['text'])
    print("PREAMBLE:")
    print(row['PREAMBLE'])
    print("articles:")
    print(row['articles'])
    # print("-" * 80)
    # print("footer:")
    # print(row['footer'])

-----------------
Text after removing footer :
نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على عقد تأسيس مكتب عمان الوطني للاستثمارات الهندسية والتخطيط العمراني المؤرخ في ١٤ يناير ١٩٧٤. قررنا المادة ١ الموافقة على تأسيس مكتب للاستثمارات الهندسية باسم “مكتب عمان الوطني للاستثمارات الهندسية والتخطيط العمراني”، ورخصنا له بمزاولة أعماله في السلطنة. المادة ٢ تدعيما للمكتب في مزاولة أعماله تسند إليه الدولة الدراسات التخطيطية الهندسية والمعمارية اللازمة لمشاريع السلطنة والإشراف على تنفيذها وذلك: أ) إما بالأمر المباشر، ب) وإما عن طريق المناقصات المحلية ويكون شأنه في ذلك شأن المكاتب الوطنية، ج) وإما بمنحه الأفضلية في الأحوال التي يستدعي فيها الأمر مناقصات عالمية وذلك ما لم تتجاوز أسعاره عن ١٠% من قيمة العطاءات الأخرى المقدمة. المادة ٣ ينشر هذا المرسوم في الجريدة الرسمية ويعتبر نافذا من تاريخ التوقيع عليه.
PREAMBLE:
نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على عقد تأسيس مكتب عمان الوطني للاستثمارات الهندسية والتخطيط العمراني المؤرخ في ١٤ يناير ١٩٧٤
articles:
المادة ١ : الموافقة على تأسيس مكتب للاستثمارات الهندسية باسم “مكتب عمان الوطني للاستثمارات الهندسية والتخطيط العمراني”، ورخصنا له بمزاولة أعماله في السلطنة.
----------------
المادة ٢ : تدعيما للمكتب في مزاولة أعماله تسند إليه الدولة الدراسات التخطيطية الهندسية والمعمارية اللازمة لمشاريع السلطنة والإشراف على تنفيذها وذلك: أ) إما بالأمر المباشر، ب) وإما عن طريق المناقصات المحلية ويكون شأنه في ذلك شأن المكاتب الوطنية، ج) وإما بمنحه الأفضلية في الأحوال التي يستدعي فيها الأمر مناقصات عالمية وذلك ما لم تتجاوز أسعاره عن ١٠% من قيمة العطاءات الأخرى المقدمة.
----------------
المادة ٣ : ينشر هذا المرسوم في الجريدة الرسمية ويعتبر نافذا من تاريخ التوقيع عليه.
-----------------
Text after removing footer :
نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على عقد تأسيس شركة المقاولات (شركة عمان الوطنية للمقاولات) المؤرخ في ١٤ يناير ١٩٧٤. رسمنا بما هو آت المادة ١ الموافقة على تأسيس شركة للمقاولات في عمان تسمى “شركة عمان الوطنية للمقاولات” المرافق عقدها لهذا المرسوم السلطاني والترخيص لها بمزاولة أعمالها. المادة ٢ تدعيما للشركة لمزاولة أعمالها تسند إليها الدولة بأعمال المقاولات: أ) إما بالأمر المباشر، ب) وإما عن طريق المناقصات المحلية ويكون شأنها في ذلك شأن الشركات الوطنية، ج) وإما بمنحها الأفضلية في إسناد المقاولة إليها في الأحوال التي يستدعي الأمر مناقصات عالمية وذلك ما لم تتجاوز أسعارها عن ١٠٪ من قيمة العطاءات الأخرى المقدمة. المادة ٣ ينشر هذا المرسوم في الجريدة الرسمية ويعتبر نافذا من تاريخ التوقيع عليه.
PREAMBLE:
نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على عقد تأسيس شركة المقاولات (شركة عمان الوطنية للمقاولات) المؤرخ في ١٤ يناير ١٩٧٤
articles:
المادة ١ : الموافقة على تأسيس شركة للمقاولات في عمان تسمى “شركة عمان الوطنية للمقاولات” المرافق عقدها لهذا المرسوم السلطاني والترخيص لها بمزاولة أعمالها.
----------------
المادة ٢ : تدعيما للشركة لمزاولة أعمالها تسند إليها الدولة بأعمال المقاولات: أ) إما بالأمر المباشر، ب) وإما عن طريق المناقصات المحلية ويكون شأنها في ذلك شأن الشركات الوطنية، ج) وإما بمنحها الأفضلية في إسناد المقاولة إليها في الأحوال التي يستدعي الأمر مناقصات عالمية وذلك ما لم تتجاوز أسعارها عن ١٠٪ من قيمة العطاءات الأخرى المقدمة.
----------------
المادة ٣ : ينشر هذا المرسوم في الجريدة الرسمية ويعتبر نافذا من تاريخ التوقيع عليه.
-----------------
Text after removing footer :
نحن قابوس بن سعيد سلطان عمان نظرا لما تقتضيه المصلحة العامة فقد قررنا إعادة تنظيم دائرة الحسابات والخزينة. رسمنا بما هو آت المادة ١ تسمى هذه الدائرة بدائرة المالية بدلا من دائرة الحسابات والخزينة. المادة ٢ تقع مسؤولة هذه الدائرة على مستشار الشؤون المالية. المادة ٣ تستقل دائرة تدقيق الحسابات عن دائرة المالية وتكون تحت مسؤولية وزارة شؤون الديوان السلطاني. المادة ٤ ينشر هذا المرسوم في الجريدة الرسمية.
PREAMBLE:
نحن قابوس بن سعيد سلطان عمان نظرا لما تقتضيه المصلحة العامة فقد قررنا إعادة تنظيم دائرة الحسابات والخزينة
articles:
المادة ١ : تسمى هذه الدائرة بدائرة المالية بدلا من دائرة الحسابات والخزينة.
----------------
المادة ٢ : تقع مسؤولة هذه الدائرة على مستشار الشؤون المالية.
----------------
المادة ٣ : تستقل دائرة تدقيق الحسابات عن دائرة المالية وتكون تحت مسؤولية وزارة شؤون الديوان السلطاني.
----------------
المادة ٤ : ينشر هذا المرسوم في الجريدة الرسمية.
-----------------
Text after removing footer :
بعد الاطلاع على قانون الجنسية العمانية رقم (١) لسنة ١٩٧٢ وبناء على ما عرضه معالي وزير الداخلية والعدل على صاحب الجلالة السلطان المعظم. فقد تقرر مايلي المادة ١ تعدل المادة ٢ فقرة ٣ من القانون كالآتي: أن يسبق طلبه إقامة فعلية متواصلة وشرعية في عمان لمدة لا تقل عن عشر سنوات ولا مانع من أن يترك البلد بين حين وآخر في مهماته الخاصة على أن لا تكون فترة غيابه في سنة تتجاوز الشهرين، أما إذا كان متزوجا بعمانية فتخفض مدة الإقامة إلى خمس سنين بعد الزواج. المادة ٢ ينشر هذا التعديل في الجريدة الرسمية.
PREAMBLE:
بعد الاطلاع على قانون الجنسية العمانية رقم (١) لسنة ١٩٧٢ وبناء على ما عرضه معالي وزير الداخلية والعدل على صاحب الجلالة السلطان المعظم
articles:
المادة ١ : تعدل
----------------
المادة ٢ : فقرة ٣ من القانون كالآتي: أن يسبق طلبه إقامة فعلية متواصلة وشرعية في عمان لمدة لا تقل عن عشر سنوات ولا مانع من أن يترك البلد بين حين وآخر في مهماته الخاصة على أن لا تكون فترة غيابه في سنة تتجاوز الشهرين، أما إذا كان متزوجا بعمانية فتخفض مدة الإقامة إلى خمس سنين بعد الزواج.
----------------
المادة ٢ : ينشر هذا التعديل في الجريدة الرسمية.
-----------------
Text after removing footer :
نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على اتفاقية تأسيس المصرف العربي الدولي للتجارة الخارجية والتنمية بين كل من سلطنة عمان وجمهورية مصر العربية والجمهورية العربية الليبية، والنظام الأساسي المرافق للاتفاقية والموقع عليها منا بتاريخ ٢٤ / ٩ / ١٩٧٣. قررنا المادة ١ التصديق على اتفاقية تأسيس المصرف العربي الدولي للتجارة الخارجية والتنمية والنظام الأساسي المرافق لها. المادة ٢ ينشر هذا المرسوم في الجريدة الرسمية ويعتبر نافذا ويعمل به من تاريخ نشره.
PREAMBLE:
نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على اتفاقية تأسيس المصرف العربي الدولي للتجارة الخارجية والتنمية بين كل من سلطنة عمان وجمهورية مصر العربية والجمهورية العربية الليبية، والنظام الأساسي المرافق للاتفاقية والموقع عليها منا بتاريخ ٢٤ / ٩ / ١٩٧٣
articles:
المادة ١ : التصديق على اتفاقية تأسيس المصرف العربي الدولي للتجارة الخارجية والتنمية والنظام الأساسي المرافق لها.
----------------
المادة ٢ : ينشر هذا المرسوم في الجريدة الرسمية ويعتبر نافذا ويعمل به من تاريخ نشره.
-----------------
Text after removing footer :
نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على اتفاقية تأسيس البنك العربي للتنمية الاقتصادية في أفريقيا بين حكومات الجامعة العربية والموقع عليها بتاريخ ١١ مارس ١٩٧٤. رسمنا بما هو آت المادة ١ التصديق على اتفاقية تأسيس البنك العربي للتنمية الاقتصادية في أفريقيا والنظام الأساسي المرافق لها. المادة ٢ ينشر هذا المرسوم في الجريدة الرسمية ويعتبر نافذا به من تاريخ نشره.
PREAMBLE:
نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على اتفاقية تأسيس البنك العربي للتنمية الاقتصادية في أفريقيا بين حكومات الجامعة العربية والموقع عليها بتاريخ ١١ مارس ١٩٧٤
articles:
المادة ١ : التصديق على اتفاقية تأسيس البنك العربي للتنمية الاقتصادية في أفريقيا والنظام الأساسي المرافق لها.
----------------
المادة ٢ : ينشر هذا المرسوم في الجريدة الرسمية ويعتبر نافذا به من تاريخ نشره.
-----------------
Text after removing footer :
نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على المادتين (٦) و (٦٠) من قانون السلكين الدبلوماسي والقنصلي رقم ٤٦ لسنة ١٩٧٣ الصادر في ٢٦ / ١٢ / ١٩٧٣، وبناء على ما عرضه علينا وزير الدولة للشؤون الخارجية. رسمنا بما هو آت المادة ١ يعين السيد / اسماعيل مبارك ابراهيم بدرجة سكرتير أول في وزارة الخارجية. المادة ٢ على وزير الدولة للشؤون الخارجية تنفيذ هذا المرسوم ويعمل به اعتبار من تاريخه وينشر في الجريدة الرسمية.
PREAMBLE:
نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على المادتين (٦) و (٦٠) من قانون السلكين الدبلوماسي والقنصلي رقم ٤٦ لسنة ١٩٧٣ الصادر في ٢٦ / ١٢ / ١٩٧٣، وبناء على ما عرضه علينا وزير الدولة للشؤون الخارجية
articles:
المادة ١ : يعين السيد / اسماعيل مبارك ابراهيم بدرجة سكرتير أول في وزارة الخارجية.
----------------
المادة ٢ : على وزير الدولة للشؤون الخارجية تنفيذ هذا المرسوم ويعمل به اعتبار من تاريخه وينشر في الجريدة الرسمية.
-----------------
Text after removing footer :
نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على المادتين (٦) و (٦٠) من قانون السلكين الدبلوماسي والقنصلي رقم ٤٦ لسنة ١٩٧٣ الصادر في ٢٦ / ١٢ / ١٩٧٣، وبناء على ما عرضه وزير الدولة للشؤون الخارجية. رسمنا بما هو آت المادة ١ يعين السيد / عبدالمنعم النكلاوي بدرجة مستشار في وزارة الخارجية. المادة ٢ على وزير الدولة للشؤون الخارجية تنفيذ هذا المرسوم ويعمل به اعتبارا من تاريخه وينشر في الجريدة الرسمية.
PREAMBLE:
نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على المادتين (٦) و (٦٠) من قانون السلكين الدبلوماسي والقنصلي رقم ٤٦ لسنة ١٩٧٣ الصادر في ٢٦ / ١٢ / ١٩٧٣، وبناء على ما عرضه وزير الدولة للشؤون الخارجية
articles:
المادة ١ : يعين السيد / عبدالمنعم النكلاوي بدرجة مستشار في وزارة الخارجية.
----------------
المادة ٢ : على وزير الدولة للشؤون الخارجية تنفيذ هذا المرسوم ويعمل به اعتبارا من تاريخه وينشر في الجريدة الرسمية.
-----------------
Text after removing footer :
نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على المادتين (٦) و (٦٠) من قانون السلكين الدبلوماسي والقنصلي رقم ٤٦ لسنة ١٩٧٣ الصادر في ٢٦ / ١٢ / ١٩٧٣، وبناء على ما عرضه وزير الدولة للشؤون الخارجية. رسمنا بما هو آت المادة ١ يعين السيد / مختار محمد الزواري بدرجة وزير مفوض في وزارة الخارجية. المادة ٢ على وزير الدولة للشؤون الخارجية تنفيذ هذا المرسوم ويعمل به من تاريخه وينشر في الجريدة الرسمية.
PREAMBLE:
نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على المادتين (٦) و (٦٠) من قانون السلكين الدبلوماسي والقنصلي رقم ٤٦ لسنة ١٩٧٣ الصادر في ٢٦ / ١٢ / ١٩٧٣، وبناء على ما عرضه وزير الدولة للشؤون الخارجية
articles:
المادة ١ : يعين السيد / مختار محمد الزواري بدرجة وزير مفوض في وزارة الخارجية.
----------------
المادة ٢ : على وزير الدولة للشؤون الخارجية تنفيذ هذا المرسوم ويعمل به من تاريخه وينشر في الجريدة الرسمية.
-----------------
Text after removing footer :
نحن قابوس بن سعيد سلطان عمان بناء على ما عرضه وزير الشؤون الاجتماعية والعمل ووافق عليه مجلس الوزراء. قررنا المادة ١ إجراء التعديلات الآتية في قانون العمل العماني الصادر بالمرسوم السلطاني رقم ٣٤ لسنة ١٩٧٣: مادة ٥٨ وتقرأ: لا يجوز لصاحب العمل أن يقتطع من أجر العامل أكثر من ١٠٪ وفاء لما يكون قد أقرضه من مال ولا يتقاضى عن هذا المال أية فائدة، وللوزير أن يعدل أحكام هذه المادة إذا كان صاحب العمل قد أدخل أو ينوي إدخال نظام قروض لإنشاء مساكن لعماله معتمد من قبل الوزارة أو إذا كان صاحب العمل أحد البنوك المعتمدة في السلطنة. مادة ٧٢ وتقرأ: يجب على صاحب العمل أن يمنح كل عامل راحة أسبوعية لا تقل عن أربع وعشرون ساعة متتالية. ويشترط للاستفادة من أجر الراحة الأسبوعية بالنسبة للعمال المعينين بغير الراتب الشهري، أن يكونوا قد عملوا مدة خمسة أيام متتالية في الأسبوع على الأقل ما لم يكن غيابهم لعذر مشروع ويجوز في الأماكن التي تحدد بقرار من الوزير تجميع الراحات الأسبوعية للعمال عن مدة لا تتجاوز ثمانية أسابيع إذا اتفق العمال وأصحاب الأعمال على ذلك كتابة.
PREAMBLE:
نحن قابوس بن سعيد سلطان عمان بناء على ما عرضه وزير الشؤون الاجتماعية والعمل ووافق عليه مجلس الوزراء
articles:
المادة ١ : إجراء التعديلات الآتية في قانون العمل العماني الصادر بالمرسوم السلطاني رقم ٣٤ لسنة ١٩٧٣:
----------------
مادة ٥٨ : وتقرأ: لا يجوز لصاحب العمل أن يقتطع من أجر العامل أكثر من ١٠٪ وفاء لما يكون قد أقرضه من مال ولا يتقاضى عن هذا المال أية فائدة، وللوزير أن يعدل أحكام هذه المادة إذا كان صاحب العمل قد أدخل أو ينوي إدخال نظام قروض لإنشاء مساكن لعماله معتمد من قبل الوزارة أو إذا كان صاحب العمل أحد البنوك المعتمدة في السلطنة.
----------------
مادة ٧٢ : وتقرأ: يجب على صاحب العمل أن يمنح كل عامل راحة أسبوعية لا تقل عن أربع وعشرون ساعة متتالية. ويشترط للاستفادة من أجر الراحة الأسبوعية بالنسبة للعمال المعينين بغير الراتب الشهري، أن يكونوا قد عملوا مدة خمسة أيام متتالية في الأسبوع على الأقل ما لم يكن غيابهم لعذر مشروع ويجوز في الأماكن التي تحدد بقرار من الوزير تجميع الراحات الأسبوعية للعمال عن مدة لا تتجاوز ثمانية أسابيع إذا اتفق العمال وأصحاب الأعمال على ذلك كتابة.

In [36]:
data_1 = df_clean[(df_clean['word_count_articles'] <= 200)].copy()
len(data_1)

6352

In [37]:
import re

def create_full_chunk(row):
    # 1. دریافت مقادیر و تبدیل به رشته (برای جلوگیری از خطای None)
    title = str(row.get('title', '')).strip()  #
    topic = str(row.get('title_semantic', '')).strip()
    preamble = str(row.get('PREAMBLE', '')).strip()
    raw_articles = str(row.get('articles', '')).strip()

    # 2. پاکسازی بخش مواد (Articles Cleaning)
    # این دستور تمام خطوطی که فقط شامل خط تیره هستند را با دو اینتر جایگزین می‌کند
    # پترن: \n (شروع خط جدید) + خط تیره‌های متوالی + \n (پایان خط)
    clean_articles = re.sub(r'\n\s*-+\s*\n', '\n\n', raw_articles)

    # 3. ساخت قالب نهایی
    chunk_text = (
        f"[TITLE]\n{title}\n\n"
        f"[TOPIC]\n{topic}\n\n"
        f"[PREAMBLE]\n{preamble}\n\n"
        f"[ARTICLES]\n{clean_articles}"
    )

    return chunk_text


data_1['chunks'] = data_1.apply(create_full_chunk, axis=1)
print(data_1['chunks'].iloc[10])

[TITLE]
مرسوم سلطاني رقم ٣٨ / ٧٤ بشأن استبدال جميع وحدات الوزن المستعملة في السلطنة بنظام الجرام والكيلوجرام والطن

[TOPIC]
مرسوم | استبدال | جميع وحدات الوزن المستعملة في السلطنة بنظام الجرام والكيلوجرام والطن

[PREAMBLE]
نحن قابوس بن سعيد سلطان عمان بناء على ما عرضه علينا وزير التنمية، وتحقيقا للمنفعة العامة، وتنظيمها لعمليات البيع والشراء وتمشيا مع القواعد العصرية للموازين

[ARTICLES]
المادة ١ : تستبدل جميع وحدات الوزن المستعملة حاليا في السلطنة بنظام الجرام والكيلوجرام والطن حيث يكون كل ألف جرام يساوي كيلوجرام واحد وكل ألف كيلوجرام يساوي طن واحد.

المادة ٢ : تصدر دائرة الضبط والجودة والمواصفات التابعة للمديرية العامة للصناعة بوزارة التنمية جميع قطع الوزن بالنظام الجديد المنصوص عليه أعلاه.

المادة ٣ : على جميع أصحاب الدكاكين والمحلات التجارية والمتعاملين بالوزن في كافة أنحاء السلطنة تطبيق استبدال الأوزان القديمة بواسطة البلديات المعنية أو مكاتب الولاة أو مركز الإرشاد الزراعي، في مدة أقصاها الخامس عشر من شهر نوفمبر (تشرين الثاني) سنة ١٩٧٤.

المادة ٤ : كل من يتعامل بعد هذا التاريخ بأية وحدة وزن غير المنصوص عليها في هذا المرسوم يعرض نفسه لعقوبة الحبس مدة لا تزيد عن شهر واحد أو بغرامة لا تقل عن مائة ريال عماني، أو بالعقوبتين معا.

المادة ٥ : على وزارة التنمية وبقية الدوائر المختصة مراعاة تطبيق هذا المرسوم كل في اختصاصه.

المادة ٦ : ينشر هذا المرسوم في الجريدة الرسمية ويسري مفعوله ابتداء من تاريخ نشره.

In [38]:
data_1['word_count_chunks'] = data_1['chunks'].apply(
    lambda x: len(x.split()) if isinstance(x, str) else 0
)

In [39]:
data_1['word_count_chunks'].describe()

count    6352.000000
mean      140.841310
std        49.533754
min        61.000000
25%       106.000000
50%       132.000000
75%       161.000000
max       770.000000
Name: word_count_chunks, dtype: float64

In [40]:
data_1[(data_1['word_count_chunks'] >= 300)]['word_count_chunks'].describe()

count     65.000000
mean     362.184615
std       76.777864
min      300.000000
25%      320.000000
50%      335.000000
75%      376.000000
max      770.000000
Name: word_count_chunks, dtype: float64

In [41]:
import tiktoken

enc = tiktoken.get_encoding("cl100k_base")

data_1['token_count'] = data_1['chunks'].apply(
    lambda x: len(enc.encode(x)) if isinstance(x, str) else 0
)

data_1['token_count'].describe()

count    6352.000000
mean      589.526134
std       217.237071
min       225.000000
25%       439.000000
50%       552.000000
75%       678.000000
max      3155.000000
Name: token_count, dtype: float64

In [42]:
data_1.iloc[0]

json_link                        https://qanoon.om/wp-json/wp/v2/posts/110
short_link                                        https://qanoon.om/?p=110
canonical_link                         https://qanoon.om/p/1974/rd1974002/
date                                                   1974-01-14 00:00:00
title                    مرسوم سلطاني رقم ٢ / ٧٤ بالموافقة على تأسيس مك...
text                     نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على ع...
html                     <p><a class="pdf-link" href="http://data.qanoo...
error                                                                  NaN
text_word_count                                                        122
title_word_count                                                        16
title_semantic           مرسوم | تصديق | علي انشاء مكتب عمان الوطني للا...
footer                   صدر في: ٣٠ ذي الحجة ١٣٩٣هـ الموافق: ١٤ يناير ١...
articles                 المادة ١ : الموافقة على تأسيس مكتب للاستثمارات...
num_articles                                                             3
word_count_articles                                                    103
avg_words_per_article                                                   33
PREAMBLE                 نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على ع...
chunks                   [TITLE]\nمرسوم سلطاني رقم ٢ / ٧٤ بالموافقة على...
word_count_chunks                                                      157
token_count                                                            674
Name: 19, dtype: object

In [43]:
data_1[(data_1['token_count'] > 700)][['token_count','num_articles']].describe()

       token_count  num_articles
count  1424.000000   1424.000000
mean    902.419242      3.682584
std     213.490229      1.336689
min     701.000000      1.000000
25%     762.000000      3.000000
50%     841.000000      3.000000
75%     969.250000      4.000000
max    3155.000000     10.000000

In [44]:
data_2 = data_1[(data_1['token_count'] > 700)].copy()

In [45]:
print(data_2.iloc[10]['chunks'])

[TITLE]
مرسوم سلطاني رقم ٣١ / ٧٥ بإجراء تنقلات بين بعض السفراء العمانيين المعتمدين في الخارج

[TOPIC]
مرسوم | None |  تنقلات بين بعض السفراء العمانيين المعتمدين في الخارج

[PREAMBLE]
نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على المادتين (١٠)، (١٤) من قانون السلكين الدبلوماسي والقنصلي رقم ٥٠ / ٧٤، الصادر بتاريخ ٧ / ١٢ / ١٩٧٤، وبناء على ما عرضه علينا وزير الدولة للشؤون الخارجية

[ARTICLES]
المادة ١ : ينقل السفير السيد / شبيب بن تيمور آل سعيد من سفارتنا لدى جمهورية باكستان الإسلامية ويعين سفيرا فوق العادة ومفوضا لسلطنة عمان لدى المملكة المغربية.

المادة ٢ : ينقل السفير / سالم محمد الغيلاني من الديوان العام لوزارة الخارجية ويعين سفيرا فوق العادة مفوضا لسلطنة عمان لدى جمهورية باكستان الإسلامية.

المادة ٣ : ينقل السفير / ابراهيم بن حمد الحارثي من سفارتنا لدى جمهورية الجزائر الديمقراطية الشعبية ويعين سفيرا فوق العادة مفوضا لسلطنة عمان لدى المملكة العربية السعودية.

المادة ٤ : ينقل السفير / هلال بن علي الخليلي من سفارتنا لدى المملكة العربية السعودية إلى الديوان العام بوزارة الخارجية.

المادة ٥ : على وزير الدولة للشؤون الخارجية تنفيذ هذا المرسوم، ويعمل به اعتبارا من ١ / ٨ / ١٩٧٥ وينشر في الجريدة الرسمية.

In [46]:
import pandas as pd
import re

# فرض می‌کنیم تابعی برای شمارش دقیق توکن‌ها دارید، اگر نه از این تابع ساده استفاده کنید:
def count_tokens(text):
    # این را با متد اصلی خودتان (مثلاً tiktoken) جایگزین کنید
    return len(text.split())

def process_chunks(row):
    text = row['chunks']
    num_articles = row['num_articles']
    token_count = row['token_count']

    # ۱. استخراج بخش‌های ثابت (Header) و بخش بدنه (Articles)
    # با استفاده از Regex بخش‌ها را جدا می‌کنیم
    header_pattern = r"(\[TITLE\].*?\[TOPIC\].*?\[PREAMBLE\].*?)\n\s*\[ARTICLES\]"
    match = re.search(header_pattern, text, re.DOTALL)

    if not match:
        return [text] # اگر ساختار یافت نشد کل متن را برگردان

    header = match.group(1)
    articles_section = text.split("[ARTICLES]")[-1].strip()

    # جدا کردن ماده‌ها (با فرض اینکه با دو اینتر یا خط خالی جدا شده‌اند)
    articles_list = [a.strip() for a in articles_section.split('\n\n') if a.strip()]

    final_chunks = []

    # منطق شرطی شما:

    # --- حالت اول: num_articles >= 3 ---
    if num_articles >= 3:
        i = 0
        while i < len(articles_list):
            current_art = articles_list[i]
            # بررسی اینکه آیا می‌توانیم ماده بعدی را هم در این چانک جا دهیم (شرط زیر ۷۰۰ توکن)
            if i + 1 < len(articles_list):
                combined_two = current_art + "\n\n" + articles_list[i+1]
                full_test_text = f"{header}\n\n[ARTICLES]\n{combined_two}"

                if count_tokens(full_test_text) <= 700:
                    final_chunks.append(full_test_text)
                    i += 2 # دو ماده مصرف شد
                else:
                    final_chunks.append(f"{header}\n\n[ARTICLES]\n{current_art}")
                    i += 1 # یک ماده مصرف شد
            else:
                final_chunks.append(f"{header}\n\n[ARTICLES]\n{current_art}")
                i += 1

    # --- حالت دوم: num_articles == 2 ---
    elif num_articles == 2:
        for art in articles_list:
            final_chunks.append(f"{header}\n\n[ARTICLES]\n{art}")

    # --- حالت سوم: num_articles == 1 ---
    elif num_articles == 1:
        if token_count <= 900:
            final_chunks.append(text)
        else:
            # تقسیم داخلی ماده بر اساس پاراگراف (Paragraph-level)
            paragraphs = [p.strip() for p in articles_list[0].split('\n') if p.strip()]
            temp_para_group = ""
            for p in paragraphs:
                test_para = (temp_para_group + "\n" + p).strip()
                full_test_text = f"{header}\n\n[ARTICLES]\n{test_para}"

                # اینجا حد آستانه را مثلا ۶۰۰ توکن می‌گیریم که چانک‌ها خیلی بزرگ نشوند
                if count_tokens(full_test_text) <= 700:
                    temp_para_group = test_para
                else:
                    if temp_para_group:
                        final_chunks.append(f"{header}\n\n[ARTICLES]\n{temp_para_group}")
                    temp_para_group = p
            if temp_para_group:
                final_chunks.append(f"{header}\n\n[ARTICLES]\n{temp_para_group}")

    else:
        final_chunks.append(text)

    return final_chunks

# اعمال تابع روی دیتافریم
data_2['chunks'] = data_2.apply(process_chunks, axis=1)

# باز کردن لیست به ردیف‌های جداگانه (Explode)
data_2 = data_2.explode('chunks').reset_index(drop=True)

# به‌روزرسانی تعداد توکن‌های جدید برای هر چانک
data_2['token_count'] = data_2['chunks'].apply(count_tokens)

# نمایش نتیجه
print(data_2[['chunks', 'token_count']].head())

                                              chunks  token_count
0  [TITLE]\nمرسوم سلطاني رقم ٣٧ / ٧٤ بتعديل بعض م...          122
1  [TITLE]\nمرسوم سلطاني رقم ٣٧ / ٧٤ بتعديل بعض م...          118
2  [TITLE]\nمرسوم سلطاني رقم ٣٨ / ٧٤ بشأن استبدال...          112
3  [TITLE]\nمرسوم سلطاني رقم ٣٨ / ٧٤ بشأن استبدال...          141
4  [TITLE]\nمرسوم سلطاني رقم ٣٨ / ٧٤ بشأن استبدال...           92

In [47]:
# ۱. پردازش data_2 (طبق کد قبلی)
data_2['split_chunks'] = data_2.apply(process_chunks, axis=1)
data_final_long = data_2.explode('split_chunks').reset_index(drop=True)
data_final_long['new_token_count'] = data_final_long['split_chunks'].apply(count_tokens)

# ۲. آماده‌سازی بخش Long برای ادغام
# حذف ستون‌های قدیمی و جایگزینی با مقادیر جدید
data_final_long = data_final_long.drop(columns=['chunks', 'token_count'])
data_final_long = data_final_long.rename(columns={'split_chunks': 'chunks', 'new_token_count': 'token_count'})

# ۳. استخراج بخش Short از دیتافریم اصلی
df_short = data_1[data_1['token_count'] <= 700].copy()

# ۴. مرج نهایی
df_final = pd.concat([df_short, data_final_long], ignore_index=True)

# نمایش نتیجه نهایی
print(f"تعداد ردیف‌های اولیه: {len(data_1)}")
print(f"تعداد ردیف‌های نهایی: {len(df_final)}")

تعداد ردیف‌های اولیه: 6352
تعداد ردیف‌های نهایی: 8141

In [48]:
df_final.head()

,json_link,short_link,canonical_link,date,title,text,html,error,text_word_count,title_word_count,title_semantic,footer,articles,num_articles,word_count_articles,avg_words_per_article,PREAMBLE,chunks,word_count_chunks,token_count
0,https://qanoon.om/wp-json/wp/v2/posts/110,https://qanoon.om/?p=110,https://qanoon.om/p/1974/rd1974002/,1974-01-14,مرسوم سلطاني رقم ٢ / ٧٤ بالموافقة على تأسيس مك...,نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على ع...,"<p><a class=""pdf-link"" href=""http://data.qanoo...",NaN,122,16,مرسوم | تصديق | علي انشاء مكتب عمان الوطني للا...,صدر في: ٣٠ ذي الحجة ١٣٩٣هـ الموافق: ١٤ يناير ١...,المادة ١ : الموافقة على تأسيس مكتب للاستثمارات...,3,103,33,نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على ع...,[TITLE]\nمرسوم سلطاني رقم ٢ / ٧٤ بالموافقة على...,157,674
1,https://qanoon.om/wp-json/wp/v2/posts/111,https://qanoon.om/?p=111,https://qanoon.om/p/1974/rd1974003/,1974-01-14,مرسوم سلطاني رقم ٣ / ٧٤ بالموافقة على تأسيس “ش...,نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على ع...,"<p><a class=""pdf-link"" href=""http://data.qanoo...",NaN,118,13,مرسوم | تصديق | علي انشاء “شركة عمان الوطنية ل...,صدر في: ٢٠ ذي الحجة ١٣٩٣هـ الموافق: ١٤ يناير ١...,المادة ١ : الموافقة على تأسيس شركة للمقاولات ف...,3,97,31,نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على ع...,[TITLE]\nمرسوم سلطاني رقم ٣ / ٧٤ بالموافقة على...,144,599
2,https://qanoon.om/wp-json/wp/v2/posts/114,https://qanoon.om/?p=114,https://qanoon.om/p/1974/rd1974006/,1974-02-12,مرسوم سلطاني رقم ٦ / ٧٤ بخصوص إعادة تنظيم دائر...,نحن قابوس بن سعيد سلطان عمان نظرا لما تقتضيه ا...,"<p><a class=""pdf-link"" href=""http://data.qanoo...",NaN,68,12,مرسوم | تنظيم | اعادة تنظيم دائرة الحسابات وال...,صدر في: ١٩ محرم ١٣٩٤هـ الموافق: ١٢ فبراير ١٩٧٤...,المادة ١ : تسمى هذه الدائرة بدائرة المالية بدل...,4,53,12,نحن قابوس بن سعيد سلطان عمان نظرا لما تقتضيه ا...,[TITLE]\nمرسوم سلطاني رقم ٦ / ٧٤ بخصوص إعادة ت...,93,383
3,https://qanoon.om/wp-json/wp/v2/posts/116,https://qanoon.om/?p=116,https://qanoon.om/p/1974/rd1974011/,1974-03-12,مرسوم سلطاني رقم ١١ / ٧٤ بتعديل الفقرة (٣) من ...,بعد الاطلاع على قانون الجنسية العمانية رقم (١)...,"<p><a class=""pdf-link"" href=""http://data.qanoo...",NaN,94,20,مرسوم | تعديل | الفقرة من المادة من قانون الجن...,صدر في: ١٧ صفر ١٣٩٤هـ الموافق: ١٢ مارس ١٩٧٤م ح...,المادة ١ : تعدل\n----------------\nالمادة ٢ : ...,3,73,23,بعد الاطلاع على قانون الجنسية العمانية رقم (١)...,[TITLE]\nمرسوم سلطاني رقم ١١ / ٧٤ بتعديل الفقر...,132,494
4,https://qanoon.om/wp-json/wp/v2/posts/117,https://qanoon.om/?p=117,https://qanoon.om/p/1974/rd1974014/,1974-03-14,مرسوم سلطاني رقم ١٤ / ٧٤ بالتصديق على اتفاقية ...,نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على ا...,"<p><a class=""pdf-link"" href=""http://data.qanoo...",NaN,73,20,مرسوم | تصديق | علي اتفاقية انشاء المصرف الدول...,صدر في: ٢٠ صفر١٣٩٤هـ الموافق: ١٤ مارس ١٩٧٤م قا...,المادة ١ : التصديق على اتفاقية تأسيس المصرف ال...,2,34,16,نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على ا...,[TITLE]\nمرسوم سلطاني رقم ١٤ / ٧٤ بالتصديق على...,115,483

In [49]:
df_final['token_count'].describe()

count    8141.000000
mean      362.615281
std       190.773342
min        52.000000
25%       161.000000
50%       385.000000
75%       534.000000
max       770.000000
Name: token_count, dtype: float64

In [50]:
print(df_final.iloc[10]['chunks'])

[TITLE]
مرسوم سلطاني رقم ٤١ / ٧٤ بتشكيل مجلس للتنمية

[TOPIC]
مرسوم | تشكيل | مجلس للتنمية

[PREAMBLE]
نحن قابوس بن سعيد سلطان عمان نظرا لما تقتضيه المصلحة العامة ونظرا لما للتنمية من أهمية بالغة

[ARTICLES]
المادة ١ : تشكيل مجلس للتنمية برئاستنا وعضوية كل من: وزير الدولة للشؤون الخارجية مساعدا وزير الداخلية عضوا وزير الصحة عضوا وزير المواصلات عضوا وزير التجارة والصناعة عضوا وزير الزراعة والأسماك والنفط والمعادن عضوا مندوبا عن المالية عضوا

المادة ٢ : ينشر هذا المرسوم في الجريدة الرسمية ويعمل به من تاريخه.

In [51]:
print(df_final.iloc[0])

json_link                        https://qanoon.om/wp-json/wp/v2/posts/110
short_link                                        https://qanoon.om/?p=110
canonical_link                         https://qanoon.om/p/1974/rd1974002/
date                                                   1974-01-14 00:00:00
title                    مرسوم سلطاني رقم ٢ / ٧٤ بالموافقة على تأسيس مك...
text                     نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على ع...
html                     <p><a class="pdf-link" href="http://data.qanoo...
error                                                                  NaN
text_word_count                                                        122
title_word_count                                                        16
title_semantic           مرسوم | تصديق | علي انشاء مكتب عمان الوطني للا...
footer                   صدر في: ٣٠ ذي الحجة ١٣٩٣هـ الموافق: ١٤ يناير ١...
articles                 المادة ١ : الموافقة على تأسيس مكتب للاستثمارات...
num_articles                                                             3
word_count_articles                                                    103
avg_words_per_article                                                   33
PREAMBLE                 نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على ع...
chunks                   [TITLE]\nمرسوم سلطاني رقم ٢ / ٧٤ بالموافقة على...
word_count_chunks                                                      157
token_count                                                            674
Name: 0, dtype: object

In [52]:
df_final.columns.to_list()

['json_link',
 'short_link',
 'canonical_link',
 'date',
 'title',
 'text',
 'html',
 'error',
 'text_word_count',
 'title_word_count',
 'title_semantic',
 'footer',
 'articles',
 'num_articles',
 'word_count_articles',
 'avg_words_per_article',
 'PREAMBLE',
 'chunks',
 'word_count_chunks',
 'token_count']

In [53]:
df_final["year"] = df_final["date"].dt.year
df_final["id"] = (
    "rd"
    + df_final["year"].astype(str)
    + df_final.groupby("year").cumcount().add(1).astype(str).str.zfill(3)
)

In [54]:
n_samples = 200
random_samples = df_final.sample(n=n_samples)
for i, row in random_samples.head(300).iterrows():
    # print("link:", row['canonical_link'])
    # print("date:", row['date'])
    print("Title:", row['title'])
    # print("title_semantic:", row['title_semantic'])
    # print("Text after removing footer :")
    # print(row['text'])
    # print("PREAMBLE:")
    # print(row['PREAMBLE'])
    # print("articles:")
    # print(row['articles'])
    # print("-" * 80)
    # print("footer:")
    # print(row['footer'])

Title: مرسوم سلطاني رقم ١٠٩ / ٢٠٠٦ بالتصديق على اتفاقية التجارة الحرة بين حكومة سلطنة عمان وحكومة الولايات المتحدة الأمريكية
Title: وزارة القوى العاملة: قرار وزاري رقم ١ / ٢٠١٤ بتشكيل لجنة لبحث المطالب العمالية
Title: مرسوم سلطاني رقم ٧٤ / ٢٠٠٠ بتعديل الهيكل التنظيمي لوزارة التربية والتعليم
Title: وزارة الثروة الزراعية والسمكية وموارد المياه: قرار وزاري رقم ٢ / ٢٠٢٥ بتحديد الجزاءات الإدارية على المخالفين لقانون مزاولة المهن الطبية البيطرية واللوائح والقرارات الصادرة تنفيذا له
Title: مرسوم سلطاني رقم ٣٩ / ٨٥ بمنح امتيازات لبنك عمان للزراعة والأسماك
Title: وزارة الأوقاف والشؤون الدينية: قرار وزاري رقم ٥٥٧ / ٢٠٢٠ بإصدار اللائحة التنظيمية لشؤون الحج
Title: مرسوم سلطاني رقم ١ / ٢٠١٦ باعتماد خطة التنمية الخمسية التاسعة ٢٠١٦-٢٠٢٠م
Title: وزارة القوى العاملة: قرار وزاري رقم ٢٨٩ / ٢٠١٧ بإيقاف التصريح باستقدام القوى العاملة غير العمانية بصفة مؤقتة في نشاط مراكز تنمية المهارات الذهنية
Title: وزارة التجارة والصناعة: قرار وزاري رقم ٩٥ / ٩٦ بإلغاء القرار الوزاري رقم ١٢٨ / ٩٥
Title: الهيئة العامة للمخازن والاحتياطي الغذائي: قرار رقم ٨ / ٢٠١٨ بإصدار لائحة المناقصات للهيئة العامة للمخازن والاحتياطي الغذائي
Title: مرسوم سلطاني رقم ١٤ / ٢٠٢١ بإجراء ترقيات وتعيينات عسكرية
Title: وزارة النقل والاتصالات وتقنية المعلومات: قرار وزاري رقم ٤٢٣ / ٢٠٢٤ بإصدار لائحة أمن السفن والموانئ
Title: وزارة التجارة والصناعة: قرار وزاري رقم ٥١ / ٨٦ بتجديد قيد شركة الخليج للتأمين
Title: مرسوم سلطاني رقم ١٤ / ٧٦ بتغيير اسم “وزارة التراث العماني” باسم “وزارة التراث القومي”
Title: مرسوم سلطاني رقم ٣١ / ٩٩ بإجازة تنازل شركة توتال اكسبلوريشن عمان عن جزء من حقوقها والتزاماتها في الاتفاقية النفطية الموقعة بتاريخ ٩ يوليو ١٩٩٥
Title: مرسوم سلطاني رقم ١١ / ٩٠ بتحديد اختصاصات وزارة البيئة وتعديل هيكلها التنظيمي
Title: مرسوم سلطاني رقم ٢٦ / ٢٠٠٤ بتعديل ملحق أحكام تأسيس شركة عمان والإمارات للاستثمار (القابضة) ش.م.ع.ع المرافق للمرسوم السلطاني رقم ١٠ / ٩٣
Title: وزارة الإسكان والتخطيط العمراني: قرار وزاري رقم ٤٩ / ٢٠٢٣ بإصدار اللائحة التنظيمية لتقديم وزارة الإسكان والتخطيط العمراني بعض خدماتها من خلال المكاتب الهندسية ومكاتب الاستشارات الهندسية
Title: الهيئة العامة لحماية المستهلك: قرار رقم ٢٥٣ / ٢٠١٥ بتعديل القرار رقم ١٢ / ٢٠١١ بشأن حظر رفع أسعار السلع والخدمات
Title: مرسوم سلطاني رقم ١٠٩ / ٨١ بتفويض وزير المواصلات بالتوقيع نيابة عن جلالة السلطان على اتفاقية الخدمات الجوية بين حكومة سلطنة عمان وحكومة جمهورية الصومال الديمقراطية
Title: مرسوم سلطاني رقم ١ / ٧٨ باختصاصات المديرية العامة للمواصفات والمقاييس بوزارة التجارة والصناعة
Title: مرسوم سلطاني رقم ٤١ / ٨٣ بتعيين عضوين بمجلس إدارة شركة الأسماك الوطنية العمانية ممثلين لحصة حكومة السلطنة فيها
Title: مرسوم سلطاني رقم ٥٣ / ٩٠ بتجديد عضوية بمجلس محافظي البنك المركزي العماني
Title: مرسوم سلطاني رقم ٤١ / ٩٩ بإصدار نظام الجامعات الخاصة
Title: مرسوم سلطاني رقم ٣٦ / ٢٠١٦ بالتصديق على اتفاقية بين حكومة سلطنة عمان وحكومة جمهورية البرازيل الاتحادية حول الإعفاء المتبادل من التأشيرة لحاملي جوازات السفر الدبلوماسية والخاصة والرسمية والخدمة
Title: مرسوم سلطاني رقم ٧٣ / ٨١ بتقرير صفة المنفعة العامة لمشروع طريق ضنك
Title: مرسوم سلطاني رقم ١٦ / ٨١ بنقل رئيس شؤون القبائل بوزارة شؤون الديوان السلطاني إلى الدرجة المالية الأولى من الحلقة الأولى من الجدول العام
Title: مرسوم سلطاني رقم ١ / ٢٠٢١ باعتماد خطة التنمية الخمسية العاشرة ٢٠٢١-٢٠٢٥م
Title: مرسوم سلطاني رقم ٧٧ / ٨٩ بإصدار قانون ضريبة الأرباح على المؤسسات التجارية والصناعية
Title: هيئة البيئة: قرار رقم ١٨٧ / ٢٠٢٤ بتعديل بعض أحكام لائحة تنظيم التصاريح البيئية
Title: هيئة تنظيم الاتصالات: قرار رقم ٤١ / ٢٠١٤ بإصدار لائحة تقديم خدمات الاتصالات لذوي الإعاقة
Title: وزارة الزراعة والثروة السمكية: قرار وزاري رقم ٣٨ / ٢٠١٨ بحظر استيراد الطيور الحية من جمهورية العراق
Title: مرسوم سلطاني رقم ٨٠ / ٢٠٢٣ في شأن الإعفاء من الضرائب
Title: وزارة الثروة الزراعية والسمكية وموارد المياه: قرار وزاري رقم ٢٤١ / ٢٠٢٥ بحظر استيراد المياه المعبأة ومنتجاتها من الجمهورية الإسلامية الإيرانية
Title: المجلس العماني للاختصاصات الطبية: قرار رقم ١٤ / ٢٠٢٥ بتعديل بعض أحكام لائحة التدريب في المجلس العماني للاختصاصات الطبية
Title: مرسوم سلطاني رقم ٨٧ / ٨٤ بإصدار قانون الضمان الاجتماعي
Title: مرسوم سلطاني رقم ٣٤ / ٢٠١٨ برد الجنسية العمانية
Title: وزارة الزراعة والثروة السمكية: قرار وزاري رقم ٢٥٦ / ٢٠١٨ بحظر استيراد الطيور الحية من بعض الدول
Title: مرسوم سلطاني رقم ٦١ / ٩٨ بنقل موظف إلى وزارة الخارجية ومنحه لقب سفير
Title: مرسوم سلطاني رقم ٦١ / ٢٠١٠ بمنح الدرجة الخاصة
Title: مرسوم سلطاني رقم ٧٨ / ٢٠١١ بتعيين مستشار للشؤون المحلية بوزارة الداخلية
Title: بلدية مسقط: قرار رقم ١٥١ / ٢٠١٦ بإصدار لائحة تنظيم استخدام المواقف العامة
Title: هيئة المنطقة الاقتصادية الخاصة بالدقم: قرار رقم ٣٢٣ / ٢٠١٥ بإصدار لائحة تنظيم البيئة الاستثمارية في المنطقة الاقتصادية الخاصة بالدقم
Title: وزارة الزراعة والثروة السمكية: قرار وزاري رقم ٣١٢ / ٢٠١٤ بإصدار اللائحة التنظيمية للأسواق السمكية
Title: مرسوم سلطاني رقم ٣١ / ٢٠٠٨ بتقرير صفة المنفعة العامة لمشروع إعادة تخطيط منطقة الخلوف بولاية محوت
Title: مرسوم سلطاني رقم ١٧ / ٨٣ بتفسير أحكام المرسوم السلطاني رقم ٣٩ / ٨٢
Title: وزارة التجارة والصناعة: قرار وزاري رقم ٣٥ / ٩٥ بتحديد رسم إصدار شهادة مطابقة للمواصفات القياسية
Title: مرسوم سلطاني رقم ١٥ / ٢٠١٢ بنقل موظف إلى وزارة الخارجية
Title: مرسوم سلطاني رقم ٦٨ / ٢٠٠٤ بتقرير صفة المنفعة العامة لأعمال شبكة التجميع والنقل اللازمة لمشاريع الصرف الصحي بكل من ولايات (صور، نزوى، خصب، البريمي)
Title: مرسوم سلطاني رقم ٤٢ / ٢٠١٨ في شأن الهيئة العامة للكهرباء والمياه
Title: وزارة الصحة: قرار وزاري رقم ١٢٤ / ٢٠١٥ بإصدار اللائحة التنظيمية للمؤسسات الصحية الخاصة لعلاج وتأهيل مرضى الإدمان على المخدرات والمؤثرات العقلية
Title: مرسوم سلطاني رقم ٥٨ / ٨٥ بإعادة تشكيل مجلس حماية البيئة ومكافحة التلوث
Title: مرسوم سلطاني رقم ١٣ / ٢٠١٩ بإجازة تنازل شركة النفط العمانية للاستكشاف والإنتاج ش.م.م عن ٥٠٪ من حقوقها والتزاماتها في الاتفاقية الموقعة بتاريخ ١١ أكتوبر ٢٠١١م للمنطقة رقم (٤٢) إلى شركة شل العمانية للاستكشاف والإنتاج بي في
Title: وزارة العمل: قرار وزاري رقم ٤٧٩ / ٢٠٢٢ بتعديل بعض أحكام اللائحة التنظيمية للجان الانتخابية للاتحاد العام لعمال سلطنة عمان
Title: مرسوم سلطاني رقم ٦ / ٢٠١٨ بإجازة تنازل شركة مول ويست عمان بي في – فرع عمان عن ٢٥٪ من حقوقها والتزاماتها في الاتفاقية النفطية الموقعة بتاريخ ٩ سبتمبر ٢٠١٢م للمنطقة رقم (٦٦) إلى شركة هايدروكربون فايندر إي آند بي ش.م.م
Title: مرسوم سلطاني رقم ٢١ / ٧٧ بتحديد اختصاصات وزارة الإعلام والثقافة فيما يتعلق بالشؤون الثقافية
Title: مرسوم سلطاني رقم ٢٩ / ٨٩ بتعديل بعض أحكام المرسوم السلطاني رقم ٤٧ / ٧٧ بإصدار قانون حماية الثروة الحيوانية والحجر البيطري
Title: مرسوم سلطاني رقم ١ / ٢٠٠٤ بالتصديق على الميزانية العامة للدولة للسنة المالية ٢٠٠٤م
Title: مرسوم سلطاني رقم ٨٢ / ٩٨ بتأسيس شركة مسقط للإيداع وتسجيل الأوراق المالية
Title: وزارة الزراعة والثروة السمكية: قرار وزاري رقم ٢٤٥ / ٢٠١٥ بشأن ضوابط إدخال الحشائش إلى محافظتي البريمي ومسندم عبر المنافذ الحدودية
Title: مرسوم سلطاني رقم ٥٧ / ٢٠٠٨ بتعديل جداول رواتب موظفي جامعة السلطان قابوس المرفقة بالمرسوم السلطاني رقم ١٠٢ / ٢٠٠٧
Title: مرسوم سلطاني رقم ٤٢ / ٢٠١٣ بإجازة تنازل شركة ماري بتروليوم ليمتد عن ٢٥٪ من حقوقها والتزاماتها في الاتفاقية النفطية الموقعة بتاريخ ٢٨ يونيو ٢٠٠٦م للمنطقة رقم (٤٣ب) إلى شركة حواسنة ليمتد لايابيليتي
Title: وزارة التجارة والصناعة: قرار وزاري رقم ٢٠٦ / ٢٠١٨ بتحديد رسوم بعض خدمات الملكية الصناعية لطلبة المدارس والكليات والجامعات والباحثين في المراكز البحثية والمؤسسات الصغيرة
Title: مرسوم سلطاني رقم ١ / ٢٠٢٤ بالتصديق على الميزانية العامة للدولة للسنة المالية ٢٠٢٤م
Title: مرسوم سلطاني رقم ٨٠ / ٢٠٠٣ بانضمام سلطنة عمان إلى اتفاقية منظمة السياحة العالمية
Title: مرسوم سلطاني رقم ٣٣ / ٢٠٠٢ بإصدار قانون السياحة
Title: مرسوم سلطاني رقم ٣٢ / ٢٠٠٥ بتعديل نظام معاشات ومكافآت ما بعد الخدمة لمنتسبي وزارة الدفاع وقوات السلطان المسلحة
Title: غرفة تجارة وصناعة عمان: قرار رقم ٢٢ / ٢٠٢٠ بتعديل بعض أحكام نظام عمل مركز عمان للتحكيم التجاري
Title: مرسوم سلطاني رقم ٥ / ٢٠١٠ بتقرير صفة المنفعة العامة لمشروع إزالة وإعادة تخطيط مدينة روي بمحافظة مسقط
Title: مرسوم سلطاني رقم ٤٣ / ٩١ بتعيين سفراء غير مقيمين
Title: هيئة تنظيم الاتصالات: قرار رقم ٢٥ / ٢٠٢١ بتعديل بعض أحكام الترخيص من الفئة الأولى للشركة العمانية القطرية للاتصالات (ش.م.ع.ع) لإنشاء وتشغيل نظام خدمات اتصالات عامة ثابتة
Title: مرسوم سلطاني رقم ٥٧ / ٢٠٢٢ بإعادة تنظيم اللجنة العمانية لحقوق الإنسان
Title: مرسوم سلطاني رقم ٤٧ / ٧٨ بمنح الجنسية العمانية لبعض الأشخاص ممن أدوا خدمات طويلة في القوات المسلحة
Title: مرسوم سلطاني رقم ٩٢ / ٩١ بتعيين ممثلي حصة الحكومة في مجلس إدارة شركة صلالة للفنادق
Title: وزارة الزراعة والثروة السمكية: قرار وزاري رقم ٢٠٩ / ٢٠١٩ بتعديل بعض أحكام لائحة دعم قطاع الثروة السمكية
Title: هيئة البيئة: قرار رقم ٦٥ / ٢٠٢٣ بتعديل بعض أحكام لائحة تنظيم تصدير المخلفات
Title: مرسوم سلطاني رقم ٥١ / ٨٢ بتفويض المندوب الدائم لسلطنة عمان لدى جامعة الدول العربية بالتوقيع على النظام الأساسي للمنظمة الإسلامية للتربية والثقافة والعلوم
Title: هيئة تنظيم الاتصالات: قرار رقم ٢٣ / ٢٠٢١ بتعديل بعض أحكام الترخيص من الفئة الأولى لشركة أواصر عمان وشركاؤهم (ش.م.ع.م) لإنشاء وتشغيل نظام خدمات اتصالات عامة ثابتة
Title: وزارة الشؤون الرياضية: قرار وزاري رقم ١٤٦ / ٢٠٢٠ بإشهار الاتحاد العماني لكرة الطاولة واعتماد نظامه الاساسي
Title: مرسوم سلطاني رقم ١٠٤ / ٢٠٠٥ بإنشاء مركز القبول الموحد
Title: مرسوم سلطاني رقم ١٦ / ٢٠٠٤ بإصدار قانون منح امتياز مرفق الصرف الصحي بمحافظة ظفار
Title: مرسوم سلطاني رقم ٤٩ / ٨١ بنقل وكيل شؤون الأراضي في وزارة شؤون الأراضي والبلديات وتعديل هيكلها التنظيمي
Title: وزارة المالية: قرار وزاري رقم ٨ / ٢٠١٨ بتعديل دليل تصنيف الميزانية العامة للدولة (الملحق رقم ١) المرفق باللائحة التنفيذية للقانون المالي
Title: مرسوم سلطاني رقم ٢٠ / ٢٠١٥ بإصدار القانون الموحد لمكافحة الإغراق والتدابير التعويضية والوقائية لدول مجلس التعاون لدول الخليج العربية
Title: مرسوم سلطاني رقم ٩٣ / ٨٦ بتعديل اسم المديرية العامة لموارد المياه والري بوزارة الزراعة والأسماك وتحديد اختصاصاتها
Title: مرسوم سلطاني رقم ٣٢ / ٢٠٢٠ بتعديل بعض أحكام قانون مكافحة الأمراض المعدية
Title: وزارة الزراعة والثروة السمكية: قرار وزاري رقم ٦٨ / ٢٠٢٠ برفع حظر استيراد المنتجات والأعلاف الحيوانية عن المملكة البلجيكية
Title: صندوق تقاعد موظفي الخدمة المدنية: قرار رقم ١٣٢ / ٢٠١٥ بإصدار اللائحة المالية لصندوق تقاعد موظفي الخدمة المدنية
Title: مرسوم سلطاني رقم ٣٢ / ٩٢ بتعيين سفير للسلطنة لدى دولة الإمارات العربية المتحدة
Title: مرسوم سلطاني رقم ١٤ / ٢٠١١ بتعيين مستشارين للدولة
Title: مرسوم سلطاني رقم ١١٣ / ٨١ بتعيين نائب لرئيس ديوان تشريفات جلالة السلطان لشؤون المراسم
Title: مرسوم سلطاني رقم ١٤ / ٧٧ بمنح الجنسية العمانية لبعض الأشخاص
Title: مرسوم سلطاني رقم ٥٤ / ٢٠٢١ بتطبيق القانون (النظام) الموحد لمكافحة الغش التجاري لدول مجلس التعاون لدول الخليج العربية
Title: وزارة العمل: قرار وزاري رقم ٢٠ / ٢٠٢١ بتنظيم مزاولة بعض المهن في مؤسسات التعليم العالي الخاصة
Title: مرسوم سلطاني رقم ٧ / ٩٨ بتعديل بعض أحكام نظام كلية الشريعة والقانون الصادر بالمرسوم السلطاني رقم ٢٦ / ٩٧
Title: مرسوم سلطاني رقم ١٥ / ٩٥ بالتصديق على اتفاقية تشجيع وحماية الاستثمارات بين سلطنة عمان وحكومة جمهورية الصين الشعبية
Title: مرسوم سلطاني رقم ٥١ / ٩٠ بإجراء تنقلات وتعيينات في السلك الدبلوماسي
Title: وزارة المالية: قرار وزاري رقم ٢٠٧ / ٢٠١٩ بتعديل دليل تصنيف الميزانية العامة للدولة (الملحق رقم ١) المرفق باللائحة التنفيذية للقانون المالي
Title: مرسوم سلطاني رقم ١٠٤ / ٨٥ بتعديل اسم وزارة البيئة واختصاصاتها
Title: مرسوم سلطاني رقم ٦٧ / ٢٠٠٧ بمنح الجنسية العمانية
Title: مرسوم سلطاني رقم ٥٣ / ٧٩ بترقية السيد سالم بن علي آل سعيد وتعيينه نائبا لمحافظ العاصمة
Title: هيئة تنظيم الاتصالات: قرار رقم ٢٢ / ٢٠١٤ بإصدار اللائحة التنظيمية للخطة الوطنية للترقيم
Title: المركز الوطني للإحصاء والمعلومات: قرار رقم ١٠٣ / ٢٠٢٢ بإصدار استراتيجية البيانات الوطنية
Title: مرسوم سلطاني رقم ٩٧ / ٢٠٠٠ في شأن المناقصات الخاصة بكل من شركة مصفاة نفط عمان وشركة الغاز العمانية
Title: مرسوم سلطاني رقم ٤ / ٩٠ بإجراء تعديل في النظام الداخلي للمجلس الاستشاري للدولة
Title: وزارة التجارة والصناعة وترويج الاستثمار: قرار وزاري رقم ١٨٤ / ٢٠٢٠ بتعديل بعض أحكام لائحة تنظيم العروض الترويجية
Title: مرسوم سلطاني رقم ٣٤ / ٩٧ بتعيين وكيل لوزارة التجارة والصناعة للسياحة
Title: مرسوم سلطاني رقم ٣٩ / ٨٠ بتفويض وزير المواصلات في توقيع اتفاقية البرنامج الإقليمي للأرصاد البحرية لدول الخليج
Title: وزارة المالية: قرار رقم ١٦٧ / ٢٠١٧ بتعديل بعض أحكام اللائحة التنفيذية لنظام تحصيل الضرائب والرسوم وغيرها من المبالغ المستحقة لوحدات الجهاز الإداري للدولة
Title: مرسوم سلطاني رقم ٣٨ / ٧٨ بإجراء بعض التغييرات في المناصب الوزارية وتعيين وزراء جدد
Title: مرسوم سلطاني رقم ١٤ / ٩٣ بمنح الجنسية العمانية
Title: مرسوم سلطاني رقم ٦٣ / ٢٠١٩ بإنشاء وزارة التقنية والاتصالات
Title: مرسوم سلطاني رقم ٢٤ / ٧٨ بتنسيق العمل بين وزارة شؤون الأراضي والبلديات ووزارة الزراعة والأسماك والنفط والمعادن فيما يتعلق بالأراضي الزراعية
Title: هيئة تنظيم الخدمات العامة: قرار رقم ٣١ / ٢٠٢٣ بإصدار لائحة تنظيم جودة المياه الصالحة للشرب
Title: مرسوم سلطاني رقم ٣ / ٢٠٠١ بتعيين سفيرين غير مقيمين
Title: مرسوم سلطاني رقم ٥٣ / ٢٠٠٠ بإنشاء مركر السلطان قابوس للثقافة الإسلامية
Title: هيئة تنظيم الاتصالات: قرار رقم ٩٠ / ٢٠٢٢ بتعديل بعض أحكام الترخيص من الفئة الأولى للشركة العمانية للاتصالات (ش.م.ع.ع) لتقديم خدمات الاتصالات العامة الثابتة الأساسية
Title: مرسوم سلطاني رقم ١٥ / ٢٠١٦ بإجازة تنازل شركة تيثيز أويل عمان ليمتد عن ١٠٠٪ من حصتها وحقوقها والتزاماتها في الاتفاقية النفطية الموقعة بتاريخ ٦ سبتمبر ٢٠٠٥م للمنطقة رقم (١٥) إلى شركة أودين انرجي أ اس، وإجازة تنازل شركة أودين انرجي أ اس عن ٩٠٪ من حصتها وحقوقها والتزاماتها في الاتفاقية النفطية الموقعة بتاريخ ٦ سبتمبر٢٠٠٥م للمنطقة رقم (١٥) إلى شركة هايدروكاربون فاينادر ش م م
Title: مرسوم سلطاني رقم ١٢ / ٨٢ بترقية عدد من أعضاء السلك الدبلوماسي إلى سفراء ووزراء مفوضين
Title: مرسوم سلطاني رقم ٤١ / ٢٠٢٤ بإصدار قانون المحاماة والاستشارات القانونية
Title: مرسوم سلطاني رقم ٣١ / ٨٢ بتعيين وكيل وزارة الشؤون الاجتماعية والعمل
Title: مرسوم سلطاني رقم ٤٩ / ٢٠٢١ بنقل متحف المدرسة السعيدية للتعليم من وزارة التربية والتعليم إلى المتحف الوطني
Title: مرسوم سلطاني رقم ١٠٧ / ٢٠٠٨ بإجازة تنازل شركة حواسنه ليمتد لايابيليتي عن ٢٥٪ من حقوقها والتزاماتها في الاتفاقية النفطية الموقعة بتاريخ ٢٨ يونيو ٢٠٠٦م (المنطقة ٤٣ ب) إلى شركة ماري غاز ليمتد
Title: مرسوم سلطاني رقم ٣ / ٢٠٢٤ بالتصديق على اتفاقية الخدمات الجوية بين حكومة سلطنة عمان وحكومة جمهورية البرازيل الاتحادية
Title: وزارة التجارة والصناعة: قرار وزاري رقم ١٩٥ / ٢٠١٧ باعتبار مواصفة قياسية عمانية ملزمة
Title: مرسوم سلطاني رقم ٤ / ٢٠١٣ بتعيينات عسكرية
Title: مرسوم سلطاني رقم ٧ / ٩٥ بمنح الجنسية العمانية
Title: مرسوم سلطاني رقم ٣٢ / ٢٠١٧ بتقرير صفة المنفعة العامة لمشروع إنشاء سد الحماية (G2) من مخاطر الفيضانات في وادي عدي بمحافظة مسقط
Title: مرسوم سلطاني رقم ٢٧ / ٩٧ بتعديل ملحق أحكام تأسيس الشركة العمانية للغاز الطبيعي المسال المرفق بالمرسوم السلطاني رقم ٢٦ / ٩٤
Title: مرسوم سلطاني رقم ١ / ٩٣ بالتصديق على الموازنة العامة للدولة لعام ١٩٩٣م
Title: مرسوم سلطاني رقم ٢٠ / ٨٧ باعتماد الهيكل التنظيمي لوزارة الإسكان
Title: مرسوم سلطاني رقم ٦ / ٨٥ باعتماد الهيكل التنظيمي لمكتب الممثل الخاص لجلالة السلطان
Title: مرسوم سلطاني رقم ٣ / ٢٠١٧ بإصدار نظام الهيئة العامة للمخازن والاحتياطي الغذائي
Title: وزارة الإسكان: قرار وزاري رقم ٩٢ / ٢٠١٤ بتحديد القيمة الإيجارية للأراضي المخصصة لمشاريع الاستزراع السمكي
Title: مرسوم سلطاني رقم ٦١ / ٢٠٠١ بالتصديق على اتفاقية التشجيع والحماية المتبادلة للاستثمارات بين سلطنة عمان وحكومة المملكة المغربية
Title: مرسوم سلطاني رقم ١٠٧ / ٢٠٢٥ بالتصديق على اتفاقية بين حكومة سلطنة عمان وحكومة المملكة المتحدة لبريطانيا العظمى وإيرلندا الشمالية في شأن تصريح العمل لأزواج الموظفين الرسميين
Title: مرسوم سلطاني رقم ١٩ / ٨٦ بالتفويض في توقيع اتفاقية تبادل الإعفاء الضريبي بين حكومة سلطنة عمان وحكومة المملكة الأردنية الهاشمية
Title: هيئة تنظيم الاتصالات: قرار رقم ١١٥٢ / ٢ / ٣ / ٢٠٢٢ / ٤ بإصدار لائحة تنظيم أبراج الاتصالات
Title: مرسوم سلطاني رقم ٥٩ / ٢٠١٤ بإصدار تعديلات على بعض أحكام قانون سوق رأس المال
Title: مرسوم سلطاني رقم ١٢ / ٩٥ بتعيين وكيل لوزارة الزراعة والثروة السمكية
Title: مرسوم سلطاني رقم ١١ / ٢٠٠٠ بتعيين مستشار خاص لجلالة السلطان
Title: مرسوم سلطاني رقم ١١ / ٩١ بإجازة تنازل إحدى الشركات عن جميع حقوقها والتزاماتها في الاتفاقية النفطية الموقعة بتاريخ ٢٥ فبراير ١٩٨٥م
Title: وزارة التنمية الاجتماعية: قرار وزاري رقم ١٧١ / ٢٠٢٥ بشأن إشهار الجمعية العمانية للرفق بالحيوان
Title: مرسوم سلطاني رقم ٥٠ / ٧٩ بإجازة التنازل الصادر من شركة كلف أويل ليمتد إلى شركة كلف أويل أستراليا أن-أل
Title: وزارة العدل والشؤون القانونية: قرار وزاري رقم ٣٥ / ٢٠٢٢ بتعديل القرار الوزاري رقم ٣٠٠ / ٢٠١٩ بتخويل صفة الضبطية القضائية لبعض موظفي هيئة الطيران المدني
Title: وزارة القوى العاملة: قرار وزاري رقم ٩٠ / ٢٠١٣ بتحديد إجراءات وضوابط التعامل مع منشآت القطاع الخاص المخالفة لأحكام قانون العمل والقرارات المنظمة له
Title: هيئة تنظيم الاتصالات: قرار رقم ٤٨ / ٢٠١٦ بإصدار لائحة تنظيم إعادة تقديم خدمة النفاذ إلى شبكة المعلومات العالمية (الإنترنت)
Title: مرسوم سلطاني رقم ٤٤ / ٨٨ بإجازة التنازل بين بعض الشركات عن أجزاء من حصتها في الاتفاقية النفطية الموقعة بتاريخ ١٨ مارس ١٩٨٤م
Title: هيئة تنمية المؤسسات الصغيرة والمتوسطة: قرار رقم ٢٦٢ / ٢٠٢٢ بإصدار اللائحة التنظيمية لدعم الصناعات الحرفية
Title: مرسوم سلطاني رقم ٤٣ / ٢٠١٧ بتعيين نائب لرئيس مجلس محافظي البنك المركزي العماني
Title: مرسوم سلطاني رقم ٣٦ / ٩٠ بإصدار قانون الأسلحة والذخائر
Title: مرسوم سلطاني رقم ٤٣ / ٢٠١٩ بتعيين أمين عام لوزارة المالية
Title: مرسوم سلطاني رقم ١٦ / ٢٠١٥ بتقرير صفة المنفعة العامة لمشروع مبنى نادي دبا الرياضي
Title: مرسوم سلطاني رقم ٤٠ / ٢٠٠٨ بتعديل المرسوم السلطاني رقم ٢٩ / ٢٠٠٦ بتعيين أعضاء المجلس البلدي لبلدية مسقط
Title: مرسوم سلطاني رقم ٣٢ / ٢٠٠٦ بالتصديق على اتفاقية تطبيق الضمانات والبروتوكول المرفق بها في إطار معاهدة عدم انتشار الأسلحة النووية
Title: مرسوم سلطاني رقم ٤٦ / ٢٠١٣ برد الجنسية العمانية
Title: وزارة التجارة والصناعة وترويج الاستثمار: قرار وزاري رقم ٢٩ / ٢٠٢١ بشأن التعامل مع المخالفين لقرارات اللجنة العليا المعنية ببحث آلية التعامل مع التطورات الناتجة عن انتشار فيروس كورونا (كوفيد ١٩)
Title: مرسوم سلطاني رقم ٢٢ / ٨٣ بتفويض وزير الدولة للشؤون الخارجية في التوقيع نيابة عن حكومة السلطنة على وثيقة الانضمام إلى اتفاقية إنشاء الصندوق الدولي للتنمية الزراعية
Title: مرسوم سلطاني رقم ٥١ / ٢٠٠٦ بتقرير صفة المنفعة العامة لمشروع تطوير سوق ولاية المصنعة
Title: وزارة التجارة والصناعة وترويج الاستثمار: قرار وزاري رقم ٦٧ / ٢٠٢٣ باعتبار مواصفة قياسية عمانية ملزمة
Title: مرسوم سلطاني رقم ٤٢ / ٩٤ بإجازة تنازل شركة كونكويست اكسبلوريشن عمان انك عن جزء من حصتها في الاتفاقية البترولية المؤرخة ٢٣ يوليو ١٩٨٩م
Title: مرسوم سلطاني رقم ٤٩ / ٢٠٠٧ بتعيين مساعد للمفتش العام للشرطة والجمارك
Title: وزارة الصحة: قرار وزاري رقم ١٤١ / ٢٠١٤ بشأن التدابير الوقائية ضد متلازمة الحميات النزفية (مرض إيبولا)
Title: مرسوم سلطاني رقم ١١٨ / ٩١ بتعيين وكيلين لوزارة الشؤون الاجتماعية والعمل
Title: مرسوم سلطاني رقم ٥٧ / ٢٠٢٤ بالتصديق على اتفاقية بين حكومة سلطنة عمان وحكومة جمهورية بلغاريا حول الإعفاء المتبادل من متطلبات تأشيرة الإقامة القصيرة لحاملي جوازات السفر الدبلوماسية والخاصة والخدمة
Title: مرسوم سلطاني رقم ٦٤ / ٨١ بنقل عبدالقادر الغساني إلى الدرجة المالية الأولى من الحلقة الأولى والمخصصة لوكيل الوزارة
Title: مرسوم سلطاني رقم ٢٩ / ٢٠٢٢ بالتصديق على اتفاقية التعاون في مجال النقل البحري بين حكومة سلطنة عمان وحكومة الجمهورية الإسلامية الإيرانية
Title: مرسوم سلطاني رقم ٤٩ / ٩٠ بإنشاء لجنة للتنسيق التجاري والصناعي
Title: مرسوم سلطاني رقم ٣٤ / ٨٥ بمنح الجنسية العمانية لبعض الأفراد
Title: مرسوم سلطاني رقم ٣ / ٢٠١٩ بالتصديق على تعديل اتفاقية القضاء على جميع أشكال التمييز ضد المرأة وسحب بعض تحفظات السلطنة عليها
Title: مرسوم سلطاني رقم ٦٩ / ٢٠١٣ بتقرير صفة المنفعة العامة لمشروع تطوير دوارات الصويحرة وصلان وفلج القبائل بولاية صحار
Title: مرسوم سلطاني رقم ٩١ / ٨٢ بتحديد المسميات والرتب الخاصة بوحدات قوة الشرطة والعاملين فيها
Title: مرسوم سلطاني رقم ٧٥ / ٨١ بتعيين مرافق عسكري أول لجلالة السلطان ورئيس لمكتب القصر، وتعيين نائب لرئيس مكتب القصر
Title: مرسوم سلطاني رقم ٣١ / ٢٠١٢ بإنشاء المركز الوطني للإحصاء والمعلومات
Title: مرسوم سلطاني رقم ٣ / ٨٥ بتعيين محافظ العاصمة
Title: مرسوم سلطاني رقم ٦٨ / ٨٧ بإصدار قانون العلامات والبيانات التجارية
Title: مرسوم سلطاني رقم ٣٥ / ٢٠٢٥ بإنشاء محكمة الاستثمار والتجارة وإصدار قانونها
Title: مرسوم سلطاني رقم ٣٠ / ٢٠١٦ بإصدار قانون مكافحة غسل الأموال وتمويل الإرهاب
Title: مرسوم سلطاني رقم ٥٤ / ٢٠٢٠ بتعيين نائب لرئيس جهاز الضرائب
Title: مرسوم سلطاني رقم ٢٦ / ٨٠ بتعديل الهيكل التنظيمي للأمانة الفنية لمجلس التنمية
Title: لجنة العقوبات المالية المستهدفة: قرار رقم ١ / ٢٠٢٣ بإدراج أفراد وكيانات في القائمة الإرهابية المحلية
Title: مرسوم سلطاني رقم ٨٧ / ٩٩ بإجازة الاتفاقية النفطية بين حكومة السلطنة ومجموعة شركات (١) نوفس استراليا اينرجي كمباني بي-تي-واي-ليمتد (٢) اتلانتيس هولدينج نوروي ايه-اس (٣) ايجل اينرجي (عمان) ليمتد
Title: وزارة التنمية الاجتماعية: قرار وزاري رقم ٤٨ / ٢٠١٧ بتعديل بعض أحكام اللائحة التنظيمية لدور الحضانة
Title: مرسوم سلطاني رقم ٥٦ / ٢٠٠٦ بإنشاء مديرية عامة للتدقيق الداخلي بوزارة الصحة

In [55]:
import pandas as pd
import re

# تابعی برای استخراج نوع و شماره قانون
def extract_law_info(text):
    if pd.isna(text):
        return pd.Series([None, None])

    # الگوی رجکس برای پیدا کردن شماره بعد از کلمه "رقم"
    # [\d٠-٩] هم اعداد انگلیسی و هم اعداد فارسی/عربی را پوشش می‌دهد
    match = re.search(r'رقم\s+([\d٠-٩]+\s*/\s*[\d٠-٩]+)', str(text))

    if match:
        law_number = match.group(1).strip() # استخراج گروه اعداد (مثلا: ٤١ / ٧٤)

        # پیدا کردن متن قبل از کلمه "رقم" برای پیدا کردن نوع قانون
        # text[:match.start()] تمام متن قبل از شروع پترن "رقم ..." را می‌دهد
        pre_text = text[:match.start()].strip()

        # مدیریت حالتی که نام وزارتخانه با دو نقطه جدا شده است
        # مثال: "وزارة الداخلية: قرار وزاري" -> فقط "قرار وزاري" را می‌خواهیم
        if ':' in pre_text:
            law_type = pre_text.split(':')[-1].strip()
        else:
            law_type = pre_text

        return pd.Series([law_type, law_number])
    else:
        # اگر الگوی "رقم ..." پیدا نشد
        return pd.Series([None, None])

# اعمال تابع روی ستون title و ساخت دو ستون جدید
df_final[['law_type', 'law_number']] = df_final['title'].apply(extract_law_info)

# نمایش نتیجه برای بررسی
print(df_final[['title', 'law_type', 'law_number']].head())

                                               title      law_type law_number
0  مرسوم سلطاني رقم ٢ / ٧٤ بالموافقة على تأسيس مك...  مرسوم سلطاني     ٢ / ٧٤
1  مرسوم سلطاني رقم ٣ / ٧٤ بالموافقة على تأسيس “ش...  مرسوم سلطاني     ٣ / ٧٤
2  مرسوم سلطاني رقم ٦ / ٧٤ بخصوص إعادة تنظيم دائر...  مرسوم سلطاني     ٦ / ٧٤
3  مرسوم سلطاني رقم ١١ / ٧٤ بتعديل الفقرة (٣) من ...  مرسوم سلطاني    ١١ / ٧٤
4  مرسوم سلطاني رقم ١٤ / ٧٤ بالتصديق على اتفاقية ...  مرسوم سلطاني    ١٤ / ٧٤

In [56]:
n_samples = 200
random_samples = df_final.sample(n=n_samples)
for i, row in random_samples.head(300).iterrows():
    print("Title:", row['title'])
    print("law_type:", row['law_type'])
    print("law_number:", row['law_number'])

Title: مرسوم سلطاني رقم ١١ / ٢٠١٣ بتعديل بعض أحكام نظام المجلس الأعلى للتخطيط
law_type: مرسوم سلطاني
law_number: ١١ / ٢٠١٣
Title: مرسوم سلطاني رقم ٤٤ / ٢٠٠٠ بالتصديق على اتفاقية التشجيع والحماية المتبادلة للاستثمارات بين حكومة سلطنة عمان وحكومة الجمهورية الجزائرية الديمقراطية الشعبية
law_type: مرسوم سلطاني
law_number: ٤٤ / ٢٠٠٠
Title: مرسوم سلطاني رقم ٥٥ / ٩٨ بالتصديق على اتفاقية تجنب الازدواج الضريبي على الدخل الناشئ من النقل الجوي الدولي وملحقها بين حكومة سلطنة عمان وحكومة جمهورية سنغافورة
law_type: مرسوم سلطاني
law_number: ٥٥ / ٩٨
Title: مرسوم سلطاني رقم ٦٢ / ٩٧ بإضافة مادة جديدة إلى المرسوم السلطاني رقم (٧٩ / ٨١)
law_type: مرسوم سلطاني
law_number: ٦٢ / ٩٧
Title: وزارة التنمية الاجتماعية: قرار وزاري رقم ١٢٥ / ٢٠١٩ بإصدار اللائحة التنفيذية لقانون الطفل
law_type: قرار وزاري
law_number: ١٢٥ / ٢٠١٩
Title: وزارة الإسكان: قرار وزاري رقم ٥٣ / ٢٠١٣ بإصدار اللائحة التنظيمية لضوابط تخطيط الأراضي
law_type: قرار وزاري
law_number: ٥٣ / ٢٠١٣
Title: مرسوم سلطاني رقم ١٧ / ٢٠١٩ بتعيين قاضيين في المحكمة العليا
law_type: مرسوم سلطاني
law_number: ١٧ / ٢٠١٩
Title: مرسوم سلطاني رقم ٩٤ / ٢٠٠٤ بترقية وتعيين بعض أعضاء الادعاء العام
law_type: مرسوم سلطاني
law_number: ٩٤ / ٢٠٠٤
Title: وزارة الثقافة والرياضة والشباب: قرار وزاري رقم ٨٩ / ٢٠٢٢ بإصدار لائحة تنظيم فرق الفنون الشعبية
law_type: قرار وزاري
law_number: ٨٩ / ٢٠٢٢
Title: مرسوم سلطاني رقم ١١٢ / ٢٠٠٨ بمنح الدرجة الخاصة
law_type: مرسوم سلطاني
law_number: ١١٢ / ٢٠٠٨
Title: مرسوم سلطاني رقم ١٠٩ / ٢٠٠١ بتعديل في التشكيل الوزاري
law_type: مرسوم سلطاني
law_number: ١٠٩ / ٢٠٠١
Title: وزارة الصحة: قرار وزاري رقم ١٢٥ / ٩٢ بشأن الإبلاغ عن الأمراض المعدية
law_type: قرار وزاري
law_number: ١٢٥ / ٩٢
Title: وزارة الصحة: قرار وزاري رقم ٢٧ / ٢٠١٤ بتحديد رسوم خدمات الحجر الصحي
law_type: قرار وزاري
law_number: ٢٧ / ٢٠١٤
Title: هيئة حماية المستهلك: قرار رقم ٢٠٦ / ٢٠٢٣ بتعديل بعض أحكام القرار رقم ٢٥٦ / ٢٠١٥ في شأن حظر تداول التبغ الممضوغ (غير المدخن)
law_type: قرار
law_number: ٢٠٦ / ٢٠٢٣
Title: مرسوم سلطاني رقم ٢٩ / ٨٢ بالمصادقة على انضمام سلطنة عمان إلى اتفاقية مؤسسة الإنتاج البرامجي المشترك
law_type: مرسوم سلطاني
law_number: ٢٩ / ٨٢
Title: مرسوم سلطاني رقم ٦٠ / ٨٩ بمنح الجنسية العمانية
law_type: مرسوم سلطاني
law_number: ٦٠ / ٨٩
Title: مرسوم سلطاني رقم ٤٥ / ٨٥ باعتماد الهيكل التنظيمي للسكرتارية الفنية للجنة التخطيط للتنمية والبيئة بالمنطقة الجنوبية
law_type: مرسوم سلطاني
law_number: ٤٥ / ٨٥
Title: وزارة الإسكان والتخطيط العمراني: قرار وزاري رقم ١١٣ / ٢٠٢١ بإصدار لائحة الرقابة على مكاتب وشركات الوساطة في المجالات العقارية والمطورين العقاريين في شأن مكافحة غسل الأموال وتمويل الإرهاب
law_type: قرار وزاري
law_number: ١١٣ / ٢٠٢١
Title: هيئة تنظيم الاتصالات: قرار رقم ٢٨ / ٢٠١٦ بإصدار لائحة متطلبات جودة الخدمة التي يلتزم المرخص له بتقديمها
law_type: قرار
law_number: ٢٨ / ٢٠١٦
Title: مرسوم سلطاني رقم ٢٠ / ٧٦ باستحداث مديرية عامة بوزارة الأشغال العامة تسمى “المديرية العامة للشؤون الفنية”
law_type: مرسوم سلطاني
law_number: ٢٠ / ٧٦
Title: مرسوم سلطاني رقم ٢١ / ٨١ بالتصديق على الاتفاقية العامة للتعاون الاقتصادي والفني والتجاري بين الدول الأعضاء في منظمة المؤتمر الإسلامي
law_type: مرسوم سلطاني
law_number: ٢١ / ٨١
Title: مرسوم سلطاني رقم ٩٥ / ٩٦ بمنح امتياز مشروع الغاز الطبيعي المسال والأحكام الخاصة بالتنفيذ
law_type: مرسوم سلطاني
law_number: ٩٥ / ٩٦
Title: مرسوم سلطاني رقم ١٦ / ٢٠٢٣ بالموافقة على انضمام سلطنة عمان إلى الميثاق العربي لحقوق الإنسان
law_type: مرسوم سلطاني
law_number: ١٦ / ٢٠٢٣
Title: مرسوم سلطاني رقم ٥ / ٩٨ بتعديل بعض أحكام قانون تأمين المركبات
law_type: مرسوم سلطاني
law_number: ٥ / ٩٨
Title: وزارة الصحة: قرار وزاري رقم ٨٨ / ٢٠٠٠ بتعديل اللائحة التنظيمية للمعاهد التعليمية التابعة لوزارة الصحة
law_type: قرار وزاري
law_number: ٨٨ / ٢٠٠٠
Title: مرسوم سلطاني رقم ٥ / ٨٤ بتعيين سفير للسلطنة لدى الامبراطورية اليابانية
law_type: مرسوم سلطاني
law_number: ٥ / ٨٤
Title: مرسوم سلطاني رقم ٢٤ / ٩٧ بتعديل بعض أحكام المرسوم السلطاني رقم ٣١ / ٩٦
law_type: مرسوم سلطاني
law_number: ٢٤ / ٩٧
Title: مرسوم سلطاني رقم ١٠٠ / ٢٠٠٤ بتعديل بعض أحكام نظام معاشات ومكافآت ما بعد الخدمة لمنتسبي وزارة الدفاع وقوات السلطان المسلحة
law_type: مرسوم سلطاني
law_number: ١٠٠ / ٢٠٠٤
Title: مرسوم سلطاني رقم ١٩ / ٨١ بتقرير صفة المنفعة العامة لمشروع إنشاء حديقة السلطان قابوس العامة بمنطقة القرم
law_type: مرسوم سلطاني
law_number: ١٩ / ٨١
Title: مرسوم سلطاني رقم ٣١ / ٢٠٢١ بتعديل بعض أحكام المرسوم السلطاني رقم ٣٥ / ٢٠١٤ بإنشاء كلية العلوم الشرعية وإصدار نظامها
law_type: مرسوم سلطاني
law_number: ٣١ / ٢٠٢١
Title: مرسوم سلطاني رقم ٩٣ / ٢٠٠٢ بتعيين قاض بالمحكمة العليا
law_type: مرسوم سلطاني
law_number: ٩٣ / ٢٠٠٢
Title: مرسوم سلطاني رقم ١٠٧ / ٢٠١٠ بتعديل بعض الأحكام المنظمة للعلاقة بين ملاك ومستأجري المساكن والمحال التجارية والصناعية وتسجيل عقود الإيجار الخاصة بها الصادرة بالمرسوم السلطاني رقم ٦ / ٨٩
law_type: مرسوم سلطاني
law_number: ١٠٧ / ٢٠١٠
Title: شرطة عمان السلطانية: قرار رقم ٧١ / ٩٧ بشأن تحديد رسوم إصدار جواز السفر العادي
law_type: قرار
law_number: ٧١ / ٩٧
Title: مرسوم سلطاني رقم ٦٤ / ٢٠٠٦ بإصدار قانون المبيدات
law_type: مرسوم سلطاني
law_number: ٦٤ / ٢٠٠٦
Title: مرسوم سلطاني رقم ٤٠ / ٢٠٠٣ بإصدار قانون الكتاب بالعدل
law_type: مرسوم سلطاني
law_number: ٤٠ / ٢٠٠٣
Title: الهيئة العمانية للاعتماد الأكاديمي: قرار رقم ٤ / ٢٠٢٠ بتعديل بعض أحكام لائحة شؤون الموظفين بالهيئة العمانية للاعتماد الأكاديمي
law_type: قرار
law_number: ٤ / ٢٠٢٠
Title: مرسوم سلطاني رقم ٣٤ / ٨٦ بتعيين سفير غير مقيم لدى اتحاد الجمهوريات الاشتراكية السوفييتية
law_type: مرسوم سلطاني
law_number: ٣٤ / ٨٦
Title: مرسوم سلطاني رقم ٦٦ / ٩٦ بتعديل قانون المرور
law_type: مرسوم سلطاني
law_number: ٦٦ / ٩٦
Title: مرسوم سلطاني رقم ٤٤ / ٢٠٠٦ بتعديل بعض أحكام نظام معاشات ومكافآت ما بعد الخدمة لمنتسبي وزارة الدفاع وقوات السلطان المسلحة
law_type: مرسوم سلطاني
law_number: ٤٤ / ٢٠٠٦
Title: وزارة التجارة والصناعة: قرار وزاري رقم ٩٨ / ٢٠٠١ بفرض رسم على زيارة قلعة نخل
law_type: قرار وزاري
law_number: ٩٨ / ٢٠٠١
Title: مرسوم سلطاني رقم ٧٠ / ٨٨ بتجديد عضوية نائب رئيس مجلس محافظي البنك المركزي العماني، الرئيس التنفيذي للبنك
law_type: مرسوم سلطاني
law_number: ٧٠ / ٨٨
Title: مرسوم سلطاني رقم ٣٧ / ٢٠٠٩ بإجازة الاتفاقية النفطية بين حكومة سلطنة عمان وشركة بتروتل عمان أل أل سي (المنطقة ١٧)
law_type: مرسوم سلطاني
law_number: ٣٧ / ٢٠٠٩
Title: مرسوم سلطاني رقم ٦٣ / ٢٠١٩ بإنشاء وزارة التقنية والاتصالات
law_type: مرسوم سلطاني
law_number: ٦٣ / ٢٠١٩
Title: مرسوم سلطاني رقم ٩٧ / ٩٦ بمنح لقب سفير
law_type: مرسوم سلطاني
law_number: ٩٧ / ٩٦
Title: الهيئة العامة لسوق المال: قرار رقم خ / ٣ / ٢٠٢٣ بإصدار نموذج وثيقة التأمين الموحدة للضمان الممدد على المركبات
law_type: None
law_number: None
Title: مرسوم سلطاني رقم ٤٨ / ٢٠٠١ بالتعيين في بعض المناصب وتعيين عضو في مجلس الدولة
law_type: مرسوم سلطاني
law_number: ٤٨ / ٢٠٠١
Title: مرسوم سلطاني رقم ٦٨ / ٨٢ بنقل سفير السلطنة لدى دولة الكويت وتعيينه سفيرا فوق العادة ومفوضا للسلطنة لدى جمهورية باكستان الإسلامية
law_type: مرسوم سلطاني
law_number: ٦٨ / ٨٢
Title: وزارة الثروة الزراعية والسمكية وموارد المياه: قرار وزاري رقم ٢٢٧ / ٢٠٢٥ برفع حظر استيراد الطيور الحية من بعض الدول
law_type: قرار وزاري
law_number: ٢٢٧ / ٢٠٢٥
Title: مرسوم سلطاني رقم ٢٩ / ٢٠٢٣ بإنشاء سفارة لسلطنة عمان في المجر
law_type: مرسوم سلطاني
law_number: ٢٩ / ٢٠٢٣
Title: مرسوم سلطاني رقم ٦٦ / ٩٨ بتعيين أعضاء في مجلس التعليم العالي
law_type: مرسوم سلطاني
law_number: ٦٦ / ٩٨
Title: مرسوم سلطاني رقم ٩٦ / ٨٥ بتعيين وكيل لمكتب المستشار الخاص لجلالة السلطان للشؤون الدينية والتاريخية
law_type: مرسوم سلطاني
law_number: ٩٦ / ٨٥
Title: مرسوم سلطاني رقم ٨٩ / ٢٠٢٠ بإنشاء وزارة العمل وتحديد اختصاصاتها واعتماد هيكلها التنظيمي
law_type: مرسوم سلطاني
law_number: ٨٩ / ٢٠٢٠
Title: ديوان البلاط السلطاني: قرار ديواني رقم ٢٠ / ٢٠١٨ بشأن رسوم العضوية وتأجير المرافق بمجمع السلطان قابوس الشبابي للثقافة والترفيه بصلالة
law_type: قرار ديواني
law_number: ٢٠ / ٢٠١٨
Title: وزارة الشؤون الرياضية: قرار وزاري رقم ٢٤٥ / ٢٠١٩ بإشهار الاتحاد العماني للجولف واعتماد نظامه الأساسي
law_type: قرار وزاري
law_number: ٢٤٥ / ٢٠١٩
Title: مرسوم سلطاني رقم ٦٢ / ٨٦ بتعيين مستشار للدولة لشؤون القبائل
law_type: مرسوم سلطاني
law_number: ٦٢ / ٨٦
Title: هيئة تنظيم الاتصالات: قرار رقم ٩٣ / ٢٠٢٢ بإصدار لائحة تنظيم تقديم خدمات إنترنت الأشياء
law_type: قرار
law_number: ٩٣ / ٢٠٢٢
Title: مرسوم سلطاني رقم ٦٢ / ٩٢ بتجديد عضوية بمجلس محافظي البنك المركزي العماني
law_type: مرسوم سلطاني
law_number: ٦٢ / ٩٢
Title: وزارة العمل: قرار وزاري رقم ٢٣٥ / ٢٠٢٢ بتنظيم مزاولة بعض المهن
law_type: قرار وزاري
law_number: ٢٣٥ / ٢٠٢٢
Title: المعهد العالي للقضاء: قرار وزاري رقم ٣٠٧ / ٢٠١٤ بإصدار لائحة الدراسة وبرامج التدريب بالمعهد العالي للقضاء
law_type: قرار وزاري
law_number: ٣٠٧ / ٢٠١٤
Title: مرسوم سلطاني رقم ١٥ / ٨٤ بالتصديق على الاتفاقية الثنائية بين حكومة السلطنة وحكومة المملكة الهولندية بشأن الخدمات الجوية بين إقليميهما وما وراءهما
law_type: مرسوم سلطاني
law_number: ١٥ / ٨٤
Title: مرسوم سلطاني رقم ٥٢ / ٧٩ بنقل سفير السلطنة لدى الجمهورية العراقية إلى الديوان العام بوزارة الخارجية
law_type: مرسوم سلطاني
law_number: ٥٢ / ٧٩
Title: مرسوم سلطاني رقم ٣٧ / ٩٢ بتعديل في قانون بلدية مسقط
law_type: مرسوم سلطاني
law_number: ٣٧ / ٩٢
Title: مرسوم سلطاني رقم ٧٥ / ٩٧ بإجازة تنازل شركة بخا اكسبلوريشن ليمتد عن جميع حقوقها والتزاماتها في الاتفاقية النفطية الموقعة بتاريخ ٢٥ فبراير ١٩٨٥م
law_type: مرسوم سلطاني
law_number: ٧٥ / ٩٧
Title: صندوق الحماية الاجتماعية: قرار رقم ر / ٧ / ٢٠٢٣ بإصدار اللائحة التنفيذية لقانون الحماية الاجتماعية
law_type: None
law_number: None
Title: مرسوم سلطاني رقم ١٢٥ / ٢٠٠٨ بتعديل بعض أحكام نظام استحقاق الأراضي الحكومية الصادر بالمرسوم السلطاني رقم ٨١ / ٨٤
law_type: مرسوم سلطاني
law_number: ١٢٥ / ٢٠٠٨
Title: مرسوم سلطاني رقم ٧٤ / ٩٠ في شأن المعايرة القانونية لأجهزة القياس
law_type: مرسوم سلطاني
law_number: ٧٤ / ٩٠
Title: مرسوم سلطاني رقم ٤ / ٢٠٢٠ بإصدار قانون جهاز الأمن الداخلي
law_type: مرسوم سلطاني
law_number: ٤ / ٢٠٢٠
Title: مرسوم سلطاني رقم ٧٠ / ٢٠١٣ بتقرير صفة المنفعة العامة لمشروع ازدواجية طريق إزكي – نزوى بمحافظة الداخلية
law_type: مرسوم سلطاني
law_number: ٧٠ / ٢٠١٣
Title: مرسوم سلطاني رقم ٦٧ / ٢٠٢٠ بتعيين رئيس لجامعة السلطان قابوس
law_type: مرسوم سلطاني
law_number: ٦٧ / ٢٠٢٠
Title: جهاز الضرائب: قرار رقم ٢ / ٢٠٢١ بتحديد السلع الغذائية الخاضعة لضريبة القيمة المضافة بمعدل الصفر بالمائة
law_type: قرار
law_number: ٢ / ٢٠٢١
Title: مرسوم سلطاني رقم ٤٢ / ٢٠٢٤ بالتصديق على اتفاقية بين حكومة سلطنة عمان ومجلس التعاون لدول الخليج العربية في شأن مقر الهيئة الاستشارية للمجلس الأعلى لمجلس التعاون لدول الخليج العربية ومكتب الشبكة الخليجية لضمان جودة التعليم العالي بدول مجلس التعاون ومركز الترجمة والتعريب والاهتمام باللغة العربية
law_type: مرسوم سلطاني
law_number: ٤٢ / ٢٠٢٤
Title: مرسوم سلطاني رقم ٧٣ / ٩١ بالتفويض في توقيع الاتفاق بين حكومة سلطنة عمان وحكومة الجمهورية الإسلامية الإيرانية لتنظيم الخدمات الجوية بين إقليميهما
law_type: مرسوم سلطاني
law_number: ٧٣ / ٩١
Title: وزارة التجارة والصناعة: قرار وزاري رقم ٦٧ / ٢٠٢٠ بتحديد رسم طلب بيانات عبر النظام الإلكتروني (استثمر بسهولة)
law_type: قرار وزاري
law_number: ٦٧ / ٢٠٢٠
Title: مرسوم سلطاني رقم ٥٢ / ٨٧ بتقرير صفة المنفعة العامة لمشروع إنشاء مرسى للقوارب في منطقة الشطيفي
law_type: مرسوم سلطاني
law_number: ٥٢ / ٨٧
Title: مرسوم سلطاني رقم ٨٤ / ٨٥ بمنح الجنسية العمانية لبعض الأشخاص
law_type: مرسوم سلطاني
law_number: ٨٤ / ٨٥
Title: هيئة حماية المستهلك: قرار رقم ٥٧٣ / ٢٠٢٤ بتحديد قواعد التعيين في غير أدنى الوظائف
law_type: قرار
law_number: ٥٧٣ / ٢٠٢٤
Title: وزارة التعليم العالي والبحث العلمي والابتكار: قرار وزاري رقم ١٠١ / ٢٠٢٣ بتعديل بعض أحكام القرار الوزاري رقم ٤٣ / ٢٠٠٨ بإنشاء فرع وبدء الدراسة بالجامعة العربية المفتوحة بسلطنة عمان
law_type: قرار وزاري
law_number: ١٠١ / ٢٠٢٣
Title: مرسوم سلطاني رقم ٨٢ / ٢٠٢٣ بتعيين أمين عام لمكتب نائب رئيس الوزراء لشؤون العلاقات والتعاون الدولي والممثل الخاص لجلالة السلطان
law_type: مرسوم سلطاني
law_number: ٨٢ / ٢٠٢٣
Title: مرسوم سلطاني رقم ٤٩ / ٢٠٢٥ بمنح الجنسية العمانية
law_type: مرسوم سلطاني
law_number: ٤٩ / ٢٠٢٥
Title: مرسوم سلطاني رقم ١٠٣ / ٢٠٠٨ بتعيين وزير للقوى العاملة
law_type: مرسوم سلطاني
law_number: ١٠٣ / ٢٠٠٨
Title: وزارة العدل والشؤون القانونية: قرار وزاري رقم ٢٥ / ٢٠٢١ بإصدار لائحة الرقابة على المحامين ومكاتب المحاماة والشركات المدنية للمحاماة بشأن مكافحة غسل الأموال وتمويل الإرهاب
law_type: قرار وزاري
law_number: ٢٥ / ٢٠٢١
Title: مرسوم سلطاني رقم ٥١ / ٩٠ بإجراء تنقلات وتعيينات في السلك الدبلوماسي
law_type: مرسوم سلطاني
law_number: ٥١ / ٩٠
Title: الهيئة العامة للكهرباء والمياه: قرار رقم ١ / ٢٠١٧ بإصدار اللائحة المالية للهيئة العامة للكهرباء والمياه
law_type: قرار
law_number: ١ / ٢٠١٧
Title: وزارة المالية: قرار وزاري رقم ١٤٨ / ٢٠١٧ بتعديل دليل تصنيف الميزانية العامة للدولة (الملحق رقم ١) المرفق باللائحة التنفيذية للقانون المالي
law_type: قرار وزاري
law_number: ١٤٨ / ٢٠١٧
Title: مرسوم سلطاني رقم ٦٢ / ٢٠٠٩ بإنشاء سفارة لسلطنة عمان في جمهورية البرازيل الاتحادية
law_type: مرسوم سلطاني
law_number: ٦٢ / ٢٠٠٩
Title: مرسوم سلطاني رقم ١١٨ / ٢٠١٠ بإنشاء دائرة ابتدائية لمحكمة القضاء الإداري بصحار
law_type: مرسوم سلطاني
law_number: ١١٨ / ٢٠١٠
Title: مرسوم سلطاني رقم ٤٨ / ٩٦ بإجراء تعديلات في قانون الأسلحة والذخائر
law_type: مرسوم سلطاني
law_number: ٤٨ / ٩٦
Title: مرسوم سلطاني رقم ٢٧ / ٢٠٢١ بالتصديق على اتفاقية بين سلطنة عمان وجمهورية البيرو حول الإعفاء المتبادل من التأشيرات لحاملي جوازات السفر الدبلوماسية أو الخاصة أو الخدمة
law_type: مرسوم سلطاني
law_number: ٢٧ / ٢٠٢١
Title: مرسوم سلطاني رقم ٨٣ / ٢٠٠٢ بإصدار قانون البعثات والمنح والإعانات الدراسية
law_type: مرسوم سلطاني
law_number: ٨٣ / ٢٠٠٢
Title: مرسوم سلطاني رقم ١٣٢ / ٢٠٢٠ بتعيين قاضيين في المحكمة العليا
law_type: مرسوم سلطاني
law_number: ١٣٢ / ٢٠٢٠
Title: مرسوم سلطاني رقم ٢٦ / ٢٠٠٠ بالموافقة على انضمام سلطنة عمان إلى اتفاقية إنشاء معهد التطعيم الدولي
law_type: مرسوم سلطاني
law_number: ٢٦ / ٢٠٠٠
Title: مرسوم سلطاني رقم ٩٢ / ٢٠٠٠ بإصدار قانون حماية المستنبطات النباتية
law_type: مرسوم سلطاني
law_number: ٩٢ / ٢٠٠٠
Title: وزارة الصحة: قرار وزاري رقم ٥ / ٢٠٢٣ باستبدال جدول الأمراض المعدية الملحق بقانون مكافحة الأمراض المعدية
law_type: قرار وزاري
law_number: ٥ / ٢٠٢٣
Title: مرسوم سلطاني رقم ٣٨ / ٢٠١٩ بإنشاء مركز عمان للمعلومات الائتمانية والمالية وإصدار نظامه
law_type: مرسوم سلطاني
law_number: ٣٨ / ٢٠١٩
Title: مرسوم سلطاني رقم ٦٥ / ٧٨ بمنح الجنسية العمانية لبعض الأشخاص ممن أدوا خدمات طويلة في القوات المسلحة
law_type: مرسوم سلطاني
law_number: ٦٥ / ٧٨
Title: المؤسسة العامة للمناطق الصناعية: قرار إداري رقم ١١ / ٢٠١٧ بإصدار لائحة المناقصات للمؤسسة العامة للمناطق الصناعية
law_type: قرار إداري
law_number: ١١ / ٢٠١٧
Title: وزارة العدل: قرار وزاري رقم ٣٠٠ / ٢٠١٩ بتخويل صفة الضبطية القضائية لبعض موظفي الهيئة العامة للطيران المدني
law_type: قرار وزاري
law_number: ٣٠٠ / ٢٠١٩
Title: مرسوم سلطاني رقم ١١٠ / ٢٠٠٤ بالتصديق على الاتفاقية التجارية بين حكومة سلطنة عمان وحكومة الجمهورية الإسلامية الإيرانية
law_type: مرسوم سلطاني
law_number: ١١٠ / ٢٠٠٤
Title: مرسوم سلطاني رقم ٧٢ / ٩٩ بتعديل قانون الجنسية العمانية
law_type: مرسوم سلطاني
law_number: ٧٢ / ٩٩
Title: وزارة التنمية الاجتماعية: قرار وزاري رقم ١٧٧ / ٢٠٢٣ بشأن إشهار جمعية الرؤية الإيجابية
law_type: قرار وزاري
law_number: ١٧٧ / ٢٠٢٣
Title: وزارة المالية: قرار وزاري رقم ٢٩ / ٢٠٢١ بتعديل دليل تصنيف الميزانية العامة للدولة (الملحق رقم ١) المرفق باللائحة التنفيذية للقانون المالي
law_type: قرار وزاري
law_number: ٢٩ / ٢٠٢١
Title: وزارة البلديات الإقليمية وموارد المياه: قرار وزاري رقم ٣٢ / ٢٠١٨ بتحديد الرسوم والأثمان والتأمينات والضمانات المالية التي تحصلها وزارة البلديات الإقليمية وموارد المياه
law_type: قرار وزاري
law_number: ٣٢ / ٢٠١٨
Title: مرسوم سلطاني رقم ٦٥ / ٢٠١٣ بمنح الجنسية العمانية
law_type: مرسوم سلطاني
law_number: ٦٥ / ٢٠١٣
Title: مرسوم سلطاني رقم ٩٥ / ٩٤ بتعديل بعض أحكام قانون تنظيم الجنسية العمانية
law_type: مرسوم سلطاني
law_number: ٩٥ / ٩٤
Title: وزارة الإسكان والتخطيط العمراني: قرار وزاري رقم ٢٠٠ / ٢٠٢٤ بتنظيم العنونة في سلطنة عمان
law_type: قرار وزاري
law_number: ٢٠٠ / ٢٠٢٤
Title: صندوق الحماية الاجتماعية: قرار رقم ر / ١ / ٢٠٢٥ بتحديد متوسط نمو الأجور ونسبة زيادة المعاشات
law_type: None
law_number: None
Title: بلدية مسقط: قرار رقم ١ / ٢٠١٨ بتحديد الرسوم والأثمان والتأمينات والضمانات المالية التي تحصلها بلدية مسقط
law_type: قرار
law_number: ١ / ٢٠١٨
Title: مرسوم سلطاني رقم ٨ / ٩٤ بتعيين الأعضاء الممثلين لحصة الحكومة في بنك الإسكان العماني
law_type: مرسوم سلطاني
law_number: ٨ / ٩٤
Title: وزارة البيئة والشؤون المناخية: قرار وزاري رقم ٢٥ / ٢٠١٥ بشأن الأسس والضوابط البيئية المتعلقة بإنشاء أو تركيب أو تشغيل محطات تقوية الهاتف المتنقل العالمي (الأبراج والهوائيات)
law_type: قرار وزاري
law_number: ٢٥ / ٢٠١٥
Title: مرسوم سلطاني رقم ٣٧ / ٢٠٠٨ بتحديد اختصاصات وزارة التربية والتعليم واعتماد هيكلها التنظيمي
law_type: مرسوم سلطاني
law_number: ٣٧ / ٢٠٠٨
Title: شرطة عمان السلطانية: قرار رقم ٩٨ / ٢٠٢٣ بتحديد اختصاصات المركز الوطني لإدارة الحالات الطارئة واعتماد هيكله التنظيمي
law_type: قرار
law_number: ٩٨ / ٢٠٢٣
Title: مرسوم سلطاني رقم ٢٠ / ٢٠١٩ بإصدار قانون الثروة المائية الحية
law_type: مرسوم سلطاني
law_number: ٢٠ / ٢٠١٩
Title: مرسوم سلطاني رقم ١٣ / ٢٠٢١ بإعادة تنظيم مجلس الأمن الوطني
law_type: مرسوم سلطاني
law_number: ١٣ / ٢٠٢١
Title: الهيئة العامة لحماية المستهلك: قرار رقم ٢٤٥ / ٢٠١٧ بشأن حظر تداول السلع التي تحتوي على مادة الأسبستوس
law_type: قرار
law_number: ٢٤٥ / ٢٠١٧
Title: مرسوم سلطاني رقم ٢١ / ٩٨ بتقرير صفة المنفعة العامة للمشروعات الصناعية والمرافق المكملة لها والمرتبطة بها والمزمع إنشاؤها في منطقة قلهات
law_type: مرسوم سلطاني
law_number: ٢١ / ٩٨
Title: هيئة تنظيم الاتصالات: قرار رقم ٢٦ / ٢٠٢١ بتعديل بعض أحكام الترخيص من الفئة الأولى للشركة العمانية للاتصالات (ش.م.ع.ع) لتقديم خدمات الاتصالات العامة الثابتة الأساسية
law_type: قرار
law_number: ٢٦ / ٢٠٢١
Title: مرسوم سلطاني رقم ٨٠ / ٨١ بتعيين رئيس لهيئة حسم المنازعات التجارية
law_type: مرسوم سلطاني
law_number: ٨٠ / ٨١
Title: وزارة الزراعة والثروة السمكية: قرار وزاري رقم ١٤٥ / ٢٠٢٠ برفع حظر استيراد الحيوانات الحية عن جمهورية كينيا
law_type: قرار وزاري
law_number: ١٤٥ / ٢٠٢٠
Title: مجلس الشؤون الإدارية للقضاء: قرار رقم ٧٧ / ٢٠٢٠ بتخصيص دائرة في المحكمة الإبتدائية في ولاية الدقم للنظر في الجنح والمخالفات التي يرتكبها الأحداث
law_type: قرار
law_number: ٧٧ / ٢٠٢٠
Title: وزارة الإسكان: قرار وزاري رقم ٩٢ / ٢٠١٤ بتحديد القيمة الإيجارية للأراضي المخصصة لمشاريع الاستزراع السمكي
law_type: قرار وزاري
law_number: ٩٢ / ٢٠١٤
Title: مرسوم سلطاني رقم ٧٣ / ٢٠٠١ بتعديل بعض أحكام قانون الإجراءات الجزائية
law_type: مرسوم سلطاني
law_number: ٧٣ / ٢٠٠١
Title: مرسوم سلطاني رقم ٦ / ٢٠١١ بمنح الجنسية العمانية
law_type: مرسوم سلطاني
law_number: ٦ / ٢٠١١
Title: هيئة تنظيم الاتصالات: قرار رقم ٣٢ / ٢٠١٩ بتعديل بعض أحكام القرار رقم ١٧ / ٢٠٠٧ بإصدار القواعد والشروط الخاصة بالترخيص من الفئة الثانية لتقديم خدمات الاتصالات العامة الإضافية
law_type: قرار
law_number: ٣٢ / ٢٠١٩
Title: مجلس المناقصات: قرار رقم ١٠٤ / ٢٠٢٢ بإصدار اللائحة التنظيمية لتصنيف وتسجيل الموردين والمقاولين والمكاتب الاستشارية
law_type: قرار
law_number: ١٠٤ / ٢٠٢٢
Title: مرسوم سلطاني رقم ٦٣ / ٩٥ بالتفويض في التوقيع على اتفاقية بين حكومة سلطنة عمان وحكومة جمهورية أوغندا بشأن الخدمات الجوية بين إقليميهما وما وراءهما
law_type: مرسوم سلطاني
law_number: ٦٣ / ٩٥
Title: مرسوم سلطاني رقم ٦٩ / ٨٧ بالتفويض في توقيع مذكرة التفاهم بين حكومة السلطنة ومقاطعة أونتاريو بكندا حول التعاون في مجالي التعليم والتدريب
law_type: مرسوم سلطاني
law_number: ٦٩ / ٨٧
Title: مرسوم سلطاني رقم ٦٧ / ٢٠٠٥ بتعيين مستشار بوزارة التجارة والصناعة
law_type: مرسوم سلطاني
law_number: ٦٧ / ٢٠٠٥
Title: وزارة الثروة الزراعية والسمكية وموارد المياه: قرار وزاري رقم ٢٥٨ / ٢٠٢٣ بحظر استيراد النباتات المصابة ببكتيريا الآفة الحجرية (Xylella fastidiosa) وعوائلها والسلالات المنبثقة عنها والحشرات الناقلة لها
law_type: قرار وزاري
law_number: ٢٥٨ / ٢٠٢٣
Title: مرسوم سلطاني رقم ٢٩ / ٨٨ بإجراء تعديل في قانون البعثات والإعانات الدراسية
law_type: مرسوم سلطاني
law_number: ٢٩ / ٨٨
Title: مرسوم سلطاني رقم ٧٧ / ٢٠٠٤ بإصدار قانون التخصيص
law_type: مرسوم سلطاني
law_number: ٧٧ / ٢٠٠٤
Title: وزارة التجارة والصناعة: قرار وزاري رقم ٧٤ / ٢٠٠٠ بشأن البيانات الإيضاحية وسلامة الأغذية
law_type: قرار وزاري
law_number: ٧٤ / ٢٠٠٠
Title: وزارة الثقافة والرياضة والشباب: قرار وزاري رقم ٨٩ / ٢٠٢٤ بتعديل بعض أحكام القرار الوزاري رقم ٢٣ / ٢٠٢١ بشأن اعتماد نموذج نظام أساسي للاتحادات الرياضية المدعومة حكوميا
law_type: قرار وزاري
law_number: ٨٩ / ٢٠٢٤
Title: جهاز الضرائب: قرار رقم ٤٥٦ / ٢٠٢٢ بتعديل بعض أحكام اللائحة التنفيذية لقانون ضريبة القيمة المضافة
law_type: قرار
law_number: ٤٥٦ / ٢٠٢٢
Title: مرسوم سلطاني رقم ٨٢ / ٩٧ بإضافة مادة جديدة إلى المرسوم السلطاني رقم (٢٥ / ٨٤) بتنظيم القضاء الجزائي
law_type: مرسوم سلطاني
law_number: ٨٢ / ٩٧
Title: مرسوم سلطاني رقم ١١٥ / ٩١ بإجراء تعديل في بعض الوزارات وإنشاء هيئة للتدريب المهني

In [57]:
n_samples = 20
random_samples = df_final.sample(n=n_samples)
for i, row in random_samples.head(300).iterrows():
    print("Title:", row['title'])
    print("title_semantic:", row['title_semantic'])
    print("PREAMBLE:", row['PREAMBLE'])
    print()

Title: مرسوم سلطاني رقم ٤٩ / ٨٣ بالتصديق على زيادة حصة السلطنة في حقوق السحب الخاص في صندوق النقد الدولي
title_semantic: مرسوم | تصديق | علي زيادة حصة السلطنة في حقوق تجريد الخاص في صندوق النقد الدولي
PREAMBLE: نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على المرسوم السلطاني رقم ٢٦ / ٧٥ بإصدار قانون تنظيم الجهاز الإداري للدولة وتعديلاته، وعلى القانون المصرفي العماني رقم ٧ / ٧٤، وعلى المرسوم السلطاني رقم ٣١ / ٧١ بالتفويض بطلب انضمام سلطنة عمان إلى عضوية بعض المنظمات الدولية، وعلى المرسوم السلطاني رقم ٣٤ / ٧٧ بشأن التصديق على موافقة مجلس محافظي البنك المركزي العماني على التعديلات التي طرأت على مواد اتفاقية صندوق النقد الدولي، وعلى المرسوم السلطاني رقم ٥٠ / ٧٨، والمرسوم السلطاني رقم ١ / ٨١ بالتصديق على زيادة حصة السلطنة في حقوق السحب الخاص في صندوق النقد الدولي، وعلى قرار مجلس محافظي صندوق النقد الدولي رقم ٣٤ / ٢ الصادر في ١١ / ١٢ / ١٩٧٨، وبناء على ما تقتضيه المصلحة العامة

Title: وزارة العدل والشؤون القانونية: استدراك
title_semantic: None
PREAMBLE: تنوه وزارة العدل والشؤون القانونية إلى أنه قد وقع خطأ مادي عند نشر قانون القضاء العسكري الصادر بالمرسوم السلطاني رقم ٨٧ / ٢٠٢٢، المنشور في عدد الجريدة الرسمية رقم (١٤٧١)، الصادر في ١٧ من جمادى الأولى ١٤٤٤هـ، الموافق ١١ من ديسمبر ٢٠٢٢م، إذ وردت

Title: مرسوم سلطاني رقم ٧٣ / ٩٢ بإصدار قانون مكافحة الأمراض المعدية
title_semantic: مرسوم | اصدار | قانون مكافحة الامراض المعدية
PREAMBLE: نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على المرسوم السلطاني رقم ٢٦ / ٧٥ بإصدار قانون تنظيم الجهاز الإداري للدولة وتعديلاته، وعلى القانون رقم ٨ / ٧٣ بشأن الأمراض المعدية، وبناء على ما تقتضيه المصلحة العامة

Title: مرسوم سلطاني رقم ٨٨ / ٢٠٠٨ في شأن هيئة تنازع الاختصاص والأحكام
title_semantic: مرسوم | تنظيم | هيئة تنازع الاختصاص والاحكام
PREAMBLE: نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على النظام الأساسي للدولة الصادر بالمرسوم السلطاني رقم ١٠١ / ٩٦، وعلى قانون السلطة القضائية الصادر بالمرسوم السلطاني ر قم ٩٠ / ٩٩، وعلى قانون محكمة القضاء الإداري الصادر بالمرسوم السلطاني رقم ٩١ / ٩٩، وعلى المرسوم السلطاني رقم ٤٧ / ٢٠٠٠ بتحديد اختصاصات وزارة العدل واعتماد هيكلها التنظيمي، وعلى جدول رواتب وعلاوات وبدلات القضاة وأعضاء محكمة القضاء الإداري وأعضاء الادعاء العام الصادر بالمرسوم السلطاني رقم ١١٠ / ٢٠٠٠، وعلى قانون الإجراءات المدنية والتجارية الصادر بالمرسوم السلطاني رقم ٢٩ / ٢٠٠٢، وبناء على ما تقتضيه المصلحة العامة

Title: هيئة البيئة: قرار رقم ١٨٧ / ٢٠٢٤ بتعديل بعض أحكام لائحة تنظيم التصاريح البيئية
title_semantic: قرار | تعديل | بعض احكام لائحة تنظيم التصاريح البيئية
PREAMBLE: استنادا إلى قانون حماية البيئة ومكافحة التلوث الصادر بالمرسوم السلطاني رقم ١١٤ / ٢٠٠١، وإلى لائحة تنظيم التصاريح البيئية الصادرة بالقرار رقم ١٠٧ / ٢٠٢٣، وبناء على ما تقتضيه المصلحة العامة. تقرر

Title: مرسوم سلطاني رقم ١ / ٢٠٢١ باعتماد خطة التنمية الخمسية العاشرة ٢٠٢١-٢٠٢٥م
title_semantic: مرسوم | اعتماد | خطة التنمية الخمسية العاشرة م
PREAMBLE: نحن هيثم بن طارق سلطان عمان بعد الاطلاع على النظام الأساسي للدولة، وعلى قانون التنمية الاقتصادية لسنة ١٩٧٥، وعلى المرسوم السلطاني رقم ٩٤ / ٢٠٢٠ بإنشاء وزارة الاقتصاد وتحديد اختصاصاتها، وبعد العرض على مجلس عمان، وبناء على ما تقتضيه المصلحة العامة

Title: مرسوم سلطاني رقم ١٢ / ٧٧ بإنشاء مديرية عامة للإدارة والخدمات بمحافظة العاصمة
title_semantic: مرسوم | انشاء | مديرية عامة للادارة والخدمات بمحافظة العاصمة
PREAMBLE: نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على قانون تنظيم الجهاز الإداري للدولة رقم ٢٦ / ٧٥ والمرسوم رقم ١٣ / ٧٦ المعدل له والملاحق التابعة له، وعلى قانون الخدمة المدنية رقم ٢٧ / ٧٥، وبناء على ما عرضه مستشارنا الخاص ومحافظ العاصمة بعد مراجعته من ديوان التشريع

Title: مرسوم سلطاني رقم ٤٤ / ٩٤ بتعيين أمين عام بمكتب نائب رئيس الوزراء لشؤون الأمن والدفاع
title_semantic: مرسوم | تعيين | امين عام بمكتب نائب رئيس الوزراء لشؤون الامن والدفاع
PREAMBLE: نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على المرسوم السلطاني رقم ٢٦ / ٧٥ بإصدار قانون تنظيم الجهاز الإداري للدولة وتعديلاته، وبناء على ما تقتضيه المصلحة العامة

Title: وزارة النقل والاتصالات وتقنية المعلومات: قرار وزاري رقم ٦ / ٢٠٢٥ بتعديل القرار الوزاري رقم ٣٤ / ٢٠٢٤ بإصدار اللائحة التنفيذية لقانون حماية البيانات الشخصية
title_semantic: قرار | تعديل | القرار الوزاري اصدار اللائحة التنفيذية لقانون حماية البيانات الشخصية
PREAMBLE: استنادا إلى قانون حماية البيانات الشخصية الصادر بالمرسوم السلطاني رقم ٦ / ٢٠٢٢، وإلى القرار الوزاري رقم ٣٤ / ٢٠٢٤ بإصدار اللائحة التنفيذية لقانون حماية البيانات الشخصية، وبناء على ما تقتضيه المصلحة العامة، تقرر

Title: مرسوم سلطاني رقم ٣٧ / ٢٠١٢ بتشكيل مجلس محافظي البنك المركزي العماني
title_semantic: مرسوم | تشكيل | مجلس محافظي البنك المركزي العماني
PREAMBLE: نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على النظام الأساسي للدولة الصادر بالمرسوم السلطاني رقم ١٠١ / ٩٦، وعلى القانون المصرفي الصادر بالمرسوم السلطاني رقم ١١٤ / ٢٠٠٠، وعلى المرسوم السلطاني رقم ١٠٤ / ٢٠٠٧ بتشكيل مجلس محافظي البنك المركزي العماني، وبناء على ما تقتضيه المصلحة العامة

Title: مرسوم سلطاني رقم ٣٣ / ٢٠٢٢ بالتصديق على اتفاقية بين حكومة سلطنة عمان وحكومة جمهورية فيتنام الاشتراكية حول الإعفاء المتبادل من التأشيرة لحاملي جوازات السفر الدبلوماسية والخاصة والخدمة والرسمية
title_semantic: مرسوم | تصديق | علي اتفاقية بين حكومة سلطنة عمان وحكومة جمهورية فيتنام الاشتراكية حول اعفاء المتبادل من التاشيرة لحاملي جوازات السفر الدبلوماسية والخاصة والخدمة والرسمية
PREAMBLE: نحن هيثم بن طارق سلطان عمان بعد الاطلاع على النظام الأساسي للدولة، وعلى الاتفاقية بين حكومة سلطنة عمان وحكومة جمهورية فيتنام الاشتراكية حول الإعفاء المتبادل من التأشيرة لحاملي جوازات السفر الدبلوماسية والخاصة والخدمة والرسمية، الموقعة في مدينة هانوي بتاريخ ٢٨ من أبريل ٢٠٢٢م، وبناء على ما تقتضيه المصلحة العامة

Title: مرسوم سلطاني رقم ١٣٠ / ٢٠٢٠ بتعيين مندوب دائم للسلطنة لدى منظمة الأمم المتحدة للتربية والعلم والثقافة (اليونسكو)
title_semantic: مرسوم | تعيين | مندوب دائم للسلطنة لدي منظمة الامم المتحدة للتربية والعلم والثقافة (اليونسكو)
PREAMBLE: نحن هيثم بن طارق سلطان عمان بعد الاطلاع على النظام الأساسي للدولة، وعلى قانون الخدمة المدنية الصادر بالمرسوم السلطاني رقم ١٢٠ / ٢٠٠٤، وبناء على ما تقتضيه المصلحة العامة

Title: مرسوم سلطاني رقم ٧٥ / ٩٨ بإجراء تعديل في قانون حماية البيئة ومكافحة التلوث
title_semantic: مرسوم | تعديل | قانون حماية البيئة ومكافحة التلوث
PREAMBLE: نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على النظام الأساسي للدولة الصادر بالمرسوم السلطاني رقم ١٠١ / ٩٦، وعلى قانون حماية البيئة ومكافحة التلوث الصادر بالمرسوم السلطاني رقم ١٠ / ٨٢ وتعديلاته، وبناء على ما تقتضيه المصلحة العامة

Title: مرسوم سلطاني رقم ٢١ / ٨٨ بإجراء تعديلات في قانون تنظيم مزاولة مهنة المحاسبة والمراجعة
title_semantic: مرسوم | تعديل | قانون تنظيم مزاولة مهنة المحاسبة والمراجعة
PREAMBLE: نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على المرسوم السلطاني رقم ٢٦ / ٧٥ بإصدار قانون تنظيم الجهاز الإداري للدولة وتعديلاته، وعلى المرسوم السلطاني رقم ٧٧ / ٨٦ بإصدار قانون تنظيم مزاولة مهنة المحاسبة والمراجعة، وبناء على ما تقتضيه المصلحة العامة

Title: وزارة التعليم العالي: قرار وزاري رقم ٣٨ / ٢٠١٦ بإصدار لائحة تنظيم البحث العلمي بكليات العلوم التطبيقية
title_semantic: قرار | اصدار | لائحة تنظيم البحث العلمي بكليات العلوم التطبيقية
PREAMBLE: استنادا إلى المرسوم السلطاني رقم ٦ / ٢٠٠٢ بتحديد اختصاصات وزارة التعليم العالي واعتماد هيكلها التنظيمي، وإلى المرسوم السلطاني رقم ٦٢ / ٢٠٠٧ بتنظيم كليات العلوم التطبيقية، وإلى اللائحة التنفيذية للمرسوم السلطاني رقم ٦٢ / ٢٠٠٧ بتنظيم كليات العلوم التطبيقية الصادرة بالقرار الوزاري رقم ١٣ / ٢٠١٠، وبناء على ما تقتضيه المصلحة العامة. تقرر

Title: مرسوم سلطاني رقم ١٢٢ / ٢٠٠٨ بتعديل بعض أحكام قانون منح امتياز تطوير وإدارة وتشغيل ميناء صحار الصناعي وإجازة الاتفاقيات المتعلقة به الصادر بالمرسوم السلطاني رقم (٨٠ / ٢٠٠٢)
title_semantic: مرسوم | تعديل | بعض احكام قانون منح امتياز تطوير وادارة وتشغيل ميناء صحار الصناعي تصديق الاتفاقيات المتعلقة به الصادر بالمرسوم السلطاني رقم ( )
PREAMBLE: نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على النظام الأساسي للدولة الصادر بالمرسوم السلطاني رقم ١٠١ / ٩٦، وعلى قانون منح امتياز تطوير وإدارة وتشغيل ميناء صحار الصناعي وإجازة الاتفاقيات المتعلقة به الصادر بالمرسوم السلطاني رقم ٨٠ / ٢٠٠٢، وعلى اتفاقية الامتياز الموقعة بين الحكومة وشركة ميناء صحار الصناعي، وعلى اتفاقية حق الانتفاع بميناء صحار الصناعي، وعلى ملحق اتفاقية الامتياز الموقع بتاريخ ١٤ / ١١/ ٢٠٠٧م، وعلى ملحق اتفاقية حق الانتفاع بميناء صحار الصناعي الموقع بتاريخ ١٣ / ٩ / ٢٠٠٨م، وبناء على ما تقتضيه المصلحة العامة

Title: ديوان البلاط السلطاني: قرار ديواني رقم ٣٠ / ٢٠٢٠ باستبدال عضو المجلس البلدي لمحافظة مسقط
title_semantic: سند | استبدال | عضو المجلس البلدي لمحافظة مسقط
PREAMBLE: استنادا إلى قانون المجالس البلدية الصادر بالمرسوم السلطاني رقم ١١٦ / ٢٠١١، وإلى المرسوم السلطاني رقم ٨١ / ٢٠٢٠ بالتعيين في بعض المناصب، وإلى اللائحة التنفيذية لقانون المجالس البلدية الصادرة بالقرار الديواني رقم ١٥ / ٢٠١٢، وإلى القرار الديواني رقم ٣٩ / ٢٠١٦ بتسمية أعضاء المجلس البلدي للفترة الثانية بمحافظة مسقط، وبناء على ما تقتضيه المصلحة العامة. تقرر

Title: مرسوم سلطاني رقم ٢٥ / ٧٨ بنقل وكيل وزارة الداخلية إلى وزارة شؤون الديوان السلطاني
title_semantic: مرسوم | نقل | وكيل وزارة الداخلية الي وزارة شؤون الديوان السلطاني
PREAMBLE: نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على المرسوم السلطاني رقم ٢٦ / ٧٥ بإصدار قانون تنظيم الجهاز الإداري للدولة وتعديلاته، وعلى المرسوم السلطاني رقم ٢٧ / ٧٥ بإصدار قانون الخدمة المدنية، ونظرا لما تقتضيه المصلحة العامة

Title: وزارة البيئة والشؤون المناخية: قرار وزاري رقم ١٢ / ٢٠١٧ بتعديل بعض أحكام لائحة إعادة استخدام مياه الصرف وتصريفها
title_semantic: قرار | تعديل | بعض احكام لائحة اعادة استخدام مياه الصرف وتصريفها
PREAMBLE: استنادا إلى قانون حماية البيئة ومكافحة التلوث الصادر بالمرسوم السلطاني رقم ١١٤ / ٢٠٠١، وإلى المرسوم السلطاني رقم ٩٠ / ٢٠٠٧ بإنشاء وزارة البيئة والشؤون المناخية، وإلى المرسوم السلطاني رقم ١٨ / ٢٠٠٨ بتحديد اختصاصات وزارة البيئة والشؤون المناخية واعتماد هيكلها التنظيمي، وإلى لائحة إعادة استخدام مياه الصرف وتصريفها الصادرة بالقرار الوزاري رقم ١٤٥ / ٩٣، وإلى موافقة وزارة المالية، وبناء على ما تقتضيه المصلحة العامة، تقرر

Title: مرسوم سلطاني رقم ٦٣ / ٨١ بتعيين سفير السلطنة لدى جمهورية السودان الديمقراطية سفير فوق العادة ومفوض للسلطنة غير مقيم لدى جمهورية النيجر
title_semantic: مرسوم | تعيين | سفير السلطنة لدي جمهورية السودان الديمقراطية سفير فوق العادة ومفوض للسلطنة غير مقيم لدي جمهورية النيجر
PREAMBLE: نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على المرسوم السلطاني رقم ٢٦ / ٧٥ بإصدار قانون تنظيم الجهاز الإداري للدولة وتعديلاته، وعلى المرسوم السلطاني رقم ٤٤ / ٨٠ بإصدار قانون السلكين الدبلوماسي والقنصلي، وبناء على ما تقتضيه المصلحة العامة

In [58]:
import pandas as pd
import re

# 1. تابع نرمال‌سازی برای یکدست کردن متن
def normalize_arabic(text):
    text = re.sub(r'[أإآ]', 'ا', text)
    text = re.sub(r'ة', 'ه', text)
    text = re.sub(r'ى', 'ي', text)
    text = re.sub(r'ؤ', 'و', text)
    text = re.sub(r'ئ', 'ي', text)
    return text

# 2. لیست توسعه‌یافته کلمات توقف (بر اساس خروجی‌های شما)
custom_stopwords = set([
    # کلمات پایه قبلی (با نرمال‌سازی)
    'مرسوم', 'سلطاني', 'رقم', 'قرار', 'وزاري', 'وزاره', 'قانون',
    'نحن', 'قابوس', 'بن', 'سعيد', 'سلطان', 'عمان', 'بعد', 'الاطلاع',
    'علي', 'في', 'من', 'الي', 'عن', 'بناء', 'ما', 'تقتضيه', 'المصلحة',
    'العامة', 'الصادر', 'بالمرسوم', 'النظام', 'الاساسي', 'للدوله',
    'وتعديلاته', 'استنادا', 'اللايحه', 'التنفيذيه', 'القرار', 'وتحديد',
    'اختصاصاتها', 'واعتماد', 'هيكلها', 'التنظيمي', 'تقرر', 'بشان',
    'تاريخ', 'الموافق', 'م', 'ه', 'سنه', 'لعام', 'لايحه', 'اصدار',
    'باصدار', 'بتعديل', 'تعديل', 'وبناء', 'والي', 'وعلي', 'التصديق', 'بالتصديق',

    # --- موارد جدید اضافه شده بر اساس نمونه‌های شما ---
    # نام‌های جدید
    'هيثم', 'طارق', 'ال',

    # افعال و اسامی اجرایی (Procedural)
    'تعيين', 'بتعيين', 'نقل', 'بنقل', 'ترقيه', 'بترقيه', 'انشاء', 'بانشاء',
    'الغاء', 'بالغاء', 'اجازه', 'باجازه', 'تجديد', 'بتجديد', 'تمديد', 'بتمديد',
    'تطبيق', 'بتطبيق', 'تنظيم', 'بتنظيم', 'تقرير', 'بتقرير', 'اعاده', 'باعاده',
    'تشكيل', 'بتشكيل', 'منح', 'بمنح', 'فرض', 'بفرض', 'حظر', 'بحظر',
    'استحداث', 'باستحداث', 'اعتبار', 'باعتبار', 'تخويل', 'بتخويل',
    'تسميه', 'بتسميه', 'اضافه', 'باضافه', 'استبدال', 'باستبدال',
    'تصريح', 'باستقدام', 'ايقاف', 'بايقاف', 'توقيع', 'بالتوقيع', 'تفويض', 'بالتفويض',

    # کلمات عمومی حقوقی و اداری (Generic Entities)
    'حكومه', 'سلطنه', 'جمهوريه', 'دوله', 'مجلس', 'لجنه', 'هيي', 'موسسه', 'شركه', 'وشركه',
    'مكتب', 'دايره', 'مديريه', 'قسم', 'فرع', 'منطقه', 'محافظه', 'ولايه',
    'ماده', 'الماده', 'بند', 'فقره', 'احكام', 'الاحكام', 'نصوص',
    'اتفاقيه', 'مذكره', 'تفاهم', 'بروتوكول', 'وثيقه', 'عقد',
    'رئيس', 'نايب', 'وكيل', 'مدير', 'عام', 'امين', 'عضو', 'اعضاء', 'سفير',
    'الدرجه', 'الخاصه', 'الماليه', 'الاداري', 'التنفيذي', 'المرفق', 'الملحق',
    'بعض', 'كل', 'جميع', 'غير', 'شوي', 'لدى', 'بين', 'حول', 'ضمن', 'ذات',
    'الجهاز', 'السلكين', 'الدبلوماسي', 'والقنصلي', 'الموحد', 'الرسميه', 'الجريده',
    'الاول', 'الثاني', 'الجزء', 'المتبقي', 'مشروع', 'لمشروع', 'سند', 'صنه'
])

def extract_tags_optimized(row):
    # ترکیب ستون‌ها
    text_source = f"{str(row['title'])} {str(row['title_semantic'])} {str(row['PREAMBLE'])}"

    # پاکسازی اولیه
    text_clean = re.sub(r'[^\w\s]', ' ', text_source)
    text_clean = re.sub(r'\d+', '', text_clean)

    # نرمال‌سازی متن (بسیار مهم برای حذف دایره لغات تکراری)
    text_normalized = normalize_arabic(text_clean)

    words = text_normalized.split()

    tags = []
    seen = set()

    for word in words:
        original_word = word # کلمه اصلی نرمال شده
        processed_word = word

        # حذف پیشوندهای عربی (ال، ب، و، ل، ف) اگر طول کلمه اجازه دهد
        # مرحله 1: حذف "ال"
        if processed_word.startswith('ال') and len(processed_word) > 4:
            processed_word = processed_word[2:]

        # مرحله 2: حذف حروف ربط چسبیده (و، ف، ب، ل)
        # فقط در صورتی حذف می‌کنیم که کلمه باقی‌مانده هنوز معنی‌دار باشد (طول > 3)
        if processed_word.startswith(('و', 'ف', 'ب', 'ل')) and len(processed_word) > 4:
            processed_word = processed_word[1:]
            # دوباره چک کردن "ال" بعد از حذف حرف ربط (مثلاً "والتخطيط" -> "تخطيط")
            if processed_word.startswith('ال') and len(processed_word) > 4:
                processed_word = processed_word[2:]

        # چک کردن کلمه نهایی با لیست توقف
        if (processed_word not in custom_stopwords and
            original_word not in custom_stopwords and
            len(processed_word) > 3): # کلمات خیلی کوتاه (2 و 3 حرفي) معمولا نویز هستند

            if processed_word not in seen:
                tags.append(processed_word) # کلمه پردازش شده (بدون ال و...) را ذخیره می‌کنیم
                seen.add(processed_word)

    if not tags:
        return None

    # برگرداندن 6 تگ اول (تعداد کمتر اما با کیفیت‌تر)
    return tags[:6]

# اعمال روی دیتا فریم
df_final['semantic_tags'] = df_final.apply(extract_tags_optimized, axis=1)

# نمایش چند نمونه برای تست
print(df_final[['title', 'semantic_tags']].head(10))

                                               title  \
0  مرسوم سلطاني رقم ٢ / ٧٤ بالموافقة على تأسيس مك...
1  مرسوم سلطاني رقم ٣ / ٧٤ بالموافقة على تأسيس “ش...
2  مرسوم سلطاني رقم ٦ / ٧٤ بخصوص إعادة تنظيم دائر...
3  مرسوم سلطاني رقم ١١ / ٧٤ بتعديل الفقرة (٣) من ...
4  مرسوم سلطاني رقم ١٤ / ٧٤ بالتصديق على اتفاقية ...
5  مرسوم سلطاني رقم ١٧ / ٧٤ بالتصديق على اتفاقية ...
6  مرسوم سلطاني رقم ٣٠ / ٧٤ بتعيين سكرتير أول في ...
7  مرسوم سلطاني رقم ٣١ / ٧٤ بتعيين مستشار في وزار...
8  مرسوم سلطاني رقم ٣٢ / ٧٤ بتعيين وزير مفوض في و...
9  مرسوم سلطاني رقم ٣٩ / ٧٤ بتعيين مستشار بوزارة ...

                                     semantic_tags
0  [موافقه, تاسيس, وطني, لاستشارات, هندسيه, تخطيط]
1  [موافقه, تاسيس, طنيه, لمقاولات, تصديق, مقاولات]
2         [خصوص, حسابات, خزينه, نظرا, مصلحه, عامه]
3        [جنسيه, عماني, لسنه, عمانيه, عرضه, معالي]
4        [تاسيس, مصرف, دولي, عربي, لتجاره, خارجيه]
5   [تاسيس, عربي, لتنميه, اقتصاديه, افريقيا, نظام]
6      [سكرتير, خارجيه, مادتين, لسنه, عرضه, علينا]
7       [مستشار, خارجيه, مادتين, لسنه, عرضه, وزير]
8         [وزير, مفوض, خارجيه, مادتين, لسنه, عرضه]
9      [مستشار, خارجيه, مادتين, عرضه, علينا, وزير]

In [59]:
n_samples = 200
random_samples = df_final.sample(n=n_samples)
for i, row in random_samples.head(300).iterrows():

    print("semantic_tags:", row['semantic_tags'])

semantic_tags: ['جنسيه', 'عمانيه', 'مصلحه', 'عامه']
semantic_tags: ['معتمد', 'مملكه', 'مغربيه', 'سفيرا', 'مقيم', 'اسلاميه']
semantic_tags: ['رييس', 'اداره', 'غرفه', 'تجاره', 'صناعه', 'مصلحه']
semantic_tags: ['تشجيع', 'حمايه', 'متبادله', 'لاستثمارات', 'مملكه', 'سويد']
semantic_tags: ['منفعه', 'عامه', 'تطوير', 'طينه', 'بخور', 'ملكيه']
semantic_tags: ['منظمه', 'لاستثمار', 'خليجي', 'شركات', 'تجاريه', 'ضريبه']
semantic_tags: ['داخليه', 'تحديد', 'رسوم', 'اثمان', 'التي', 'تحصلها']
semantic_tags: ['مساعد', 'زراء', 'مصلحه', 'عامه']
semantic_tags: ['وزير', 'محافظ', 'مسقط', 'ممارسه', 'نشاط', 'تداول']
semantic_tags: ['موازنه', 'عامه', 'تصديق', 'مالي', 'مصلحه']
semantic_tags: ['تحديد', 'رسوم', 'دعاوي', 'مدنيه', 'احوال', 'شخصيه']
semantic_tags: ['تجاره', 'صناعه', 'ترويج', 'استثمار', 'مبادي', 'حوكمه']
semantic_tags: ['امتياز', 'استكشاف', 'تعدين', 'عالميه', 'متكامله', 'لهندسه']
semantic_tags: ['دكتور', 'سالم', 'حمدان', 'سويد', 'اخزمي', 'كيلا']
semantic_tags: ['هييه', 'عامه', 'لكهرباء', 'مياه', 'اداري', 'شوون']
semantic_tags: ['موافقه', 'انضمام', 'دوليه', 'مسووليه', 'مدنيه', 'اضرار']
semantic_tags: ['برفع', 'مستوي', 'دايرتي', 'شوون', 'رياضيه', 'محافظتي']
semantic_tags: ['تحديد', 'اختصاصات', 'اسكان', 'اعتماد', 'كهرباء', 'مياه']
semantic_tags: ['خدمه', 'مدنيه', 'اختصاصاته', 'تحديد', 'مصلحه', 'عامه']
semantic_tags: ['تعليم', 'عالي', 'علمي', 'ابتكار', 'تنظيميه', 'برنامج']
semantic_tags: ['غرفه', 'تجاره', 'صناعه', 'مصلحه', 'عامه']
semantic_tags: ['اعفاء', 'شركات', 'ساطه', 'اوراق', 'ضريبه', 'تجاريه']
semantic_tags: ['غرفه', 'تجاره', 'صناعه', 'نظام', 'مركز', 'لتحكيم']
semantic_tags: ['تنازل', 'كونكويست', 'اكسبلوريشن', 'حصتها', 'تروليه', 'مورخه']
semantic_tags: ['اجراء', 'ترقيات', 'تعيينات', 'عسكريه', 'مصلحه', 'عامه']
semantic_tags: ['هييه', 'رسيل', 'صناعيه', 'مسووليه', 'اشراف', 'لديه']
semantic_tags: ['قضاه', 'قاضي', 'محكمه', 'عليا', 'سلطه', 'قضاييه']
semantic_tags: ['انضمام', 'اتفاقيتين', 'دوليتين', 'قواعد', 'تصادم', 'بحار']
semantic_tags: ['خدمه', 'مدنيه', 'مركزي', 'لمساءله', 'اداريه', 'نظام']
semantic_tags: ['تحديد', 'صلاحيات', 'مستشار', 'لشوون', 'جزاييه', 'جزاء']
semantic_tags: ['سفيرين', 'مصلحه', 'عامه']
semantic_tags: ['شوون', 'قانونيه', 'ضبطيه', 'قضاييه', 'لبعض', 'موظفي']
semantic_tags: ['اثيوبيا', 'خدمات', 'جويه', 'اقليميهما', 'راءهما', 'اقليمهما']
semantic_tags: ['مسندم', 'خدمه', 'مدنيه', 'لسنه', 'ملحق', 'معدل']
semantic_tags: ['اجراء', 'طنيه', 'لطواري', 'تحديد', 'اختصاصات', 'دفاع']
semantic_tags: ['تجاره', 'صناعه', 'يانات', 'ايضاحيه', 'سلامه', 'اغذيه']
semantic_tags: ['اعتماد', 'تنميه', 'خمسيه', 'سابعه', 'اقتصاديه', 'لسنه']
semantic_tags: ['تدريب', 'مهني', 'شوون', 'لديات', 'اقليميه', 'خدمه']
semantic_tags: ['سفراء', 'مقيمين', 'خارجيه', 'مصلحه', 'عامه']
semantic_tags: ['هييه', 'اتصالات', 'تسجيل', 'استخدام', 'ترددات', 'اجهزه']
semantic_tags: ['اسكان', 'خدمه', 'مدنيه', 'مصلحه', 'عامه']
semantic_tags: ['قنصليه', 'عامه', 'سنغافوره', 'خارجيه', 'مصلحه']
semantic_tags: ['عامله', 'تحديد', 'الحد', 'ادني', 'اجور', 'عمانيه']
semantic_tags: ['نظام', 'هييه', 'عامه', 'لدفاع', 'مدني', 'اسعاف']
semantic_tags: ['منفعه', 'عامه', 'منتجع', 'سياحي', 'ملكيه', 'لمنفعه']
semantic_tags: ['نسبه', 'حقوق', 'التزامات', 'نفطيه', 'لمنطقه', 'تصديق']
semantic_tags: ['شوون', 'قانونيه', 'ضبطيه', 'قضاييه', 'لبعض', 'موظفي']
semantic_tags: ['تنازل', 'ماري', 'تروليوم', 'يمتد', 'حقوقها', 'تزاماتها']
semantic_tags: ['مقيم', 'خارجيه', 'مصلحه', 'عامه']
semantic_tags: ['زراء', 'قيرغيزيه', 'اعفاء', 'متبادل', 'تاشيره', 'حاملي']
semantic_tags: ['منفعه', 'عامه', 'ازدواجيه', 'طريق', 'حمريه', 'مرحله']
semantic_tags: ['جنسيه', 'عمانيه', 'مصلحه', 'عامه']
semantic_tags: ['صندوق', 'عماني', 'لاستثمار', 'نظامه', 'احتياطي', 'مالي']
semantic_tags: ['هييه', 'تقنيه', 'معلومات', 'نظام', 'هييات', 'موسسات']
semantic_tags: ['اجراء', 'تعداد', 'لسكان', 'مساكن', 'منشات', 'احصايي']
semantic_tags: ['زراعه', 'ثروه', 'سمكيه', 'استيراد', 'طيور', 'يطري']
semantic_tags: ['سفاره', 'لسلطنه', 'مملكه', 'تايلند', 'مصلحه', 'عامه']
semantic_tags: ['تعديلات', 'مصرفي', 'اراضي', 'وبعد', 'مصلحه', 'عامه']
semantic_tags: ['اسكان', 'تخطيط', 'عمراني', 'رسوم', 'اثمان', 'التي']
semantic_tags: ['اقتصاد', 'وطني', 'خدمه', 'مدنيه', 'اجراء', 'زاري']
semantic_tags: ['طيران', 'مدني', 'نظرا', 'مصلحه', 'عامه', 'عرضه']
semantic_tags: ['تجاره', 'صناعه', 'مزيونه', 'انضمام', 'مراكش', 'منظمه']
semantic_tags: ['زراعه', 'ثروه', 'سمكيه', 'برفع', 'استيراد', 'حيوانات']
semantic_tags: ['برفع', 'مستوي', 'شوون', 'اداريه', 'ماليه', 'هييه']
semantic_tags: ['اجراء', 'مصلحه', 'عامه']
semantic_tags: ['مزاوله', 'مهنه', 'صيدله', 'موسسات', 'صيدلانيه', 'زاري']
semantic_tags: ['سياحه', 'تحديد', 'رسوم', 'مشاركه', 'معارض', 'سياحيه']
semantic_tags: ['عراق', 'اعفاء', 'متبادل', 'تاشيره', 'حاملي', 'جوازات']
semantic_tags: ['مسمي', 'ظيفي', 'خدمه', 'مدنيه', 'تحديد', 'منصب']
semantic_tags: ['عامله', 'مزاوله', 'تحديد', 'اختصاصات', 'مصلحه', 'عامه']
semantic_tags: ['طيران', 'مدني', 'دولي', 'تصديق']
semantic_tags: ['ترخيص', 'اولي', 'لشركه', 'عمانيه', 'قطريه', 'لاتصالات']
semantic_tags: ['لتربيه', 'تعليم', 'تدريب', 'مهني', 'عرضه', 'علينا']
semantic_tags: ['غرفه', 'تجاره', 'صناعه', 'نظام', 'مركز', 'لتحكيم']
semantic_tags: ['موزانه', 'عامه', 'تصديق', 'مالي', 'مصلحه']
semantic_tags: ['تجاره', 'صناعه', 'تحديد', 'رسوم', 'تراخيص', 'مكاتب']
semantic_tags: ['ثروه', 'زراعيه', 'سمكيه', 'موارد', 'مياه', 'استيراد']
semantic_tags: ['شوون', 'قانونيه', 'تحويلات', 'اعمال', 'محاماه', 'مكافحه']
semantic_tags: ['نزويلا', 'وليفاريه', 'اعفاء', 'متطلبات', 'تاشيره', 'حاملي']
semantic_tags: ['مقيم', 'خارجيه', 'مصلحه', 'عامه']
semantic_tags: ['حقوق', 'انسان', 'مصلحه', 'عامه']
semantic_tags: ['هييه', 'اتصالات', 'تقديم', 'خدمه', 'مركز', 'هاتفي']
semantic_tags: ['تولي', 'اعمال', 'اسكان', 'وكاله', 'تكليف', 'خدمه']
semantic_tags: ['يمنيه', 'مجالات', 'رياضيه', 'شبابيه', 'تصديق', 'موقع']
semantic_tags: ['خارجيه', 'مصلحه', 'عامه']
semantic_tags: ['اتصالات', 'لمواني', 'شوون', 'حريه', 'خدمه', 'مدنيه']
semantic_tags: ['امتياز', 'مرفق', 'كهرباء', 'صلاله', 'شركات', 'تجاريه']
semantic_tags: ['انتاج', 'تخزين', 'اسلحه', 'كيمياييه', 'تدمير', 'تصديق']
semantic_tags: ['شرطه', 'سلطانيه', 'مرور', 'صادره', 'مصلحه', 'عامه']
semantic_tags: ['عامه', 'لكشافه', 'مرشدات', 'تربيه', 'تعليم', 'حركه']
semantic_tags: ['اعتماد', 'هيكل', 'اسكان', 'مصلحه', 'عامه']
semantic_tags: ['عاده', 'مفوض', 'لسلطنه', 'مقيم', 'مملكه', 'سويد']
semantic_tags: ['ترخيص', 'اولي', 'لشركه', 'عمانيه', 'لنطاق', 'عريض']
semantic_tags: ['هييه', 'عامه', 'لسوق', 'قواعد', 'تامين', 'شركات']
semantic_tags: ['اعتماد', 'هيكل', 'كهرباء', 'مياه', 'مصلحه', 'عامه']
semantic_tags: ['شوون', 'قانونيه', 'ضبطيه', 'قضاييه', 'لبعض', 'موظفي']
semantic_tags: ['لقوي', 'عامله', 'طنيه', 'اعتماد', 'هيكل', 'شوون']
semantic_tags: ['تجاره', 'صناعه', 'صحار', 'مناطق', 'جمارك', 'لدول']
semantic_tags: ['خدمه', 'مدنيه', 'صادره', 'اجتماعه', 'منعقد', 'مصلحه']
semantic_tags: ['اجراء', 'تعيينات', 'ترقيات', 'عسكريه', 'دفاع', 'اكاديميه']
semantic_tags: ['جدول', 'رواتب', 'علاوات', 'بدلات', 'قضاه', 'محكمه']
semantic_tags: ['خدمه', 'مدنيه', 'اختصاصاته', 'مصلحه', 'عامه']
semantic_tags: ['اختصاصات', 'عامه', 'لمواصفات', 'مقاييس', 'تجاره', 'صناعه']
semantic_tags: ['سفاره', 'لسلطنه', 'مملكه', 'هولندا', 'مصلحه', 'عامه']
semantic_tags: ['خارجيه', 'مصلحه', 'عامه']
semantic_tags: ['دوليه', 'تركيه', 'تصديق', 'موقعه', 'مسقط', 'يناير']
semantic_tags: ['جمارك', 'لدول', 'تعاون', 'خليج', 'عربيه', 'نظام']
semantic_tags: ['منفعه', 'عامه', 'جسور', 'علويه', 'طريق', 'رسيل']
semantic_tags: ['اختصاصات', 'حمايه', 'بييه', 'موارد', 'مياه', 'هيكله']
semantic_tags: ['اجراء', 'تعديلات', 'شعارها', 'نشيدها', 'وطني', 'مصلحه']
semantic_tags: ['تجنب', 'ازدواج', 'ضريبي', 'ومنع', 'تهرب', 'نسبه']
semantic_tags: ['اسكان', 'تحديد', 'تمليك', 'تاجير', 'اراضي', 'حكوميه']
semantic_tags: ['منفعه', 'عامه', 'داخليه', 'بديه', 'ملكيه', 'لمنفعه']
semantic_tags: ['منظمه', 'انتلسات', 'تشغيل', 'تصديق', 'مذكوره', 'مصلحه']
semantic_tags: ['منفعه', 'عامه', 'مرسي', 'لقوارب', 'شطيفي', 'ملكيه']
semantic_tags: ['سجلات', 'طنيه', 'شرطه', 'مكافحه', 'جرايم', 'تقنيه']
semantic_tags: ['قطاع', 'تدريب', 'مهني', 'نظام', 'مسمي', 'تعليم']
semantic_tags: ['سفراء', 'مقيمين', 'مصلحه', 'عامه']
semantic_tags: ['تجنب', 'ازدواج', 'ضريبي', 'ومنع', 'تهرب', 'ارباح']
semantic_tags: ['هييه', 'اتصالات', 'متطلبات', 'جوده', 'خدمه', 'التي']
semantic_tags: ['استثمار', 'اجنبي', 'كالات', 'تجاريه', 'ملكيه', 'لمنفعه']
semantic_tags: ['مقيم', 'خارجيه', 'مصلحه', 'عامه']
semantic_tags: ['شوري', 'داخليه', 'صادره', 'تعديلاتها', 'مصلحه', 'عامه']
semantic_tags: ['سفاره', 'مصلحه', 'عامه']
semantic_tags: ['خارجيه', 'جمعيه', 'صداقه', 'عمانيه', 'اسبانيه', 'زاري']
semantic_tags: ['ثروه', 'زراعيه', 'سمكيه', 'موارد', 'مياه', 'سلامه']
semantic_tags: ['مكافحه', 'امراض', 'معديه', 'مصلحه', 'عامه']
semantic_tags: ['عضويه', 'رييس', 'محافظي', 'مركزي', 'عماني', 'لبنك']
semantic_tags: ['تحديد', 'اختصاصات', 'زراعه', 'اعتماد', 'ثروه', 'سمكيه']
semantic_tags: ['رييس', 'هييه', 'منازعات', 'تجاريه', 'خدمه', 'مدنيه']
semantic_tags: ['علمي', 'مالي', 'مناقصات', 'رقابه', 'اداريه', 'لقانون']
semantic_tags: ['برفع', 'مستوي', 'نيابه', 'مزيونه', 'اعتماد', 'تقسيم']
semantic_tags: ['تربيه', 'تعليم', 'تنظيميه', 'لمدارس', 'مدارس', 'صادره']
semantic_tags: ['انضمام', 'تقديم', 'مساعده', 'حاله', 'وقوع', 'حادث']
semantic_tags: ['تجاره', 'صناعه', 'زاري', 'اسعار', 'مخفضه', 'معروضات']
semantic_tags: ['تراث', 'سياحه', 'تحديد', 'رسوم', 'زياره', 'قلاع']
semantic_tags: ['رقابه', 'اداريه', 'جزاء', 'عماني', 'معاشات', 'مكافات']
semantic_tags: ['جامعه', 'تقنيه', 'علوم', 'تطبيقيه', 'مسندم', 'نظام']
semantic_tags: ['اعتماد', 'داخليه', 'زراء', 'اجراء', 'زاري', 'مصلحه']
semantic_tags: ['تحديد', 'اختصاصات', 'تجاره', 'صناعه', 'اعتماد', 'مصلحه']
semantic_tags: ['مساعد', 'رييس', 'اركان', 'دفاع', 'لعمليات', 'مصلحه']
semantic_tags: ['تعليم', 'عالي', 'علمي', 'ابتكار', 'شروط', 'ضوابط']
semantic_tags: ['ثروه', 'زراعيه', 'سمكيه', 'موارد', 'مياه', 'وجمع']
semantic_tags: ['منحه', 'رفيعه', 'خدمه', 'مدنيه', 'درجه', 'خاصه']
semantic_tags: ['شوون', 'اداريه', 'ماليه', 'ديوان', 'تشريفات', 'درجه']
semantic_tags: ['لايات', 'متحده', 'امريكيه', 'ديوان', 'خارجيه', 'مصلحه']
semantic_tags: ['نظام', 'جامعات', 'لتعليم', 'عالي', 'مصلحه', 'عامه']
semantic_tags: ['اختصاصات', 'شوون', 'موارد', 'طاقه', 'صندوق', 'احتياطي']
semantic_tags: ['عاده', 'مفوض', 'لسلطنه', 'مقيم', 'تنزانيا']
semantic_tags: ['لسلطنه', 'ماليزيا', 'مصلحه', 'عامه']
semantic_tags: ['صلاله', 'تجاري', 'شركات', 'تجاريه', 'ضريبه', 'ارباح']
semantic_tags: ['محكمه', 'قضاء', 'تحكيم', 'منازعات', 'مدنيه', 'تجاريه']
semantic_tags: ['ديوان', 'بلاط', 'ديواني', 'تحديد', 'كتابي', 'ظفار']
semantic_tags: ['صندوق', 'احتياطي', 'معاملات', 'خارجيه', 'داخليه', 'مصلحه']
semantic_tags: ['هييه', 'عامه', 'لسوق', 'ثيقه', 'موحده', 'لتامين']
semantic_tags: ['زراعه', 'ثروه', 'سمكيه', 'استزراع', 'احياء', 'ماييه']
semantic_tags: ['مركز', 'سلامه', 'جوده', 'غذاء', 'لديات', 'اقليميه']
semantic_tags: ['تجاره', 'صناعه', 'مواصفه', 'قياسيه', 'عمانيه', 'ملزمه']
semantic_tags: ['وزير', 'تجاره', 'صناعه', 'اعفاء', 'اداره', 'يمثلون']
semantic_tags: ['زراعه', 'ثروه', 'سمكيه', 'برفع', 'استيراد', 'طيور']
semantic_tags: ['مسقط', 'لايداع', 'تسجيل', 'اوراق', 'شركات', 'تجاريه']
semantic_tags: ['زراعه', 'ثروه', 'سمكيه', 'برفع', 'استيراد', 'بلطي']
semantic_tags: ['نظام', 'استحقاق', 'اراضي', 'حكوميه', 'مصلحه', 'عامه']
semantic_tags: ['وزير', 'كهرباء', 'مياه', 'عضوا', 'مصادر', 'ثروه']
semantic_tags: ['مقيم', 'مصلحه', 'عامه']
semantic_tags: ['تربيه', 'تعليم', 'مسمي', 'سكرتاريه', 'عامه', 'طنيه']
semantic_tags: ['مواد', 'غرفه', 'تجاره', 'صناعه', 'اجراء', 'مصلحه']
semantic_tags: ['اجراءات', 'جزاييه', 'مصلحه', 'عامه']
semantic_tags: ['اعتماد', 'هيكل', 'لامانه', 'عامه', 'زراء', 'مصلحه']
semantic_tags: ['ثناييه', 'تنزانيا', 'متحده', 'خدمات', 'جويه', 'اقليميهما']
semantic_tags: ['هيكل', 'حمايه', 'بييه', 'مكافحه', 'تلوث', 'مصلحه']
semantic_tags: ['مكررا', 'نظام', 'جمارك', 'لسنه', 'مصلحه', 'عامه']
semantic_tags: ['تنازل', 'انترناشونال', 'تروليم', 'كوربوريشن', 'حقوقها', 'تزاماتها']
semantic_tags: ['اختصاصات', 'مواصلات', 'وبعد', 'قاضي', 'احداث', 'زارات']
semantic_tags: ['رييس', 'محكمه', 'جزاييه', 'عاصمه', 'نايبه', 'جزاء']
semantic_tags: ['منفعه', 'عامه', 'طريق', 'ريمي', 'مزدوج', 'ملكيه']
semantic_tags: ['مركزي', 'عماني', 'عليا', 'لاستقرار', 'مالي', 'ايحتها']
semantic_tags: ['بيان', 'كوبنهاجن', 'للحد', 'تعاطي', 'منشطات', 'رياضه']
semantic_tags: ['تعديلات', 'نفطيه', 'اموكو', 'لبترول', 'موقعه', 'تصديق']
semantic_tags: ['مقيم', 'مصلحه', 'عامه']
semantic_tags: ['رييس', 'زراء', 'شوون', 'دفاع', 'تحديد', 'اختصاصات']
semantic_tags: ['اعتماد', 'هيكل', 'زراعه', 'اسماك', 'مصلحه', 'عامه']
semantic_tags: ['حمايه', 'بييه', 'مكافحه', 'تلوث', 'مراقبه', 'بحري']
semantic_tags: ['منشور', 'مالي', 'دليل', 'تصنيف', 'ميزانيه', 'عامه']
semantic_tags: ['شوري', 'داخليه', 'لمجلس', 'مصلحه', 'عامه']
semantic_tags: ['محكمه', 'رييس', 'سلطه', 'قضاييه', 'مصلحه', 'عامه']
semantic_tags: ['تجاره', 'صناعه', 'سماح', 'مواطني', 'تعاون', 'لدول']
semantic_tags: ['مستشار', 'اكاديمي', 'تعليم', 'عالي', 'خدمه', 'مدنيه']
semantic_tags: ['تنميه', 'اجتماعيه', 'خدمه', 'مدنيه', 'مصلحه', 'عامه']
semantic_tags: ['اطاريه', 'لمساعده', 'مجال', 'حمايه', 'مدنيه', 'تصديق']
semantic_tags: ['نظام', 'هييه', 'عامه', 'حمايه', 'مستهلك', 'هييات']
semantic_tags: ['هييه', 'عامه', 'لسوق', 'قواعد', 'تامين', 'شركات']
semantic_tags: ['موافقه', 'انضمام', 'معاهده', 'اعتراف', 'دولي', 'حقوق']
semantic_tags: ['زراعه', 'ثروه', 'سمكيه', 'زاري', 'صادرات', 'اسماك']
semantic_tags: ['مملكه', 'اسبانيا', 'تجنب', 'ازدواج', 'ضريبي', 'ومنع']
semantic_tags: ['معهد', 'قضاء', 'شرعي', 'ارشاد', 'مصلحه', 'عامه']
semantic_tags: ['ثالث', 'مياه', 'اقليميه', 'قاري', 'محصوره', 'لصيد']
semantic_tags: ['اجراء', 'تعداد', 'الكتروني', 'لسكان', 'مساكن', 'منشات']
semantic_tags: ['هييه', 'اتصالات', 'ترخيض', 'اولي', 'لاتصالات', 'تشغيل']
semantic_tags: ['خدمه', 'مدنيه', 'مصلحه', 'عامه']

In [64]:
n_samples = 10
random_samples = df_final.sample(n=n_samples)
for i, row in random_samples.head(10).iterrows():
    print("chunks:", row['chunks'])
    print("="*60)

chunks: [TITLE]
هيئة تنظيم الاتصالات: قرار رقم ١ / ٢٠١٥ بتعديل بعض أحكام القرار رقم ١٣٣ / ٢٠٠٨ بإصدار لائحة تنظيم تسجيل واستخدام الترددات والأجهزة الراديوية وتحديد أسعارها

[TOPIC]
قرار | تعديل | بعض احكام القرار اصدار لائحة تنظيم تسجيل واستخدام الترددات والاجهزة الراديوية تحديد اسعارها

[PREAMBLE]
استنادا إلى قانون تنظيم الاتصالات الصادر بالمرسوم السلطاني رقم ٣٠ / ٢٠٠٢، وإلى اللائحة التنفيذية لقانون تنظيم الاتصالات الصادرة بالقرار رقم ١٤٤ / ٢٠٠٨، وإلى القرار رقم ١٣٣ / ٢٠٠٨ بإصدار لائحة تنظيم تسجيل واستخدام الترددات والأجهزة الراديوية وتحديد أسعارها، وإلى موافقة مجلس الإدارة في اجتماعه رقم ٣ / ٢٠١٤ بتاريخ ٢١ من يوليو ٢٠١٤م، وبناء على ما تقتضيه المصلحة العامة. تقرر

[ARTICLES]
المادة الثانية : يلغى كل ما يخالف هذا القرار، أو يتعارض مع أحكامه.

المادة الثالثة : ينشر هذا القرار في الجريدة الرسمية، ويعمل به من اليوم التالي لتاريخ نشره.
============================================================
chunks: [TITLE]
مرسوم سلطاني رقم ٦٣ / ٩٥ بالتفويض في التوقيع على اتفاقية بين حكومة سلطنة عمان وحكومة جمهورية أوغندا بشأن الخدمات الجوية بين إقليميهما وما وراءهما

[TOPIC]
مرسوم | تفويض | توقيع علي اتفاقية بين حكومة سلطنة عمان وحكومة جمهورية اوغندا بشان الخدمات الجوية بين اقليميهما وما وراءهما

[PREAMBLE]
نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على المرسوم السلطاني رقم ٢٦ / ٧٥ بإصدار قانون تنظيم الجهاز الإداري للدولة وتعديلاته، وعلى مشروع الاتفاقية بين حكومة سلطنة عمان وحكومة جمهورية أوغندا بشأن الخدمات الجوية بين إقليميهما وما وراءهما، وبناء على ما تقتضيه المصلحة العامة

[ARTICLES]
مادة (١) : يفوض وزير المواصلات في توقيع الاتفاقية بين حكومة سلطنة عمان وحكومة جمهورية أوغندا بشأن الخدمات الجوية بين إقليميهما وما وراءهما المشار إليها.

مادة (٢) : ينشر هذا المرسوم في الجريدة الرسمية ويعمل به اعتبارا من تاريخ صدوره.
============================================================
chunks: [TITLE]
مرسوم سلطاني رقم ٤٢ / ٩٩ في شأن إنشاء الكليات والمعاهد العليا الخاصة

[TOPIC]
مرسوم | انشاء | الكليات والمعاهد العليا الخاصة

[PREAMBLE]
نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على النظام الأساسي للدولة الصادر بالمرسوم السلطاني رقم ١٠١ / ٩٦، وعلى المرسوم السلطاني رقم ١٥ / ٩٤ بتحديد اختصاصات وزارة التعليم العالي، وعلى المرسوم السلطاني رقم ١٨ / ٩٦ في شأن إنشاء الكليات والمعاهد الخاصة، وعلى المرسوم السلطاني رقم ٦٥ / ٩٨ بإنشاء مجلس للتعليم العالي، وبناء على ما تقتضيه المصلحة العامة

[ARTICLES]
مادة (١) : يجوز بقرار من وزير التعليم العالي بعد موافقة مجلس التعليم العالي إنشاء كليات أو معاهد عليا خاصة تتولى القيام بتدريس نوع أو أكثر من التخصصات العملية أو الفنية بعد المرحلة الثانوية، بما يخدم احتياجات خطط التنمية في السلطنة وسوق العمل بها. وتشرف وزارة التعليم العالي على الكليات والمعاهد العليا المشار إليها.

مادة (٢) : يصدر وزير التعليم العالي اللوائح اللازمة لإنشاء وتنظيم الكليات والمعاهد العليا الخاصة بعد موافقة مجلس التعليم العالي، وإلى أن تصدر هذه اللوائح يستمر العمل باللوائح الحالية بما لا يتعارض مع أحكام هذا المرسوم.
============================================================
chunks: [TITLE]
مرسوم سلطاني رقم ٢٠ / ٢٠١٨ بإجراء تنقلات وتعيينات في السلك الدبلوماسي

[TOPIC]
مرسوم | None |  تنقلات وتعيينات في السلك الدبلوماسي

[PREAMBLE]
نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على النظام الأساسي للدولة الصادر بالمرسوم السلطاني رقم ١٠١ / ٩٦، وعلى قانون تنظيم وزارة الخارجية الصادر بالمرسوم السلطاني رقم ٣٢ / ٢٠٠٨، وبناء على ما تقتضيه المصلحة العامة

[ARTICLES]
المادة الثالثة : يمنح كل من: ١- الوزير المفوض أحمد بن سعيد بن عمر الكثيري لقب سفير، ويعين سفيرا لنا فوق العادة، ومفوضا لدى جمهورية أوزبكستان. ٢- الوزير المفوض يوسف بن أحمد بن حمد الجابري لقب سفير، ويعين سفيرا لنا فوق العادة، ومفوضا لدى جمهورية النمسا. ٣- الوزير المفوض سيف بن هلال بن علي المعمري لقب سفير، ويعين سفيرا لنا فوق العادة، ومفوضا لدى الجمهورية الإسلامية الموريتانية.

المادة الرابعة : ينشر هذا المرسوم في الجريدة الرسمية، ويعمل به من تاريخ صدوره.
============================================================
chunks: [TITLE]
وزارة الإسكان: قرار وزاري رقم ٣٥ / ٢٠١٨ بتعديل القرار رقم ٢ / ٢٠٠٩ بشأن تحديد أسس تثمين الأراضي والمنشآت والمحاصيل الزراعية المنزوعة ملكيتها للمنفعة العامة

[TOPIC]
قرار | تعديل | القرار بشان تحديد اسس تثمين الاراضي والمنشات والمحاصيل الزراعية المنزوعة ملكيتها للمنفعة العامة

[PREAMBLE]
استنادا إلى قانون نزع الملكية للمنفعة العامة الصادر بالمرسوم السلطاني رقم ٦٤ / ٧٨، وإلى نظام استحقاق الأراضي الحكومية الصادر بالمرسوم السلطاني رقم ٨١ / ٨٤، وإلى المرسوم السلطاني رقم ٣٢ / ٢٠١٢ بإسناد بعض الاختصاصات، وإلى المرسوم السلطاني رقم ٦٤ / ٢٠١٤ بتحديد اختصاصات وزارة الإسكان واعتماد هيكلها التنظيمي، وإلى القرار الوزاري رقم ٢ / ٢٠٠٩ بشأن تحديد أسس تثمين الأراضي والمنشآت والمحاصيل الزراعية المنزوعة ملكيتها للمنفعة العامة، وإلى موافقة وزارة المالية، وإلى موافقة مجلس الوزراء، وبناء على ما تقتضيه المصلحة العامة، تقرر

[ARTICLES]
المادة الأولى : يستبدل بنص البند (٥) من أولا من القسم الأول من القرار رقم ٢ / ٢٠٠٩ بشأن تحديد أسس تثمين الأراضي والمنشآت والمحاصيل الزراعية المنزوعة ملكيتها للمنفعة العامة النص الآتي: ٥ – على الجهة طالبة نزع الملكية والمسؤولة عن المشروع تعويض المواطن في شكل فائدة سنوية بنسبة (٦٪) من قيمة العقار المتأثر تضاف إلى المبالغ المقدرة للتعويضات وذلك من تاريخ انتقال سند الملكية إلى الجهة طالبة نزع الملكية وحتى تاريخ تسلم التعويض العيني أو النقدي أو إلغاء المشروع. وفي جميع الأحوال لا يستحق المواطن التعويض إذا كان التأخير في تسلم التعويض العيني أو النقدي يرجع إليه.

المادة الثانية : يلغى كل ما يخالف هذا القرار أو يتعارض مع أحكامه.
============================================================
chunks: [TITLE]
مرسوم سلطاني رقم ١٨ / ٩٩ بتحديد اختصاصات وزارة البلديات الإقليمية والبيئة واعتماد هيكلها التنظيمي

[TOPIC]
مرسوم | تحديد اختصاصات | وزارة البلديات الاقليمية والبيئة اعتماد هيكلها التنظيمي

[PREAMBLE]
نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على النظام الأساسي للدولة الصادر بالمرسوم السلطاني رقم ١٠١ / ٩٦، وعلى قانون تنظيم الجهاز الإداري للدولة الصادر بالمرسوم السلطاني رقم ٢٦ / ٧٥، وعلى المرسوم السلطاني رقم ٢ / ٨٥ بإجراء تعديل في التشكيل الوزاري، وعلى المرسوم السلطاني رقم ١١٧ / ٩١ بتعديل اسم وزارة البلديات الإقليمية والبيئة، وعلى المرسوم السلطاني رقم ٥٩ / ٩٢ باعتماد الهيكل التنظيمي لوزارة البلديات الإقليمية والبيئة، وبناء على ما تقتضيه المصلحة العامة

[ARTICLES]
مادة (١) : تحدد اختصاصات وزارة البلديات الإقليمية والبيئة وفقا للمحلق رقم ١ المرافق.

مادة (٢) : يعتمد الهيكل التنظيمي لوزارة البلديات الإقليمية والبيئة وفقا للملحق رقم ٢ المرافق.
============================================================
chunks: [TITLE]
وزارة التجارة والصناعة: قرار وزاري رقم ١٣٨ / ٢٠١٩ باعتبار مواصفتين قياسيتين دوليتين متعلقتين بأسطوانات الغاز مواصفات عمانية ملزمة

[TOPIC]
قرار | اعتبار | مواصفتين قياسيتين دوليتين متعلقتين باسطوانات الغاز مواصفات عمانية ملزمة

[PREAMBLE]
استنادا إلى المرسوم السلطاني رقم ١١ / ٢٠١٧ بتحديد اختصاصات وزارة التجارة والصناعة، واعتماد هيكلها التنظيمي، وإلى القرار الوزاري رقم ١٢ / ٨٧ باعتبار مواصفة قياسية عمانية ملزمة، وإلى القرار الوزاري رقم ٤١ / ٢٠٠٥ بالعمل بمواصفات قياسية دولية أو أجنبية، وإلى القرار الوزاري رقم ٢٣٢ / ٢٠١٥ باعتبار مواصفة قياسية عمانية ملزمة، وبناء على ما تقتضيه المصلحة العامة، تقرر

[ARTICLES]
المادة الأولى : تعتبر المواصفتان القياسيتان الدوليتان الآتيتان مواصفات قياسية عمانية ملزمة: ١ – ISO22991 : 2004 المواصفة القياسية الخاصة بأسطوانات الغاز – أسطوانات الصلب الملحومة المتنقلة القابلة لإعادة التعبئة والمستخدمة للغازات البترولية المسالة – التصميم والتركيب. ٢ – ISO10464 : 2004 المواصفة القياسية الخاصة بأسطوانات الغاز – أسطوانات الصلب الملحومة القابلة لإعادة التعبئة والمستخدمة للغازات البترولية المسالة – التصميم والتركيب – الفحص الدوري والاختبار.

المادة الثانية : تفرض غرامة إدارية لا تتجاوز (١٠٠٠) ألف ريال عماني على كل من يخالف أحكام هذا القرار، وتضاعف الغرامة في حال تكرار المخالفة.
============================================================
chunks: [TITLE]
وزارة الزراعة والثروة السمكية: قرار وزاري رقم ٣٨٣ / ٢٠١٧ بحظر استيراد الطيور الحية من مملكة هولندا

[TOPIC]
قرار | حظر | استيراد الطيور الحية من مملكة هولندا

[PREAMBLE]
استنادا إلى قانون الحجر البيطري الصادر بالمرسوم السلطاني رقم ٤٥ / ٢٠٠٤، وإلى اللائحة التنفيذية لقانون الحجر البيطري الصادرة بالقرار الوزاري رقم ١٠٧ / ٢٠٠٨، وإلى توصية الجهة البيطرية المختصة بشأن حظر استيراد الطيور الحية ومنتجاتها ومشتقاتها ومخلفاتها من بعض الدول، وبناء على ما تقتضيه المصلحة العامة، تقرر

[ARTICLES]
المادة الأولى : يحظر استيراد الطيور الحية ومنتجاتها ومشتقاتها ومخلفاتها من مملكة هولندا، وذلك لحين زوال سبب الحظر، وصدور قرار بهذا الشأن.

المادة الثانية : على الجهات المختصة تنفيذ هذا القرار، كل في مجال اختصاصه.

المادة الثالثة : ينشر هذا القرار في الجريدة الرسمية، ويعمل به من تاريخ صدوره.
============================================================
chunks: [TITLE]
مرسوم سلطاني رقم ٩٣ / ٨٦ بتعديل اسم المديرية العامة لموارد المياه والري بوزارة الزراعة والأسماك وتحديد اختصاصاتها

[TOPIC]
مرسوم | تعديل | اسم المديرية العامة لموارد المياه والري بوزارة الزراعة والاسماك تحديد اختصاصاتها

[PREAMBLE]
نحن قابوس بن سعيد سلطان عمان بعد الاطلاع على المرسوم السلطاني رقم ٢٦ / ٧٥ بإصدار قانون تنظيم الجهاز الإداري للدولة وتعديلاته، وعلى المرسوم السلطاني رقم ٦٣ / ٨٤ باعتماد الهيكل التنظيمي لوزارة الزراعة والأسماك، وعلى المرسوم السلطاني رقم ١٠٤ / ٨٥ بتعديل اسم وزارة البيئة واختصاصاتها، وعلى المرسوم السلطاني رقم ١٠٥ / ٨٥ بتعديل اسم مجلس حماية البيئة ومكافحة التلوث وإعادة تشكيله، وبناء على ما تقتضيه المصلحة العامة

[ARTICLES]
مادة (١) : يعدل اسم “المديرية العامة لموارد المياه والري” بوزارة الزراعة والأسماك ليصبح “المديرية العامة لشؤون الري” ويعدل الهيكل التنظيمي للوزارة على هذا الأساس.

مادة (٢) : تتحدد اختصاصات المديرية العامة لشؤون الري المشار إليها، كما يلي: ١- الإشراف على أعمال صيانة الأفلاج والآبار والعيون. ٢- الحفاظ على الأراضي الزراعية من التآكل والدمار نتيجة فيضانات الأودية المجاورة لها بإقامة المنشآت اللازمة. ٣- إنشاء سدود التغذية الجوفية لتوفير المياه اللازمة لأغراض التنمية الزراعية. ٤- توفير البيانات المساحية والإحصائية عن الأفلاج والآبار والعيون والسدود.
============================================================
chunks: [TITLE]
هيئة المنطقة الاقتصادية الخاصة بالدقم: قرار رقم ٣٠ / ٢٠١٧ بإصدار نظام الترخيص والعمل بالموقع التابع للإقليم الجمركي في المنطقة الاقتصادية الخاصة بالدقم

[TOPIC]
قرار | اصدار | نظام تصريح تطبيق بالموقع التابع للاقليم الجمركي في المنطقة الاقتصادية الخاصة بالدقم

[PREAMBLE]
استنادا إلى المرسوم السلطاني رقم ١١٩ / ٢٠١١ بإنشاء هيئة المنطقة الاقتصادية الخاصة بالدقم وإصدار نظامها، وإلى نظام المنطقة الاقتصادية الخاصة بالدقم الصادر بالمرسوم السلطاني رقم ٧٩ / ٢٠١٣، وإلى المرسوم السلطاني رقم ٥ / ٢٠١٦ بتقرير صفة المنفعة العامة لمشروع تطوير منطقة رأس مركز بولاية الدقم، وضمها إلى المنطقة الاقتصادية الخاصة بالدقم، وإلى لائحة تنظيم البيئة الاستثمارية في المنطقة الاقتصادية الخاصة بالدقم الصادرة بالقرار رقم ٣٢٣ / ٢٠١٥، وإلى نظام الإدارة الجمركية في المنطقة الاقتصادية الخاصة بالدقم الصادر بالقرار رقم ٩ / ٢٠١٦، وإلى موافقة مجلس إدارة هيئة المنطقة الاقتصادية الخاصة بالدقم، وبناء على ما تقتضيه المصلحة العامة، تقرر

[ARTICLES]
المادة الأولى : يعمل بنظام الترخيص والعمل بالموقع التابع للإقليم الجمركي في المنطقة الاقتصادية الخاصة بالدقم، المرفق.

المادة الثانية : يلغى كل ما يخالف النظام المرفق، أو يتعارض مع أحكامه.
============================================================

In [61]:
# import json
# import pandas as pd
# import numpy as np
# # لیست نهایی برای ذخیره آبجکت‌ها
# json_output_list = []
#
# # پیمایش روی تک تک سطرهای دیتا فریم
# for index, row in df_final.iterrows():
#
#     # ---------------------------------------------------------
#     # 1. تولید ID طبق پترن درخواستی: rd1974002_chunk_01
#     # فرمول: rd + سال (4 رقم) + آی‌دی (3 رقم با پدینگ صفر) + _chunk_01
#     # ---------------------------------------------------------
#     try:
#         # سال
#         year_str = str(int(row["year"])) if pd.notna(row["year"]) else "0000"
#
#         # آی‌دی عددی داخل سال
#         if pd.notna(row["id"]):
#             id_val = int(row["id"]) if isinstance(row["id"], (int, float)) else int(str(row["id"]))
#             id_str = str(id_val).zfill(3)
#         else:
#             id_str = "000"
#
#         # شماره چانک بر اساس index دیتافریم (از 1 شروع می‌کنیم)
#         chunk_num = int(index) + 1
#         chunk_str = str(chunk_num).zfill(2)  # اگر دیتاست بزرگ است → 3
#
#         generated_id = f"rd{year_str}{id_str}_chunk_{chunk_str}"
#
#     except Exception:
#         generated_id = f"rd_error_{index}_chunk_{str(index + 1).zfill(2)}"
#
#
#     # ---------------------------------------------------------
#     # 2. ساخت دیکشنری برای هر سطر
#     # ---------------------------------------------------------
#     # مدیریت مقادیر NaN (چون JSON مقدار NaN را قبول نمی‌کند و باید null شود)
#     # تابع کمکی برای هندل کردن NaN
#
#
#     def get_val(val):
#         if val is None:
#             return None
#
#         # pandas Timestamp / datetime
#         if isinstance(val, (pd.Timestamp,)):
#             return val.isoformat()
#
#         # numpy datetime64
#         if isinstance(val, np.datetime64):
#             return pd.to_datetime(val).isoformat()
#
#         # list / tuple
#         if isinstance(val, (list, tuple)):
#             return val if len(val) > 0 else None
#
#         # numpy array
#         if hasattr(val, "tolist"):
#             return val.tolist()
#
#         # scalar NaN
#         if pd.isna(val):
#             return None
#
#         return val
#
#
#     record = {
#         "id": generated_id,
#         "text": get_val(row['text']),
#         "chunk": get_val(row['chunks']),
#         "metadata": {
#             "doc_id": get_val(row['id']),
#             "law_type": get_val(row['law_type']),
#             "law_number": get_val(row['law_number']),
#             "year": get_val(row['year']),
#             "date": get_val(row['date']),
#             "footer": get_val(row['footer']),
#             "title": get_val(row['title']),
#             "semantic_tags": get_val(row['semantic_tags']),
#             "canonical_link": get_val(row['canonical_link'])
#         }
#     }
#
#     json_output_list.append(record)
#
# # ---------------------------------------------------------
# # 3. ذخیره در فایل JSON
# # ---------------------------------------------------------
# output_filename = 'oman_laws_final_dataset.json'
#
# with open(output_filename, 'w', encoding='utf-8') as f:
#     # ensure_ascii=False باعث می‌شود متن فارسی/عربی درست ذخیره شود (نه به صورت یونیکد)
#     # indent=4 برای مرتب‌سازی و خوانایی فایل
#     json.dump(json_output_list, f, ensure_ascii=False, indent=4)
#
# print(f"فایل جیسون با موفقیت ایجاد شد: {output_filename}")
# print(f"تعداد رکوردها: {len(json_output_list)}")